### ISSUE TITLE
Questions for Dai

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#1]
1. ResourceSubType should ResourceSubTypeSynonym be a String not an Int
and ResourceTypeName should be ResourceSubTypeName ?
2. Physical FK missing from Community to Intersection table ProjectLZ 
3. Remember all PK IDs are now Varchar(32) for GUUID
4. WGCharacteristicWealthGroup - FK COloum to ResourceSubType is IDWGResource not WGResourceSubType in model 
5. Use of ProXava http://www.openxava.org/xavapro/pricing
6. Server setup

**Comment by daiClegg** [comment]
- ResourceSubType should ResourceSubTypeSynonym be a String not an Int and ResourceTypeName should be ResourceSubTypeName ?

as discussed -the synonym pig's ear relationship is to another ResourceSubType,
 
 - Physical FK missing from Community to Intersection table ProjectLZ

fixed in Implementation model, right? Fixed it in the Design model - pointing at the INT PK

 - Remember all PK IDs are now Varchar(32) for GUUID

yup

 - WGCharacteristicWealthGroup - FK Column to ResourceSubType is IDWGResource not WGResourceSubType in model

fixed.

 - Use of ProXava http://www.openxava.org/xavapro/pricing

Agreed it's the right solution; have requested authorisation

 - Server setup

Have passed Public Key to server admins; waiting for their response.

**Comment by dbrownukk** [comment]
Dai,
Great - just working on the pigs ear..
David


    On Tuesday, 7 November 2017, 18:15:47 GMT, daiClegg <notifications@github.com> wrote:  
 
    
   - ResourceSubType should ResourceSubTypeSynonym be a String not an Int and ResourceTypeName should be ResourceSubTypeName ?

as discussed -the synonym pig's ear relationship is to another ResourceSubType,
   
   - Physical FK missing from Community to Intersection table ProjectLZ

fixed in Implementation model, right? Fixed it in the Design model - pointing at the INT PK
   
   - Remember all PK IDs are now Varchar(32) for GUUID

yup
   
   - WGCharacteristicWealthGroup - FK Column to ResourceSubType is IDWGResource not WGResourceSubType in model

fixed.
   
   - Use of ProXava http://www.openxava.org/xavapro/pricing

Agreed it's the right solution; have requested authorisation
   
   - Server setup

Have passed Public Key to server admins; waiting for their response.

**Comment by daiClegg** [comment]
David,

Some more follow up on your questions/issues:


I just re-checked the model. The Amount and  Unit in WGCharacteristics (in the design model) are the Amount and Unit of an asset (ResourceSubType) the WG could be expected to have , e.g. 5 acres land  or 1(unit)  bicycle.
So the Unit is acres, kilograms, unit (i.e. just a count) etc, and the amounts how many/much.
Amount is decimal cos it might be 1/2 an acre etc.
Make sense?

I’ve asked John to clarify the Number of Participants field - cos in the first WG Interview spreadsheet i opened the Men & Women cells did not add up to the Number of Participants cell.

The Type of Year field in the spreadsheet is in the design model in the WGInterview table - with a set of values “Good”, “Bad” ,”Normal”. I suspect we’ll need other values eventually, but let’s go with those for now.

And the Year notes are pretty obvious from the spreadsheet i think. If it’s easy enough to add as another child (table layout makes most sense?) on the Community, that would be useful.

Anything else unresolved right now?

cheers
dai

**Comment by dbrownukk** [comment]
Thanks Dai - gradually catching up with you..
    On Thursday, 9 November 2017, 12:45:42 GMT, daiClegg <notifications@github.com> wrote:  
 
 David,

Some more follow up on your questions/issues:


I just re-checked the model. The Amount and Unit in WGCharacteristics (in the design model) are the Amount and Unit of an asset (ResourceSubType) the WG could be expected to have , e.g. 5 acres land or 1(unit) bicycle.
So the Unit is acres, kilograms, unit (i.e. just a count) etc, and the amounts how many/much.
Amount is decimal cos it might be 1/2 an acre etc.
Make sense?

I’ve asked John to clarify the Number of Participants field - cos in the first WG Interview spreadsheet i opened the Men & Women cells did not add up to the Number of Participants cell.

The Type of Year field in the spreadsheet is in the design model in the WGInterview table - with a set of values “Good”, “Bad” ,”Normal”. I suspect we’ll need other values eventually, but let’s go with those for now.

And the Year notes are pretty obvious from the spreadsheet i think. If it’s easy enough to add as another child (table layout makes most sense?) on the Community, that would be useful.

Anything else unresolved right now?

cheers
dai

**Comment by daiClegg** [comment]
Is this still open as the repository for further questions?
I'd prefer it closed and new issues opened for each new question - it makes it easier subsequently to search issues if the subject is the key object in the issue, e.g. "WGCharacteristics Amoint & Unit types"

**Comment by daiClegg** [comment]
Ok to close?> I don't think there are any more questions outstanding.
See my previous comment
