### ISSUE TITLE
Project (Project1) displays with no LZ

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#10]
Steps to reproduce:

### Login in as:  

- Organization: EFD_v2_Test
- User: admin
- P/W:  <<as set>>
### 
Log in succeeds.

## Step 2:
- If not already displaying "Projects", select "Projects"

## Step 3:

Double click "Project 1"

### "Project1 is displayed in detail, detail, detail format  (Project, Livelihood Zone, Community)
Community has data, LIvelihood Zone does not.

## Expected Behaviour:

Every Project must include at least one livelihood zone within which each Community that is part of the project will be situated.
 Community displayed is correctly identified (sub district 1 of District 1, in LZ 1) in Community detail display, but not in the Project view.

**Comment by daiClegg** [comment]
Retested by creating a new project (Test for Issue #10) and was able to associate a Community with this project without previously associating a LZ, in which the Site of the Community is situated.

**Comment by dbrownukk** [comment]
Would love to say this is a Model problem but its an implementation of the model problem - will look into this..

**Comment by daiClegg** [comment]
Note if the Site to be associated in the Community dialogue does not exist get an error message:

       "Site with key {locationid=null} not found"

on tabbing out of the Site name field.

**Comment by dbrownukk** [comment]
Project + LZ does not now have site - closing
