### ISSUE TITLE
Upgrade to OpenXava 5.9 

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#106]

**Comment by daiClegg** [comment]
Started to run a smoke test.
Created Project & LZ ok.
Opened Community Module - menu is missing.
Checked other modules and it is also missing on the  Livelihood Zones module.
It is present on Project, Wealth Group Interview and Site modules

**Comment by daiClegg** [comment]
Menu problem now resolved will return to Smoke test...

**Comment by daiClegg** [comment]
Tried to continue smoke test and ran into #113 
Will continue when that is resolved

**Comment by dbrownukk** [comment]
#113 resolved - now on 5.9.1 Openxava version

**Comment by daiClegg** [comment]
I completed the smoke test for M1.
Some bugs logged separately, but nothing obviously attributable to the upgrade, which can now be regarded as successful
