### ISSUE TITLE
Exception oin uploading WG I/V Spreadsheet - V3

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#107]
On V3 of the app - does not reproduce on V2

Invoke WealthGroupInterview module in List view
Select
Project::           Karamoja Central Sorghum and LIvestock
District:            Nakapiripirit
SubDistrict:     Cucu
WealthGroup: Very Poor

In Detail view: click select file to upload an interview spreadsheet.
Select any valid spreadsheet ( i have tried 2 different ones and checked they are valid in V2)
Attempt to upload spreadsheet.,

Exception thrown (attached):

(https://github.com/dbrownukk/EFD_v2/files/2069905/HTTP.Status.500.docx)

If you thewn use the browser 'back' control to return to the app, it hangs attempting to reload the page? Log off resets state.

**Comment by dbrownukk** [comment]
A new xava.properties file was missing extra settings, in particular a pointer to JPAFilePeristor

# DRB 12/10/17 - Responsive support in 5.7
flowLayout=false
summationInList=false
resizeColumns=true
csvSeparator=,
pageRowCount=15
filePersistorClass=org.openxava.web.editors.JPAFilePersistor
i18nWarnings=false
showDefaultActionInBottom=false

fixed

**Comment by daiClegg** [comment]
Tested ok.
Now behaves as V2 on upload.
Also the  "Editor not available" message no longer appears.
