### ISSUE TITLE
Exception inserting new Community

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#113]
Log out& Login
Invoke Communities Moule
Filter list to "Balaka Test" - shows one community
Lick "New" in the main menu bar to insert a community
Select "Balaka Test" from Projects dropdown.
Click Search button to include an existing district

Throws exception: 

ERROR: An exception occurred processing JSP page /xava/core.jsp at line 78 75: 76: 77:
style='padding-top: 2px;'> 78: 79:
80: 81: <%@include file="viewExt.jsp"%> Stacktrace:

Reproduces consisently.

**Comment by daiClegg** [comment]
tested again with a brand new project (Test Issue #113); same problem attempting to select from existing districts (of which there were none)

Successfully added a new Community to the project by creating a new District for it.
Same exception curs when attempting to add another Community and attempting to select from existing Districts.

**Comment by dbrownukk** [comment]
Reproduced on my local dev instance. 5.9.1 of Openxava just been released with some fixes to filtered lovs - will upgrade first and investigate..

**Comment by dbrownukk** [comment]
fixed - project in the site list is the problem - but why it worked on local machine and not on linux server took many hours to untangle.

mysql 5.7.21
java 1.8 171
tomcat 7 and 8 

lookup works now

**Comment by daiClegg** [comment]
Tested ok.
Tried where:
sites exist in an LZ associated with the project, but not themselves associated with the project.
no sites exists in a  connected LZ
sites exist in connected LZ but are already associated with the project,
