### ISSUE TITLE
Cutting WGs from Community not working

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#114]
In Community module
Select any Community in any Project that has WGs
(i tested My "TestProject")
Click either the scissors icon by the uploaded spreadsheet or (with a WG row selected) the scissors button in the WG menu for any WG.
Confirmation message says "1 row cut from Wealthgroup".
Save appears to work ok, but the WG remains and the Spreadsheet remains attached to it.

**Comment by daiClegg** [comment]
Accessing the same Community in the WG Interview model and the WGs appear to be gone, as expected.
Logged out and in and the Community & WGINterviewmodels still show an inconsistent view of the Community's WGs.

(nb in this project there are 2 WGs still showing in Community module but not in the WG INterviews module, and one other (Poor) that i created today That appears as expected in both views.

**Comment by dbrownukk** [comment]
The cut and paste is a new addition in OpenXava 5.9 It was added in as a default rather than intended behaviour. Cannot get to work in any meaningful way. 

Added into EFD_v2 controllers.xml with hidden=true

I can add back and investigate if this is a requirement..

**Comment by daiClegg** [comment]
Scissors icons now removed, leaving Delete (bin icon either on the WG row or in the block menu) as the only remove option.
This is fine; ;both options work as expected.
