### ISSUE TITLE
Need Live, Acceptance Testing and Test Instances

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#115]
In order to support a deployment pattern of Development, Test, User Test & Production, we need to have shared instances, possibly of different deployments, for Test & Acceptance Test as well as a live deployment.

From the user's perspective, they will behave identically apart from actual functional differences in the application. 
However is should be possible to differentiate, from within the App, what instance a user is connected to. For example an 'About' option or a description on the login screen,
It is not a requirement that every user that is defined for one instance should be defined for another; the user credential sets can be regarded as orthogonal, although they will inevitably have overlaps.
If it is necessary, in order to support simple deployment & re-deployment, that there are some small differences that will be acceptable since simplicity and speed of the development cycle is important.

**Comment by dbrownukk** [comment]
Using Virtualbox 
Edit EFD_v2-labels - and include testing level in title 

EFD_v2=Evidence for Development OHEA Data Set V2 -  Acceptance Testing
# EFD_v2=Evidence for Development OHEA Data Set V2 -  User Testing

this will appear in heading

deploy to vbox environment and export vbox machine 

move vbox export to idaps server and deploy - access is via a dufferent port - other than 8080

**Comment by dbrownukk** [comment]
Virtualisation on the idaps CPU is not enabled 

Need to raise ticket to enable virtualisation - usually a bios setting I believe (well it was on my laptop)

**Comment by daiClegg** [comment]
Raised ticket with Reading support.
They say MS do not allow VMs on their VMs.
So we need an alternative.

Notes from David (in mail thread)

If we want the virtual machines for test/dev/qa and the virtual machine for the field then Docker is not viable - it requires Professional edition of Windows. MS Hyper V has the same requirement.

I can create a Docker image but obviously would take some time and no support from the Reading team. 

Alternatives?

Use Virtualbox on field laptops and investigate the Open Virtualisation export format from Virtualbox - seems that you can import into various cloud vendors such as AWS.

**Comment by daiClegg** [comment]
I agree we should not go down the Docker route.

we have already established that the standalone VM for field work is very effective, so using the same solution for test/QA images seems to be the right way to go.

That then drives us to other hosts for testing and for training sessions, This is a new requirement, but a training class image is effectively identical to a QA or Test image, so solve one and we solve all.
The thing these have in common is that they are low load and either sporadic or temporary. So an AWS pay-by-the-hour approach coukld be very cost-effective.

But this would mean creating a new Virtual Box image for each deployment, and finding a way to host them for download.
We could use the IDAPs server for that purpose, but we'd need credentials, just as we do for live instance use.
But what is the cost of setting up such a download page and of creating and deploying the Virtual Box update for each deployment ?

For discussion...

**Comment by dbrownukk** [comment]
AWS instance created and tested. 

Easy to create an image and duplicate if other test areas are needed 

http://35.178.211.58/EFD_v2/

Need to discuss how these are requested and used, but is now available, just needs starting on AWS

**Comment by daiClegg** [comment]
Tried to connect vanilla to this URL,  but it timed out 
Set up an AWS account, logged n and searched for connectable services,, but can't find this URL.
What next?

**Comment by dbrownukk** [comment]
I shut it down and the IP address changed..

Starting now..   http://35.178.33.15/EFD_v2/

**Comment by daiClegg** [comment]
Works a treat; response time is, if anything, faster than the Azure IDAPs instance.
We need a way for an accredited user to get access on demand.
And we need an official way to pay for the time used.
to be discussed.

leaving open until this is resolved.

**Comment by daiClegg** [comment]
To make the on-demand test instance workable we ideally need a paid account with a fixed IP address so an accredited user can just start it without any sys-admin intervention.
A minimal AWS VM at probably only a few $s a month would suffice.
Reading IT might prefer an Azure server if we want them to pay.
So need to invstigate an equivalent Azure solution.
Then can take it to Reading IT as a request for service.

**Comment by daiClegg** [comment]
We also need, a web interface on the IDAPs server to gate-keep the on-demand server so that only accredited users can start the meter running on it.

Note that there is an analogous requirement for users who want to download the stand-alone instance (see issue #85)

And we could also add a mechanism for users to request an account if they are not already registered.

So there is a requirement for an admin- interface to the server that might acquire further functions later.

**Comment by daiClegg** [comment]
The OX concept of Organizations can be used to provide apparently different instances, but they will be running the same version of the application.
This can be useful for a Training class on the production release.
The requirement for Test & Acceptance (User) Test instances with different versions still stands.

**Comment by daiClegg** [comment]
Currently using different instances for production and test.

**Comment by daiClegg** [comment]
Covered by #389
