### ISSUE TITLE
Site Create PopUp has lost LZ picker

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#116]
In Project Module:

Create a new project (i tested with "Test Issue #109")
Add a new LZ

In Communities Module:

Find the new project
Click + to add a new site
   (Popup does not allow you to select from the available LZs for the project.0
Enter Site details (District & SubDistrict) 
Click Create
   Error: "Value for Livelihood zone in Site is required"

This dialog used to have an LZ picker the Smoke test script doesn't have a screenshot for it, but it does mention it in the text.

**Comment by dbrownukk** [comment]
Had removed as a result of search issue - now that is fixed omitted to replace that code..

Fixed

**Comment by daiClegg** [comment]
Tested ok.
