### ISSUE TITLE
Adding Site to an LZ in LZ create popup does not filter sites for Add dialog

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#117]
In the Project module,
select any project (i used Test Issue #109)
In the LZ block, click New
   (pops up LZ create dialog)
Enter LZ name & select LZ country.
In the Site block of the LZ popup, click add  
   (pops list of ALL sites)
Select any site in any LZ.
   (pops successful modify messages)
Click Save
   (fails with an "existing key" error)

Since this is a new LZ there are no Sites to add so should get an empty list.
Alternatively Add should not be offered.

**Comment by daiClegg** [comment]
Actually, should just remove the Site edit capability on LZs in Project.
The Community Module is the place to add sites.
And the Edit dialog in the Project module for an LZ already in a Project does not ofer the capability to edit Sites.
Let's make liefe simpler - and consistent.

**Comment by dbrownukk** [comment]
removed Site from Project / LZ create/edit

**Comment by daiClegg** [comment]
Tested OK.
