### ISSUE TITLE
Livestock  units not consistently generated in WG template spreadsheet

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#118]
View Project "Test Issue #109" in Communities module.
Click on "Poor" WG to view detail..
   (Note characteristic Livestock resources defined: Goats, Pigs, Chicken, Ducks, Dairy Cow, Local 
    Cow each with unit "Item" defined)
Close WG detail popup.
IClick "Template Spreadsheet" for "Poor" WG.
View generated spreadshhet
   (note in Livestock tab no unit is specified for Chicken & Ducks, but is correctly specified for 
     other Livestock)

Is this prejudice against birds???

**Comment by dbrownukk** [comment]
The power of data driven applications

The resource sub type unit for Chicken and Ducks is blank in the Resource Sub Type table. 

Need to set Units to be mandatory but will need all Units set first - setting them all to Item for the moment and will set to not null

**Comment by daiClegg** [comment]
Works now as expected, but, wrt However 2...

There may be Local Units, e.g. Maize is always measured by the Sack in this LZ, And it's is 50Kg.
So the characteristic resource will override the stored unity. But, before we allow this we need to implement the enhancement that allows for Local Units.

**Comment by dbrownukk** [comment]
OK, will set to use unit value from characteristic resource..

**Comment by daiClegg** [comment]
in community module,
select a WG
add a characteristic resource
   <the unit is not defaulted from the resource sub-type reference table>

generated spreadsheet doe sno pick it up either.
Am i misunderstanding what the expected behaviour should be?

**Comment by dbrownukk** [comment]
Hmm, seems to work here for all WGs I try..  Can you send specific WG details..
thx

**Comment by daiClegg** [comment]
Project: Test Issue #109 
LZ: Smoke TestLZ1
District: Smoke Test District
Sub District:  Smoke Test SubDistrict
WG: Better Off

This has one Characteristic Resource - Local Chickens with no unit specified
In the Resource SubTypes table Local Chickens have Unit = unit

If i generate the spreadsheet i get no unit for Local Chickens.
I had expected it to default to the unit on the Resource SubTypes table
Is that not correct?

**Comment by daiClegg** [comment]
I think that makes sense. Agree?

**Comment by dbrownukk** [comment]
Agreed and deployed ready for testing

**Comment by daiClegg** [comment]
Tested Ok
