### ISSUE TITLE
ISO Country Code has wrong format

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#12]
Specified as Varchar(2). Should have been Varchar(3)

My mistake

**Comment by dbrownukk** [comment]
ISO does have 2 and 3 char options - easy change to 3 
Fixed in Laptop version, yet to be deployed on Reading server

**Comment by daiClegg** [comment]
please update when dep[loyed and i'll test & close

**Comment by daiClegg** [comment]
please update the issue when deployed & i will test & close

**Comment by dbrownukk** [comment]
deployed..

**Comment by daiClegg** [comment]
tested ok.
