### ISSUE TITLE
Change WGI status'

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#120]
Change WGI status to

Generated ( set during template creation from cummunity screen)
Loaded (on upload after wgi)
Part Parsed (parsed but one or more sections failed)
Full Parse .  (successfully parsed all sections)
Validated  (All assets are Valid)

**Comment by daiClegg** [comment]
Sorry,  i somehow failed o enter my testing results for this.

The status change is not automated Generated to Uploaded when you do an upload
Others appear to be ok

**Comment by dbrownukk** [comment]
On Upload status is now set to 'Uploaded'

Found a possible OX bug - Spreadsheet field is @Required but you can upload, though not save, an empty file. Cancel should be only option if file name is empty in the dialog. Would need to re-code the dialog box to fix, thus will leave

**Comment by daiClegg** [comment]
I can't create a new WGI to take through the lifecycle and verify this; blocked by #132

**Comment by daiClegg** [comment]
#132 now fixed.
resumed testing,
Tested OK.
