### ISSUE TITLE
Validate button on WGI checks all assets are Valid and sets WGI to Valid or warns invalids still exist

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#122]

**Comment by daiClegg** [comment]
I used  Project: Karamoja 
LZ: Central Sorghum and Livestock 
District: Moroto 
SubDistrict: Namatwae 
WG: Very Poor
Status: Part parse;

First i Parsed: 
   <said already parsed - as expected.>
Then i Validated: 
   <lots of messages about Invalid Resource subtypes - as expected.>
I went through and corrected all the invalid resources and saved.
Validated again: 
   <same messages - i had not corrected the 'Invalid' status on each resource entry.>
Then i went through and corrected 'Invalid' status on each resource entry
Validated again.
   <messages all gone - as expected.>
   < But failed Validate with the following message:

Impossible to execute Validate asset data action: MetaControllers.getMetaAction only allow action qualified names, with this style: ControllerName.actionName, and it has been received: TypicalNotResetOnSave



--

**Comment by dbrownukk** [comment]
fixed and tested on idaps server 
Validated Karamoja - Central Sorghum and Livestock Moroto Namatwae Very Poor 

Tested that Not Checked and Invalid resources fail Validation

**Comment by daiClegg** [comment]
Tested OK.
