### ISSUE TITLE
WGI assets - resource sub type pick list needs context set for appropriate asset based on Asset Tab

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#123]

**Comment by daiClegg** [comment]
I need to upload a spreadsheet with at least one invalid item in order to test this.
Currently blocked  by Issue #129

**Comment by dbrownukk** [comment]
#129 should be fixed..

**Comment by dbrownukk** [comment]
This is how the resource sub type lookup appears in the WGI asset .collections  - Food Products 

	@ManyToOne
	@JoinColumn(name = "ResourceSubType")
	@DescriptionsList(descriptionProperties="resourcetypename", condition="${resourcetype.resourcetypename} in ('Crops','Wild Foods','Livestock Products','Food Purchase')")
	private ResourceSubType resourceSubType;

and Non Food Products

	@ManyToOne
	@JoinColumn(name = "ResourceSubType")
	@DescriptionsList(descriptionProperties="resourcetypename", condition="${resourcetype.resourcetypename} in ('Non Food Purchase','Other Tradeable Goods')")
	private ResourceSubType resourceSubType;


Thus - very hard coded... We need to prevent Resource Types from being edited as this will break the ship

**Comment by daiClegg** [comment]
see also Issue #131

**Comment by dbrownukk** [comment]
#131 now ready to test

**Comment by daiClegg** [comment]
closing this as #131 is ok. and no other instances of this issue are visible in any tests so far.
