### ISSUE TITLE
Unable to load WG interview spreadsheet as generated

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#124]
In Communities module, add a WG to any Community of any Project & generate the spreadsheet
Note it is a .xls file

In WG module
select the Project & Comunity as above, 
select the Wealth Group created.
in Detail view, click Select File to attach interview spreadsheet
Select the spreadsheet as just generated.
Click "Upload File"
   < module hangs; have to stop the page load & log out to reset the module>

Even if you fill in the spreadsheet correctly (e.g. Interview details and one resource), it still hangs.
Open the generated spreadsheet & save as .xlsx
Load now works, but parse fails with error message: 
                   Impossible to execute Parse spreadsheet action: null
(even with an apparently valid, though almost empty, interview spreadsheet)

**Comment by dbrownukk** [comment]
Thanks for accurate description, would never have found the problem otherwise.

After spreadsheet file upload the form is still in 'updated' state but not committed.  You need to do a 'Save' to commit the data, but clearly not obvious. The upload dialog needs to execute a save but this is inconsistent with everywhere else.  

To prevent the above problem I have added a refresh() to the spreadsheet parse, at the beginning. This resets the WGI to the saved state. If the spreadsheet file upload has not been saved then it will disappear - not ideal but consistent with the rest of the app.

A workable solution?

**Comment by daiClegg** [comment]
Generate spreadsheet still generates a .xls file (old format) which the load will not accept - and hangs in trying to.
As documented above as the first problem,

 (i put 2 issues in one Issue here. Will try not to do that in future)

if i save the generated spreadsheet as .xlsx i can then load it.

but parse still fails with the same error message.

**Comment by dbrownukk** [comment]
thinking this is a MS client issue - will test on other machines

**Comment by daiClegg** [comment]
Ha. Azure Linux doesn’t support old format of Excel.

But should we not generate.xlsx anyway?

**Comment by dbrownukk** [comment]
WIll see if I can easily change to xlsx generation.

**Comment by daiClegg** [comment]
So idd some more testing:

Project: Test Issue #109 
LZ: :SmokeTestLZ1 
District: : SmokeTestDistrict  
SubDistrict: SmokeTest SubDistrict 
WG: TestXLS Load

I  created the WG and generated the spreadsheet (.xls)
I edited the (blank template & added one Resource: 
Pigs/unit/3
Saved & then Saved as .xlsx
Note i had not added the Interview details

In WGI module, 

i attempted to load the .xls
 <it hangs and i have to stop the page load & log out to continue. This is consistent and reproducible>
i then attempted to load the .xlsx version - 
 <as expected -  reports successful load>
i then attempted parse 
 <as expected, fails with invalid interview details>

Back to the spreadsheets & added correct interview details to both .xls & .xlsx versions then repeat load sequence:

.xls file is the same behaviour - hangs
.xlsx file the parse fails but with a violation:
    " Impossible to execute Parse spreadsheet action: null"
( i suspect this is another problem, but the only data in that spreadsheet is the Pigs Livestock entry, and i think that is ok)


I have left the .xlsx i used attached to the WGI record, so you can save it, save it and save as .xls to repeat my test.
Seems bizarre that it generates as .xls, but now only loads .xlsx.

hth.

**Comment by dbrownukk** [comment]
The OXFILES table column DATA was set to BLOB and too small for the .xls files but ok for the smaller .xlsx files.

Column DATA now set to LONGBLOB

tested on reading server

**Comment by daiClegg** [comment]
Tested Ok.
