### ISSUE TITLE
Cannot delete WG once Template has been generated

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#126]
Project: Test Issue 
LZ: Smoke TestLZ
District: SmokeTest District
SubDistrict: SmokeTest SubDistrict
WG: Better OffI created WG 'Better Off' & saved. Then deleted it
 <as expected>
Created it again & added a characteristic resource,saved,  then deleted it
 <as expected >
Created it again, added a characteristic resource,saved, generated template spreadsheet, then deleted it
 <deleted failed:
Impossible to execute Remove selected action: org.hibernate.exception.ConstraintViolationException: could not execute statement

This Community also has  Poor & very poor  WGs - same situation there. 

Also reproduced on another project and reproduced without adding a characteristic resource before generating the spreadsheet

**Comment by dbrownukk** [comment]
A WGI is created on creation of spreadsheet, but is not deleted on attempt to delete Wealthgroup. 

Added to Wealthgroup 

	@OneToMany(mappedBy = "wealthgroup", cascade=CascadeType.REMOVE)
	private List<WealthGroupInterview> wealthGroupInterview;

so that WGI is deleted on delete of a community

**Comment by daiClegg** [comment]
Tested ok.
