### ISSUE TITLE
Resource Types

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#127]
Resource Type 'Other Tradeable Goods' is handled during template spreadsheet generation and parse

In the Reading server Resource Type table we also have 'Other Productive Assets' and 'OtherFoodStuff'

How should these be handled or are they just a throwback?

**Comment by daiClegg** [comment]
closing this; may conceivably need new issue(s) raised when the full resource sub-type set is loaded, but there is no issue right now.
