### ISSUE TITLE
Parse uploaded spreadsheet succeeds but ignored spreadsheet content.

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#129]
Project: Test Issue 123
Zone: Issue123 Zone 
District: District123 
Subdistrict: SubDistrict123 
WG: Poor

uploaded a valid spreadsheet (still attached to the WGI record) & saved it.
 <upload success message, but status not changed to Uploaded.>
Changed status to Uploaded and Saved.
Click Parse Spreadsheet & Parse successful message appears. 
  <no Resources are created, though there are plenty in the spreadsheet>

Tested with the .xls &  .xlsx versions of the spreadsheet; same result,

Blocking Issue #123

**Comment by dbrownukk** [comment]
Tested on my latest local spreadsheet and worked, but with some assets not populated there is a problem with a null in determining filter on resource type drop down. Filter really does not like the null rows.

Needs rethinking

**Comment by dbrownukk** [comment]
Sadly had to ditch part of the very neat Asset mapped super class. Could not figure a way to filter ResourceSubType based on the Tab in use - globals an option but not a good one. 

Moved ResourceSubType into each resource asset - no change to database.

Tested with 

Project: Test Issue 123
Zone: Issue123 Zone
District: District123
Subdistrict: SubDistrict123
WG: Poor

**Comment by daiClegg** [comment]
Tested Ok.

There are some outstanding issues about what resource types should be n the drop-down for each tab. i will log those as a separate issue.
But the load-parse-edit-validate sequence works a treat.
