### ISSUE TITLE
row counts for WGI Reosurces tabs are unreliable if parse fails.

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#130]
Project: TestUnreliableCount
LZ: UnreliableRowCoutZone
District: URCDistrict  
SubDistrict: <null>
WG: Uncorrect II

The spreadsheet attached to this WG has errors in the Employment tab.
When you first upload the spreadsheet and parse it.
Then save it, and  the errors messages appear - as expected 
However the tab row numbers are zero - even though the data is there.
Save makes no difference.
But log out and log in and the row counts are correct.

**Comment by dbrownukk** [comment]
each resource tab now does a refresh. Collection refresh did not refresh all counts

deployed

**Comment by daiClegg** [comment]
Tested Ok.
