### ISSUE TITLE
Generate Spreadsheet raises error messages and does not create WGI instance

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#132]
Project: DemoProject180205 
LZ: Coffee-Banana-Pigs
District: Mukono
SubDistrict: Bugoye/Ntenjeru
WG: Better Off

View the Characteristic Resources and note there is one (Land - Upland).
Click Generate Spreadsheet
  <error messages: "Value for {0} in {1} is required" and "may not be emplty" are popped>
  < but spreadsheet is generated>
Open generated spreadsheet.
 <confirm it is the correct WG &  that the Land asset has been correctly generated>

**Comment by daiClegg** [comment]
Did not discover this before i logged the issue initially...

Go to WGI module
View the Subdistrict.
Note only one WGI exists (Poor - previously created and validated successfully)

   < create of Better Off WGI has failed.

**Comment by dbrownukk** [comment]
The trouble with model driven development. Make one change without dependency analysis and you create problems elsewhere. I set the Spreadsheet attribute in the WGI screen to be @Required. But of course that is at the entity level not at the screen/form level. Thus creating the entity without the spreadsheet raises an error.

**Comment by dbrownukk** [comment]
fix deployed

**Comment by daiClegg** [comment]
Tested ok.
