### ISSUE TITLE
Ttile of a Pay column in WGI spreadsheet needs clarifying.

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#134]
ON the Employment tab, column F currently has "Cash Pay:    Amount" as the title.
It should read: "Cash Pay:    Amount per unit of work"

^he ambiguity of this column name emerged in testing, but we've been round this spec in detail with the users so it cannot be regarded as a bug. Hence logged as an Enh.

**Comment by dbrownukk** [comment]
fixed and deployed to Reading server

**Comment by daiClegg** [comment]
Thanks for the super swift turnaround.

Tested ok.
