### ISSUE TITLE
Problem Parsing Transfers Tab

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#135]
Project: TutorialProject
LZ: TutorialLZ 
District: District1 
SubDistrict: SubDistrict1 
WG: TestWG5

There is one row in the Transfers tab of the spreadsheet attached to this WG
As far as i know, the format and content of the transfer record is correct.
But parsing throws a warning message (in green) for the tab.
All other tabs are parsed, albeit partially  - as expected.

**Comment by dbrownukk** [comment]
boolean for official/unofficial was causing a problem

fixed and deployed

**Comment by daiClegg** [comment]
Tested Ok;
also tried Official Transfers and different types of transfer (Cash, Food, Other)
