### ISSUE TITLE
Create report to aggregate Income for a Wealth Group

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#138]
Simple tabular report to provide details of income:

Union of relevant details from Livestock Sales, Crops, Livestock Products, WildFoods, Employment, Transfers of types Cash & Other  

Report should be exportable as Excel and available to the user from the WGI module

**Comment by dbrownukk** [comment]
Am thinking this is an Openxava View from the Wealthgroup Interview Class, rather than a jaspersoft report. The OX filtering and export to pdf/excel is good.

**Comment by daiClegg** [comment]
Shall i try to build the base view as the union of 6 queries?

**Comment by daiClegg** [comment]
Pausing on this while we get the standard reports completed.  
They may well provide the necessary view for this.

**Comment by dbrownukk** [comment]
Deployed and available from WGI reports menu - creates a spreadsheet

Currently working on crops, livestock sales and products

Need to add Employment, Transfers and Wildfoods to database view and then add extra fields to jasper report 

Deployed for first impression ....

**Comment by daiClegg** [comment]
Looks good so far, but i haven't yet tried to build models in Excel on the basis of this.

There are columns that i don't expect to need, but i am of a mind to just ignore them since they might be useful for some other use case later.

**Comment by dbrownukk** [comment]
Added in Employment, Transfers and Wildfoods

**Comment by daiClegg** [comment]
Report runs fine on first tests.
Need to test more WGIs

**Comment by daiClegg** [comment]
shoiuld be covered by #146

**Comment by daiClegg** [comment]
Essentially the same view as #146, but restricted to a specific WG.

**Comment by daiClegg** [comment]
Dependent Issue #169 is now closed, so closing this again. 
Coore use case met - some bugs o/w but deal with them as seperate issues.
