### ISSUE TITLE
Unable to parse apparently valid spreadsheet

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#139]
Project: Tutorial Project
LZ: TutorialLZ 
District: District1 
SubDistrict: SubDistrict1 
WG: TestWG9

The attached spreadsheet was created from a real study (Homa Bay April 2018)
There are some details that appear to be "wrong" but should not cause the parser to fail, and  although i  have tried various tweaks to the content, i cannot discover what is making the parser barf

**Comment by dbrownukk** [comment]
Took some time but have figured this out but not fixed yet.

Transfers, Crops and others have a Market 1/2/3 and Market % column in the spreadsheet. 

Market is set to String, Market % set to a Double number. Is this correct?

However, the template spreadsheet generation sets Market to Number Format in the spreadsheet - it should set % market to number format with validation. Should it set both?

Hopefully will fix tomorrow and get back to charts..

**Comment by dbrownukk** [comment]
Template spreadsheet generation was missing a few columns in LSP

Fixed in template creation and parse.

Also created defensive number parsing and a check if spreadsheet has had added or deleted columns - which mess up the parse.. Will now only fail on the offending sheet

yet to be deployed

**Comment by dbrownukk** [comment]
deployed and tested.

Comes up with a warning that there is an error in number of columns in Sheet 9 (LiveStockProducts)

I could put in a decode of the sheet number but this is a rare occurrence 

Lets chat through template - it needed a few fixes but looking good now I think..

**Comment by daiClegg** [comment]
Tested Ok. Was able to parse and validate (when i had corrected the spreadsheet data as expected).

Got the error message - mine said it was  column count on sheet 10 (still Livestock Products)

But i compared this sheet (sheet 10 is Livestock Products) to the generated template and it appears to have the same number of columns.
Aslo checked Sheet 9 (Livestock Sales) that also appears to be correct.

Am i missing/misinterpreting something?

**Comment by dbrownukk** [comment]
Hmm, just checked again and parse of the AririPoorMk3 spreadsheet on TutorialLZ District1 SubDistrict1 TestWG9 on my local instance says sheet 9 is in error! 

However, glad it now works having fixed a couple of String/Double issues...

**Comment by daiClegg** [comment]
Just tried again on the AWS instance.

Project: Testproject180204
LZ: Coffee-Banana-Pigs 
District: District1 
SubDistrict: SubDistrict1 
WG: WG1



It's sheet 10 for me:

![image](https://user-images.githubusercontent.com/30879677/44341845-0bc50d80-a481-11e8-8c96-fb43e117c809.png)

The rest seems to be as was.

**Comment by daiClegg** [comment]
Did you get any resolution of the sheet 10/sheet 9 discrepancy?

**Comment by dbrownukk** [comment]
Blank row was returning a Null not a blank 

Apache POI overcomes by returning null as a BLANK 

cell[k][i][j] = sheet.getRow(i + 3).getCell((j + 1), Row.CREATE_NULL_AS_BLANK);

Also checked if next row is null

**Comment by daiClegg** [comment]
Cannot reproduce.
