### ISSUE TITLE
Wealthgroup - does it have a name

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#14]
In the example spreadsheets (5_Community_MengoMpungo_James )
the Wealth Group Characteristics sheet has Wealth Group names as well as the English and Local name 

i.e. in Row 2 we have 
  | Wealth Group 1 | Wealth Group 2 | Wealth Group 3 | Wealth Group 4 | Wealth Group 5

this is not modelled - should it be?? or are they always named as above?

**Comment by daiClegg** [comment]
The Wealth Groups are usually described as "poor", "middle" & "Better off", with sometimes a "very poor"  in the reporting/analytics. These are the commonly used English names.
The local names are whatever the interviewers are told in the Community interview that identifies the groups for that community. They would be used locally, but generally not in the analysis.

The template spreadsheet is pre-designed with 5 wealth groups (as noted) cos that's the most anyone has ever found. And it allows correlation between the different worksheets.

So in answer to the question: the English names are the ones normally used in processing the data, the local names for communication locally when collecting data and the numbered Wealth Groups just to correlate the data in the spreadsheets. Make sense?

**Comment by dbrownukk** [comment]
Dai,
This appeared as an issue because I have a module for Wealth Groups which does not have any context on te screen, thus a list of 'Poor' Wealth Groups looked wrong.
If we can only create/edit a Wealth Group in the context of a Community then everything makes sense.
I will remove the standalone Wealth Group module.
Hoping to put a new version up today on the Reading server. Several changes and validations now in place and should have the spreadsheet creation fixed.. all being well
David



    On Tuesday, 2 January 2018, 18:36:53 GMT, dai clegg <notifications@github.com> wrote:  
 
 
The Wealth Groups are usually described as "poor", "middle" & "Better off", with sometimes a "very poor" in the reporting/analytics. These are the commonly used English names.
The local names are whatever the interviewers are told in the Community interview that identifies the groups for that community. They would be used locally, but generally not in the analysis.

The template spreadsheet is pre-designed with 5 wealth groups (as noted) cos that's the most anyone has ever found. And it allows correlation between the different worksheets.

So in answer to the question: the English names are the ones normally used in processing the data, the local names for communication locally when collecting data and the numbered Wealth Groups just to correlate the data in the spreadsheets. Make sense?
