### ISSUE TITLE
Capture exchange rate for Asset of type Cash if it is not in a Project-defined currency

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#141]
WG Interview data can include Assets of type  "Asset - Cash". The currency is also recorded.

However, when valuing such an asset for reporting or other analysis an exchange rate is needed for anything except the base currency of the Project, which is the currency of the Country where the LZ under survey is.
There is the capability to record an alternative currency for a Project and a nominal exchange rate for the project.

The problem arises if a Cash asset is recorded in any other currency.
There is no way to value it. So it must be rejected.
Domain experts have asserted that this never occurs, so just flat rejecting it, to protect the integrity of reports, is the only way to go.

The user workaround would be to convert the currency in the WGI record before validating.
Not a good solution but the only one possible, i think.

**Comment by daiClegg** [comment]
see Issue #92 for where this is relevant.

**Comment by daiClegg** [comment]
Feature for OIHM

**Comment by daiClegg** [comment]
Would it be possible to generate validation into the interview spreadsheet to warn the user if they are entering a currency that is not the Project Currency or the Alternative Currency?
And require that they enter the exchange rate if they do so.

 Something like the attached:

[CurrencyValidation.xlsx](https://github.com/dbrownukk/EFD_v2/files/2881083/CurrencyValidation.xlsx)

That way upload just has to check there is an exchange rate and store it.

**Comment by daiClegg** [comment]
I f a cash asset is not in the project currency or the project alternative currency, then an exchange rate for it, into the project currency, must be captured

**Comment by dbrownukk** [comment]
For OHEA and OIHM 

added Exchange Rate to Template Spreadsheets in Cash Asset tab

On parse - 

1. Is entered Currency valid  (in list of currencies)
2. If it is not LZ Currency then in  
OHEA - is it Project Alt Currency or in 
OIHM is it Study alt currency.

if it is then use entered exchange rate for the asset, set the currency to whatever is found in point '2' above and multiply by exchange rate and save amount in core currency.

**Comment by daiClegg** [comment]
```
If       the Currency is valid (Parse check 1 above)
  and    is neither of LZ currency nor the alternative currency (Parse check 2 above) 
  then   the exchange rate must not be null or zero, nor can it be -ive.  It might legitimately be 1.

```

**Comment by daiClegg** [comment]
The WGI & HH records should include the entered exchange rate, in addition to the currency, & amount. 
Applying the conversion at data load time, rather than at report time is fine.

**Comment by dbrownukk** [comment]
Calculation

If spreadsheet cash tab entered  currency is same as LZ currency then exchange rate is set to 1

If entered currency is same as Project alt currency then use Project al exchange rate (similarly for Study in OIHM)

else validate currency exists and use entered exchange rate. 

Is the standard to divide or multiply? Assuming multiply.

**Comment by daiClegg** [comment]
That looks right to me.
And i agree - assume multiply to exchange.

**Comment by dbrownukk** [comment]
Implemented in OIHM and OHEA - to be deployed

**Comment by daiClegg** [comment]
Steps to test:
(alternative currency use)
1. Create 2 projects (A & B) both with currency UGX, one (B) with alt currency USD & an exchange rate.
2. Create a HH spreadsheet for each with cash in UGX & USD 
3. Set no exchange rates in the spreadsheets
4. Load the HHs

A should fail, B should pass

(test additional currency)

1. Copy the HH for project B spreadsheet
2. Edit the HH details to make sure they are unique
3. Add a 3rd currency to with no exchange rate
4. Load HH2 for B

Should fail.
 

1. Add an exchange rate in the spreadsheet
2. Load HH2 spreadsheet

Should succeed

**Comment by daiClegg** [comment]
**Note for further thought:** 

- what should happen if the Project & the Study have different Alternative Currencies?

**Comment by daiClegg** [comment]
Created Studies: 'Currency Test A' & 'Currency Test B' as step 1 of alternative currency usage test above.

**Comment by dbrownukk** [comment]
For clarity, when Country appears in LZ I have added Currency for the country.

**Comment by dbrownukk** [comment]
We have 3 potential currencies now. 

1. LZ Currency associated with a Project that a Study or Community is part of
2. A Project Alternative Currency
3. Any other Currrency and Exchange rate that is entered (EnteredCashCurrency)

If LZCurrency = enteredCashCurrency then ExchangeRate = 1.00

If Project Alternative Currency = enteredCashCurrency then ExchangeRate = Project Alternative ExhangeRate

else

ExchangeRate = EnteredExchangeRate

Amount is calculated and displayed as Total Amount Entered x ExchangeRate

**Comment by daiClegg** [comment]
Instance: EFD_HM
App:        OIHM
Module:  Study

In List view select Study "Currency Test A"
Select Edit Project (Currency Test A)
> Note alternative currency USD & Exchange rate are specified
> not visible in this view, but the LZ of the site is in Uganda - hence Study Currency is UGX
Exit Study module
Invoke HH module
In list view filter on Study "Currency Test A"
Select the only HH
In detail view, navigate to Cash Assets
> note 2 assets UGX & USD - valid and correctly specified.
Exit HH module
Invoke Study Module
Select Study "Currency Test C"
Select Edit Project (Currency Test C)
> Note alternative currency is not specified
> not visible in this view, but the LZ of the site is in Uganda - hence Study Currency is UGX
Exit Study module
Invoke HH module
In list view filter on Study "Currency Test C"
Select the only HH
In detail view, navigate to Cash Assets
> note 2 assets UGX & USD - valid with USD exchange rate 0
>the USD Cash asset should have been invalid

>

**Comment by daiClegg** [comment]
Instance: EFD_HM
App: OIHM
Module: HH

_Test Additional Currency_

1. In list view filter on Study "Currency Test A"
2. Select the second HH
3. In detail view, navigate to Cash Assets

> note 3 assets UGX, USD & GBP - all valid 
> GBP has zero exchange rate

**Comment by daiClegg** [comment]
The problem seems to be that the parse is accepting the zero exchange rates from the spreadsheet, which is the value generated into the cell.

Parse should not accept zero as an exchange rate.

**Comment by dbrownukk** [comment]
I think to be consistent with other validations the zero exchangerate is accepted in the spreadsheet but the Parse and Validation scripts identify the zero value and set row to Status Invalid

**Comment by daiClegg** [comment]
That's fine by me, but if the currency of the uploaded cash asset is either the Project currency or, if defined, the Alternative currency, then no exchange rate will have been entered & it will upload a zero value. This is not invalid since there is no conversion to do. For the Project Currency, it's effectively 1 and for the Alternative Currency, the exchange rate to apply is already defined elsewhere. Make sense?

**Comment by dbrownukk** [comment]
Yes, that is what it does.  Sets exchange rate to 1 if in currency of project, else uses alt currency exchange rate if that is entered.

deployed

(Note that Amount is not persisted. getAmount() performs calc and is used instead of Amount)

**Comment by daiClegg** [comment]
Instance: EFD_HM
App: OIHM
Module: HH
Study: Currency Test A

Loaded the same spreadsheet again (new HH) and the 3rd currency parsed as Invalid, as expected.

Instance: EFD_HM
App: OIHM
Module: HH
Study: Currency Test C

Loaded spreadsheet into new HH with a valid exchange rate for a non-specified currency.
Parsed as Valid, as expected


**Tested Ok**
