### ISSUE TITLE
Possible to change Validated WG Interview data

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#142]
After validation, you can change the resource sub-type for an entered resource and it is accepted and reflected in the report.

I suspect this is not intended but is it acceptable? For example, i changed "Tangawizi" to "Ginger".
They are both in the database, as synonyms. So it is semantically correct. But is it a bit dubious?

Comment from David:

getView().setEditable("propertyName",false);

In which case, we should set all validated wealthgroup details to be non updateable. To update you would reset the WGI status to anything other than 'Validated' and then go to a resource item and set line status to Invalid so that it can be edited.

Response from Dai:

Re-setting from Validated to Parse to unlock would then make it a deliberate action.
That would eliminate any accidental editing.

Sounds like a good resolution. I will propose it.
let's discuss when we meet on Wednesday.

**Comment by daiClegg** [comment]
Can also add new resources to validated WGIs. 
This should not be allowed.

**Comment by daiClegg** [comment]
Maybe an access-controlled feature to set back to fully Parsed in order to modify data.

Should it be possible to set any other status after 'validated' - no.

**Comment by dbrownukk** [comment]
This is how I have coded this.

1. If WGI Status != 'Validated' and a user manually changes to 'Validated' using the LOV then it is rejected and User is told to run Validate script.

2. Run Validation script - If Valid then Status is set to Validated and WGI set to Read Only

3. All Validated WGIs are set to ReadOnly. A button 'Set Editable' appears for all 'Validated' WGIs. This could be controlled by role, but is a deliberate act to set the whole WGI to editable.

**Comment by daiClegg** [comment]
Tested OK.
I like the UX.

Noted the hint text issue.
If there is anything to do when the OX bug is fixed, use a new issue for that.
