### ISSUE TITLE
Access Control Model

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#143]
Need to define and setup the access control model
OX has Users, Roles, Folders and Modules. We can exclude actions and specific data from a role. Users are given a role. More complex than we probably need but needs defining. 

i.e.
Team Leader - can create Resource Sub Types 

Main Users can create and edit most data - they own (entered?)

View Only User

**Comment by daiClegg** [comment]
First step is persona analysis - who are the different roles? What do they want to achieve? How  do they differ? 
I'm of a mind to build a matrix of roles and features and have C & J fill it in.
The matrix would differ between networked & standalone instances.

Might need to agree processes (e.g. adding resources in standalone)

**Comment by daiClegg** [comment]
some specifics of this need to be included for M4, but not necessarily the whole model, so wil leave this out of M4 & reference this issue from specific roles work for M4

**Comment by daiClegg** [comment]
We have used the current use of Roles with users successfully.
We may need to tweak it and we may need data-constrained access (#207) but right now we have a successful access control method in place
