### ISSUE TITLE
Calculate Disposable Income for HEA

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#145]
Need calc for Disposable Income and where to include it

**Comment by daiClegg** [comment]
I have that and will add here.
When we have it double check with C & J before implementing.

But also need to understand where it is used/
The reason i hadn't documented it already is because there was no feature that needed it.

Is this a new report feature?

**Comment by daiClegg** [comment]
Need to find out where it is exposed except in modeling.

**Comment by daiClegg** [comment]
Disposable income calculation:

Disposable Income (DI) = Total Income (TI) - Cost of covering shortfall in Required Calories (RC) from Own Production (OP).

TI = 
    Sum(Units Sold * Price per Unit) for all  Crops, Wild Foods and Livestock Products 
 + Sum(Units Worked * No. of People Working * Cash Payment) for all Employments
 + Sum(Cash Transfer Amount * No. of People receiving * No. of Times Received) for all Cash Transfers

RC = 2100 * 365 * No. of People in Household 

OP =
    Sum(Units Consumed * KCal per Unit) for all Crops, Wild Foods and Livestock Products 
 + Sum(KCal per Unit of Food Type * No. of Units Paid) for all Employment paid in Food
 + Sum((KCal per Unit of Food Type Transferred * No. of Units Consumed) for all Food Transfers
 
tbc...

**Comment by daiClegg** [comment]
There is no current requirement to calculate disposable income except in modeling.
However, it will be needed at some point so not closing this; put it in the icebox for now.

**Comment by daiClegg** [comment]
Assigning to M2. See Std of Living calc (issue #233) for rationale.

**Comment by celiapetty** [comment]
Re agric input costs: these are recorded for crops, livestock, fishing (see extract from IHM interview form attached). In the current version of IHM they are deducted from DI . They must be retrievable in reports.  I agree with John's suggestion that they should
[IHM hhold interview template crops.docx](https://github.com/dbrownukk/EFD_v2/files/2857237/IHM.hhold.interview.template.crops.docx)
 be reported separately . This would allow the user to look at each hhold's input costs  and do whatever further calculation they wish

**Comment by daiClegg** [comment]
Not testable until HEA includes a feature that uses DI, so closing as feature complete.
Will log separate issues for anomalies, when the DI calculation is used in HEA reporting.

**Feature Complete**

**Comment by daiClegg** [comment]
I have edited the layout of some formulae in my 22nd October post because the layout was confusing, i think. Hopefully, it's more clear now.
