### ISSUE TITLE
Export all data for a Project to a spreadsheet 

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#146]
This would use existing views and a report to create xls for all data for a project

**Comment by daiClegg** [comment]
It should also meet the need for the modelling data extract.

**Comment by daiClegg** [comment]
Shoul dalso meet the need for #136

**Comment by daiClegg** [comment]
Should include any calculated values available, to save re-coding them in excel, where they will almost certainly also be needed.

**Comment by dbrownukk** [comment]
view and report virtually there - problem exceeding Java Heap - puzzling that out....

**Comment by dbrownukk** [comment]
deployed. Available from Project module detail

(Suspect it should be available from Community and WGI modules?)

**Comment by daiClegg** [comment]
Tested ok, but will need user testing.
Will close this for now and create new issue or re-open if user testing necessitates
