### ISSUE TITLE
Add field to store Interview notes file 

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#155]
Probably more generic - add many files to an Interview or Project (anything else?)

**Comment by daiClegg** [comment]
The interview notes file is a template that the interview uses  to capture their notes  during the course of a WG interview.
The notes are then transcribed into the generated WG Interview template spreadsheet for uploading.

But thinking about this some questions occur to me: 
Is this printed out and a hard copy used in the interview? 
If not the implication is that a Word doc is being edited in the interview. That is not the impression i've got about how WG interviews are conducted.
If so, and the interview notes are written by hand onto the paper copy then it needs to be scanned or photographed to upload. 
From an OHEA perspective there is little difference, as long as we can accept and store a .doc or a.jpeg or other image file formats. I guess that means blob not clob.

I will clarify anyway, just for our understanding

**Comment by daiClegg** [comment]
John's comments:

> Additional information is in the form of  images and existing documents e.g. ther local studies and at least historically reports written fro the data.So the study team should be able to upload or cut and paste any files which are relevant  to the area. There are many unpublished documents which are relevant to the future use of the data for modellng.

**Comment by daiClegg** [comment]
John has clarified that Notes should also be attachable to Project, Community, & WGI.
I would define the requirement as the ability to upload documents.
How many is not specified.

There might easily be 5 or 6 i guess. If we need to set a limit then 10 should be comfortable.

I would suggest best practice would be to name the files meaningfully so that they can be identified just from their names in OHEA.

**Comment by dbrownukk** [comment]
Project done - to do Community and WGI

**Comment by dbrownukk** [comment]
Added 'Notes' field to WGI, Project and Community - multiple files can be added - names are displayed, thus indicative content file names should be used.

**Comment by daiClegg** [comment]
Tested ok with multiple small files. (on project_ 
delete attached file works ok.
Tried attach of one small and 1 big (100mb) files, (no community)
No waiting cursor.
After a while i tried cancel; cancel button appears to be live (ie visual feedback of the press..
But cancel was not immediate.
Tried 'X' to close the file selector popup.
This worked (or maybe the Cancel, eventually?)
Returns to the detail view; no attached files shown, but the page is still loading and is unresponsive.
Stopped the page load; appears to be ok.
Requested Reload.
Wipes the old page. paints the header, then goes into a very interesting state - browser reload wait cursor is in overdrive & not responding to a stop load request.
had to close the tab.
Logged out & logged in . Community record as expected - no load.


definitely, need some feedback during load of a sizeable file .
also need Cancel & close popup buttons to respond quickly and/or provide feedback

**Comment by daiClegg** [comment]
Closing this as fixed since the functionality is as required. Will log the issue about handling feedback during load of very large files separately as an Enh.
