### ISSUE TITLE
DIsallow manual change of WGI to Validated  

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#156]
Change of a WGI to Validated should only be possible using the Validation action

**Comment by dbrownukk** [comment]
If you manually change a Wealthgroup Interview status to 'Validated' you get an error that you can only set to Validated using the Validate Asset Data button. The Status is set back to whatever it was before the change to Validated.

There is no way to remove an individual value from the LOV - well, there probably is but it requires creating another LOV and switching between them.

Deployed

**Comment by daiClegg** [comment]
Tested ok
