### ISSUE TITLE
Hover over a field/label and get extra info  - is this possible?

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#158]

**Comment by dbrownukk** [comment]
Form OX docs 

Tooltips
To define a tooltip add the suffix [description] in the labels i18n file of your project, for the element (action, property, etc) where you want the tooltip. For example, with next entry in your labels file:
Warehouse.number[description]=Id number of the warehouse
You get:
tooltip_en.png

Since v5.8 if the label and the tooltip matches the tooltip is not shown.


-- thus, the tooltip text will need defining

**Comment by daiClegg** [comment]
Action: ask C & J for what they want to see for any problematic fields on any screen.

Need to know the maximum character count first.
If no maximum, will go with 80 characters.

**Comment by daiClegg** [comment]
Since this issue was opened in August no requirements for tooltips have emerged, so closing this issue.
