### ISSUE TITLE
Food Consumed Chart includes unnecessary entries in Legend

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#159]
Employment types should only be included if there is payment for the employment in food (crop, wild food, food purchase). This is indicated by non-zero values in the FoodPayment Food Type and Food Payment Unit fields.

Livestock is not consumed so should be excluded.

Livestock products should be included if there is a non-zero value for Units consumed.

**Comment by daiClegg** [comment]
Widened the scope of this issue to cover other aspects of the report:


Report is not including Food Purchases. See:

Project:Mukono New Test
LZ: Banana Coffee Piggery 
District: Mukono 
Sub District: Ntenjeru 
WG: Middle

There are multiple food purchases but they do not seem to be represented.
I checked the RSTs have valid KCals.


To summarise:

Food consumed comes from the Crops. LS Products & Wild Foods that are not sold 
Plus Food Purchases
Plus Food Transfers & Employment that are paid in food. In both these cases the food type is specified.
Note this means that validate should check that the Food type for Transfers and for Employment, if specified is a valid Crop, Wild Food, Pood Purchase or Livestock Product type 
That is Issue #162 .

And where an employment or transfer is in food or part in food, it is the Food type, not the employment or transfer type, that should appear in the legend.

**Comment by dbrownukk** [comment]
Crops  = (Number produced - Number Sold) * KCal
LSP = (Number produced - Number Sold) * KCal
WildFood = (Number produced - Number Sold) * KCal
Food Purchased = UnitsPurchased * KCal

**Comment by dbrownukk** [comment]
deployed

**Comment by dbrownukk** [comment]
Looking at the chart, is it not better to understand where the Food Consumed comes from? Setting the Employment gained food to 'Crops Coconut' would hide the fact that it was gained through employment - it would look as though they had grown the coconut.  

I have changed the view to include the Resource Type of the payment food type and set this example to be:-

Employment Crop Coconut 

Does that make sense?

**Comment by daiClegg** [comment]
This makes sense.
I've tested, creating some variant test data on 
Project: Mukono New Test
LZ: Banana Coffee Piggery 
District: Mukono 
SubDistrict: Nakisunga

It works well for Employment paid in food and for Transfers in food.

Very nice.
