### ISSUE TITLE
Displaying a map of a LivelihoodZone

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#16]
LivelihoodZone in the design model has a placeholder property for a map.
If we have a map as an image how best can that be uploaded and displayed?
(.pdf? .png? .jpg?)

**Comment by dbrownukk** [comment]
Very doable - there is a File stereotype. I doubt it will display an interactive map but definitely can store a file and display it. On the list

**Comment by dbrownukk** [comment]
changed    @Column(name="LZZoneMap",length=250) 
                  private String lzzonemap;
   
to 

 @Stereotype("IMAGE")
    @Column(length=32)
    private String lzzonemap;

it displays the image - which obviously could be a map..

![map](https://user-images.githubusercontent.com/12796427/34794328-38897372-f646-11e7-959a-702fe0bc4624.PNG)

**Comment by daiClegg** [comment]
Looks good; not deployed yet though? Let me know when it is and i'll test & close.

**Comment by dbrownukk** [comment]
Deployed

**Comment by dbrownukk** [comment]
Created a new Label - For Testing - can remove if OK

**Comment by daiClegg** [comment]
David,


The ‘Testing’ Label if ve helpful. Good idea.
I’ve tested the map loading and it’s ok. issue is now closed.

cheers
dai
