### ISSUE TITLE
WGI assets and resources - RST LOV is wrong

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#161]
The RST LOV must only show valid RSTs for the particular asset or resource.

i.e. Food Stock asset had a drop down list that included Food% - namely RSTs for 'Food Stocks' and 'Food Purchase'

If you choose a Food Purchase RST in the Food Asset Tab and record the Food Asset with a RST from the Food Purchase RST then the data is a mess (I think..) 

Came to light in the reports/charts

Dai - correct me if I am wrong before I change the RST LOV

**Comment by daiClegg** [comment]
the valid values will have different constraints in different places.
I need to go through all the tabs ad specify for each one.

**Comment by daiClegg** [comment]
Validation notes attached.

[WGIResourceTabsValidation.xlsx](https://github.com/dbrownukk/EFD_v2/files/2352393/WGIResourceTabsValidation.xlsx)

**Comment by dbrownukk** [comment]
Done all but AssetCash - navigating back to Project/Country/Currency and Project/AltCurrency to get two currencies is a chunk of work to code and test.

**Comment by dbrownukk** [comment]
Need to check spreadsheet generation - Transfer TransferType is now an Enum with 3 values.

Yet to deploy

**Comment by dbrownukk** [comment]
spreadsheet creation works - changed to handle the enum

**Comment by daiClegg** [comment]
Enum on Transfers: Tested Ok.

Livestock Products: Allows Livestock Products (correct) and also Livestock (incorrect). If Livestock are sold, they appear separately in Livestock Sales 
Transfer: Transfer food/other type does not allow Other Tradable Goods; it should - someone might give me a bicycle


Everything else Tested OK.

**Comment by dbrownukk** [comment]
Removed Livestock from Livestock Products

Added Other Tradeable to Transfers, 

though I need to figure out how to change the label in the ElementCollection - no documentation on this and the *.tab in i18n file not working. Label should not just say "Resource Type of Food resource sub type " if you can add a wheelbarrow - a Wagonwheel would be ok...

**Comment by dbrownukk** [comment]
not deployed yet

**Comment by daiClegg** [comment]
See also issue #193 

eave this ope until that is resolved

**Comment by daiClegg** [comment]
From the thread on issue #193: 
> we don't allow Livestock Types in Food Purchase and LivestockProduct Sales.

Tested OK.
