### ISSUE TITLE
Food type for food type Transfers and for Employment paid in food, should be valid

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#162]
Validate should check that the Food type for Transfers and for Employment, if specified, is a valid Crop, WildFood, Pood Purchase or Livestock Product type.
These will be used in the Food Consumed report

**Comment by dbrownukk** [comment]
Fixed read only Food RST in Employment LOV which was appearing as Hex number in readonly mode

**Comment by dbrownukk** [comment]
Food for 

Employment checks for valid Crop, Wild Food, Lisvestock Product or Food Purchase

Transfer does the same

Units are also validated and if incorrect marks row as INVALID

**Comment by daiClegg** [comment]
tested Ok.
Also noted use of "?" as a default - which failed validation until i changed it.
