### ISSUE TITLE
Validate amounts  for Crops. Livestock Products, Transfers & Wild Food

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#163]
The spreadsheet tabs for Crops. Livestock Products, Transfers & Wild Food include fields for Units Produced , Units Sold, Units Consumed and Units Other Use..

In all cases the following validation is required:

Units Produced  = Units Sold + Units Consumed + Units Other Use.

Note: This could possibly be caught in the spreadsheet before uploading?  That would be helpful to interviewers, but we'd still need the validation at Validate time (or Parse?) to protect against someone messing with the spreadsheet.

**Comment by dbrownukk** [comment]
Using @Depends for unitsConsumed in the WGI module - do not want to change spreadsheet generation at this point before the training.

**Comment by daiClegg** [comment]
This now appears to work well; i tested a spreadsheet with no consumed/sold/other use values and the Consumed value in the uploaded record is was the units produced - as expected.

Will mark for discussion as requested.

**Comment by daiClegg** [comment]
Added to OIHM.
Will spec the validation as part of OIHM HH Interview spreadsheet 
Will test if it works in OHEA - as is implied by a comment above , in which case this issue is fixed for OHEA and it's only #172 that is outstanding there.

**Comment by daiClegg** [comment]
The validation is not there in OHEA spreadsheet and the columns are still in the original order.
As expected.

The validation in the App does work.

If this enhancement is implemented in OHEA it will render all test data invalid - because of the column changes.

So we either have to do this before production or it might be very disruptive to do later.

**Comment by daiClegg** [comment]
In OIHM:
- the spreadsheet column sequence is correct (see #293)
- the Units Consumed column is not validated in the spreadsheet
- the Units Consumed column is calculated on Parse and any uploaded content ignored

This is satisfactory.
Leaving open as an Enhancement of OHEA and adding to OHEA bug sprint milestone

**Comment by dbrownukk** [comment]
OHEA M5 fixes

Crops, LSP, Transfers, Wildfoods

1. In Wealthgroup Interview Module, each of above has corrected order of fields and calculated Units Consumed
2. Creation of OHEA Template spreadsheet from Community Module has corrected order of columns in each of above. Also, now has a Version number on first worksheet to inform correct spreadsheet template is used in parse.
3. Parse of a populated spreadsheet - now parses correct values in the correct order from a template. However, this does mean that older style (pre this fix) spreadsheets will not parse correctly. They should parse but data may not be in the correct column...

**Comment by daiClegg** [comment]
Bug noted on Jan 18 re exception after editing Other Use is **Tested OK**

**Comment by daiClegg** [comment]
After discussion...

Parse to reject any spreadsheet that is not at the latest version to avoid the problem identified in point 3 of @dbrownukk most recent comment.

**Comment by daiClegg** [comment]
Testing of changes documented in  @dbrownukk most recent comment

1. In Wealthgroup Interview Module, each of above has corrected order of fields and calculated Units Consumed
>**Tested OK**
2. Creation of OHEA Template spreadsheet from Community Module has corrected order of columns in each of above. Also, now has a Version number on first worksheet to inform correct spreadsheet template is used in parse.
> Blocked by Issue #336
3. Parse of a populated spreadsheet - now parses correct values in the correct order from a template. However, this does mean that older style (pre this fix) spreadsheets will not parse correctly. They should parse but data may not be in the correct column...
> BLocked by #336

**Comment by daiClegg** [comment]
D'oh. Yes of course. I had forgotten the workflow is subtly different than for HHs in OIHM.
But i agree that the New button should go.

**Comment by daiClegg** [comment]
Outstanding anomaly (from comment 3 days ago by @daiClegg 

Instance:   EFD_HM
App:           OHEA
Module:     WGI
Project:      UIPath Test
WG:            Poor

The attached spreadsheet has "Spreadsheet Version 1" as its version number.
Parse to reject any spreadsheet that is not at the latest version...

**Not yet implemented **

**Comment by daiClegg** [comment]
Fixed in OIHM by #340

**Comment by daiClegg** [comment]
Could Have for OHEA in OHEA M5

**Comment by daiClegg** [comment]
Spreadsheet version number  Tested Ok.

Is the rest in scope for OHEA M5? 
Currently can still  create & validate negative units consumed

**Comment by daiClegg** [comment]
> Is the rest in scope for OHEA M5?

Yes, but only when #340 is done & tested for OIHM, cos this will be a backport of that code.

**Comment by daiClegg** [comment]
#336 & #340 are now closed, so the block is cleared.
Will re-test, since it's not immediately clear whether this should now all work.

**Comment by daiClegg** [comment]
All anomolies identified above have been  **Tested Ok**
