### ISSUE TITLE
Normalisation calculation in reports appears to be faulty

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#165]
Normalisation appears to be done by size of the household of the Poor WG for all WGs.
It should be by the HH size of each respective WG.
This appears to be the same in all the reports.

**Comment by dbrownukk** [comment]
logic was wrong trying to parameterise reports 
Need to use condition on Value i.e. in Food Assets:
$P{wgAverageNumberInHH}==1?$F{xx}/$P{wgAverageNumberInHH}:
$F{xx}/$F{WGHHSize}.intValueExact()

**Comment by dbrownukk** [comment]
It was not WGHHSize - this is in the community WG template - should use wgAverageNumberInHH from WGI 

Created normalise boolean in Java call of report - then use condition in chart value calc.

deployed

**Comment by daiClegg** [comment]
First test on:
Project: Mukonu NewTest
LZ- Banana Coffee Piggery 
District - Mukono 
SubDistrict - Ntenjere

Assets appear correct , but no ash assets to test,

**Comment by daiClegg** [comment]
I tested on the same community as above.

Food Consumed 
  - tested ok

Non-Food Purchases 
  - report says "No Validated Wealthgroups for this Community"
  - in fact there are validated wealth groups, but they have no non-food expenditure.
  - so the report correctly identifies it has no data, but the explanation is deceptive
  - suggest "No data is available for this report" 
  - or           " No data is available for non-food expenditure" where the report title is parameterised .

Food Consumed
 - tested ok

 Cash Income
 - tested ok

Re-tested Assets:
 - I'm not sure what's going on here, but it may be affected by issue #167.
 - In the Livestock/Trees/Tradables/Cash chart, while the Better Off WG is, overall, normalised correctly, the individual assets as a proportion of the whole are different between the non-normalised & normalised reports. 
  - The Poor & Middle groups appear not to be normalised correctly (divided by 2 not by HHsize)

**Comment by dbrownukk** [comment]
tested on Project: Mukonu NewTest
LZ- Banana Coffee Piggery
District - Mukono
SubDistrict - Ntenjere

Assets are divided by relevant WG Average Number in Household

Better Off and Middle Land = 10 acres

BetterOff Average in HH = 9 
Middle Average in HH  = 7

giving different results in asset chart for Land
 
Changed no data message in nonfood expenditure chart

**Comment by daiClegg** [comment]
Testing on:

- Project: Mukonu NewTest
- LZ- Banana Coffee Piggery
- District - Mukono
- SubDistrict - Ntenjere

**Food Consumed:** Tested OK.
**Non-Food Expenditure**: Tested as expected - correct no data message.
**Food Expenditure**: Tested Ok.
**Food Consumed**: Tested OK
**Cash Income**: Tested OK
**Assets**: Tested OK

Need to test missing data categories.

**Comment by daiClegg** [comment]
**Non-Food Expenditure:** :Tested Ok. on  Project Test251018
**Assets:  (food & Cash)** :  Tested on :
Project: est251018
LZ: Test251018LZ2 
District: td1 
SubDistrict: tst1 
WG test2 - has a stock of maize
But he report says: " No Validated Wealthgroups with Food Stocks for this Community"

Cash holdings - to be tested.

**Comment by daiClegg** [comment]
All testing for Issue #167: Tested ok

**Comment by daiClegg** [comment]
whoops forgot Cash

**Comment by daiClegg** [comment]
See latest testing (29th Oct) in #issue 167

**Comment by dbrownukk** [comment]
Tested in Test251018 Test251018LZ2 td1 tst1

Cash of 5000 GBP appears 

Test6, Average number in HH = 10

Normalised Cash = 500

Note that I have added values and Average HH number to the report - appears too small on this example that has 6 WGs

**Comment by daiClegg** [comment]
Project: ngombre (was Mukono New test)
SubDistrict: Nakisunga

Cash Income                 - Tested Ok.
Assets                            - Tested Ok.
Food Expenditure          - Tested Ok.
Non-Food Expenditure  - Not Tested. none in this Community (see below).
Food Consumed            - Tested Ok.



Project: Mukono Trial
SubDistrict:  Mugomba/Mpata

Non Food Expenditure - Tested OK.
