### ISSUE TITLE
RST name in WGI module displayed as hex string if WGI has been validated

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#166]
The display is all correct throughout the data editing process, but once Validation has succeeded theRST names are all displayed as hex strings
.
See attached

![image.png](https://images.zenhubusercontent.com/5a81590c4b5806bc2bc688fc/3a871aff-0a0b-4ad9-b95a-e9141ac329d1)

**Comment by dbrownukk** [comment]
Raised a bug with OpenXava - the problem is created by setting the element collection reference to read only. Scheduled to be fixed in 6.0.1.

Will try and find a workaround..

**Comment by daiClegg** [comment]
Tested Ok - and updating of WGIO status to Fully Parsed on setting editable.
