### ISSUE TITLE
 Assets chart for Livestock, Trees, Tradeable, Cash appears to be counting rather than valuing assets

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#167]
All these asset types have a value.
For  Livestock, Trees & Tradeable Goods, the value is the number owned * the price per unit.
For cash, it's the number - if the currency is the project currency.
or it's the number * the Project.Alternative Exchange Rate if it's the Project.Alternative Currency.
(note this assumes no other currency is held. That should be validated on entry. (see Issue #168 )

**Comment by dbrownukk** [comment]
Report Y axis was using wginterview_assets view column xx instead of 'amount'

**Comment by daiClegg** [comment]
Testing on Project: Test251018
LZ: Test251018LZ2
District:  td1 
SubDistrict:tst1 
WG: test6

This WG has a cash asset. But the Assets report shows it as value 0
This may be something to do with the fact that all the WGs have all their Livestock assets as price per unit =0.

**Comment by daiClegg** [comment]
I retested and set the currency to GBP. This time it showed up properly.
However, i don't know why it didn't load from the spreadsheet; i had to set all the values in the app.
Will log that as a separate issue

**Comment by daiClegg** [comment]
Tested On:

Project: Mukono - New Test.
LZ: Banana Coffee Piggery 
District: Mukono 
SubDistrict: Nakisunga 

Assets Foodstock 
-------------------

shows Food Assets correctly, but shows a spurious Food Purchase Item for both BetterOff & MIddle Groups.

OnlyFoodStore Assets should show on this page of the report(Food Purchases are not Assets)

Assets - Livestock, Trees, Tradeable, Cash
-------------------------------------------

does not appear to be normalising correctly.
not clear to me what's happening but Cash in normalises, bu others not in the same proportions

**Comment by dbrownukk** [comment]
Asset Foodstock - spurious data 

Seems to be confused with Maize as a Land type!...

Edited the data and reparsed spreadsheet and set all to Valid 

reran reports and spurious data has gone, now for normalisation problem..

Debugging HHAverage and normalisation 

Project: Mukono - New Test.
LZ: Banana Coffee Piggery
District: Mukono
SubDistrict: Nakisunga

Set Average Number in Household
Poor 10
Middle 5
Better Off 2

Normalised 

Cash for Better Off 50,000 Normalised to about 5,000 i.e. looks as though normalised by HHAvg for Poor  -- Wrong 

BO Food stocks 50kg Meat , normalised = 7 - which is Wrong and confusing

Middle Land - 3 acres, normalised to 0.5 acres - wrong and again confusing

**Comment by daiClegg** [comment]
Tested Ok

**Comment by daiClegg** [comment]
See Issue #165 for normalisation testing.

Tested on: 
Project: ngombre (was Mukono - New Test)
SubDistrict: Nakisunga

Tested Assets - Food Asset is now reported correctly. - Tested Ok.
