### ISSUE TITLE
WealthGroup Income report does not include corrected fields from parse operations

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#169]
Project: Mukonu - New Test
LZ: Banana Coffee Piggery 
District: Mukono 
SubDistrict: Nakisunga 
WG: Better Off

Note this WG has a wild foods entry of "Jackk Fruit" that is corrected in parsing to "Jack Fruit"
In the export, the entered data is included, but the corrected data is not.

Steps to reproduce:

- Run the wealthGroup Income report for this WG
- Open the export in Excel.
- Search for "Jackk"; it will occur in this WG's data
- Search for "Jack Fruit"; it does not occur.

Note that the Project Export report *does* export the correct data: ie ResourceSubType Name, not entered name.

For the Disposable Income model i am working on i only need one WG.
Extracting the appropriate data inside Excel is proving challenging so i would prefer to have the single WG export, if it's just a matter of correcting the view it uses.

**Comment by dbrownukk** [comment]
An earlier fix to the View has fixed this I believe. 

Resource Sub Type Name = Jack Fruits 
Entered Name = Jackk fruit

**Comment by daiClegg** [comment]
Sorry, i had added another issue in here; the issue of Food Type for transfers.

In this WG, there is a Transfer of type Food. 

The TransferFoodOtherType is reported; that is the entered food type; in this case it's null.
The Food Resource SubType, in this case NIle Perch (hand-corrected in the Parse phase), is not exported.
You can verify this by searching for 'NIle Perch' in the export spreadsheet.

**Comment by dbrownukk** [comment]
Also fixed the Resource Type Food resource sub type to display correctly when not editable - it was displayed as a hex string...

Added foodResourceSubType to view - now in WG Income report, second to last column

**Comment by daiClegg** [comment]
Tested Ok.
