### ISSUE TITLE
Livelihood Zone module should be master/detail with its Sites

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#17]

**Comment by daiClegg** [comment]
LZ module needs a detail - Sites will  normally be created from Communities when including them in a Project, but if a user is viewing, or editing an LZ they will expect to see and be able to edit the Sites intheat LZ.

Think of it as Towns in a county

**Comment by dbrownukk** [comment]
Put LZ in Site detail

**Comment by daiClegg** [comment]
Can Zone Name be the first column please left to right then becomes more specific, geographically (Zone, District, Sub District/Village)

**Comment by daiClegg** [comment]
See issue #18

**Comment by dbrownukk** [comment]
SIte module removed.
Options are:
1. Create LZ in context of a Project in Project Module
2. Create LZ in LZ Module - you can also create Site at this point in context of LZ
3. Create Site in Community module in context of Community and Project and LZ

**Comment by daiClegg** [comment]
ok.
