### ISSUE TITLE
Wealth Group Income report does not include Food Purchase Resource Type

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#170]
Project: Mukonu - New Test
LZ: Banana Coffee Piggery
District: Mukono
SubDistrict: Ntenjeru
WG: Better Off

This WG has multiple Food Purchases but they do not feature in the WG Income report.
They do appear on the Project export report, issue #146

**Comment by dbrownukk** [comment]
For discussion - Should 'Food Purchase' appear on an Income report 

if so, need to add to view wginterview_cash_income_report

**Comment by daiClegg** [comment]
Some notes pending a fuller discussion:

John was equivocal about this.
He generally omits it because he is not convinced it is reliable data; you are asking people to remember what they might have bought over the last year and what they paid. 

However, for what-if modeling one input needed is a list of the crops that WGs might purchase if they have a shortfall in their own production. 

It turns out that this information is gathered in the Community interview - but it was never specified to be included in OHEA.  Food Purchases for WGs provide a good place to record this, albeit at a later stage in the process. 

But that doesn't make a conclusive argument for including them in the charts, only for including them in the export (which is already done).

John's view, on balance, is to omit Food Purchases from both charts, because of the dubious data and deal with it in the modelling.

My consideration of how that impacts the implementation is that we could have 2 charts one with and one without.  But that has to be an ENH that is not in scope for M4.

thoughts?


Note what-if modelling in OHEA version 1 will probably be supported in a spreadsheet based on exported data from the WGI report (requirements still being finalised).

**Comment by dbrownukk** [comment]
Two charts - one with, one without Food Purchases.
Without chart first

**Comment by dbrownukk** [comment]
Now have two reports, one with and one without Food Purchases with extra column - Units Purchased

**Comment by daiClegg** [comment]
Tested Ok.
