### ISSUE TITLE
Upload/Parsing does not assign Food Resource SubType correctly for Food Transfer in WGI

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#171]
Project: Test Food Transfers
LZ: Test99 
District: d1 
SubDistrict: sd1 
WG: WG1, WG2. WG3

I tried various tests on varous WGs to see if i could identify the problem more precisely, but i haven't

The spreadsheet i'm using, with some edited variations to try to diagnose the problem, has 3 food transfers with various subsets of data in the columns for food, but parsing just says 'Problem Parsing Transfers' 

At least we need to know what the mandatory columns are to parse, so that the data can be corrected in the spreadsheet, or left to be done when uploaded.

I can do more testing (one transfer per spreadsheet per WG, if that woul dmake diagnosis easier in the code, but i'd rather not waste time if it's easy enough to debug from the data here.

**Comment by dbrownukk** [comment]
Notes for fix
1. Found that resourcesubtype check could return 2 or more rows - Goats and Goat exist as 2 different rst with Goats a synonym for Goat, which is correct. 
Code in checkSubType now handles this.

**Comment by dbrownukk** [comment]
Tested and seems fixed.

TestFoodTransfers LZ Test99 District d1 WG = WG1

Also set Unit to a default of ? if it is null. Seen several examples where this is null and causes problem on save as it is mandatory..

**Comment by dbrownukk** [comment]
Yet to deploy

**Comment by daiClegg** [comment]
Tested Ok.

...having tripped over the "?" default again. But that's a data problem, so entirely correct.
