### ISSUE TITLE
Generated Spreadsheet is missing corrections/updates applied to loader

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#172]
There are a number of issues with trying to use a generated blank spreadsheet to record WGI data. They are all logged here in one issue because they'll probably all be fixed together.
I can split them out if that's better.

[https://app.zenhub.com/files/100863714/33d6ebcb-2312-4d39-aed0-91434563626a/download](https://app.zenhub.com/files/100863714/33d6ebcb-2312-4d39-aed0-91434563626a/download)

**Comment by dbrownukk** [comment]
Done the bugs and the Date input validation 

![image.png](https://images.zenhubusercontent.com/5a814e994b5806bc2bc6879c/1afccd5c-833b-405a-930f-c8678c5dd157)

**Comment by daiClegg** [comment]
Interview date: tested ok.
Employment column order: tested ok.
Employment type validation: tested ok.

Set status to ENH, since the only outstanding items are ENH. 

But still in M4. Celia would really like the column ordering change, and in John's HEA implementation does use that order, but he never flagged this ordering of columns as a problem during spreadsheet design.

If it doesn't make the cut (no  ENH is Must Have), so be it.

**Comment by daiClegg** [comment]
The only remaining issue is the ordering, in the generated spreadsheet, of Units Consumed & Units Other Use columns, in the tabs where they occur, as justified in Celia's reported comments above.

Tabs are: Crops, Livestock Products & Wild Foods

**Comment by dbrownukk** [comment]
Ran through OHEA and OIHM and templates + WGI / HH seem consistent.

**Comment by daiClegg** [comment]
**Tested Ok**

but see also #163 for parsing & validating
