### ISSUE TITLE
Adding KCal to a Synonym RST does not give helpful message

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#173]
To reproduce:

- Create a new RST, Test, as a Wild Food with a KCal of 1234.
- Add another RST, Test1, as a Wild Food; enter KCal 4567 and select Test as Synonym.
- Commit.

Commit message says successful, and the KCal value has been reset to 0.

That is correct behaviour, but may be deceptive to a user who hasn't realised it's a synonym or who doesn't know the rules for KCal on synonyms.

Better would be a supplementary warning message on commit that tells you:
"KCal of a Synonym must be zero; value is inherited from base Synonym".

**Comment by dbrownukk** [comment]
Adding a KCal to a RST with a synonym now gives a message 

A Resource Subtype acting as a synonym will assume KCal value from master, this value is set to 0

**Comment by daiClegg** [comment]
Tested Ok.
