### ISSUE TITLE
Parse appears to fail to find valid match of "Goat"

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#175]
Project: Homa Bay Test
LZ: Sugar cane & bricks 
District: Kisumu 
SubDistrict: Ariri 
WG: Middle

IN the livestock assets, as loaded , include an entry for "Goats, Item"
And this is not matched, even though "Goats, Item" & "Goat, Item" are recorded Livestock types.

Screenshot attached:

![Screen Shot 2018-10-24 at 08.52.18.png](https://images.zenhubusercontent.com/5a81590c4b5806bc2bc688fc/df7e0a37-9ddd-4dc9-925b-d45b48da9bb1)

**Comment by dbrownukk** [comment]
ResourceSubType for LiveStockSales only has Chicken.

Changed the validation of Livestock Sales to run through Resource Sub Types of 'Livestock and fixed the wgi status that was occasionally not set.

**Comment by daiClegg** [comment]
Tested OK. - Goats issue.

Not encountered invalid WGI status update, so not tested
