### ISSUE TITLE
Livelihood Zone association with a Project is not correctly managed

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#177]
Project: Homabay test

View this project in the Project Module & it appears to have no LZ.
View it in the Communities Module and you see 2 Communities both in Sugar cane & Bricks LZ
View Sugar cane & Bricks in LZ module and there it is, all okely dokely
Go back to Project and attempt to add an LZ t Homabay Test
The popup reports "Errors trying to obtain data list"
And also "There are -1 records in list"

See attachment:
![Screen Shot 2018-10-25 at 11.12.44.png](https://images.zenhubusercontent.com/5a81590c4b5806bc2bc688fc/b916c47c-1b33-4ddd-bd6f-ce007d4bd968)

I didn't create this project, so i'm not sure how it got in this state.
It might have been a user not using the correct path through the software, but either way the software has failed to protect itself from creative user interaction!

I created a new Project and i cannot Add an LZ to that, though i can create a new LZ and associate it with the project, via the Project module. And it displays correctly when i do that.
(See Project Test251018)

I'm thinking there may be 2 bugs here:
1. can no longer add LZs to new projects
2. Homabay Test Project is in some way screwed up.

i can split these out if that proves to be the case, but  conflating them pending investigation.

**Comment by dbrownukk** [comment]
1. Can no longer add LZs to a new Project - List of values excluded all if no LZ was associated - 
fixed - to be deployed.

**Comment by dbrownukk** [comment]
Deployed and tested - you can now create a new Project and add or create a LZ 

Homabay test looks ok to me

**Comment by daiClegg** [comment]
Tested ok .
