### ISSUE TITLE
'System Error' accessing specific WGI records

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#179]
Project: Mukonu - New Test
LZ: Banana Coffee Piggery
District: Mukono
SubDistrict: Nakisunga
WG: Better Off/Middle/Poor

In WGI Module
restrict list view to Nakisunga.
select any of these 3 WGs.

I get a blank WGI detail view and a red "System Error" alert.

User Admin
Have logged off and logged on.
Does not reproduce for other WGs
Can view the Community record for thisa Village/SubDistrict in the Community Modue

**Comment by dbrownukk** [comment]
Apologies - TransferType in wgi transfer is now a drop down list, i.e. an enum, with database type of int for 0 = food, 1 = cash, 3 = other 

Needed to update database... 

Done and fixed in idaps instance..

**Comment by daiClegg** [comment]
Tested OK.
