### ISSUE TITLE
Site - Livelihood Zone name picker should be the first field

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#18]
Sites are always in the context of an LZ so the UI should set that context from the start.
If the Site module disappears - subsumed in a master/detail with LZ (see Issue #17 ) - then this issue is irrelevant.

**Comment by daiClegg** [comment]
Maybe Site is only ever accessed in the context of LZ or Community, so doesn't need it's own module

**Comment by dbrownukk** [comment]
Complete in LZ Module

**Comment by dbrownukk** [comment]
Keeping it simple - standalone Site module is removed.

**Comment by daiClegg** [comment]
Agree
