### ISSUE TITLE
Loader does not load apparently valid Food Stock and Cash Assets

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#181]
Tested On:

Project: Test251018
LZ:Test251018LZ2 
District: td1 
SubDistrict: tst1 
WG: test2, test 6

The spreadsheets uploaded for these 2 WGs have Cash & FooodStock Assets.
They appear correct, but do not load - they create a blank record and report an error.
(note i have manually corrected the entries, in order to test the reports)

**Comment by daiClegg** [comment]
Same is true of the Middle & Better Off WGs in this Community.
These datasets were all prepared on older generated spreadsheets, but i had changed the columns round in the Employment tab to correct that.

That issue is now resolved. So for one of my tests i did replace the Employment tab in the Poor WG with a newly generated spreadsheet Employment tab, and re-entered the data, to test if that was the problem. It made no difference :o(

**Comment by dbrownukk** [comment]
Tested with Food Stock and Cash assets 

On upload there is now an attempted commit. However, a validate is done of a preexisting set of assets. If this fails then teh upload is not saved until the error is fixed. i.e. In this case a food purchase item had a null unit. Add in a unit, save and then parse with the new spreadsheet data,

**Comment by daiClegg** [comment]
I tried this with fixed Food Purchase - but still no food purchases appear on upload/parse. 
No error message.

**Comment by daiClegg** [comment]
Tested on same project with WG7

**Comment by daiClegg** [comment]
Retested with the same spreadsheet (WG8)

This now appears to work - it parses the Cash & Food Stock assets correctly
The missing unit in one of the food purchases is still there & still causes an error on save (as it should), but the food purchase, non-food processes, cash assets and food stock assets all load correctly.
I think this is fixed as a by-product of one of another fix,
