### ISSUE TITLE
Unable to parse apparently valid employment details

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#182]
Project: Test30Oct - All
LZ: Sugarcane and Brick Making 
District: Homa Bay 
SubDistrict: Ariri 
WG: Poor

I have attempted to parse this spreadsheet several times.
Went through a cycle of deleting it, trying a change in the source spreadsheet to identify the problem, then uploading again. 
It always fails to parse the Employment details, although there are four of them and they look fine.
This is data Celia needs to load for the training class.

**Comment by daiClegg** [comment]
The issue that identified the Employment tab problem was issue #172

**Comment by dbrownukk** [comment]
parsing of spreadsheet
checkSubTypeEntered(unitEntered, RST rst) was using a bad if (unitEntered = "") 

this checks the food rst if entered for Emp

fixed to be 

if(unitEntered.isEmpty())

**Comment by dbrownukk** [comment]
deployed and tested

**Comment by daiClegg** [comment]
The parse now works successfully on all the Ariri WGs in this project.
That is, it can read the uploaded spreadsheet and create the appropriate Employment Records,
However, all the Employment records are set to Invalid by parse, although they appear to be valid:
See attached screenshot
![screen shot 2018-10-31 at 10 03 42](https://user-images.githubusercontent.com/30879677/47781124-da748380-dcf4-11e8-95d9-c42fa0ae3c4e.png)

The Kabonyo data is suspect because it was entered into an old generated spreadsheet, pre the recent fix for the Employment tab format. and still fails. John is going to re-enter that data in the correct generated spreadsheet  and re-test.

**Comment by dbrownukk** [comment]
Parse was looking for a valid food payment type, which clearly there is not as there was no food payment.. fixed.

yet to deploy

**Comment by dbrownukk** [comment]
deployed

**Comment by daiClegg** [comment]
Tested Ok.
