### ISSUE TITLE
Correcting 'incomplete spreadsheet data'

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#183]
I've just created a project (Student demo Nov 1 2018). I've  generated a new spreadsheet  (based on Ariri Better off) and uploaded this with some known errors. 
The first error is 'Incomplete spreadsheet data . Interview number is empty'
That's correct-the interview number on the spreadsheet was empty.
I deleted the spreadsheet I'd just uploaded
I corrected the original spreadsheet on my desktop added an  interview number on the spreadsheet, and saved the file .
I  uploaded the corrected spreadsheet.
The same error message appeared.

**Comment by celiapetty** [comment]
Thanks David. I'll test this when you've implemented. The only other
problem from yesterday was employment so will see how this works when I
upload the new file.

**Comment by dbrownukk** [comment]
Celia,
Now implemented. I had found the file upload looked wrong as you were perhaps parsing a file that was not the file you thought your were parsing. Hopefully this will be clearer. 
Fixing issues is generally easy - it is the testing and any knock ons that are the problem! Keeps my brain very active...
regards,
David 
Any issues, please do update Github.
    On Friday, 2 November 2018, 10:32:05 GMT, celiapetty <notifications@github.com> wrote:  
 
 Thanks David. I'll test this when you've implemented. The only other
problem from yesterday was employment so will see how this works when I
upload the new file.

**Comment by celiapetty** [comment]
Thanks David-will keep github up dated!
Celia

**Comment by daiClegg** [comment]
Is the automatic save implemented (as per previous comment)?
Is that the intended behaviour i should test?

**Comment by daiClegg** [comment]
Yes.

**Comment by daiClegg** [comment]
Tested Ok.
