### ISSUE TITLE
Employment data won't upload

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#185]
Error message: problem loading employment. Employment doesn't upload. All other categories do upload.

**Comment by celiapetty** [comment]
Re my last message,' Employment data doesn't upload': see Student demo Nov 2018

**Comment by celiapetty** [comment]
I may have mis labelled the last issue

**Comment by dbrownukk** [comment]
Looking at the Student demo Nov 2018 there is a missing 'Unit' for the Employment. 

The template spreadsheet generation now has a pick list for Employment Unit. Also, from a previous issue, the Unit and Number of People columns were exchanged. That is how the new template is generated and parsed.

**Comment by celiapetty** [comment]
I've created a new spreadsheet and entered data for Student demo Nov 2018 better off. Everything except the employment data has uploaded

**Comment by dbrownukk** [comment]
The Employment Unit cell in the generated spreadsheet should have a drop down list of Day,Week,Month, Year . Somehow, the 3 rows of employment data you have entered insist on being numeric - did you use copy and paste? If so, just copy from cell D7 up to cells D4/D5/D6 and the correct drop down validation will appear.

Removing cut and paste functionality maybe a bit drastic! But it does copy the validation from whatever is copied. 

Hopefully that will give a fully loadable spreadsheet.

**Comment by celiapetty** [comment]
That would explain it....I was experimenting with cut and paste, which
seemed like a useful thing to do, but I can see patience may be a
better option. I'll try again!
By the way the problem with livestock products (units) does seem to be a
bug?

**Comment by celiapetty** [comment]
OK-tested and employment now works.
I'll be in Uganda from Sunday and may have less time to test. Could you
send John Seaman a Github log in as he may also come across bugs next week?
I'll send an email to you both.

**Comment by daiClegg** [comment]
Tested ok by Celia; will close
