### ISSUE TITLE
Livestock products units not accepted

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#186]
Column D livestock units on data entry spreadsheet. Alert message: Enter number only. I should be able to enter  litre/kg

**Comment by dbrownukk** [comment]
Did you copy into column D. If you go to cell D11 in the Student demo spreadsheet you will see the drop down is available. Copy back up to the previous rows. 

The challenge of data entry in spreadsheets.

**Comment by celiapetty** [comment]
For my test, I started from scratch so didn't copy-paste, but there may be
times when, used with due caution and training this could be very helpful
(and potentially reduce errors in transcription etc).

**Comment by daiClegg** [comment]
Celia, does this now work how you expect?
There are no steps to reproduce here, so i can't test it.

**Comment by celiapetty** [comment]
To reproduce, copy paste item
from 1 project to another. Teaching point don't copy paste from 1 spreadsheet to another.

**Comment by celiapetty** [comment]
To clarify futher: this relates to spreadsheet cells where there is a drop down

**Comment by daiClegg** [comment]
This bug relates to copy/pasting between cells in the spreadsheet.
In such cases, validation and constraints may not be properly applied.

It might be possible to add further constraints to the generated spreadsheet to stop the user doing this, but programming at this level in Excel is notoriously difficult.
Establishing best practice among users is a morecost-effective resolution
