### ISSUE TITLE
Date appears US style mm/dd/yy

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#187]
This is a new issues: I'm sure date appeared using  the UK/European convention when I last tested. Now appears mm/dd/yy. As most users will be familiar with the UK/European standard method I suggest we stick to this.

**Comment by daiClegg** [comment]
Where? In what module? All modules? Or in the generated spreadsheet?
I can test Savid’s tgeory that it’s machine dependent on my phone if I know where to test

**Comment by daiClegg** [comment]
Comment from David:

The I/V Sequence is not used by the software, other than to record it.

The date issue: I am guessing it is a machine setting rather than the software as the date format is taken from the local country setting. Is it a new machine set to US locale?

**Comment by celiapetty** [comment]
Thanks for clarifying the I/V sequence question.
Re the date-No, it's the machine I've been working on throughout. Maybe an
automatic update-I'll check if excel has shifted to US settings?  Not sure
if this is  possible.

**Comment by daiClegg** [comment]
In the project module, list & detail views, the date is displayed in american format, this is in chrome on my laptop & on Celia's.

**Comment by dbrownukk** [comment]
Appears in dd/mm/yy from my windows laptop and Mac in Chrome.

Have a look at https://support.netdocuments.com/hc/en-us/articles/115000004283-Setting-Google-Chrome-to-show-region-specific-date-formats

Mine is set to -  English (United Kingdom)

**Comment by daiClegg** [comment]
Tested David's suggestion.
It works.

Strangely, i had never noticed that the dates were American before.
It may be that i'm just used to American dates and don't even notice them.

There may be a teaching point here - if users observe this and want to remove it - they should adjust their browser settings.

Closing the bug
