### ISSUE TITLE
Reloading spreadsheet

### ISSUE THREAD

**Issue by DrJohnSeaman** [dbrownukk/EFD_v2#188]
I deleted a wealth group (HomaBay Sugarcane and bricck making Kabonyo- poor) and saved this in order to reload a spreadsheet.
The result is that Kabonyo- poor no longer appears (wealth group tab) in the list of wealth groups. The community data is still there although the percentage in population does not sum to 100.  

How do I reload the wealth group spreadsheet?

**Comment by daiClegg** [comment]
What's the status of this please?
No labels, so i don't know the status.

Thx.

**Comment by daiClegg** [comment]
Closing as there is no  implied software change
