### ISSUE TITLE
Deleting and re-loading spreadsheet

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#189]
This looks similar to the issue John has just posted. I created and uploaded a new WG spreadsheet. Error message 'Incomplete spreadsheet data interview number is empty' came up.   The spreadsheet did have an interview number (9) taken from the interview form I had transcribed. This number was different from the Interview number I had entered in the Wealth Group interview box  ie '1'.  I entered '1' when defining the wealth group as I understood the order in which data appears in charts had to be defined in ascending order with 1 the poorest. I then deleted the spreadsheet and changed '9' to '1' in the spreadsheet. I tried to upload but the same error message came up.

**Comment by celiapetty** [comment]
ok possibly the issue was my failure to 'save' having deleted the previous spreadsheet. However, I did note a green flash in the corner of the cell with no. 1. This indicated in the drop down that the number had been stored as text. I therefore saved as a number. Will see how the next wealth group behaves...

**Comment by daiClegg** [comment]
If you reference another issue, please enter it in the text.
It's very easy to do; just type '#' followed by the number of the issue and Github will create the link automatically

**Comment by daiClegg** [comment]
What's the status of this please? 
No labels, so i don't know where it is or where in the fix cycle it is.

Thx.

**Comment by daiClegg** [comment]
Cannot do anything with this.
Closing.
