### ISSUE TITLE
Cannot Parse apparently legitimate spreadsheet

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#192]
Project: 
LZ: Training LZ 
District: Kisumu 
SubDistrict: Kibonyo 
WG: Better off

Attempting to parse the uploaded spreadsheet results in 2 error messages`;

> Incomplete Spreadsheet data, correct spreadsheet and upload again
> Impossible to execute Parse spreadsheet action: java.sql.SQLException: Illegal operation on empty result set.

I have reviewed the spreadsheet and i cannot see what is wrong with it.

**Comment by daiClegg** [comment]
As a test i compared the spreadsheet to an old one from a project that was successfully loaded, parsed and validated



I couldn't see any difference in the format or ordering of tabs except - except the old one didn't have a validation tab that the new one does.
So i created a new project (191118TestUpload) in the test organistaion with one WG and uploaded the old spreadsheet.
It successfully uploaded, parsed and validated - but no data was parsed from the uploaded spreadsheet.

I noted the Java parse error which was something you mentioned y'day in relation to a log entry.
Might it be related?

**Comment by dbrownukk** [comment]
Downloaded spreadsheet to my local instance and parse is ok.

Investigating

**Comment by daiClegg** [comment]
Did you reproduce my failure to parse on the Reading instance?
The original one was created by Celia & Stella y'day.

**Comment by daiClegg** [comment]
I took another spreadsheet that had been part parsed and was able to complete the parse and validate  it successfully.
Note this was a spreadsheet that had already been part parsed (ie lots of valid & some invalid Resource records already created)

**Comment by daiClegg** [comment]
This still reproduces in the default org.
Is that right?

I just reproduced it on :
Project:  MyTestProject
LZ: MyTestLivelihoodZone 
District: MyDistrict1 
SubDistrict: Village1 
WG: Middle

**Comment by daiClegg** [comment]
Is this fixed? i think it was, but just need to confirm before i close

Does not reproduce in the project above

**Comment by daiClegg** [comment]
no longer reproduces.
