### ISSUE TITLE
Should Livestock Products allow Livestock types?

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#193]

**Comment by daiClegg** [comment]
The problem with allowing livestock types is you need a KCal for them, because they can also be bought - as Food Purchases, by the Kg for anything but small animals. And anyway KCal of sizable animals is surely not feasible.  
Smaller ones, e.g. chicken, would always be sold as whole carcases. Larger ones may be.
So perhaps we just set up livestock products to include ''Carcase' for each livestock type, with an 'Item' unit  and for larger animals also 'Meat' with a 'Kg' unit and with a KCal specified

wdyt?

**Comment by celiapetty** [comment]
From John's email :'The first issue - Livestock as food purchase, if I understand this correctly. For a whole animal this is usually calculated and entered in Kg, where the 'dressed weight' has been agreed  - typically 15kg for a large goat for example (15 * the Kcal value) as livestock weights vary a lot from place to place.  Village poultry are usually calculated at 1 Kg each. So Goat, meat 15Kg...Goat half a carcass 7.5Kg'

**Comment by daiClegg** [comment]
This conversation arose because of an entry of 'Chicken Meat' in Kgs in one of the Homa Bayt interview datasets, which Celia suggested would really be a whole carcase. 
That raised the question of how we handle sale/purchase of carcases.

Taking into account John's additional comments (see previous comment in this thread), I think the simplest way to handle the requirement is to define Livestock Products for 'meat' of each livestock 
type; we already have that for some - each with a Kg unit and a KCal value.

If, for small livestock types (e.g. chicken) it is likely that trade might be in whole carcasses, and if it's feasible to attribute a KCal value to such, we could additionally have Livestock products of 'carcass' with a Kcal value for some select small livestock types - that would make data entry easier in some cases.

If you are both happy with this, then we don't need to allow Livestock Types in Food Purchase and LivestockProduct Sales. 

Ok?

**Comment by celiapetty** [comment]
That sounds ok to me.
John? ok with you?

**Comment by daiClegg** [comment]
John agreed, in an offline email.

So official position is we don't allow Livestock Types in Food Purchase and Livestock Product Sales.
