### ISSUE TITLE
Units Consumed not included in WG Income Report

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#196]
Org:              OHEA_Training
Project:        Day1
LZ:                Day1LZ 
District:        Day1District 
SubDistrict: Day1subdistrict 
WG:              Middle

The WG Income report has 'null' for the Units Consumed column forCrops, Livestock Products & Wild Foods. (not tested Transfers - none in this WG). 
Several of the values displayed in the app have non-zero values, and the rest display explicitly as zero.

**Comment by daiClegg** [comment]
Is this related to the fix for Issues #163 & #172 ?

**Comment by daiClegg** [comment]
Screenshot:
![screen shot 2018-11-29 at 23 11 40](https://user-images.githubusercontent.com/30879677/49258118-40efdd00-f42c-11e8-9da7-ab7d77c9b11b.png)

**Comment by dbrownukk** [comment]
fixed as per #202 I believe 

Now maintained in table trigger since OX does not persist @depends columns

**Comment by daiClegg** [comment]
Tested OK.
