### ISSUE TITLE
WG Income Report do not include correct KCal for Synonym Resources

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#199]
Org: OHEA_Training
Project: Day1
LZ: Day1LZ 
District: Day1District 
SubDIstrict: 
Day1subdistrict 
WG: Poor

To reproduce, run the WG Income with Purchases Report for this WG.

Note cell AI in Row 26 (Small Fish) & Row 16 (Sweet Potatoes).
The KCal value is 0 for these two, but correct for all other Resources
This appears to be because they are Synonyms.

In the case of Synonyms the base resource KCal value should be returned.

Not tested the report that excludes Food Purchases (both the synonyms in this WG are in Food Purchases). Can do that test if necessary.

**Comment by dbrownukk** [comment]
created a new function that takes the resource subtype id used in the resource/asset and determines if it is a synonym or not. Returns kcal value

CREATE DEFINER=`efd`@`%` FUNCTION `get_syn_kcal`(
	`rstid` VARCHAR(32)

) RETURNS int(11)
    DETERMINISTIC
    SQL SECURITY INVOKER
    COMMENT 'gets the kcal from the parent rst for a rst synonym'
BEGIN
declare kcal int(11); 
declare synid varchar(32);
declare ret_kcal int(11);

select resourcesubtypekcal, resourcesubtypesynonym_idresourcesubtype into kcal, synid from resourcesubtype 
where IDresourcesubtype = rstid;


IF synid is null then
set ret_kcal = kcal;
else

select resourcesubtypekcal into kcal from resourcesubtype where idresourcesubtype = synid;
set ret_kcal = kcal;

end if;

return ret_kcal;

END

**Comment by daiClegg** [comment]
does this work for a synonym of a synonym? ?I think not.
But there shouldn't be any synonyms of synonyms.
I also need to chack that is not allowed.

**Comment by dbrownukk** [comment]
no, but I did consider it and we could change the function to travel the pigs ear... 
I think you can create a synonym of a synonym, at the moment

**Comment by daiClegg** [comment]
I know you just want to write some clever recursive code  :o)
But i'd prefer to disallow a synonym of a synonym.
There is no loss of functionality:
> x is a synonym of y &  y is a synonym of z 

is logically equivalent to 

> x is a synonym of z & y is a synonym of z.

wdyt?

**Comment by daiClegg** [comment]
Tested the report (the original issue) OK.

the drop-down filter is not yet deployed right?

Leaving this issue open and taking off the Testing label, pending deployment of the final fix.

**Comment by dbrownukk** [comment]
RST drop down list for synonym now deployed. 

Maize Meal is a synonym for Maize, thus Maize Meal does not appear in drop down.

**Comment by daiClegg** [comment]
Tested OK. 
Very neat solution.

Will check existing RSTs for any the already violated this rule
