### ISSUE TITLE
WG Income Report shows Livestock Sales as Livestock?

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#200]
Org: OHEA_Training
Project: Day1
LZ: Day1LZ
District: Day1District
SubDIstrict:
Day1subdistrict
WG: Poor

To reproduce, 

1. view Livestock Purchases  of the WG. 
    Note Chicken - Local": 5 owned at start of year & 12 sold.
2. run the WG Income with Purchases Report for this WG.
    Note, in Row 28 cell AG says "Chicken - Local", cell AX - shows 5 owned at start of year, 
    cell AN shows 12 sold,  but cell AF says "Livestock", not "Livestock Sales".

**Comment by daiClegg** [comment]
Yes i meant Livestock Sales; But i do see a sale of Chickens on that WG, as i reported - modulo Purchases/Sales typo in the description:
![screen shot 2018-12-06 at 09 55 23](https://user-images.githubusercontent.com/30879677/49576433-1971a680-f93d-11e8-9c4f-995ef2f4e03c.png)

**Comment by dbrownukk** [comment]
Livestock sales are validated against Resource Type Livestock. We do have a RT of Livestock Sales but I do not think it is used anywhere. 

Don't like the thought of hard coding 'Livestock Sales' for 'Livestock'. The report would need a decode which would mean writing the sql select out in long hand rather than the existing select *.

However, can edit the view wginterview_cash_income_report and hard code the view..

**Comment by daiClegg** [comment]
Agree about avoiding hard-coding wherever possible.
Can we push this to discussion for a catch up later in the week or do you need a quick decision?

**Comment by dbrownukk** [comment]
I have 'hard coded' the view. It is just the union from the livestocksales entity, though does raise the question, should the other RTs in the union have a hard coded type. 

Currently describes any Livestock Sale as a Livestock sale, which seems correct. For testing and quick discussion later in week..

**Comment by daiClegg** [comment]
Tested OK.
Looks correct now.

But leaving open, pending discussion

**Comment by dbrownukk** [comment]
Hard code the individual RTs in each of the Unions

**Comment by dbrownukk** [comment]
Hard coded the view so that RTs are correct and shows the asset type rather than the originating RST parent RT

**Comment by daiClegg** [comment]
Tested OK.
