### ISSUE TITLE
In WG Income report, 'Food Purchases' of crops RSTs shown as 'Crops' not 'Food Purchases'

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#201]
Org: OHEA_Training
Project: Day1
LZ: Day1LZ
District: Day1District
SubDIstrict:
Day1subdistrict
WG: Poor

To reproduce, run the WG Income with Purchases Report for this WG.

**Comment by daiClegg** [comment]
It's a bug from the user's perspective, but i can see how it might seem more natural to report these as what they are, rather than the role they play in this WG's livelihood, so i've tagged it as Bug & Enh.

**Comment by dbrownukk** [comment]
Action - fix the report to show Food Purchase, where it is a Crop/WF or LSP is a Food Purchase if in Wealth Income report with Purchases

**Comment by dbrownukk** [comment]
'Crop' Food Purchases now shown as Food Purchases
Small change to view

**Comment by daiClegg** [comment]
Testede Ok
