### ISSUE TITLE
In WG Income Report, Units Consumed incorrect for Crops, Wild Foods & Livestock Products

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#202]
Org: OHEA_Training
Project: Day1
LZ: Day1LZ
District: Day1District
SubDIstrict:
Day1subdistrict
WG: Poor

To reproduce,

1. view Crops, Wild Foods and Livestock Products of the WG. 
    Note there are non-zero units consumer in all three categories.
2. run the WG Income with Purchases Report for this WG. 
    Note, in Column AP value is null for Crops. Wild Foods & Livestock Products.
    Note in Row 13 (Maize) column AP is 0, but this is a Food Purchase incorrectly categorised 
     (see Issue #201 )

**Comment by dbrownukk** [comment]
The 'Consumed' field was changed to a dependent field. Need to check all @depends attributes used in reports. The screens handle the @depends correctly.

**Comment by dbrownukk** [comment]
To ensure database value for units consumed is maintained there are now database triggers used to calc unitsconsumed. OX does not consider @depends fields to be persistent but as they are used in reports they should be persisted, if only by a trigger.

**Comment by daiClegg** [comment]
Tested OK
