### ISSUE TITLE
Generate HH Interview Spreadsheet

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#211]
The HH Interview Spreadsheet template in OIHM should mirror the OHEA WG Interview spreadsheet where appropriate.

Note that configuration of the spreadsheet with the likely resources to be encountered is more fundamental to IHM than to HEA. 

See also #210  - upload

**Comment by daiClegg** [comment]
1. The OHEA spreadsheet format and data validation UI should be mirrored as closely as possible
1. Unit price to be captured for each sale (Crops, LS, LSP, Wild Foods)
1. The existing IHM spreadsheet includes Purchases; these are not necessary. Unit price to be captured for each sale (Crops, LS, LSP, Wild Foods)
1. It would be useful to collect Inputs data. They have a similar data structure to Purchases but relate specifically to agricultural and Employment inputs. Examples would include Fertilizer, Animal Drugs, Seeds, Hiring a Shepherd, Pesticides and Herbicides.
Some of these might relate to a specific Employment or Crop, some will not. If the dependent Crop(s)/Employment (s) for a specific input can be captured, that would be desirable.

**Comment by daiClegg** [comment]
When reporting, if inputs have been ascribed to specific Crops/Employments , would cash income from those Crops/Employments, be diminished to cover inputs? 
If so, how would the user know this had been done? Does it matter?
If Inputs are not apportioned to specific Crops/Employments, where are they reported? 
As a “General Inputs” line in the DI calculation?

**Comment by daiClegg** [comment]
See #163 for validation of Produced/Sold/Other USe/Consumed columns in various tabs of the spreadsheet

**Comment by daiClegg** [comment]
Attached 1st candidate HH Interview Spreadsheet
Questions to be resolved are highlighted in yellow in the relevant tab.
I suggest answers are added here, so we don't have different answers in different versions of the spreadsheet.

Please specify the question and the tab it is on with each answer.




[OIHM-HouseholdInterviewTemplate.xlsx](https://github.com/dbrownukk/EFD_v2/files/2788181/OIHM-HouseholdInterviewTemplate.xlsx)

**Comment by DrJohnSeaman** [comment]
Interviewers are required. Type of year not

**Comment by celiapetty** [comment]
Should get my comments back to you by end of tomorrow.

**Comment by celiapetty** [comment]
Responses attached
[OIHM-HouseholdInterviewTemplate +CP (1).xlsx](https://github.com/dbrownukk/EFD_v2/files/2803092/OIHM-HouseholdInterviewTemplate.%2BCP.1.xlsx)

**Comment by daiClegg** [comment]
Attaching sample OpenIHM HH interview spreadsheet for reference
[ExampleOpenIHM-HHInterviewSpreadsheet.xlsx](https://github.com/dbrownukk/EFD_v2/files/2804084/ExampleOpenIHM-HHInterviewSpreadsheet.xlsx)

**Comment by daiClegg** [comment]
I  reviewed all the feedback.
My updates to the spreadsheet are here:

[OIHM-HouseholdInterviewTemplateV2.xlsx](https://github.com/dbrownukk/EFD_v2/files/2842268/OIHM-HouseholdInterviewTemplateV2.xlsx)

And i have consolidated all the notes, questions. feedback and some further issues arising here:

[Design Questions.docx](https://github.com/dbrownukk/EFD_v2/files/2842271/Design.Questions.docx)

Note the Design Questions doc includes observations about training/methodology/semantics in a separate section at the end of the doc.

@DrJohnSeaman  @celiapetty: Please Review.

**Comment by DrJohnSeaman** [comment]
I come late to this so I may be cutting across previous discussion..

Interview tab on spreadsheet  - 'Site'? e.g. Village name ? Could be clearer.
2. Assets-land. Probably not a) land titles are rare, most land is nominally useufruct & although land is exchanged  this is socially complicated. Not a routine measurment.
3. Assets - livestock is the 'Number at Start of Year'. In which case the column is not strictly needed in livestock  sales. Either way this is rough and ready but the alternative is a lot of questions on  births, deaths sales etc.) Units 'Produced' is products e.g. Kg of butter. May have already been resolved.
4. Semantic, Methodology & Training Issues
Assets – Other Tradable goods. The value the owner puts on it. It is of interest either to estimate the value of the households assets or (potentially) if we introduce the full model as the sale value, for which the current value is the best guide. Although tools of trade is not usually factored into the model.

Also I am not sure if it is planned to automatically deduct inputs from DI. If so it shouldnt be..as it is confusing. As long as the information can be exported the user can do this.

**Comment by daiClegg** [comment]
@DrJohnSeaman , if you lick the link in the mail "view in Github" you can see the whole thread so you won't miss any previous discussion - and that's helpful for everyone.

Your comments:

1. Interview tab on spreadsheet - 'Site'? e.g. Village name ? Could be clearer.

What would make it clearer? I know Celia has done IHM in villages, refugee camps and in urban situations; that's partly why 'Site'. I agree it's a generic term, but i couldn't think of a better one that is not inaccurate in some cases.

2. Assets-land. Probably not a) land titles are rare, most land is nominally useufruct & although land is exchanged this is socially complicated. Not a routine measurement.

As per Celia's comment - adopted

3. Assets - livestock is the 'Number at Start of Year'. In which case the column is not strictly needed in livestock sales. Either way this is rough and ready but the alternative is a lot of questions on births, deaths sales etc.) Units 'Produced' is products e.g. Kg of butter. May have already been resolved.

Celia requested your input. See  her comments in Celia's response spreadsheet attached above in this issue.

4. Semantic, Methodology & Training Issues
Assets – Other Tradable goods. The value the owner puts on it. It is of interest either to estimate the value of the households assets or (potentially) if we introduce the full model as the sale value, for which the current value is the best guide. Although tools of trade is not usually factored into the model.

This section of my doc was just where i collected Celia's comments about traing etc. They have no impact on the software, but i thought you wouldn; twant to lose them.


5. Also I am not sure if it is planned to automatically deduct inputs from DI. If so it shouldnt be..as it is confusing. As long as the information can be exported the user can do this.

Calculation of DI is documented in Issue #145.
Currently it makes no mention of Inputs.
@celiapetty has mentioned the impact of inputs cost on DI, but it has not been expressed as a requirement for any specific report. Is there any such requirement?

**Comment by DrJohnSeaman** [comment]
Your point about inputs and DI is conceded. Otherwise I was working from your synthesis. and missed Celia's comments

Site. Location? 

Assets - livestock. 'Number at Start of Year'. Livestock sales should follow the OHEA layout. Number at start of year is not strictly required in Livestock sales although the duplicate might be retained, as with OHEA for modelling - personally I prefer to have this data in one place rather than have to look it up in another table. Other uses and units consumed are not need in Livesales.

Employment paid in food. I would use the OHEA layout (food type etc). I thnk that agrees with Celia's comment.

**Comment by dbrownukk** [comment]
Validations added for HH and HHM questions 
Inputs added with validation of 100% resource

deployed

**Comment by daiClegg** [comment]
Study-level question apparently included in HH config tab.
--

Study: M1 Workflow Study

CQUs:

![screenshot 2019-03-07 at 22 09 30](https://user-images.githubusercontent.com/30879677/53992999-0d58d900-4126-11e9-8fe9-c33702d352b2.png)

HH Config tab of the generated spreadsheet:

![screenshot 2019-03-07 at 22 12 50](https://user-images.githubusercontent.com/30879677/53993042-30838880-4126-11e9-9661-d7c82eef5930.png)

"What Colour is your house" does not belong here. 

This occurs because the level of the CQU is not at the same level as the CQ.
I think we discussed and agreed that should be enforced?
The Study module Questions tab displays the Level of the CQ, not the Level of the CQU. 
But the generator is(rightly) using the Level of the CQU. 

![screenshot 2019-03-07 at 22 15 17](https://user-images.githubusercontent.com/30879677/53993270-cfa88000-4126-11e9-9924-1487d22c3676.png)

As i investigated this i realised it is a problem with Issue #221, but i decided to keep the comment here, since that's where the problem manifests itself

**Comment by daiClegg** [comment]
Validation of HH level CQUs all ok. (LOV & Integer)

**Comment by daiClegg** [comment]
Correctly, no data entry allowed for an LOV with no defined values.
--
should there be a warning in Save of CQU create dialog if an LOV has no valid values?
Study: M1 Workflow Study
Question: "What is your favourite Colour?"

**Comment by daiClegg** [comment]
Validation for range enforced on a Text type question
--

Study: M1 Workflow Study
Question: "What is your name?"

The spreadsheet only allows numbers in the answer of a queston of type Text

**Comment by daiClegg** [comment]
All tests ok apart from issues reported here and elsewhere as referenced above and also in Inputs, Issue

**Comment by daiClegg** [comment]
more test findings documented below, one comment per anomaly...

**Comment by daiClegg** [comment]
Units Other Use column should precede Units Consumed column, 
which should be calculated automatically
--

This is a usability issue that exists in OHEA as well see (issue #172 )
Normal best practice is to specify Units Produced, Units Sold, Units Other Use (e.g. gift  or whatever) and then whatever remains is Units Consumed.
To avoid errors in data collection, it would be preferable if the Units Consumed column is calculated:-
`Units Consumed = Units Produced - Units Sold - Units Other Use.`

**Comment by daiClegg** [comment]
Employment Type Dropdown should be sorted Alphabetically
--

On the Employment tab, the Employment Type field correctly includes Employment Types in the dropdown, but it woud be more helpful to users if it were sorted alphabetically.

**Comment by daiClegg** [comment]
Inputs Item Purchased should provide Dropdown of Non-Food Purchases
--

Units Purchased as Inputs will be validated against Non-Food Purchases, so tit would be helpful to users if the field had a dropdown list of those.

**Comment by daiClegg** [comment]
Any remaining anomalies have been logged as separate issues

**Feature Complete**
