### ISSUE TITLE
Copy Study Configuration  from an existing Study.

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#212]
Use an existing study as the template for a new study.

This might be for second and subsequent surveys (Studies) in a Longitudinal study; in such a case maintaining consistency is vital.
Or it might be a short cut for multiple studies on a programme or series

In either case, further configuration (deleting and/or adding Configuration Questions) is to be allowed.

**Comment by daiClegg** [comment]
This would entail:
1. User chooses any Study to which they have access
1. System copies all: 
   * ConfigurationQuestion Uses, 
   * StdOfLivingElements, 
   * DefaultDietItems
   * CharacteristicResources 

 into the current study.

**Comment by dbrownukk** [comment]
Not 100% implementation of this but close and worth a review.

From Existing Study in detail mode there is now a 'Copy Study' button. This asks for a new name of a Study - has to be unique.

Process then copies all Study fields + all resources/assets and site from currently viewed Study to new name. Go back to List mode to view. 

(Yet to do DefaultDietItems and StdofLivingElements)

ConfigQuestions - there is now also a button to copy a Topic (a collection of configQuestions) into the Study. Could also add a copy of all questions used in current study.

**Comment by daiClegg** [comment]
Love this.
Also tested Copy Topic - and that showed me how the Questions section is meant to work.
Now i get it!

Pausing further testing pending completion of the feature, but i like it so far.

It is Push copy rather than Pull, which is what i expected, but since you can change the Project to which the Study belongs, that's ok. 
If that were not the case you would only be able to copy a prStudyject within the same project.
That might be the more usual use case (longitudinal studies) but not the only use case for Copy Study.

**Comment by dbrownukk** [comment]
added the copying of DefaultDietItems , Standard of Living Elements and Question Usages

to be deployed

**Comment by daiClegg** [comment]
Copying study has unpredictable results.
--
I tried to copy every study in turn.

- Some succeeded.
- Some failed "Failed to create Study java.lang.NullPointerException", e.g. TestFoodStocks
- Some failed "Impossible to execute Copy action: Transaction marked as rollbackOnly" e.g. "M1 Workflow Study"

Will  look at the contents of each study to try to identify the relevant differences

**Comment by dbrownukk** [comment]
A data issue with RST - Food Stocks - sheep has resulted in some spurious data. 

Had to review all cascade RI constraints to prevent this type of error occurring again. 

Yet to deploy

**Comment by daiClegg** [comment]
ok; awaiting re-test

**Comment by dbrownukk** [comment]
deployed

**Comment by daiClegg** [comment]
Does not copy Food Stocks
--

Study "A Study - copy" is a copy of study "A Study"
Similarly "M1 Workflow Study - Copy" and "M1 Workflow Study"
In both cases, Foodstock is not copied.

Everything else - Tested Ok

**Comment by daiClegg** [comment]
Unable to reproduce report above: 'Copying study has unpredictable results'
INcluded Studies with Sheep and without - Tested OK

**Comment by dbrownukk** [comment]
Foodstock now copied - tb deployed

**Comment by daiClegg** [comment]
**Tested Ok**
