### ISSUE TITLE
Anonymise Households for non-authorised users

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#214]
The only Users who can see the Name of the Household are those who have a role (e.g. Team Leader, Team Member, OIHM Domain Leader) wrt the Project containing that Household.

The level is Project, not Study, because a team member in a second or subsequent survey in a Longitudinal study may not have been part of the first survey (Study) but they will need access to the HH names in order to match them up with their own survey, which is a different Study in the same Project.

HH Name cannot be included in a data export unless it is initiated by an authorised user.
Note that the HH Name filed should be included in any such export - to maintain consistency of structure for any automated consumption of the export.

In the current implementation the HHName is replaced by the HH number manually to anonymise data.
So HH Number  would be an acceptable substitute value for the HHMNAme field on export or in any chart in the application

**Comment by daiClegg** [comment]
dependent on #207; without data-constrained access we have no way of knowing who is entitled to see full HH data.

**Comment by daiClegg** [comment]
But even an authorised user might want an anonymised report - because they are intending to share it.
If we had a flag on reporting "Anonymise Y/N?" then we can support this requirement without data-constrained access control.

**Comment by daiClegg** [comment]
Note for anonymisation we need to replace the HH Name (with HH NUmber)

We should also replace the HH Member name with HH Member Number
These are both optional field so we could be replacing with null but i don't see that as a no problem, since the HH Member name might have been null anyway.

**Comment by daiClegg** [comment]
**Note**
It might be theoretically possible for someone to deduce a household's identity by the combination of the ages and genders (only xxx has both grandparents still alive and 4 sons at home). But that would assume such a detailed knowledge of the village it seems vanishingly unlikely it would happen.

**Comment by dbrownukk** [comment]
Investigate a possible approach

**Comment by dbrownukk** [comment]
Added 'Anonymised' Yes/No to OIHM and OIHM Modelling report dialogs

If set to Yes then the HH Name is removed and just the Number appears. 

Do not believe that we use the HH Member Name anywhere, at least that is what the usage report tells me..

Deployed to IDAPS_Livlihoods_TESTING

**Comment by daiClegg** [comment]
Very Nice

**Tested Ok**

**Comment by daiClegg** [comment]
Tested in Reports & Modelling

**Comment by dbrownukk** [comment]
Deployed to QA and Prod
