### ISSUE TITLE
Capture and Store Micro-Nutrients for Food type RSTs

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#215]
RST data definition should be extended to include not just Kcal Value but also MIcro-Nutrients such as Proteins, Vitamins, Trace Elements etc.

What nutrients should be stored and what the most reliable source for their values is wip

**Comment by DrJohnSeaman** [comment]
I would include  
Protein, fat, calcium, iron , vitamin A, thiamiine and riboflavine. 
John

**Comment by daiClegg** [comment]
Closing the issue means no further action needs be taken. It does not mean you have completed your input.

@celiapetty do you have further input?

**Comment by celiapetty** [comment]
No-this must have been closed in error. I will be asking Zala to arrange a meeting with Prof Carol Wagstaff re micronutrients she would like to see in the dbase.

**Comment by daiClegg** [comment]
When we meet Carol and any other stakeholders, i would like to identify the use cases for storing micronutrients - for example, what, reports might be of value and to whom.
Otherwise, although we can add a feature to capture and store the data, it will not be used.
It is not used in any currently requested or implemented use case in OIHM or in OHEA.

**Comment by DrJohnSeaman** [comment]
We need to decide if Celia is settling the micronutrients with Carol. Once that is settled the rest is will require some additional data on requirements afterwhich the reports are I think straightforward

**Comment by celiapetty** [comment]
I'm fixing a meeting with Carole Wagstaff -probably by phone . Will let you
know her availability

**Comment by daiClegg** [comment]
will need to break into features for data maintenance & also for reporting.

**Comment by daiClegg** [comment]
The attached spreadsheet is the definitive guide to micronutrients.
Carol Wagstaff (key stakeholder for the feature) has highlighted in the spreadsheet (tabs 1.3 to 1.6) the micronutrients with applicability to Sweet Potatoes (the original focus of this work).

[SP highlights McCance_Widdowsons_Composition_of_Foods_Integrated_Dataset_2019.xlsx](https://github.com/dbrownukk/EFD_v2/files/4664615/SP.highlights.McCance_Widdowsons_Composition_of_Foods_Integrated_Dataset_2019.xlsx)

This is not the definitive list because others may need to be introduced (relevant to the wider context of all food stuffs) and some may be removed (to simplify the view for the user)

**Comment by daiClegg** [comment]
Note John's views above on core requirements.
wip confirming the total list of required micronutirents.

**Comment by daiClegg** [comment]
The 28 micronutrients highlighted by Carol in the attached spreadsheet are the definitive list of requirements

**Comment by daiClegg** [comment]
This is not added to the EPIC that represents the MIcronutirents modelling project.

This Feature represents the extension of the RST table to include an editable reference to the McCance Woiddowson Food Source it represents.

**Comment by daiClegg** [comment]
@dbrownukk Have i understood & represented correctly your proposed design for this?

**Comment by dbrownukk** [comment]
Micronutrients added to ResourceSubType 

Deployed to EFD_HM on idaps server for feedback and testing

**Comment by daiClegg** [comment]
**Feature Complete**

This works very nicely how i had expected it to work.

Can i access the McC & W table directly or only to pick from it?
Not sure why i need to but i someone may want to if they wanted to edit or add an additional variety by hand
