### ISSUE TITLE
WG Characteristics Resource page needs to display context

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#22]
When viewing/editing Characteristic Resources for a WG you should be able to see the Project, LZ, Community and Resource Type 

See screen shot attached for example layout

![characteristicresourcesscreengrab](https://user-images.githubusercontent.com/30879677/34718582-26dc323a-f52f-11e7-9645-f88e6e1f2d0b.jpeg)

Whether the list should show all resources for all WGs in that Community or should be based on the WG and just show its Chractacterisitc Resources is debatable and must be reviewed by users.

I favour all WGs in a list to start - with default to the last WG when adding a new one,  and filter capability for a single WG (normal mechanism)

**Comment by daiClegg** [comment]
from discussion: 
Header will be Project title  LZ name, Site SubDistrict (Village)
Characteristic Resources in a list with WG name (Eng)

**Comment by dbrownukk** [comment]
Use ReferenceViews to have a different Entitity view display
Wealthgroup remains the same as before in Community Module but has extra header info in WealthGroup module

**Comment by daiClegg** [comment]
Is this deployed to the server? If so what module do i start from to test?
I tried WG and Community > WG

**Comment by dbrownukk** [comment]
List View has desired Columns 
Detail just has the Rsource type, sub type and Units 

I think it needs the context in the detail

**Comment by daiClegg** [comment]
List view also needs the WG name (Eng). and the sort order should be WG, within SubDistrict, Within LZ, within Project.
That way all resources for a particular WG together are grouped together and all WGs in a Village/SubDistrict.
I expect normal usage will be to filter by subdistrict to view them.

**Comment by dbrownukk** [comment]
Adding all the detail from the columns in the Characteristics Resources List view will result in something very similar to the Community detail screen.  Less is more I am thinking. We could have just the list without the detail and no option to create or edit the detail ??

**Comment by daiClegg** [comment]
Tested OK
