### ISSUE TITLE
Create OIHM Project & Study

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#220]
Create a Project & initial Study;
Allow the user to specify an LZ (new or added )  in which the Study is to be conducted, if they choose. Otherwise, create an LZ with the same name as the Study.
Note: will have to ask for the Country the Study is in one way or another
Donor & Sponsor are optional additional properties of a Project.

Allow creation of multiple Studies in the same project.

**Comment by dbrownukk** [comment]
http://idaps.walker.ac.uk:8080/EFD_HM/ 

user oihm and menu option Study

Lots of module menu options at the moment - will reduce as they are tested. Should end up with just a few as per OHEA

**Comment by daiClegg** [comment]
Instance: OIHM
Project: Initial Module Test

Feature Issues Close when the feature is functionally complete.
Specific bugs will be raised as separate issues.
Behaviour that stops completion of functional testing will be raised below.

Create Project: functionally complete 
Add Livelihood Zone to Project:

1. Create a new project (i used Initial Module Test)
1. Save
1. Add a livelihood zone ( i used IHM Zone)
1. Save
Error: _'Impossible to execute Save action: Another user has modified this record'_
1. Remove LZ from Project (dustbin icon)
1. Save
Error: _'Impossible to execute Save action: Another user has modified this record'_
1. Return to List view
2. From List View select test Project
No LZ is attached
1. In Project detail view, Save
Success: _'Project modified successfully'_
1. Add an LZ
1. Save
Error: _'Impossible to execute Save action: Another user has modified this record'_
1. Return to List view
2. From List View select test Project
LZ is attached.

The Error message appears to be spurious - feature works as it should but it tells you it has failed.
I was able to reproduce this error (Projects: 'Initial Module Test' & 'Test Adding LZ to Project')
And with existing LZs and when creating an LZ as part of the Project create module workflow.

**Comment by daiClegg** [comment]
The attached sketches the workflow.
Need discussion!

[IHM WorkFlow Project Setup.pptx](https://github.com/dbrownukk/EFD_v2/files/2842891/IHM.WorkFlow.Project.Setup.pptx)

**Comment by dbrownukk** [comment]
For discussion - in all day..

**Comment by daiClegg** [comment]
After discussion redefined the workflow.
Updated workflow:
[IHM WorkFlow Project Setup.pptx](https://github.com/dbrownukk/EFD_v2/files/2845879/IHM.WorkFlow.Project.Setup.pptx)

**Comment by daiClegg** [comment]
Revised design data model for Sites, LIvelihood Zones Countries to resolve HEA & IHM uploaded in [DesignModel6](https://github.com/dbrownukk/EFD_v2/blob/master/DesignDoc/IHM%26HEADesignModel6.mwb)

**Comment by dbrownukk** [comment]
Several combinations here that need a quick discussion

Site within a Study

1. Query an existing site - must be in base country of Project 

2. Add new Site - LZ or Country - not both. 
LZ not in Country of Project
Country is anywhere?

3. Edit existing Site - conditions as in 2. above.

**Comment by dbrownukk** [comment]
Added Country to the LZ search within Site

Site may have a Country or a LZ not both

Site lookup shows all Sites

**Comment by daiClegg** [comment]
Project: Test M1 Workflow
LZ: none
Study: M1 Workflow Study

attempt to select an existing District (torch symbol).
get error message:

> Impossible to execute Filtered sitesearch action: 

The action is correct - there is no LZ in which the District might exist, but the message would not help a user.
Not logging a separate issue since it is just polish

**Comment by daiClegg** [comment]
When adding Cost of Living Items for a HH Member,  if it is immaterial which gender (for example clothes for a child - same for male & female) you have to specify "Unknown" for the gender.
In this case, what you want is either not to select a gender (ie applies to all) or to select a gender value of 'both'

**Comment by daiClegg** [comment]
When adding Cost of Living Items, gender is mandatory, even for Household and Study.
It is only relevant for CoL items that apply at the HH Member level

**Comment by daiClegg** [comment]
When adding Diet Items there is no validation of the total percentage.
Feedback on a per-record basis of the running total is 'could have'
VAlidation to 100% on close of the create item pop-up is 'must have'

**Comment by daiClegg** [comment]
Standard of Living Items allows inclusion any Resource Sub Type.
Should only allow Non-Food Purchases (e.g. Clothing, Paraffin, School Fees , Soap, etc)

@DrJohnSeaman @celiapetty Is this correct? Standard of LIving items are only ever Non-food purchases, such as above?

**Comment by daiClegg** [comment]
Site should be the first sub-block in the list of Site, Standard of Living Items, Diet & Assets/Resources.
And can "Assets/Resources"be re-labelled "Characteristic Assets/Resources"

**Comment by daiClegg** [comment]
No Resource Types are included in the drop-down when creating a Tradable Characteristic resource.
Should allow any Tradeable Assets

**Comment by daiClegg** [comment]
If the window is too narrow the Study detail view just extends outside the layout box.
See screenshot below.
It is accessible with scrolling, so this is just a UI bug.
Functionality appears to be unaffected.

![image](https://user-images.githubusercontent.com/30879677/53375914-8b61f680-3954-11e9-9d13-ec7124ad3cbe.png)

**Comment by dbrownukk** [comment]
26/2/19 latest fixes yet to be deployed to idaps

**Comment by dbrownukk** [comment]
Deployed current select of fixes. 

ToDo
1.Complete Diet Item percentage check - though does now show the total
2. Check Tradeable resources list of values

Note that there is an extra Tab for 'Questions' in the Study screen. Ignore for now..

**Comment by daiClegg** [comment]
- Error attempting to select existing District: Tested OK
- Gender Unknown should be Gender Both when  configuring Gender-irrelevant questions: Tested OK
- Specifying Gender at Study & HH level should not be mandatory  - Tested OK
- **Note** there is a case for prohibiting specifying Gender except at HH Member level - thoughts?
- Maintaining running total of Food Item %ages in SoL: Tested OK
- Standard of Living Items are Non-Food Purchase: Tested OK
- Ordering of tabs to give Site precedence: Tested OK
- Characterisitc Assets/Resources correctly labelled: Tested OK
- Study Detail view layout in width-restricted windows: Tested OK

**Comment by daiClegg** [comment]
moving to WIP pending the 2 outstanding fixes

**Comment by daiClegg** [comment]
**Sub-Feature: Characteristic Assets/Resources **
- List of Values for Food Stock Asset should allow any  'Crops', 'Wild Foods' or 'Livestock Products'. There is no Resource type 'Food Stocks'.
- List of Values for LIvestock Sales should be any 'Livestock Resource SubTypes. There is no Resource Type 'Livestock Sales'

**Comment by daiClegg** [comment]
FoodStocks not correctly processed
Create a new Project (TestFoodStocks1)
Create a new study (FoodStockTest1)
Navigate to Characteristic Resources tab.
 * note the number of FoodStock Records is -1

Add a new FoodStock Characteristic Resource
*  the dropdown does not offer 'Crops', 'Wild Foods' or 'Livestock Products' (as per comment 6 days before this one)
* insert appears to work, but does not display the record.

navigate away from foodstock sub-tab and then back
* Foodstock is displayed as ERROR

**Comment by daiClegg** [comment]
Livestock Sales not correctly processing
--

Livestock Sales appears to be pre-populated with whatever Livestock Assets have been created.
There should be no defaulted Livestock Sales records.
When creating a new Livestock Sales record, the dropdown should be restricted to those Livestock Resource sub-types for which a Livestock Asset record exists.
ie you can only sell what you have.
But you don't necessarily sell any of your assets.

make sense? tag for a call if necessary

**Comment by daiClegg** [comment]
All other characteristics, Diet & Std of Living appear to work.
Will test whether they generate correctly under the Spreadsheet generation Issue

**Comment by daiClegg** [comment]
**Feature Complete**
