### ISSUE TITLE
HH DI with Standard of Living Costs: sorted by ascending DI

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#224]

**Comment by daiClegg** [comment]
As per the SOLT tab of the Example Reports spreadsheet attached to Issue #230

The only reported data items are the HH ID and the Standard of LIving calculation 
 - DI - Total Cost of StdofLiving (SOLT) for the HH
Calculation is documented in Issue #233

**Comment by daiClegg** [comment]
Standard best practice shows negative and positive DI - SOLT in a different colours in the chart.
The data is arranged in two columns - one for the negatives and one for the positives, to make that easier for the user.

Reporting the data in this format is not the requirement. 
Making it easy for the user to create the chart from the raw data is.

**Comment by DrJohnSeaman** [comment]
Correct

**Comment by daiClegg** [comment]
from Discussion....

report should include SOLT & DI for each HH, or quantile, in ascending order of DI

**Comment by celiapetty** [comment]
Yes, that's correct.

**Comment by dbrownukk** [comment]
now includes SOL and DI 
deployed

**Comment by daiClegg** [comment]
**Tested Ok**
