### ISSUE TITLE
HH Cash Income by source type: sorted by ascending DI

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#225]

**Comment by daiClegg** [comment]
As per the Cash Income tab of the Example Reports spreadsheet attached to Issue #230

The reported data items are the HH ID and the totals of cash income from each of:
- Crops Sales
 - Employment 
 - Livestock (Live and Products) Sales
 - Transfers
 - Wild Foods Sales 

@DrJohnSeaman  @celiapetty Am i right in how i have described the derivatino of the Livestock figure?

**Comment by celiapetty** [comment]
Yes-cash derived from live sales and sale of livestock products

**Comment by daiClegg** [comment]
ok, Will proceed on that basis.

**Comment by daiClegg** [comment]
**Feature Complete**
