### ISSUE TITLE
HH Food Income by source type: sorted by ascending DI

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#226]

**Comment by daiClegg** [comment]
As per the Food Income tab of the Example Reports spreadsheet attached to Issue #230

The reported data items are the HH ID and the KCal totals derived from each of:
As per the Cash Income tab of the Example Reports spreadsheet attached to Issue #230

The reported data items are the HH ID and the totals of cash income from each of:

 - Crops Consumed
 - Employment Paifd in Food
 - Livestock Products Consumed
 - Transfers in Food that is Consumed
 - Wild Foods Consumed

**Comment by daiClegg** [comment]
Fixed i think; you are right - sloppy cut and paste.

**Comment by daiClegg** [comment]
Some aspects of this report that are shared by other reports are discussed in #230

**Comment by daiClegg** [comment]
As reported elsewhere; roeprt fails with exception:

>  java.lang.NullPointerException Errno = 54

**Comment by dbrownukk** [comment]
deployed fix.

**Comment by daiClegg** [comment]
**Tested Ok**
