### ISSUE TITLE
HH Land Assets: sorted by ascending DI

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#227]

**Comment by daiClegg** [comment]
As per the Food Income tab of the Example Reports spreadsheet attached to Issue #230

The reported data items are the HH ID and, for each HH their Land assets, one column per type of Land Asset (Upland, Lowland etc)

There should be a column for each Land Asset Types held by at least one HH.

**Comment by DrJohnSeaman** [comment]
Correct. Just for information is the hhid the household number, as used in the survey? Not just the number used by the software?

**Comment by celiapetty** [comment]
The number shown along the x axis is the number used by the software (bars show in numerical order) not the HH ID. This can cause confusion, so best practice is to delete the numbers on the x axis manually. It would be desirable to show  the actual HH ID  under the corresponding bar

**Comment by daiClegg** [comment]
I had planned that we would always use the HHID from the initial definition of the Household as the x-axis label for all reports for all or some subset of HHs in the Study.

**Comment by celiapetty** [comment]
Good-this is an improvement on the current software

**Comment by daiClegg** [comment]
**Tested Ok**
