### ISSUE TITLE
HH Livestock Assets: sorted by ascending DI

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#228]
Livestock Assets, by type of Livestock  resource sub type( Cow, Bull, Pig etc)

This dataset is of numbers  of each asset type, not value of asset
The resulting chart means if a HH has 20 Hens their Asset bar is way higher than that of a HH that owns 2 bulls.

Surely there is no value in such a chart.
The report should either be by value of asset (stacked, by asset type) or not a stacked column chart
A clustered column layout would at least make it possible to compare assets of each type - though it would be very crowded

**Comment by daiClegg** [comment]
Celia, do you agree this report should show value of assets, not count of assets? 

The spreadsheet ( Issue #?) includes unit prices for assets, so if they are collected it would be possible to calculate value for this report.

**Comment by DrJohnSeaman** [comment]
Tos add to my previous comment. Value is the most useful. Numbers are helpful a) if the values are not available b) in theor own right e.g who owns plough oxen?

**Comment by daiClegg** [comment]
Take the point about that value of the numbers.
Should those just be delivered as a numerical report?
A chart is adding no value and is, as i mentioned above, potentially deceptive.

**Comment by celiapetty** [comment]
Just confirming we need the number of each type of assets held, as well as the value where this is available.  As long as numbers can be pasted  into Excel  (as with current version)  users can make their own decisions on how they present the data.

**Comment by daiClegg** [comment]
So to summarise:
- Keep the report by numbers of livestock assets by type  (cow, pig, chicken, etc)  not as a chart but as tabular data
- Add a new report, a stacked histogram (current visualisation format), showing value of assets by type.

**Comment by DrJohnSeaman** [comment]
Agreed

**Comment by daiClegg** [comment]
@celiapetty @DrJohnSeaman 
The Livestock Resource Sub Type datya needs cleaning up (see the scrteenshot below.
There are Cow, Local Cow, Cattle, Cow (Dairy), IMproved Cattle (Dairy) and no synonyms.
I suspect some of these are synonyms.
Can one of you review and edit the list to reflect real-world best practice please?

**Comment by daiClegg** [comment]
The reported data is correct, as recorded, but livestock names synonyms need to be corrected to make the report meaningful for real-world use.

**Feature Complete**

**Comment by celiapetty** [comment]
Noted-thanks for highlighting this
