### ISSUE TITLE
HH Income from Trade: sorted by ascending DI

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#229]
Income from trade-related employment

Are these Employments in the category 'Self-Employed?
Is this a standard report a custom report for the study these examples were taken from?

**Comment by DrJohnSeaman** [comment]
Income from trade-related employment Are these Employments in the category 'Self-Employed? If trade related is a sub category of self employment then yes
Is this a standard report a custom report for the study these examples were taken from? I dont understand this.

**Comment by celiapetty** [comment]
Under each of the 5 income sources (crops, livestock, employment, transfers, wild foods) users can select specific income types for analysis. This is an example:  income from trade related self employment

**Comment by daiClegg** [comment]
@DrJohnSeaman:  i meant: is this a standard IHM report (income from trade-related employment) or is it a custom report for the study from which these sample outputs were taken. 
That may be a question for @celiapetty 

With respect to Trade as a category of Self-Employment as a category of Employment, currently, Categories within Resource Types are not hierarchical, as we discussed in Issue #102.
Are you saying there is a requirement for hierarchies of Categories?

I would suggest we avoid that if possible as it will make it more complex for users to understand what is part of what and it will make it more complex for you guys making sure everything is classified correctly. 
However if it is a real requirement that we would be less able or unable to manage without,, then so be it.

**Comment by celiapetty** [comment]
Hierarchies of categories are best avoided in my view.   Better for users to define sub categories as required in line with objectives of study and explain reasons for this in the narrative.

**Comment by celiapetty** [comment]
There may be some confusion here? The income categories (crops, livestock, employment, wild foods, transfers) are not user defined and are required as standard food income and cash income reports. In addition to this,  in the current version of open-IHM the user can select items from a drop down list within the fixed categories (crops, livestock, employment, transfers, wild foods)  to generate an excel spreadsheet . This is an mportant function.

**Comment by daiClegg** [comment]
So are the 8 reports in the sample spreadsheet (Attached to Issue #230) all standard reports that are expected for any study?
Which ones can be customed?
Which are always parameterised/cusatomised in some way?

---

I think we've reached the point where a call would be useful.
I've invited you to a Doodle poll. Tick the slots you can make. 
We'll take the first one we have one in common, and i'll confirm by separate email.

---

**Comment by daiClegg** [comment]
Further commentary about aspects of this report that are shared with other reports continue in Issue #230

**Comment by daiClegg** [comment]
This is a specialisation of  #225 (HH Cash Income by source type: sorted by ascending DI) , based on just the Employment types that are categorised (probably in a Category) as Trade.

So this is implemented by  #225
