### ISSUE TITLE
overriding names of columns when displaying in forms

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#23]
I assume field names default tocolumn names, but can be overwritten. A

And i know the user can edit them , but that isn't persistent when the page is re-visited later.

Can you set the field name for every time it is used and for it's use in a specific page/panel? Or both?

**Comment by daiClegg** [comment]
labels can be defined globally or at module.
And differently for list view and detail view.

Changes should be logged in this issue for all label change requests.
Note make sure at least one developer is assigned (ie will get the notification) when you log a new change request.

**Comment by dbrownukk** [comment]
Examples of Field Label changes

# Labels for EFD_v2 application

EFD_v2=Evidence for Development OHEA Data Set V2
Country.isocountrycode=ISO Code
Country.countryname=Country

LivelihoodZone.module=Livelihood Zone
LivelihoodZone.lzname=Zone Name
LivelihoodZone.country=Country
LivelihoodZone.lzzonemap=Map  
Livelihood_Zone=Livelihood Zone


Project.projecttitle=Project
Project.pdate=Start Date
Project.livelihoodzones=Livelihood Zones
Project.Spreadsheet=Spreadsheet
*.tab.properties.country.description=Country
pdate=Start Date
projecttitle=Project
project_of_projectlz=Project
projectlz=Project
civparticipants=Participants


Site.livelihoodzone=Livelihood Zone
Site.gpslocation=GPS Location
Site.subdistrict=Sub District
Site.locationdistrict=District


Community.clocation=Site
Community.cinterviewdate=Interview Date
Community.cinterviewers=Interviewers
Community.cinterviewsequence=Sequence
Community.civparticipants=Participants
Community.civm=Males
Community.civf=Females
Community.project.projecttitle=Project
Community.projectlz.projecttitle=Project


WealthGroup.module=Wealth Group
WealthGroup.wgnamelocal=Wealthgroup(Local)
WealthGroup.wgnameeng=Wealthgroup(English)
WealthGroup.wgorder=Order
WealthGroup.wgwives=Wives
WealthGroup.wghhsize=HH Size
WealthGroup.wgpercent=Percent
Wealth_Group=Wealth Group


WGCharacteristicsResource.module=Characteristics Resource
WGCharacteristicsResource.resourcesubtype=Resource Sub Type
WGCharacteristicsResource.wgresourcesubtype=WG Sub Type
WGCharacteristicsResource.wgresourceunit=WG Unit
WGCharacteristicsResource.wgresourceamount=WG Amount
WGCharacteristicsResource.tab.properties.wealthgroup.wgnamelocal=Wealthgroup(Local)
WGCharacteristicsResource.tab.properties.wealthgroup.wgnameeng=Wealthgroup(Eng)
WGCharacteristicsResource.tab.properties.resourcesubtype.resourcetypename=Resource Sub Type
WGCharacteristicsResource.tab.properties.wealthgroup.community.projectlz.projecttitle=Project
WgcharacteristicsResource=Characteristic Resource
Characteristics_Resources=Characteristics Resources

ResourceSubType.module=Resource Sub Type 
ResourceSubType.resourcetype=Type
ResourceSubType.resourcesubtypesynonym=Sub Type Synonym
ResourceSubType.resourcetypename=Name
ResourceSubType.resourcesubtypeunit=Sub Type Unit
ResourceSubType.resourcesubtypekcal=Sub Type KCal
ResourceSubType.tab.properties.resourcetype.resourcetypename=Resource Type
ResourceSubType.tab.properties.resourcesubtypesynonym.resourcetypename=Synonym

ResourceType.module=Resource Type
ResourceType.resourcetypename=Name
ResourceType.resourcesubtype=Resource Sub Type
ResourceType.tab.properties.resourcetype.resourcetypename=Synonym
ResourceType.tab.properties.resourcesubtypesynonym.resourcetypename=Synonym
ResourceType.tab.properties.resourcesubtypesynonym=Synonym

**Comment by dbrownukk** [comment]
for detail mode use Entity.fieldname= Your Field Name

for list mode use Entity.tab.properties.fieldName=Your Property Name

in the above file EFD_v2-labels_en.properties in i18n folder
