### ISSUE TITLE
Produce Standard IHM Charts

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#230]
This issue is the parent issue for each individual report.
All the examples discussed in the individual report issues are attached here, so i don't have to upload them 7 times).

Spreadsheet examples:
---
[Examples of IHM output, 9.01.2019.xlsx](https://github.com/dbrownukk/EFD_v2/files/2799348/Examples.of.IHM.output.9.01.2019.xlsx)

Powerpoint examples:
---
[Examples of IHM output for 9th Jan 2019.pptx](https://github.com/dbrownukk/EFD_v2/files/2799349/Examples.of.IHM.output.for.9th.Jan.2019.pptx)

**Comment by daiClegg** [comment]
I thought i'd asked this question elsewhere, so if i have apologies for the duplicate, but, it applies to all the reports so it should be here in the parent 'Epic'

Q: 

In OHEA the charts are pdfs. The examples attached here are all in a spreadsheet.
Is that how OpenIHM delivers the outputs? As a single spreadsheet, one report, as a data table, per tab?
And is the chart also generated or is that added by hand afterwards?

If so is that how OIHM should deliver outputs?

**Comment by celiapetty** [comment]
OIHM delivers output for each report (eg DI per AE) in an excel
spreadsheet. Users produce their own charts from this data. Should discuss
options eg for model outputs.

**Comment by daiClegg** [comment]
@celiapetty I thought we had the outputs in the attached spreadsheet above? 
I have created a separate 'Feature' issue for each of them as a part of this 'Epic'.
Are there others that are missing? If so please create new issues for them (same format as i have used for the first seven) and assign to me, you & john.

And can you review the seven i have created to make sure they are all required, please, and add any notes of clarification? Thx.

If there's some uncertainty, then we should probably set up a call to discuss, but i'd like to document what we know we know first.

Note this thread is for the g
eneral discussion about reports/outputs.
Discussion of any specific rep[ortg should have its own issue.

**Comment by daiClegg** [comment]
Should not each report Tab include in the title some data to identify the Study - e.g. Study Name and maybe Site (Village), as well as what the report is of )e.g. 'Standard of LIving'

I suggest the same identifying data be repeated on each tab, so full context is visible in a single view.

**Comment by daiClegg** [comment]
@celiapetty - yes, Tab means a tab on the spreadsheet of example outputs attached to Issue#230.

@DrJohnSeaman 

> I assume that the other asset types and income sources will be added.

It's safer to never assume i'll do anything if you haven't asked me to do it.
I've been working form the required outputs that Celia sent me. 
If there are more, then i'd very much like a definitive list - of standard reports, standard, but parameterised/customised reports, optional reports (with or without customisation),  other data sets and data set selcetion criteria for custom reports.
Anything you can define before we talk next week (hopefully) will make that discussn more productive.

**Comment by celiapetty** [comment]
Household membership wasn't included in the original set I sent but I agree this would be very useful as an output. This would allow demographic data to be accessed in a way it can't be in the current software.

**Comment by daiClegg** [comment]
What does a Household Membership report look like?

And should we add the age ‘Christmas tree ‘ chart?

**Comment by daiClegg** [comment]
@celiapetty for the HH Members report do you mean something like this?

[HMembers.xlsx](https://github.com/dbrownukk/EFD_v2/files/2824785/HMembers.xlsx)

@DrJohnSeaman @celiapetty if you both agree this is a useful report i'll create a new Feature Issue for it and we can refine the content there. Also is the Population Pyramid arequirement?

**Comment by celiapetty** [comment]
Yes, that's it-a table that would allow further analysis to be made. 
I think we should include the population pyramid as a requirement

**Comment by DrJohnSeaman** [comment]
Yes to a population pyramid. By 5 year age groups ie 0 -4,5-9 etc

In addition it is sometimes useful to be able to select specific population
groups e.g. females < 16 years, everyone > 70 years. Assuming that you want
to arrange this as a standard output (ie not allowing the user to select
whatever) how about a table which dumps all the demographic data by sex and
1 year age groups say by DI and DI/ae. Big table, but it does mean that a
user can get the data if they want it.

IHM is used for a very wide range of purposes so I generally work on the
priciple that the user should be able to get any data out which was put in.

John

**Comment by celiapetty** [comment]
Examples of possible output, household and personal characteristics

[Output examples, Hhold and  personal characteristic.xlsx](https://github.com/dbrownukk/EFD_v2/files/2828561/Output.examples.Hhold.and.personal.characteristic.xlsx)

**Comment by daiClegg** [comment]
**Note** All Reports may optionally be of the relevant raw data or of the raw data per 'Adult Equivalent'.
  The equivalent in OHEA are the 'normailsed' reports - ie divided by the number of persons in the WG average household, assuming 2100 Kcal per person per day.
However in IHM the 'Adult Equivalent' is calculated more precisely as the number of KCa;ls required for each member of the household, calculated from WHO standard tables fro their Gender and Age.
This calculation is explained in detail in ...

**Comment by daiClegg** [comment]
**Note** all reports that are by HH may also be requested by Quantiles, that collect HHs into groups to make simpler reports, where the detail of each individual HH is not necessary.

For example, we might want to report the Disposable Income of a Study of 60 HHs in Quintiles.
5 groups would be created: the poorest 12, the next 12, and so on to the 5th quintile of the most well off 12 HHs. 
The report would then have one set of data points for each quintile, being the average of the equivalent data points of the 12 HHs in the quintile.

**Comment by daiClegg** [comment]
HH Member Characteristic now defined as a separate report, part of this Epic.

**Comment by daiClegg** [comment]
@DrJohnSeaman, you wrote, above
:
> IHM is used for a very wide range of purposes so I generally work on the
> principle that the user should be able to get any data out which was put in.

Do you mean like the Project report in OHEA?

**Comment by daiClegg** [comment]
**Note** Users need to filter what Resources are to be used in preparing a report run
So for example, 
 - I want the 'Food Income by Source Report, but i only want to include Crops (resources type).
 - I want to report Wild Foods by Fruits (Category)
 - I wish to include multiple Categories are Resource Types in a report.

And i may wish to create temporary Categories specifically for this Study.

**Comment by daiClegg** [comment]
Design Model including Study-specific Categories committed as IHM&HEADesignModel4

**Comment by DrJohnSeaman** [comment]
This is a descision for you.. Ideally the user should be able to select any data item or items, combine these if required, and present them in an ordered way. Practically speaking this is probably an unreasonable amount of work so a reasonable alternative would allow all the data to be exported - the user can then cut and paste as required. Perhaps give some user control e.g. export selected households, as with large data sets all the data might be a bit much.

**Comment by daiClegg** [comment]
@DrJohnSeaman How far we get with filtering and use of categories etc, as we discussed (now documented appropriately above, i hope) depends on cost. 
But it's not really my decision, As the experts, you and Celia should decide what's the ideal list. And what you value most highly. It's up to me to find a way, with David, to deliver as much of that as possible within budget. 
With luck, we won't run out of budget, but if i feel we can't deliver everything you want, i will ask you and Celia to set priorities so we get the maximum value for the spend. 
What we implement should be your decision not ours, how we deliver it is more David's and my responsibility. 

Thanks for the swift turnaround of questions and the feedback. There will be plenty more.

**Comment by daiClegg** [comment]
Categories are discussed in #102

**Comment by daiClegg** [comment]
For reporting delivered as exports of .xls files, some processing in Excel is acceptable.
Indeed might be desirable – to allow for custom analytics. 
Where the balance lies in pre-processing with OIHM and in spreadsheets is a design issue.
As long as the user can get the results they need without a deep understanding of either the calculations (such as DI) or of Excel.

ONe possible design might be a spreadsheet that manages data visualisation using a back-end spreadsheet that contains the exported raw data.
This is a discussion for M3.

**Comment by daiClegg** [comment]
The ability to report and analyse data sets from all the Studies in a Project as one unit would be useful but is not essential. Note most Projects only include one Study anyway.

Fir discussion as part of M3 planning

**Comment by daiClegg** [comment]
@celiapetty The spreadsheet you sent with example outputs, attached at the top of this thread, as , 9.01.2019.xlsx references 4 other streadsheets that i don't have. Can you attache them here please?
Thanks.

**Comment by celiapetty** [comment]
I've just checked: the file  I uploaded includes DI; Standard of living threshold; Sources of cash income [5 categories-crops, livestock, employment, wild foods transfers]; sources of food income [same 5 categories] plus land assets, lstock assets, examples of selected income from trade and selected income from l'stock- so I think the comment was meant to read the 4 standard charts (DI, SOLT, food income , cash income, plus 4 other worksheets? )As discussed, all income charts should be shown in order of DI/Adult equivalent with poorest household on the extreme left. There should be an option of showing output per Adult equivalent or the absolute 'raw' values. In addition, as discussed, users should be able to select any number of specific sources of food or cash income, within any of these categories .
We discussed other assets (land, livestock, tradeable goods, trees, cash). It is useful to be able to choose specific assets within each category and show in a chart, in order of DI/AE  as well as using a tabular format as discussed (I can't exactly remember how this would look). Apologies for the long answer to a simple question.

**Comment by daiClegg** [comment]
Celia, no i meant that the spreadsheet links to 4 other spreadsheets to reference data from them.
I have no idea what's in them, it should only be the source data for referenced data in the sheet i have.
But i'd like to have them anyway, just so i can check.

**Comment by daiClegg** [comment]
As discussed, The attached document shows the workflow for Reporting in OIHM.(IHM&HEADesignModel9.mwb) 

[OIHM reporting.docx](https://github.com/dbrownukk/EFD_v2/files/3010116/OIHM.reporting.docx)

The data model for Report Specification, referenced in this document,  is uploaded to the Design Doc

**Comment by daiClegg** [comment]
In discussion of Issue #288 (Modelling) the quantiles requirement was not for Terciles, Quartiles or QWuintiles - as defined above, but for more flexible user-defined quantiles, in the form of an ordered collection of 'buckets', each to represent a user-defined %age of the whole set; the order being from poorest to richest.
Although this is a more demanding quantile requirement, it would probably be simpler to support just one method for both reporting and modelling. So a revision to the reporting spec to accommodate this is here:
and the revised data model uploaded here:

(pending uploads)

**Comment by daiClegg** [comment]
Post w.i.p. demo &  discussion a revised spec for the reporting workflow is included here:
[OIHM.reportingV3.pdf](https://github.com/dbrownukk/EFD_v2/files/3177475/OIHM.reportingV3.pdf)

The changes are reflected in the latest design data model uploaded [here].(https://github.com/dbrownukk/EFD_v2/blob/master/DesignDoc/IHM%26HEADesignModel11.mwb)

**Comment by daiClegg** [comment]
@celiapetty @DrJohnSeaman 

Which reports should include Raw data and AE?
Is it just the DI report? Or DI with StoL as well?
Any others

**Comment by DrJohnSeaman** [comment]
I dont think I understand. Please elaborate

**Comment by daiClegg** [comment]
I meant are there any other reports that might benefit from an AE variant.
Cash Income was the only one i thought might conceivably fall into that category.
I raised the same  question in my notes today on modelling (Issue #288)

**Comment by celiapetty** [comment]
Cash income does benefit from 'raw' output and is wuite ofyen used in ihm
studies

**Comment by daiClegg** [comment]
All the composing features  are delivered, so closing this
