### ISSUE TITLE
Style choice

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#231]
Choice of styles is now available in 6.0 of OX

set in xava.properties but cannot see a way to dynamically set, which is probably a good thing..

#styleCSS=light.css is the white background. default is the colourful version

![screenshot 2019-01-28 at 16 20 42](https://user-images.githubusercontent.com/12796427/51850141-1087ca80-2319-11e9-97cf-b26746684c41.jpg)
![screenshot 2019-01-28 at 16 19 03](https://user-images.githubusercontent.com/12796427/51850153-15e51500-2319-11e9-98f7-b6fc4692471b.jpg)

**Comment by DrJohnSeaman** [comment]
I like the menu bar on the left - the current one  dissapears when scrolled.

I dont have strong feelings about colours.

John

**Comment by celiapetty** [comment]
Menu bar on left looks good. 
Re colours-no preference. We might ask users -James/Hosea/Stella which of the 2 options is clearer when it comes to the next round of testing (assuming we don't need an immediate decision on this? the switch from default colour to white )

**Comment by daiClegg** [comment]
In the testing i have done to date, the white shows more clearly.
If at some point someone raises an issue about the visibility of the app, then we can consider an alternative style sheet.
But right now we have a consensus, so let's not have a referendum about it.

Let's go with the white stylesheet.

**Comment by dbrownukk** [comment]
done, now white at http://idaps.walker.ac.uk:8080/EFD_HM/

**Comment by daiClegg** [comment]
Tested ok
