### ISSUE TITLE
Load WGI generated from John's HEA software. 

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#232]
Database: http://idaps.walker.ac.uk:8080/EFD_v2/m/SignIn
UN: Admin
Project: TestJohnsWGIExporter
LZ: Z1 
District:abcdistrict 
SubDistrict: abcsubdistrict 
WG: Test1

There is a spreadsheet attached to this WG.

John generated it as a .xslx; i saved it as a .xls
I tested both versions 
Was able to upload & save successfully.
On Parse i got the same error with both versions.

>Impossible to execute Parse spreadsheet action: For input string: "Date"

I noticed the values for Interviewees, Male & Female were all null so i set them to 2, 1 & 1.
Made no difference.

I searched the spreadsheet for the string "Data' as cell content, but got no hits.

**Comment by daiClegg** [comment]
@DrJohnSeaman  does this mirror the test results you got?
If you tried any other tests, can you document them here in a similar format to mine. Thx.

**Comment by dbrownukk** [comment]
Dai, John,

The TESTOHEAL.xls has everything shifted one column to the left. Thus is finding the word 'Date' , a string, for the Interview number, which should be an Integer.

regards,

David

**Comment by daiClegg** [comment]
Bollox. I should have spotted that. I checked row position and i just ignored the column position. Thanks and sorry for the waste of your time.

**Comment by daiClegg** [comment]
I added the missing column & the data all loads ok.
It is now attached to the project noted at the top of this thread,=, and is part-parsed.

Parse fails pretty much everything, since the format of the descriptors don't match the conventions we've adopted in OHEA.

**Comment by DrJohnSeaman** [comment]
Thanks, Ill fix it
