### ISSUE TITLE
Calculate Disposable Income after Standard of Living for Social Inclusion is achieved

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#233]
1. Disposable Income (DI) is calculated as in Issue #145 

---
However, if a family is to be part of a community there are additional costs, on top of the base food costs.
These will might include such items as kerosene/paraffin for cooking, clothing, school fees, school uniforms and so on.
The Standard of Living requirements for a study are recorded in Study Configuration (Issue #221 ) as StdOfLiving Elements.

---
2. The total cost of achieving the standard of living (SOLT) is the sum of the cost of each StdOfLiving Element for a given HH.
Each Element specifies:
 -  the Resource subtype (typically a NonFoodPurchase) that it relates to (e.g Adult Male Clothing)
 - the number of units
 - the unit cost.

 Each Element is either:
 -  a HH element (ie 1 is required) 
 - a HH Member  element (all)
 - a Gender and/or Age specific element 
ie the  members of the HH it applies by gender and by age range.

The example above, (Adult Male Clothing) is a HH Member cost element that applies to Males over the age of (say) 16. 

3. The DI after StdOfLiving is achieved, is therefore the DI - SOLT

**Comment by daiClegg** [comment]
This is a key calculation, along with base DI calculation - Issue #145 )that is used in all reports.
And it is a complex calculation, needing to retrieve data from every RST so it feels like it should be stored.
However, it would need recalculating any time an RST that involves cash changes or any time a Std. of Living element changes.
That being so it seems like it should only be calculated when the HH is validated. But it will still need update triggers setting to re-calculate.

**Comment by daiClegg** [comment]
No need to include this in M1, since not all of the data needed has been collected by then. 
Make sense?

**Comment by dbrownukk** [comment]
deployed

**Comment by daiClegg** [comment]
**Tested Ok**
