### ISSUE TITLE
HH income from Livestock

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#234]

**Comment by daiClegg** [comment]
As per the Income from Lstock tab of the Example Reports spreadsheet attached to Issue #230

The data item reported as HH Id and for each, HH their Livestock Live Sales, for each type of Livestock sold by at least one HH, the number of total value (e.g. for Hens 20 * Unit Price for Hens in the Livestock LIve Sales data for the relevant HH.

If we stick with delivery as a multi-tab spreadsheet as in the example, this is probably best delivered as 2 separate matrices - one for Values & one for Totals, since the Values will be charted, but not the Numbers. Whatever the delivery mechanism the requirement stands.

**Comment by celiapetty** [comment]
Should be clear in the heading: this chart is Income from Livestock sales.

Is my understanding correct, that income from livestock products will be reported separately?

**Comment by daiClegg** [comment]
At the workshop, i noted (not sure who said it) Income from Livestock as a required report.
If that's not needed every time it could be generated, on-demand, by customising Issue #225 (HH Cash Income by source type: sorted by ascending DI) to only include Livestock income.

I notice that Issue #229 (HH Income from Trade: sorted by ascending DI) is similarly a customisation of #225, providing a Category has been defined that identifies the Employment types classified as Trade. 

 I'd prefer to eliminate the standard report and leave them as custom reports, if that's what they are.
Are there any other reports that could be regarded as customisation of a more general report?

**Comment by celiapetty** [comment]
We should clarify this afternoon. The standard report is on the 5 main
sources of income ie Crops, Livestock&livestock products, Employment, Wild
foods and Transfers.

Within the category l'stock & l'stock products, users should be able to
select specific items/income sources  (and as discussed, this should also
be possible for the  other 4 categories)

**Comment by daiClegg** [comment]
Agreed this is just a customisation of  #225 (HH Cash Income by source type: sorted by ascending DI)
