### ISSUE TITLE
Define & Configure Households

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#235]

**Comment by celiapetty** [comment]
Households are just created from the uploaded spreadsheets: so a new, household record is created for each new, different interview spreadsheet. 
Note that in longitudinal studies,  a new household record is created for each round of interviews, but the household ID number should be retained (even though hhold membership may have changed ie some new members, some died or moved away).

**Comment by daiClegg** [comment]
Adding David to Assignees, since the key requirement that Households are created by the upload of a spreadsheet is significant for the process flow.

Households are not created in advance and a spreadsheet generated for each, as would be the analogy of WGs in HEA.
The Study is configured for what might be expected of any Household, in terms of characteristic resources, and copies of the same generated spreadsheet are used for each household in turn.
When the spreadsheet is loaded for a new household the record is created for it in the study and the actual resources (Crops, Livestock etc) are then created for that Household - And now the analogy with WGI in OHEA holds more closely

**Comment by dbrownukk** [comment]
Household and Household member data structures and CRUD screens are available.

Moving this to OIHM M2 as the data to create HH and HHM is created on populated spreadsheet parse

**Comment by dbrownukk** [comment]
HH and HHM are created on parse of uploaded spreadsheet

deployed

**Comment by daiClegg** [comment]
Testing of HH configuration included in Study configuration.
 Testing of  defining HH is part of Upload.

This feature is implemented & polish is handeled elsewhere
