### ISSUE TITLE
Calculate Adult Equivalent KCal requirement for a Household

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#236]
Adult Equivalent is calculated from the precise KCal requirement for a HH, calculated for each HH Member according to their Age & Gender, from the WHO standard tables.

It is required for all reports, for example, to define the Food Income, for the HH or per Adult Equivalent.

@celiapetty Can you link to, or upload, the table to be used please and define the algorithm?

**Comment by celiapetty** [comment]
Disposable income must be standardised for household membership. This is done using the 'adult equivalent', i.e. the total requirement of the household, measured in units of adult food energy requirements (2600 kcals per day, the daily energy requirement of a young adult male or female).
 The calculation is as follows:
Number of 'adult equivalents' in the household=(household members'  total energy requirements)/(adult energy requirement (2600 kcals per day))

**Comment by daiClegg** [comment]
@celiapetty  where is the table from which we get the requirements by age and sex please?

**Comment by DrJohnSeaman** [comment]
The 1985 values should be OK.  As far as I can see there is no more recent version which gives summary values in an accessible form.

**Comment by daiClegg** [comment]
This is surface as part of the DI calculation, so test as part of Issue #223

**Comment by daiClegg** [comment]
A spreadsheet that calculates AE & can be used to cross check is uploaded here
[Calculations.xlsx](https://github.com/dbrownukk/EFD_v2/files/3248668/Calculations.xlsx)

AOpen the spreadsheet.
Update the Links (Data menu) to point to the HH interview SS for a HH and this spreadsheet will calculate the AE.

Note it only works for HHs of 10 or fewer members.

**Comment by daiClegg** [comment]
**Tested ok**
