### ISSUE TITLE
Report HH Members characteristics

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#237]
A table with age and sex of all household Members, in order of DI to allow the user to analyse however they like? 
An example of this is in the Personal Characteristics tab of this spreadsheet:

[Output.examples.Hhold.and.personal.characteristic.xlsx](https://github.com/dbrownukk/EFD_v2/files/2830079/Output.examples.Hhold.and.personal.characteristic.xlsx)

**Comment by daiClegg** [comment]
@celiapetty In the Personal Characteristics example you provided (attached above) you include education level (Primary, Secondary, Tertiary) and Notes as well as HH Member number, Age & Sex.
Only the last 3 of these are standard properties of a HH Member record. 

Is it the requirement that every configured personal characteristic in a Study should be appended as an additional column in the report?

**Comment by celiapetty** [comment]
Question for clarification please at our next telecon

**Comment by daiClegg** [comment]
Would like some example real-world topics for inclusion in the database

**Comment by daiClegg** [comment]
In the beneficiary/non-beneficiary report, on the HH characteristics tab, DIs are included in columns representing the beneficiary status of the HH. This allows the user to easily create a report with different coloured columns for each. This is a regularly used trick in IHM reporting. 

It's moving processing into the app to save processing of the extracted data.
That's a brittle solution unless it is only ever required for yes/no characteristics and always for DI.

**Comment by daiClegg** [comment]
The column headings in this report are the HHM question prompts.
The cells below are the answers for each HHM.
Note this includes the configured and the standard questions.
The scope is, by default, all HHMs of all HHs
The order is by DI of the HHs included and by HHM number within HH,

**Comment by daiClegg** [comment]
The HH tab is the same structure - question prompts as columns.
Answers for each HH as cells below.
Sort order by DI of the included HHs.
By default all HHs included

Ignore the chart in this example.
It is just an example of how DI is often expressed for y/n answers (ie different colour for Ys & Ns)

**Comment by celiapetty** [comment]
Notes attached. If further clarification is needed please let me know.
[Household member questions.docx](https://github.com/dbrownukk/EFD_v2/files/3022663/Household.member.questions.docx)

**Comment by daiClegg** [comment]
Thanks for this. I’ll set up some more realistic test data based on it.

Is there any reason why you ask multiple yes/no questions to get the education attainment level?
Why not ask for the level as a multi-value answer: none/primary/secondary/tertiary.
That would seem better to me because it's only one question to ask.
In OIHM the interview spreadsheet the answer cell would have a drop down defined with those values, so it would be easy for the user to select. 
 
But can equally support the way you have encoded it if you prefer.

**Comment by celiapetty** [comment]
Your suggestion is better-please go with the multi-value answer/drop down
with selection.

**Comment by daiClegg** [comment]
Ok, will do.

**Comment by dbrownukk** [comment]
Did I miss the modelling of the above questionnaire?

Education level is not in the generated spreadsheet, or HHM, thus is not in this report.

**Comment by daiClegg** [comment]
There is a Topic defined called "Education" that contains a question called 
>"What level of education has HH Member achieved".

 It has Lov: 
>Primary, Secondary, Tertiary, None.

It would be in the report if that topic was included in configuration (or indeed if the individual question had been added.

**Comment by dbrownukk** [comment]
Great, questions and answers for a HHM are handled..

**Comment by daiClegg** [comment]
Instance: EFD _HM
Study:      M2 Tutorial Test

Report data appears to be correct.
However there are spurious column headers, repeating the actual questions.

**Comment by dbrownukk** [comment]
Question headings fixed
deployed

**Comment by daiClegg** [comment]
Instance:    EFD_HM
Study:         M2 Tutorial Test
Module:       Household
HH:              3
report output formatting Tested Ok, but there are some missing fields.
The HHM summary panel in the HH module is:

![image](https://user-images.githubusercontent.com/30879677/59636434-6f74a180-914b-11e9-8e54-306f496b84f2.png)

The report shows: 

![image](https://user-images.githubusercontent.com/30879677/59636489-8d420680-914b-11e9-8d9c-fc1e44cacc31.png)

The custom questions (place of birth  & place of mother's birth) correctly appear on the detail pop-up for each HHM but other standard properties are missing from the report (HoH and absence from HH data).

**Comment by dbrownukk** [comment]
added remaining fields to report for HHM
deployed

**Comment by daiClegg** [comment]
Column "Reason for Absense" misspells Absence.

Otherwise all looks ok.

**Comment by daiClegg** [comment]
**Tested OK**
