### ISSUE TITLE
Report Population by Age and Sex

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#238]
The population pyramid graphical report is widely used to display age and gender distribution in a population.

**Comment by daiClegg** [comment]
An example of this chart is on the "Population Pyramid" tab of the attached
[Output.examples.Hhold.and.personal.characteristic.xlsx](https://github.com/dbrownukk/EFD_v2/files/2832109/Output.examples.Hhold.and.personal.characteristic.xlsx)

**Comment by celiapetty** [comment]
Thanks Dai. I see where the Christmas Tree reference came from.  The pyramids generated from IHM data in Africa really do look like pyramids....

**Comment by daiClegg** [comment]
Ha, that was just me faking the data to make a Christmas Tree :o)

**Comment by DrJohnSeaman** [comment]
Very nice. You have 159 males and 159 females in the example ? coincidence. 

It would be good to have this as a percetage of the total population as well

**Comment by daiClegg** [comment]
@DrJohnSeaman 
> Very nice. You have 159 males and 159 females in the example? coincidence.

Coincidental it's exactly the same, but i did just make up numbers to make the tree emerge :o)

I want David to understand the requirement and he's possible not seen this style of chart before.
I did also tweak the chart layout so there isn't the offset between the Male & Female entries

**Comment by daiClegg** [comment]
More recent version of the mocked up example report (Population Pyramid tab) is attached here;
[Output.examples.Hhold.and.personal.characteristic.xlsx](https://github.com/dbrownukk/EFD_v2/files/2834089/Output.examples.Hhold.and.personal.characteristic.xlsx)

This uses a different technique to produce the desired layout without using negatives, so the values can be included on the bars

**Comment by daiClegg** [comment]
@DrJohnSeaman with regard to your other comment:

> It would be good to have this as a percentage of the total population as well

i'm not sure what you have in mind.
I have added the %age calculations to the example attached (update in previous comment )
And a chart showing the %ages rather than absolute values
Is that what you mean? Is that what you mean? 
Both or just %ages?

**Comment by celiapetty** [comment]
For discussion with John on our next telecon

**Comment by DrJohnSeaman** [comment]
Your example showing is correct. It would be useful to have both of the pyramids (absolute numbers and percentage of total popualtion) as reports.

**Comment by daiClegg** [comment]
Requirement is as documented.

**Comment by daiClegg** [comment]
Instance:   EFD_HM
Study:       M2 Tutorial Test

**Tested Ok**
