### ISSUE TITLE
ConfigQuestionUse is Level required

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#239]
ConfigQuestionUse holds the usage of a question.

It must be associated with a Study
Can be asked at Study, HH or HHM levels

Level is a nullable attribute of ConfigQuestionUse 

Level description in model is "If the question might be applied at more than one level, we need to specify which one it is being used at in this instance"

Does the usage not define at what level the question is asked? Or have I missed the point..

**Comment by dbrownukk** [comment]
From recent discussion, we do not know Household name or Household Members at spreadsheet creation time, thus level is more of a multi-select-checkbox that a question applies to at Study/HH/HHM levels

**Comment by daiClegg** [comment]
ConfigQuestionPrompt (CQP) also has attribute Level, which is where it is specified at what level the Question is used.
The Level in ConfigQuestionUse (CQU) is defaulted from this unless Level is null in CQP - in which case the user specifies the level it is being used at in this study.
So eventually Level in CQU is mandatory, but it may be null until the user has updated.
Depending on the flow in the UI, ie whether the record might be saved before it is completed, it might be that the Level in CQU should be mandatory.

**Comment by dbrownukk** [comment]
Fiddling the UI..   Level is one of, or a selection of, Study, HH, HHM?

**Comment by daiClegg** [comment]
I cannot think of an example where the same question might be asked at more than one level.
So in practice, i think the Level is one of Study, HH or HHM.
But i didn't want to prohibit it being applicable at more than one level.

But, if that makes the UI clunky and the code behind it complex, we should limit a question to only being applicable at one pre-defined single level.
Then if a multi-level question did occur, the user just has to enter it once for each level it might occur at. That will be way out on the edge of an edge case.

**Comment by dbrownukk** [comment]
Got it - makes sense and does help - thanks
