### ISSUE TITLE
Validation accepts invalid entries if the user has declared them valid

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#242]
Instance: HEA Testing
Project: TestJohnsWGIExporter
LZ: Z1 
District: abcdistrict 
SubDistrict: abcsubdistrict 
WG: Poor

Many of the RSTs  (see Employment. Livestock Products & others)  have no name, but have been set to Valid.
The WGI validated happily, but it's clearly invalid data, due to user error.

It should not be permissible to set an RST item as valid if it has no name.

**Comment by dbrownukk** [comment]
RST is now @Required once the resource/asset is being edited

numeric values are now also set to 0 if created in WGI or Household modules

**Comment by daiClegg** [comment]
Tested ok on the EFD_HM Instance.

Fix not deployed to HEA_TestingINstance - should i stop testing on that instance?
Make sense, but i have found a couple of regressions on EFD_HM which i will log.
