### ISSUE TITLE
OIHM Ref Generated spreadsheet - where do Study level questions go

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#243]
Ref #211 We have a tab for HH and a tab for HHMembers complete with additional config questions and room for answers. But, I do not see where Study Level Questions should go.

**Comment by daiClegg** [comment]
Study level questions don't get generated onto the spreadsheet. 'cos they aren't questions for the Household.
They are collected as part of the study set up.
Should have specced that more clearly as part of set up.

Will do that, including checking with Celia.
Meanwhile - no impact on S'sheet generation

**Comment by dbrownukk** [comment]
Thats good...

**Comment by daiClegg** [comment]
See Issue #221
