### ISSUE TITLE
Collect and analyse data About Inputs

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#244]
I have broken this out from the general spreadsheet issue (Issue #211 ) since the rest is in implementation but Inputs are still not clear to me.

The putative HH Interview Spreadsheet is attached to Issue #211 , but also added here for convenience
[OIHM-HouseholdInterviewTemplateV2.xlsx](https://github.com/dbrownukk/EFD_v2/files/2869812/OIHM-HouseholdInterviewTemplateV2.xlsx)
records Inputs in the last tab.

Currently, no reports will reflect this data, because it is not included in DI calculation - as defined in #145) and as per @DrJohnSeaman 's request  (see #211).

- How should it be integrated into analysis and reporting?
- Should any link be recorded between Inputs and use of those Inputs (e.g. Motorcycle repair for Boda Boda employment, Fertilizer for Maize) in order to analyse the profitability of specific or categories of employments, crops etc?

**Comment by DrJohnSeaman** [comment]
In principle inputs and outputs could be linked eg DI - input costs. In practice recorded inputs  can be quite messy e.g. labour, transport, fertilizer and other chemicals and in urban areas user charges, rent, taxes etc and automated  output may include subtractions which the user doesnt want. So the choice is either to allow the user to choose the inputs to subtract OR to add input costs as a report so that the user can subtract them in a spreadsheet. The former is best but more work. The latter is OK.

**Comment by celiapetty** [comment]
The attached extract from the open-IHM interview form shows how inputs are currently recorded. The total input costs (for crops, livestock or fishing) are entered in the data entry spreadsheet under the relevant heading (eg crop input costs under crop income; livestock input costs under income from sale of livestock products etc) -in the current version this is entered as a minus value, which is deducted from the income from that income source
[IHM hhold interview template crops.docx](https://github.com/dbrownukk/EFD_v2/files/2870104/IHM.hhold.interview.template.crops.docx)

**Comment by daiClegg** [comment]
@Celia,  In view of @DrJohnSeaman 's view (here and previously in  Issue #211) how do you want OIHM to handle the Inputs data?
We've already agreed on a separate tab for Inputs, with basic information.
But do we also want to collect allocation of Inputs to potentially several specific Resources, as the current interview sheet does? We could add a column to enter the Resource to be allocated.
Or add say 5 pairs of columns to record the up-to-5 Resources to share the input and what percentage each gets (as in OHEA market data).

When you've decided what data to record, we need to decide how it's reported/analysed (see John's comments on that above)

Would you prefer a short call to resolve this?

**Comment by celiapetty** [comment]
Your first suggestion: a column to enter the Resource to be allocated would work well.
The second option looks like an enhancement of the first-so the user could directly compare the amount allocated to the hhold on different resource types (eg crops vs livestock).  Is that right? 
We could break down input costs to: Crops-  seed; fertiliser & other chemicals; labour; transport; rent.
Livestock: vet fees&drugs; feed; labour; transport; rent etc. Or more practically, as we currently do,  we could continue to cross check these costs during the interview and enter the total input costs for each hhold, under each resource type, as shown in the sample interview form. I would favour this approach. The more detailed information would only be needed in specialist studies and the information could be collected and recorded separately.

**Comment by celiapetty** [comment]
typo -should read 'amount allocated by the household to different resource types...'

**Comment by celiapetty** [comment]
Dai
I've responded to your questions but there may be points to clarify. Could
you suggest times if a calk would be useful?
Celia

**Comment by DrJohnSeaman** [comment]
Dai,
I agree with your last suggestion - enter the total input costs for each hhold, under each resource type as in the sample interview form. John

**Comment by daiClegg** [comment]
@celiapetty , @DrJohnSeaman , i think we need a call on this.
We initially agreed a separate tab for inputs - distinguishing the input, but not the target resource for the input.
The interview form Celia attached above has a single box for inputs and costs but distinguished by target resource.

From a data point of view, the problem is that:
1.  a single purchase of an input might be applied to many resources (e.g. fertilizer shared amongst crops) 
1. a single resource might be the target for many inputs (e.g. livestock drugs, vet fees etc.).

Without collecting the detail of item 1,  we can't apportion the cost of shared inputs to specific resources. Does this matter?
If we collect the data in item 2 in the resource tabs we need a set of columns added for each input for that resource : Input , Units Purchased, Cost Per Unit. How many would the maximum be?
Collecting that data as a matrix (as layed out in the Input tab of my candidate spreadsheet (also attached above) solves that problem, but is separated from the resources - and currently does not record which resource - that was my initial question.

Once we have the data to whatever level of detail you think is appropriate and collected in whatever way we think is easiest to manage, then we can report it and export it  for analysis in any way we like. That's a separate issue which will document once we have agreed on data collection.

I'll ping you a Doodle poll to set up a call later this week

**Comment by daiClegg** [comment]
After discussion with Celia & John:
Must have:
  - collect individual Inputs
  - allocate their use by percentage, to up to 3 resources.

Should Have:
 - validate allocated percentages add up to 100% in the spreadsheet
 - dropdown list of valid values  (LoV) available to select appropriate Resources.

Could Have:
 Each Resource might be:
 - a Resource Sub Type ( e.g. Cows)
 - a Resource Type(e.g. Crops)
 - a resource Category (e.g. Cereals).

Attached spreadsheet has suggested layout (with %age validation but not LoV) in the Inputs tab.

[OIHM-HouseholdInterviewTemplateV2.1.xlsx](https://github.com/dbrownukk/EFD_v2/files/2886577/OIHM-HouseholdInterviewTemplateV2.1.xlsx)

**Comment by daiClegg** [comment]
Note: in the spreadsheet example above, the data entered in the inputs tab is just sample data to illustrate the requirement.

**Comment by daiClegg** [comment]
There is no Inputs tab in the Characteristic Resources.
--

Hence, there is nowhere to specify expected inputs to be generated into the interview template spreadsheet

**Comment by daiClegg** [comment]
Inputs Entry in the Spreadsheet
--
- Items Purchased should, ideally offer a drop down of all Non-Food Purchase Resource sub-types
 - Price Per Unit Validation does not allow non-nul  entry  - though the validation appears to be correct and firing correctly. I replicated the same validation setting in an unused cell in the tab and it behaves correctly, so i can't work out why the generated validation is failing.
- Very nice validation of %ages for resources use for
- Very nice comprehensive drop down of suggested values for Resource x used for, but could it be sorted to first show Resource types, (Crops, etc) then Categories, then Resource sub types? Excel doesn't allow you to start typing to shorten the drop down, so you either have to type the full thing or search all the way throug; and if you were looking for a Category say it would be dropped in amongst everything else. Maybe even colour-code Resource Types, Categories and Resource subtypes differently so the difference would be obvious. 
 - Also i can;t think why we shouldn't apply hard validation instead of suggested LOV - no write-ins allowed.

**Comment by daiClegg** [comment]
Inputs Items Purchased should, ideally offer a drop down of all Non-Food Purchase Resource sub-types
--
** Done **


I do have Sh*t for brains. In Issue #211, which i cross-referenced above, it says the drop down should include Non-Food Purchases **and** Other Tradable Goods. But i failed to put a note in here to explain that. Apologies.

**Comment by daiClegg** [comment]
Price Per Unit Validation does not allow non-null entry
--
 - though the validation appears to be correct and firing correctly. I replicated the same validation setting in an unused cell in the tab and it behaves correctly, so i can't work out why the generated validation is failing.

** Fixed **

Tested OK

**Comment by daiClegg** [comment]
Drop down of suggested values for Resource x used for
--
Could it be sorted to first show Resource types, (Crops, etc) then Categories, then Resource sub types? Excel doesn't allow you to start typing to shorten the drop down, so you either have to type the full thing or search all the way throug; and if you were looking for a Category say it would be dropped in amongst everything else. Maybe even colour-code Resource Types, Categories and Resource subtypes differently so the difference would be obvious.
** doable but currently list is built up separately to adding as a lookup LOV to spreadsheet, thus context is lost. - Future Enhancement. Now ordered by Categories, ResourceTypes, ResourceSubTypes (if that helps?)

Current imoplementaiton is very satisfactory

Tested OK.

**Comment by daiClegg** [comment]
Should we apply hard validation instead of suggested LOV?
--

** All other drop down LOVs in spreadsheet allow a new value to be entered. This would be inconsistent.

Yes, you're right.

Tested Ok.

**Comment by daiClegg** [comment]
Note above re absence of Inputs tab in Study module.
Is that not how i should pre-define expected inputs?

**Comment by daiClegg** [comment]
absence of Inputs tab in Study module.
==

**Tested Ok**

**Comment by daiClegg** [comment]
The only remaining anomaly (Other Tradable Goods not offered as nput types)  has been logged as a separate issue (#290).
So this feature is now complete

**Feature Complete**
