### ISSUE TITLE
Validate answers to Configuration questions 

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#245]
Configurable questions in OIHM will be categorised by the answer type they expect.
Supported types currently include: 

- Integer
- Decimal
- Integer range (validated upper & lower ranges) 
- Decimal range (validated upper & lower ranges) 
- Text (un-validated free text)
- List of Values (LOV - validated against pre-defined list)

Pre-defined LOVs exist for Male/Female & Yes/No.
It will be possible to define the list of allowable values when defining a new question.
And when re-using an existing question, from a previous Study, it will inherit the List of Values it was defined with.

Are there any lists that might be reused in different questions, for example 
- Where was HH member born (must be a valid country)?
- Where was HH member's Mother born (must be a valid country)?

here the list of valid countries should be the same and would be a pain to re-enter. 
Is this a valid example?
Are there others?

**Comment by celiapetty** [comment]
Dai, your example is a good one -please add this. It could be useful eg for urban studies. We might also want to record region or district of origin, where a list of options would have to be created for each study. 
On a related issue, is a standard currency and currency abbreviation list already in the o-hea software?

**Comment by daiClegg** [comment]
Country ISO codes, and currencies are defined in OHEA; will discuss with @dbrownukk  adding
 - Currency
 - Country

as pre-defined types of answers to config questions.

If you can't think of any other examples of where a list might be reused (ie is not specific to a particular Study) then we'll just go with ad-hoc lists on a per-Study basis.

If you have any example Study spreadsheets with extensive lists of Configuration questions could you attach them here please - they would be useful to check we've covered the requirements and also as real-world test data.

**Comment by dbrownukk** [comment]
We have a table for countries and currencies for a country

We have 3 tables with resource types , resourcesubtypes and categories

We have reference code table for basic list of values such as Y/N Units Areas etc.

We now have QuestionLOV for list of values for questions of type LOV

This does keep things simpler for implementation so far, but makes using a combination of the valid values difficult. Have a look at the current questionLOV. It is now implemented in the generated spreadsheet for lookup pick lists. The solutions work well but may not be the most elegant with the multiple reference tables. For discussion and testing

**Comment by daiClegg** [comment]
Done some initial testing, to get a feel for the workflow and how Domain might work.
Will update after more testing.

**Comment by dbrownukk** [comment]
Possibly base all LOVs on reference code table and synch country and currency LOVs

**Comment by daiClegg** [comment]
Workflow Note
--

I'm thinking that the Configuration Question Use module need not be visitble to the user.
Nor even the Configuration Question module.
I think they can be created in the context of adding a Configuration Question Use to a Study.
Reusing a question is covered in the dialog nicely.
Creating a new one is likewise straightforward and, to me, fairly intuitive.
But i am not sure about reusing an LOV question.
That's the next stage of testing

**Comment by daiClegg** [comment]
Different Input filed & blocks for different answer types
--
Love the way the Range & LOV blocks change with the answer type expected.
Would be nice if Ranges (age, decimal & integer) were always on their own line.
Maybe limiting the width of the pop-up to force wrapping would achieve that easily?

**Comment by daiClegg** [comment]
I'm not sure how much sense it makes to allow me to re-use individual LOV values.
For example,  the current test data has an LOV question to which the answer is Red, Blue or Green.
Another to which the answer is a point of the compass and a third to which the answer is a planet of the solar system.
The current implementation would allow me to create an LOV of Red, North and Jupiter.  
That doesn't seem helpful.

Being able to re-use a whole list (as for countries and currencies elsewhere) woul dbe more useful i feel.
For example i have a question for HH members: 
- "Country of birth?"-  answer is from a list of local countries, plus  'other' 

and another question at HH level 
- "What is the nationality of the head of HH?" -  with the same list of answers

So there are two points here:
1. Should there be an Add function in the Question LOV block of the new Question Use dialog?
1. Or could there be a way, instead to reuse all the values from an existing LOV question by restricting the query  to LOV questions only and allowing select of all the values in a single action.  UI something like this, but with a control for selecting a whole list:

![screenshot 2019-03-07 at 21 26 35](https://user-images.githubusercontent.com/30879677/53990299-e13a5980-411f-11e9-897e-86dbbe3bf02d.png)

**Comment by daiClegg** [comment]
Some other UX points:
--

1. Study name should be set in the Configuration Question Use (CQU) create dialog, it should not need to be selected, nor should it be editable; it could lead to errors and doesn't add any value to the user.
1. CQUs should sort by Level in the Questions tab of the Study module

1. Level should be mandatory in the CQU create dialog top block.

1. Configuration Question (CQ) search should only return questions at the same level as that set in the CQU create dialog top block

1. Configuration Question (CQ) create dialog  should pre-set level as that set in the CQU create dialog top block

1. CQ search list should show Topic, Prompt and Answer Type as the first 3 properties.  Hint and Notes of Topic are not needed and it would be better to move Integer & Decimal ranges to after Gender and Age ranges, which  i feel wil be more used.

1. The range block in the detail oview of a CQU is displayed even where it cannot be used (ie at Study and HH level) And it shows all possible ranges for all Question types.

**Comment by daiClegg** [comment]
Study Level Questions & Answers
--

Where do i enter the answers to study-level questons?
This needs to be part of the Study module.
Could it be an additioal tab, after Questions with a simple tabular format, popolated from the study level CQUs in the quresiotns tab?

**Comment by daiClegg** [comment]
Please add for Discusion label if there's anything controversia, difficult or unclear in this little essay of comments.

Overall flow and functionality tests OK

**Comment by daiClegg** [comment]
but i realise i've posted stuff here about CQUs generally, not just LOVs. 
Whoops. 
cross-referencing Issue #221 where some of these comments rightfully belong

**Comment by celiapetty** [comment]
I'm reviewing recent issues including this one-are there points that require further discussion (telecon)  with CP/JS?  I may have missed something.

**Comment by daiClegg** [comment]
[This](https://github.com/dbrownukk/EFD_v2/issues?q=is%3Aopen+is%3Aissue+label%3A%22For+Discussion+%28domain+experts%29%22) is where i maintain a list of all issues that need input from @celiapetty and/or @DrJohnSeaman:
You should review this list regularly, in case you've missed any notifications for individual issues as i've updated them.
At any time, if you feel one or more issues would be advanced more quickly by a call, please ask for one.

We could consider a regular call to review the list; that would be my preferred resolution.
Of course, we wouldn't have the call unless the list has at least one issue on it.

**Comment by dbrownukk** [comment]
Dai, Are we good to close this down. Questions/Answers/LOVs etc are all deployed. Just tidying the garden....

**Comment by daiClegg** [comment]
Able to define an LOV CQ with no LOV type specified
--
whoops, found a problem:



Instance: EFD_HM
Module: Topic
Topic: New Topic
Question: Question 11, Question 16

I was using the Topic module cos it made it easy to manage a list of new CQs, but the CQs are equally accessible in Study module

**Comment by daiClegg** [comment]
Able to define Range CQ with no equivalent (integer or Decimal) range specified 
--

Instance: EFD_HM
Module: Topic
Topic: New Topic
Question: Question 17, Question 18

**Comment by daiClegg** [comment]
Able to define Ranges (Age, Integer or Decimal) with invalid ranges specified (ie lower greater than higher)
--

Instance: EFD_HM
Module: Topic
Topic: New Topic
Question: Question 12, Question 13

**Comment by dbrownukk** [comment]
Tested most combinations of Questions and answer values. Note that you still get two error messages, one for the update and one for the save.  I will raise another issue for this..

**Comment by daiClegg** [comment]
Can Specify Gender creating a Study Level Questions
--

The Create CQ dialog has editable control for Gender when Study level is specified.
And the Save works without an error or warning.
But the Edit dialog does not show this control.

The List view of CQUs in the Questions tab of the Study module erroneously shows the Gender restriction.
The answers tab, correctly, does not show gender.

**Comment by daiClegg** [comment]
Can Specify  LoV to Use for a Text  Question
--

The Create CQ dialog has editable control for LoV to Use.
And the Save works without an error or warning.
The Edit dialog, correctly, does not show this control.

The generated spreadsheet and the Answers tab work correctly.
It's just the Create dialogue

**Comment by daiClegg** [comment]
Need cross field validation in the spreadsheet for interdependent questions
--
See the attached image:

![image](https://user-images.githubusercontent.com/30879677/55036466-9c189180-5012-11e9-93f4-85bee0b9ae90.png)

more detail to be added; late now; this comment is a placeholder.

**Comment by daiClegg** [comment]
@celiapetty: In OIHM it is possible to define questions of various types:
text, integer, decimal, list of alloweable values, integer ranges, decimal ranges.


It is also possible, for HH members, to specify of whom the quesitons are to be asked according to Gender and age. But this is not checled in the spreadsheet, only when the spreadsheet is uploaded and parsed.
How does OpenIHM work in this respect? How does and IHM interviewer know the age range and gender constraints on HH Member questions?

**Comment by daiClegg** [comment]
@dbrownukk just two items o/s here, barring the consultaiton with Celia.
Shall i move those to separate issues and close this as feature complete

**Comment by daiClegg** [comment]
Generated Sprradhseet Validation does not match CQU specifications
--
Instance: EFD_HM
Study: M1 End2End Test 2018
Question: Questtion 15

This quesiton is specified as decimal, but the generated cell has no validation.
This spreadsheet causes an error in parse:

> Impossible to execute Parse spreadsheet action: Cannot get a numeric value from a text cell

I think it is caused by the attached spreadsheet bacause parse is expecting the specified Decimal.

**Comment by daiClegg** [comment]
Edited the title to reflect the wider range of the testing being logged against this issue

**Comment by celiapetty** [comment]
Suggest we schedule a call to discuss open issues which I'm reviewing now -for example, I'm not sure I understand this question: How does an IHM interviewer know the age range and gender constraints on HH Member questions? How about tomorrow, 28.3.19

**Comment by daiClegg** [comment]
I'm available 28/3 most slots.

**Comment by celiapetty** [comment]
How about 2pm?

**Comment by DrJohnSeaman** [comment]
I am probably not needed but for info I am not available at 2.00

**Comment by celiapetty** [comment]
Is 3 or 4 pm any good? If not should we go ahead at 2 and discuss
separately if anything is outstanding?

**Comment by DrJohnSeaman** [comment]
4.00 would be OK for me

**Comment by celiapetty** [comment]
4pm confirmed

**Comment by daiClegg** [comment]
Gender & Age range HH Member Questions are rare so the current implementation is adequate.

**Comment by daiClegg** [comment]
Retest of :
Generated Spreadsheet Validation does not match CQU specifications
Instance:  EFD_HM
Study:      M1 End2End Test 2018
HH:           1
Question: Question 15

This question is specified as decimal, but the generated cell has no validation.
This spreadsheet causes an error in parse:

Impossible to execute Parse spreadsheet action: Cannot get a numeric value from a text cell

I think it is caused by the spreadsheet (attached to HH 1) because parse is expecting the specified Decimal.

** Fixed **
Problem was that older questions had no default values (of 0)
Removed configQuestionUse and added back in and now has number validation on Q15

**Tested Ok**

**Comment by daiClegg** [comment]
Retest of:

Age Range for all HH Member questions should default to 0 - 99
--

Current default range is 0 - 0; but does that get ignored on parse?
If so that's fine, if not the default should be that all ages get asked, so the default should be whatever ensures that in parse.
(currently blocked from testing that while i work out how to work around other anomalies - see below).

** Done **	@DefaultValueCalculator(
value=org.openxava.calculators.BigDecimalCalculator.class,
properties={ @PropertyValue(name="value", value="120") }
)

Created a new HHM question. Age range defaulted to 0 to 120.

**Tested OK**

**Comment by daiClegg** [comment]
Retest of:

**Comment by daiClegg** [comment]
Retest of:

Can Specify LoV to Use for a Text Question
--
The Create CQ dialog has editable control for LoV to Use.
And the Save works without an error or warning.
The Edit dialog, correctly, does not show this control.

The generated spreadsheet and the Answers tab work correctly.
It's just the Create dialogue

LoV does not appear with Text Questions

**Tested OK**

**Comment by daiClegg** [comment]
Retested successfully all the previously identified anomalies.


**Feature Complete**
