### ISSUE TITLE
Upgrade production instance to OX 6.0 & Include both OHEA & OIHM

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#247]
Not for current implementation, but we need to consider in advance, how we will migrate Production users onto the combined OHEA/OIHM application on OX 6.0.

Opening this issue as a place to formulate the plan for that and to make sure it doesn't get forgotten.

**Comment by daiClegg** [comment]
At upgrade, any producton projects already recorded must be preserved

**Comment by dbrownukk** [comment]
not an issue. OIHM and OHEA on one instance
