### ISSUE TITLE
Project Module forces save of Project before you can add an LZ

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#25]
It successfully saves, but then loses the context of the created project, which you then have to pick before you can return to adding/creating the LZ

**Comment by dbrownukk** [comment]
Needed to change default action using a new controller

<set property="resetAfter" value="false"/>

is the trick...


   `<controller name="Project">
   <extends controller="TypicalRealExcel"/>
    <action name="save" mode="detail"
      class="org.openxava.actions.SaveAction"
      by-default="if-possible"
      image="save.gif"
      icon="content-save"
      keystroke="Control S">
	  <set property="resetAfter" value="false"/>
	  </action>
	</controller>`

**Comment by dbrownukk** [comment]
It now keeps the saved project on the screen, you can go onto add LZ and Community

**Comment by daiClegg** [comment]
Tested OK
