### ISSUE TITLE
Gender and Age Ranges only applicable to HH Member Questions 

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#251]
Need onchange triggers to manage Gender and age ranges on Question module

**Comment by dbrownukk** [comment]
On edit of configQuestion. If Question Level is HHM then Gender and Age Ranges are available

deployed

**Comment by daiClegg** [comment]
Tested OK.
All levels & all question types display appropriate range & gender options.

**Comment by daiClegg** [comment]
Noticed in testing that there are still some issues with managing actual Lists of Values.
But this is still wip in Issue #245 and doesn't affect this issue.

**Comment by daiClegg** [comment]
Was doing more testing of CQ creation and i discovered some anomalies:

Instance EFD_HM
Module: Topic
Topic: New Topic
CQ:  Unrestricted Text question creation

I can add LOV & Ranges, Age,  Integer & Decimal as well as Gender to a study-level Text question

**Comment by daiClegg** [comment]
The treatment in Answers seems to be correct (no ranges or types), but the creation is not helpful and could lead to errors.

**Comment by dbrownukk** [comment]
Validation combinations now work.

**Comment by daiClegg** [comment]
Instance:  EFD_HM
Topic:       Topic 3
Question: Are Study Level Questions restricted?

Can still add Gender, Ranges & LOV to use,  when creating a study-level text question and some of that extraneous detail shows up in the questions list view.
However the additional properties do **not** show up in the edit dialogue, nor do they appear in the Answers tab of the Study module.

**Comment by dbrownukk** [comment]
Yep, edit was ok but Create seemed not to fire the onchange triggers (in Forms speak)

**Comment by daiClegg** [comment]
Tested O.
