### ISSUE TITLE
Log in appears to work, but with access to no modules if capitalization of the username is changed

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#254]
if you have username "James" and you log in with username "james" but same password, you get the "First Steps" module, but have no access to any other modules.

**Comment by dbrownukk** [comment]
naviox.properties setting

showModulesMenuWhenNotLoggedIn=false

Now when not logged in you will not see any modules, which makes sense..

**Comment by daiClegg** [comment]
I seem to have lost a comment here.

I logged in as james ( no init cap) but with the correct password for James (init cap).
Login appears to work, cos I can see the sign out (james) control in the top right of the window, but with no accessibility to any modules .
If I log in as james with some random password it fails as expected: Unauthorised User.

**Comment by daiClegg** [comment]
Instance: EFD_HM
Login as Oihm with the password for oihm.

Can use the study module, but not the HH Module.
Don't know what's going on but it's not right.

Equally it's not vital to fix it now, so i'll add the for discussion flag but not assign to any limestone

**Comment by daiClegg** [comment]
The absence of HH Module, was almost certainly to do with access f that module to the role, not to do with the log in,

'Oihm' appears to behave exactly like 'oihm', as does 'oihM'.
So i'm guessing usernames are not case sensitive.
I think they should be.

**Comment by dbrownukk** [comment]
user and role table were using default character set and encoding utf8 and utf8_general_ci

the 'ci' suffix stands for case insensitive...

switched all OX tables to be utf8_bin which forces case sensitive queries

deployed

**Comment by daiClegg** [comment]
**Tested OK**
