### ISSUE TITLE
New OX v6 dialog to remove filters not working

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#258]
Instance: EFD_HM
Module: WGI, List view

- In list view, click Filter control to enable filters
- Select any filter (i selected just he 'PART PARSED' record
Filter works as expected.
Filter shows in the text control at the top left - nice feature.
- Click the "Change name/remove" control next to the Filter display.
Pops the Filter Change/Remove dialog - as expected.
- Click Remove button
Get error: "Impossible to execute Remove action: User preferences node not removed"

**Comment by daiClegg** [comment]
This appears to be fixed. The control that was not working is no longer displayed - but the old mechanism for removing filters in the filter bar works as it did, so there is no loss of fuuncitonalioty

**Comment by daiClegg** [comment]
Re-opening because i now see this in a new place:

Instance: EFD_HM
Module Study

Steps:
- In the Questions tab, Click New
- In the CQU pop-up editor, Click Search
- In the CQ chooser filter the list (i filtered by Topic)
-- Note the Filter box in the top left is correctly displaying the filter applied.
- Click the Change/Remove Filter link beside the filter drop-down
--Nothing happens

I have now realised you use the filter dropdown to remove/change filter. 
Nice filter but why is that text a live link that says it will "Change/Remove Filter" when it doesn't 
Deceptive, but not terrible.

**Comment by daiClegg** [comment]
one for the ice box?

**Comment by dbrownukk** [comment]
The Change name/rename works in top level Lists but not from a reference List.

I will bug with OX.

**Comment by daiClegg** [comment]
Pending Xavier's feedback. Not a show stopper, because filtering still works as in pre-6.0 OX

**Comment by dbrownukk** [comment]
seems fixed in 6.1.2 OX

**Comment by daiClegg** [comment]
Is this deployed?

I repeated the sequence of actions above.
At the ast step:

**Comment by dbrownukk** [comment]
this is a storage problem of java user preferences.

Tried to set user.home to /tmp so that tomcat can write file but no success

**Comment by daiClegg** [comment]
This now tests ok - the steps to reproduce do not now produce that error.
