### ISSUE TITLE
What is the algorithm for naming WG interview spreadsheets?

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#261]
I think it is a concatenation of the names of:

`Project||LZ||District||SubDistrict||WG`

with truncation if the string is too long.

But i think currently it is the subdistrict & district that get lost, and actually, for a field worker, those are the important things. 
They are only ever working in one LZ and on one Project, but they will be conducting interviews in multiple sites.
So we need the site identifiers and the WG. I suggest:
- drop the project name - it appears that it is frequently the same as the LZ.
- If the name is too long,  truncate the LZ name to 10 characters.
- If the name is still too long, truncate the District name to 10 characters.
- If the name is still too long, clip trailing letters from the SubDistrict until it fits.

comments please @DrJohnSeaman , @celiapetty , @dbrownukk

**Comment by dbrownukk** [comment]
This seems to be a reasonable compromise 

filename = site.getLivelihoodZone().getLzname() + '_'
				+ StringUtils.truncate(site.getLocationdistrict(), 8) + '_'
				+ StringUtils.truncate(site.getSubdistrict(), 8) + '_'
				+ StringUtils.truncate(wealthgroup.getWgnameeng(), 10);

**Comment by daiClegg** [comment]
This is much better. Might still conceivably cause someone a problem some time, but unlikely to happen in practice.

**Tested Ok**
