### ISSUE TITLE
Need to clean up RSTs & Categories

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#262]
This is one for John & Celia.
We need to review all the RSTs and the Categories that they belong to.
There will be test data to remove.
There will be incorrect Category assignments
There will be missing RSTs & Synonyms of RSTs
There may well be incorrect KCal values assigned

**Comment by celiapetty** [comment]
Rules to follow when adding new resource sub types (RSTs). 

These rules are intended to reduce the number of duplicate entries and errors in the O-HEA and O-IHM dbase. We will include the following rules in any future ‘user guidelines’ and will edit existing entries in line with the following rules. 

1. Use the main item identifier first eg ‘Meat’, ‘Cheese’ ‘Leaves’ then follow with the specifics eg Meat, goat; Meat, rabbit.
NB:  I have checked the existing lists and see that commas and hyphens are used interchangeably as separaters.  However, commas are used more frequently than hyphens and it is more intuitive to type a comma then a space, so the rule is, separate items as follows:
Milk, cow, full fat
Milk, cow, semi skimmed
Milk, goat, full fat
Milk, sheep, full fat
Cheese, goat, full fat
Cheese, cow, full fat
Meat, goat
Meat, rabbit
Leaves, dark green
Leaves, light green
Chicken, livesale etc 

Note that the first word in any entry must be capitalised, all other words should be lower case.

2. In cases where a food type (eg Mango or Guava) is found as both a crop and a wild food the wild food should always be added as a synonym for the crop. Thus ‘Mango – wild’ is a synonym for Mango. In this case, a hyphen should be used to denote this is a wild food. Note that a single space should be entered on either side of the hyphen. Spaces are only omitted before a hyphen in the rare cases such as coco-yam where this is simply the correct spelling of the item.

3. The excessive use of synonyms (eg Dark green leaves; Leaves, dark green) should be avoided.  If an interviewer has entered in their spreadsheet an item such as Green leaves this will parse as ‘invalid’. They will then need to search to find the equivalent – in this case, ‘Leaves, dark green’ in the drop down.
 
4. Typos should not be entered as a synonym- an incorrect spelling (eg maise, tobaco) will register as invalid. The user will find the correct spelling in the drop down 

Note: We will resolve existing duplications before launching the software (duplications cannot be deleted as this would delete the associated data so the process is time consuming).

**Comment by celiapetty** [comment]
I have now edited those RSTs for which there are no duplicates in line with the above rules.  Duplicates (eg Meat Camel; Camel meat; Beans, dry; Beans-dry) remain.

**Comment by daiClegg** [comment]
Should not 'X meat' be a Synonym of 'Meat, X'?
Right now i only see 2 examples of such duplication, Goat & Camel.
And for Camel the 2 have different KCal values, which i'm sure is not correct.

**Comment by daiClegg** [comment]
I have corrected the Synonym connection between Green Grams & Green Grams - wild.
But there is no KCal value for Green Grams

**Comment by daiClegg** [comment]
All the wild foods that have no Kcal are Synonyms & all the Wild foods that are not Synonyms have a on-zero KCal. So that appears to be correct.

**Comment by daiClegg** [comment]
Some crops are still synonyms of wild food equivalents, not the other way round.
The way to fix that is for any Crop/Wild food for which the Crop is a Synonym of the wild food:

1. Edit the Crop 'X" to remove the synonym to 'X, Wild'
1. Save changes
1. Edit 'X, Wild' to add synonym 'X'
1. Save changes

**Comment by celiapetty** [comment]
Camel meat: on further review 980 looks right for Meat, camel.

**Other duplicates and RSTs incorrectly classified as synonyms**

Milk, cow -appears as a synonym for Cows milk
Milk, goat-appears as a synonym for Goat milk

Jack fruits appears as a synonym for Jackfruit

Beans, dry;   duplicated as Beans-Dry 

Cassava, fresh; duplicated as Cassava- Fresh and Cassava fresh


**Failure to distinguish dry or fresh:** 
Sweet potato – this has the value of Sweet potato, fresh.  Sweet potato, fresh appears as a synonym for Sweet potato. In fact, we want users to always distinguish between ‘Sweet potato, fresh’ and ‘Sweet potato, dry’. ‘Sweet potato’ should not be an option

In a similar way, ‘Groundnuts, dry’ appears as a synonym for ‘Groundnuts’. The options should be ‘Groundnuts, dry’ or ‘Groundnuts, fresh’

Also: ‘Cowpeas’ appears as a synonym for ‘Cowpea, dry’. 

I have edited ‘maize’ to read ‘Maize, dry’ for consistency

**Comment by daiClegg** [comment]
See also #334
