### ISSUE TITLE
OIHM spreadsheet parsing 

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#264]
OIHM spreadsheet parsing:

I realised why HH and HHM questions and answers were not being parsed and saved from the spreadsheet you were using. UploadTest190319RealWorld.xls  

The spreadsheet is independent of the Study - i.e. the related study has no questions defined in the Study module. 

So, the question is, is this fair? before I change the parse code...

Currently, the completed spreadsheet parse gets the CQUs from the Study and goes looking for a configAnswer in the spreadsheet. 

Clearly, in this case, there is no Question to Answer, despite the fact that there is an answer in the spreadsheet to a HH question. 

It does not make sense to me to go through all the effort of creating and attaching Questions to a Study at the HH and HHM levels if these can be overridden (ignored, deleted, added to) in the spreadsheet. 

Your thoughts, or is this one for SME?

I could raise an error if Study.HH/HHM.Questions in database does not match the number found in spreadsheet.

**Comment by daiClegg** [comment]
Of course. That makes sense.

I think we do **not** allow interviewers to override questions in the spreadsheet.
There is a warning when you attach the s'sheet that it doesn't match the study details, so the user has to deliberately do this, as i did for testing - legitimately as i thought.

It does mean that once you have started the interview process you're stuck with your interview design.
I think that would be good practice - for purposes of cinsistency.

Need to check with @celiapetty  and @DrJohnSeaman .
NO need to change anything for this right now.

**Comment by celiapetty** [comment]
That's correct. Users should not be able to override questions on the spreadsheet.

**Comment by daiClegg** [comment]
Thanks Celia, Will proceed on that basis.
