### ISSUE TITLE
 What are the available keyboard shortcuts?

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#27]

**Comment by dbrownukk** [comment]
Hover over an icon to see keyboard equivalent

extracted thee following from default-controllers.xml in xava directory  

New   			Control N
Save 			Control S
Refresh			Control B
Delete  		Control D
Generate PDF		Control Alt P
Generate Excel		Control Alt X		
Find/Search		Control B
Detail List 		F8
List			F9
Edit 			F7
Go Previous Page	Control A
Go Page 		Control I
Go Next Page 		Control S
Previous Record 	Control Alt LEFT arrow
Next Record		Control Alt RIGHT arrow

**Comment by daiClegg** [comment]
Thx.
