### ISSUE TITLE
  Missing controls in Copy Study and Copy in Topic Qiuestions dialogs

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#272]
No Ok or Cancel buttons in the pop-up dialogs to control these utilities.,
Can only dismiss the popup 

![image.png](https://images.zenhubusercontent.com/5a81590c4b5806bc2bc688fc/7badbb8d-3579-40ff-82e8-c0338cd3e3e7)

**Comment by daiClegg** [comment]
I've added MIlestone M2 to this bug , cos it's blocking test of Copy Study, which is still outstanding.

**Comment by dbrownukk** [comment]
Very strange, a change in controllers.xml lost the buttons

Copy Study and Copy Topic Questions now working.

Copy Study also now creates Study level Answer dummy rows

Copy Topic - If a question in a Topic is already in this Study it is not added. If no new questions are in the Topic you will see a warning.

**Comment by daiClegg** [comment]
Tested OK
