### ISSUE TITLE
Age Ranges validation apears suspect.

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#275]
Instance: EFD_HM
Study: A Study

1. Invoke Copy Study.
1. Provide target Study name and click Copy
Error message:
0 is not a valid value for Upper Age Range of Standard Of Living Element: must be between 1 and 120

But the only StoL question has no age range associated with it.

**Comment by dbrownukk** [comment]
Too agressive with validations and default values. Though I do prefer default values rather than blanks for new entity records.

Fixed

**Comment by daiClegg** [comment]
Agree defaults better than interpreting blanks.
If only because the former shows the user what they are entering, by default


Tested Ok
