### ISSUE TITLE
Create Study without Project generates unhelpful error message

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#276]
Instance: EFD_HM
Module Study

1. Click + to create a new Study
1. enter Study name
1. click Save.

> As expected - Error message points out Reference year is mandatory

1. Enter Rederence Year 
1. Click Save.
> Error message:  Impossible to execute Save action: org.hibernate.exception.ConstraintViolationException: could not execute statement
1. Select a Project form the Prokect control drop down
1. Click Save
> As expected - saves satisfactorily

It would be more helpful to the user if the error  message from a missing Project indicated that was the problem

**Comment by dbrownukk** [comment]
Fixed - added @Required to Project in Study module

**Comment by daiClegg** [comment]
**Tested OK**
