### ISSUE TITLE
Unable to parse spreadsheet with no resources entered

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#277]
Instance: EFD_HM
Study:      M1 End2End Test 2018
HH:          2

1. Generated a new spreadsheet for this study.
1. Entered just the interview, household & HH Members data.
1. Uploaded and save the sheet
1. Attempted to Parse the sheet

> Error:  Impossible to execute Parse spreadsheet action: null

I think the first 3 tabs are valid data, but even if they're not, there's no help in the error message to help me find what's wrong.

**Comment by dbrownukk** [comment]
Empty Answer was not trapped as a Null.

Also, Year of Birth not entered. If empty then is calculated from this year - age

**Comment by daiClegg** [comment]
**Tested Ok**

**Comment by daiClegg** [comment]
Birth calculation is as it should be.
