### ISSUE TITLE
Parser does not match a valid Input

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#278]
INstance:   EFD_HM
Study:        Testing #275
HH:             1

1. Record an input in the interview spreadsheet
>See spreadsheet attached to this HH
1. Upload and parse 
>as expected: no error.
1. View Inputs tab
>Item Purchased (Clothing) and unit (Item) parsed correctly
> but marked as invalid with no matching RST 
1. Click Name dropdown
>Note Clothing Unit is a valid NonFood purchase, displayed in the drop down.

**Comment by dbrownukk** [comment]
Big debug to untangle this one. Now working and deployed.

**Comment by daiClegg** [comment]
Created new HH to test:
Instance: EFD_HM
Study:      M1 End2End Test
HH           7

Added 3 INputs one with incorrect unit but appropriate name
All loaded and parsed as they should be

**Tested OK**
