### ISSUE TITLE
Household Name is not mandatory, but must be unique.

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#279]
Instance:   EFD_HM
Study:       M1 End2End Test

1. Create a new HH with no name
1. Click Save.
> Error:  Household Name must be unique within Study
>(there is already an HH with no name in this Study)

Whilst it is invalid to have 2 identical non-null HH names in a study (as enforced),  any number of unnamed HHs should be allowed.

**Comment by dbrownukk** [comment]
hhname set to blank string not a null. Null is treated as distinct in mysql unique index.

@prepersist trigger to set to null if blank...

**Comment by daiClegg** [comment]
**Tested Ok**
