### ISSUE TITLE
Upload omits HH member data

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#280]
Instance:   EFD_HM
Study:       M1 End2End Test
HH:            3

Was able to upload, parse, correct & validate the spreadsheet attached to this HH.
But it contains 3 HH members and none are included in the HH data set.

**Comment by dbrownukk** [comment]
In the populated spreadsheet the 'Person Name/ID' is blank. This is required in the HouseholdMember table, thus fails.

What should the rule be?

1. Not empty? 
2. Generated as member 1/2/3..
3. Other combination?

**Comment by daiClegg** [comment]
We need an identifier - so that the team can know who they are talking about and to provide uniqueness.
Collecting a name should not be mandatory but may be desirable, for example if that HHM is the specific target of some benefit or programme.
Any collected name must be hidden from non-authorised users for reasons of data protection.

So, i think we need a unique, generated, human-readable id (HHM1, HHM2, etc)
We should allow optional collection of an additional "real" Name if the interviewer chooses.
But i think we have to have these as separate fields since one of them must be hide-able.

wdyt?

**Comment by dbrownukk** [comment]
Added HouseholdMemberNumber which is autogenereted, mandatory and readonly

Not part of spreadsheet template

On Parse of spreadsheet the number is added.

Not recalculated if you delete a member 

If you add a new HHM then a new HHM Number is calculated  

to be deployed

**Comment by daiClegg** [comment]
*Tested OK**
