### ISSUE TITLE
Absence is parsed incorrectly

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#281]
Instance:   EFD_HM
Study:       M1 End2End Test 2018
HH:            6

There are 3 HH member in the spreadsheet attached to this HH.
M1 & M2 are reported as not Absent and M3 is absent.
The values in the app are the reverse in each case.

**Comment by dbrownukk** [comment]
Checked if months Away is populated and if = 0 then not Away, but had logic wrong way around.

Fixed

**Comment by daiClegg** [comment]
**Tested OK**
