### ISSUE TITLE
In HH Module HHM editor does not include Months Away value

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#282]
Instance: EFD_HM
Module:   Household
Study:     M1 End2End Test 
HH:          6

1. In detail view note Months Away for HHM P3 is '8'
1. invoke HHM Editor for HHM P3
>Note the Months Away field is not displayed
> same is true for any other HHM

**Comment by dbrownukk** [comment]
fixed - to be deployed

**Comment by daiClegg** [comment]
**Tested OK**
