### ISSUE TITLE
OIHM Reporting - Intersection ReportSpecUse 

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#284]
For clarification to get my head around this. 

In the OIHM reporting doc at https://github.com/dbrownukk/EFD_v2/files/3010116/OIHM.reporting.docx

The data model defines an intersection between CustomReportSpec and Study via ReportSpecUse. 

Section 1.1 says to define the Study to be reported on when creating a CustomReportSpec.

With the current model, you could choose many Studies for a CustomReportSpec, which I do not think is the intended behaviour. 

2-minute chat will resolve...

**Comment by daiClegg** [comment]
My thought was that this would allow reuse of a report spec in a different study.
The reports to run and the resources to include would remain the same.
But HH inclusions would be different with each study.

Useful for longitudinal i think, or where a series of studies are contributing to the same analysis.
