### ISSUE TITLE
Cash Income Missing an Employment

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#285]
Instance:       EFD_HM
Project:         Mukono - New Test
LZ:                 Banana Coffee Piggery
District:         Mukono
SubDistrict:  Ntenjeru
WG:               MIddle

The Middle WG has 4 employment types.
Two of them have been recorded as "Petty Day Trade".
One of them (originally entered as "Fish Trader") appears to have been omitted from the calculation.
Poor & Better Off groups appear to be accurate.

This was originally logged against Issue #94 but now moved to be a separate bug, since that Feature is otherwise complete

**Comment by dbrownukk** [comment]
Validation changes made to OHEA to match OIHM

Instance: EFD_HM
Project: Mukono - New Test
LZ: Banana Coffee Piggery
District: Mukono
SubDistrict: Ntenjeru
WG: MIddle

behaves as I would expect for Employment as none of the Employments entered in template spreadsheet exist.

**Comment by daiClegg** [comment]
Agree that the data as loaded does not reproduce this problem.
Not sure how this data got reset to an old state.
Maybe i reloaded the spreadsheet for another test.
Anyway, i have now re-edited the data so it is reproducible.

Instance: EFD_HM
Project: Mukono - New Test
LZ: Banana Coffee Piggery
District: Mukono
SubDistrict: Ntenjeru
WG: MIddle

As you observe, the Employments as entered do not exist so i edited the parsed employment records to appropriate existing employments.
to do so i had to change both 'Fish Trader' and 'Crop Trader' to "Petty Trade'.
The WG is now validated.
To reproduce:
1. Run the Cash Income chart.
> observe income from 'Petty Trade for Middle WG is about 400,000, which is the Crop Trader part of the Petty Trade Income.  
>
2. Make the WGI Editable & change the Employment type for the Fish Trader record to any other Employment type that is different to all the other Employment types for this WG.
> I used 'Government Worker.
3. Validate the WG
4. Run the Cash Income Chart.
> Note the massive hike in income due to the new Employment Type.

It appears that if there are duplicates of the same Employment Type, only one is included.
This should be prohibited in Validation anyway, i was being lazy and exposed the problem accidentally.

**Comment by dbrownukk** [comment]
Need a unique constraint on wgi and rst 

	@CollectionTable(uniqueConstraints= {
		@UniqueConstraint(name = "unique_type", columnNames = { "WealthGroupInterview_WGIID", "ResourceSubType"}) })

but need to delete any existing duplicates to enable constraint creation...

Also, will be an impact on parse

**Comment by daiClegg** [comment]
Actually, i've now thought of a use case where there could be more than one instance of the same employment
- different people in the family could be paid a different rate for the same job (e.g. a juvenile & adult). 
-  the same person could get paid different rates at different times of the year (eg. main harvest & second harvest)

So it should be allowed in the collected data, but dealt with as a single sum in the reporting.

**Comment by dbrownukk** [comment]
Cash Income Chart groups duplicate employment types. 

Wealthgroup Income Report has two lines if there are two duplicate employment types - cashincomereport and cashincomereportwithpurchases 

wgi_wealthincomereport.jrxml and wgi_wealthincomereportwithpurchases.jrxml

**Comment by daiClegg** [comment]
Fix for rolling up multiple occurrences of the same employment is not implemented - cost/value is probably not justified.
Suspend that refinement and test as is.

**Comment by daiClegg** [comment]
The WG i tested on before still ignores the 2nd Employment of type "Petty Day Trade".
Same steps to reproduce.

**Comment by dbrownukk** [comment]
Jasper should have done the grouping, but seems to fail. Added a group by to employment view so that identical employment types are summed.

deployed

**Comment by daiClegg** [comment]
**Tested OK**
