### ISSUE TITLE
SubDistrict in Community should be labelled VIllage

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#286]
Instance:   EFD_HM
Module:    Community

In the Community module, there is a field labelled SubDistrict.
This confused the team in the first production field study because all the Villages they visited were in the same SubDistrict, so they somehow ended up with a bunch of Communities all at the same Site, ie same District &  SubDistrict - and they had no distinguishing name. Which was a nightmare for them when they tried to upload interview data.

If the field had been labelled Village the problem would not have arisen.
In discussion with domain experts, i've established that in HEA all sites are Villages, so there is no loss of functionality or generality.

How they got the data into that state, i am still investigating. There are uniqueness checks o on Sites & on Communities. When i have concluded that investigation i'll raise an issue to fix that.
Meanwhile, with the right naming, the team would have avoided the problem in the first place.

**Comment by dbrownukk** [comment]
sub district changed to Village in Community Site
deployed

**Comment by daiClegg** [comment]
**Tested Ok**
