### ISSUE TITLE
Expected Inputs should be allowed to be Other Tradable Goods or Non Food Purchases

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#287]
Instance: EFD_HM
Module: Study

In the Inputs sub-tab of the Characteristic Assets/Resources tab.

- Create a new Input
> the drop-down only lists Non Food Purchases.
> Inputs may also be Other Tradable Goods.

**Comment by dbrownukk** [comment]
fixed and deployed

**Comment by daiClegg** [comment]
**Tested OK**
