### ISSUE TITLE
Unable to produce charts for apparently valid communities

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#289]
Instance: EFD_OHEA
Project:   NIMFRU (CROP & LIVESTOCK REARING) 
LZ:          Crop & Livestock Zone 
District:   Katakwi 
Village:    Adurukoi 
WG:         Better off 

This village has 3 WGs
All are validated.

I ran each chart in turn.
The results were not as i expected in any case, but  there were different (reproducible) results for different charts:

**Assets Chart:**

> Error:  "Impossible to execute Assets action: Error executing SQL statement for : wgi_asset"

**Food Expenditure & Non-Food Expenditure**
Charts run but produce only the messages: 
> "No data is available for food expenditure"
> & "No data is available for non-food expenditure"

**Food Consumed & Cash Income**
Charts run but produce only the  message: 
> "No Validated Wealth groups for this Community"

The data in this project has been heavily edited. 
Best practices were not followed throughout (through no fault of the users, who were inexperienced), so it may be that the data is corrupted in some in-obvious way, but the Community dataset appears to be valid.

I have not yet tested creating a new project from scratch with a new LZ, a single Community & one WG uploaded with one of the spreadsheets used in this community. That is the next test.

**Comment by stellangoleka** [comment]
I have tested creating a new project from scratch with a new LZ, a single Community and one WG generated from the new project then uploaded after entering data the results are the same.

Cash and Food Income charts run but produce the message:

"No Validated Wealth groups for this Community"

Then in this new project, I uploaded one of the spreadsheets used in the field. Cash and Food Income charts run but produce the same message as above.

**Comment by daiClegg** [comment]
Stella,

That’s actually good news. It proves there’s a problem with the software, not with the Katakwi data. And it shouldn’t be hard to fix.
Thanks for getting this done so swiftly.

I’ll check it out tomorrow.

Cheers 
Dai

**Comment by dbrownukk** [comment]
Identified problem - the default database schema is used not the new OHEA Prod schema. In all the testing we had different schemas but the data was copied from schema to schema. Although the charts looked correct they were running off the right data but in the wrong schema. 

Now to find a fix.

**Comment by dbrownukk** [comment]
Export of Views to move from test to prod carried over the 'efd.' schema name.

In future will use mysql-workbench export scema structure and then import using

 mysql -u efd -p efdprod  --default-character-set=utf8

and run the create view script

**Comment by daiClegg** [comment]
**Tested OK**

@celiapetty - I've run every chart on at least one community. They all work.
You can now check the data .

**Comment by celiapetty** [comment]
Many thanks
C
