### ISSUE TITLE
Example Data set from a Community Interview

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#29]
This is the spreadsheet populated in a community interview:

[1_Hosea_BugoyeNtenjeru_Community.xlsx](https://github.com/dbrownukk/EFD_v2/files/1622300/1_Hosea_BugoyeNtenjeru_Community.xlsx)

Notes: 

- OHEA, at this stage,  does not automatically load this data to populate a project.
But semantically it needs to be able to represent this data and the UX in loading the data, from such a spreadsheet, should be simple, swift and intuitive.

- There does not seem to be any expected values for any of the Characteristic Resources. The model and code currently do include this data. I am still trying to clarify whether it is ever collected and if so what it is used for.

**Comment by daiClegg** [comment]
Confirmed. Expected values (design model column 'WGCResourceAmount') is not required for Characteristics, so it can be removed from the UI.

**Comment by dbrownukk** [comment]
removed WGCResourceAmount rom latest release 30th Jan

**Comment by daiClegg** [comment]
Is this deployed?
This is what i see in the WG module WGCharacteristics frame;

![image](https://user-images.githubusercontent.com/30879677/35746068-72a91496-083d-11e8-899a-33b74bdeae81.png)

**Comment by dbrownukk** [comment]
Yep, deployed, just needed the defaults applied. Should be ok now

**Comment by daiClegg** [comment]
Tested Ok
