### ISSUE TITLE
Adding Topic to study with no questions hangs

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#291]
Instance:    EFD_HM
Module:      Study

1. create a new study.
1. click **Copy in Topic Questions**
1. select a topic (any topic) from the drop down
1. click **Copy** 
> application hangs

1. reload browser page
1. click **Cancel** (in copy topic pop-up)
1. click **New** and add a question to the study
1. repeat the copy in topic questions sequence of operations
> success!

**Comment by dbrownukk** [comment]
small fix to cater for new study in CopyTopic.java

fixed, deployed

**Comment by daiClegg** [comment]
**Tested Ok**
