### ISSUE TITLE
Employment Type Dropdown should be sorted Alphabetically

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#292]
INstsance: EFD_HM
Module:     Study

On the Employment tab, the Employment Type field correctly includes Employment Types in the dropdown, but it would be more helpful to users if it were sorted alphabetically.

**Comment by dbrownukk** [comment]
CreateXLSFileActionOIHM - changed rst query to order by rst name

All RST dropdowns in template spreadsheet are now ordered alphabetically

**Comment by daiClegg** [comment]
*Tested Ok**

very helpful for users.
