### ISSUE TITLE
Can create and use an LoV list with no entries

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#294]
Instance: EfD_HM
Module:   Study
Study:      Test Configuration Questions
Tab:          Questions

Note there is a question with prompt "What happens to an empty LoV?"
It has "emptyLOv" as it's list, which is empty.
Entering an answer (at study level) is rightly flagged as a ERROR 
But an empty LoV should not be savable in the first place.

To reproduce:
1. Click + to create new question
1. Enter prompt & hint
1. Leave level as Study (easier testing - see below)
1. Select LoV as Question type
1. Click + on List of Values To Use
1. Enter LoV List name
1. Click Create (having entered no values) (LoV)
1. Click Save (Configuration Question)
1. Click Save (Configuration Question Use)
1. Click Study Question Answers
1. Click Answer for the question you just created
1. Click drop down
> Note: no entries
1. Click Save
> Note: ERROR value

**Comment by dbrownukk** [comment]
add annotation @NotEmpty to the LOV collection

error message if no lovs belong to the lov type 

deployed

**Comment by daiClegg** [comment]
Retested:
=

Instance: EfD_HM
Module: Study
Study: Test Config Questions
Tab: Questions


1. Filter Question types to Lov
> note there are two. One as previous test & one created today.
1. Click either LOV to view detail
> note they both use "emptyLoVList"
1. Click Edit Configuration Question
1. Click Edit LoV to use
> note the LoV has no entries (i successfully removed the one it previously had - no error)
1. Click Cancel
1. Click Cancel
1. Click Close
1. Click Study Question Answers tab.
> note the incorrect answers to the LoV questions
1. Click either answer
1. click the Lov drop down in the pop u[p.
> note there are no values to choose from.
1. Click Save
1. Click Save
> note no errors throughout but the data is not valid.

This behaviour is replicated when creating new questions:

1. Click Questions tab
1. Click + to create new question
1. Enter prompt & hint
1. Leave level as Study
1. Select LoV as Question type
1. Click drop down on List of Values To Use
1. Select " emptyLoVList" List name
1. Click Create  (Configuration Question)
1. Click Save (Configuration Question Use)
1. Click Study Question Answers
1. Click Answer for the question you just created
1. Click drop down
> Note: no entries
1. Click Save
> Note: Save now appears to work and the answer value is "{id=}"

**Comment by dbrownukk** [comment]
I believe " emptyLoVList" is the problem here. New LOV type cannot be created with empty values from Question module. 

Need to delete all uses of " emptyLoVList"

**Comment by daiClegg** [comment]
As discussed, the problem arises from deleting the last entry in an LoV, rather than creating an empty list.

**Comment by dbrownukk** [comment]
replaced @NotEmpty (which should work with Collections) with @Size(min=1)

deployed fix

**Comment by daiClegg** [comment]
**Tested Ok**
