### ISSUE TITLE
Defining Livestock Assets in Study creates a Livestock Sales record

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#295]
Instance: EFD_HM
Module:   Study 
Tab:         Characteristic Assets/Resources
Sub-tab: Livestock

Livestock Sales is pre-populated with whatever Livestock Assets have been created.
There should be no defaulted Livestock Sales records.
When creating a new Livestock Sales record, the dropdown should be restricted to those Livestock Resource sub-types for which a Livestock Asset record exists.
ie you can only sell what you have.
But you don't necessarily sell any of your assets.

To reproduce:
1. Open any Study in detail view.
1. Click Characteristic Assets/Resources tab
1. Click Livestock Sales sub tab and note contents, if any
1. Click Livestock sub-tab
1. Click New
1. Select any Livestock type not already in the Study
1. Click Save
1. Click Livestock Sales saub-tab
> Note the new Livestock you added has been added here too.

**Comment by dbrownukk** [comment]
Livestock Sales was defaulted (wrongly) from 'Livestock' asset

Fixed.

Making the dropdown rst list from available livestock that they already have recorded in 'Livestock' could be tricky. It also will require that Livestock is always entered before Livestock Sales. 

Will see what is possible..

**Comment by dbrownukk** [comment]
Managed to code this to work as required. Uneasy about the hard coding.

Also added a unique constraint to characteristic resource - (study, rst, type)

**Comment by daiClegg** [comment]
I fear i have to agree. My original data model fails to specify the 'type' validation for the different intersections between Study (or WGI in OHEA) and RST. 

Let's discuss. I will think about how to model it declaratively to eliminate hard coding.
But then it is a separate decision whether to re-engineer to adopt a new model.

**Comment by daiClegg** [comment]
Some further thoughts, for discussion:

1. do we need to bother about Livestock Sales of a Livestock type that has not been recorded? 

1. constraints on which RSTs (by Resource Type) can be associated with a characteristic resource or an Asset type, are going to be needed and enforced on a case-by-case basis. Is it possible to implement a more generic mechanism such that customisation is data-based, rather than by custom code?

For the first question, In theory, it's a valid constraint, but in practice, probably not worth the hassle.

The second is worth considering. 
-  Resources to which a family (in IHM) or a WG (in HEA) have access to are such things as “Land”, “Livestock”, “Crops”, “Transfers” etc.
--They are categorised as such as part of the methodology, so the data collection is oriented around these categories.
- Some of them, for example “Wild Foods”, are synonymous with a single set of identifiable resources, normally known as a Resource Type. 
-- For “Wild Foods” examples would include “Jack Fruit,” “Nile Perch”, “Wild Berries.” 
- But some categories, for example Inputs, maybe a resource in one or more of the resource type groups; in this case “Other Tradable Goods” and “Non-Food Purchases”.

It is possible to define a list of which Asset types can be of which Resource types. That could be defined as a database table for lookup/join in a create/edit operation.
It could also be partitioned as static properties of classes that define Asset sub-types or Characteristic Resources that would then be available to create & edit operations.
The latter seems cheaper at run time, and although it is in code, it is a standard pattern in any Asset subtype class.

**Comment by daiClegg** [comment]
After discussion, leave as is.
Complexity is not high, just a bit inelegant.
But understandable & maintainable.

**Comment by daiClegg** [comment]
No Livestock sales generated from new Livestock record
Livestock sales restricted to the Livestock types owned

**Tested Ok**
