### ISSUE TITLE
Food Stocks not correctly processed in Characteristic Assets of Study module

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#296]
1. Create a new Project (TestFoodStocks1)
1. Create a new study (FoodStockTest1)
1. Navigate to Characteristic Resources tab.
> note the number of FoodStock Records is -1
1. Add a new FoodStock Characteristic Resource
> the dropdown does not offer 'Crops', 'Wild Foods' or 'Livestock Products' (as per comment 6 days before this one)

insert appears to work, but does not display the record.
navigate away from foodstock sub-tab and then back

Foodstock is displayed as ERROR

**Comment by dbrownukk** [comment]
Perplexed. fixed this a while back and cannot reproduce. What am I missing?

**Comment by daiClegg** [comment]
I was working through large features that are still open, to close them as 'feature complete' and to record any remaining anomalies that were not previously documented as tested ok within the feature as new issues.
Needless to say i was re-testing each one as i went to make sure i only raised issues that were still there. This should not have been included. As you say it is fixed.
