### ISSUE TITLE
Obscure error message when unable to upload HH interview spreadsheet

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#297]
Instance: EFD_HM
Module:   Household
Study:      test Issue 293 
HH Id:       1

In Study Module:
1. Created this Study to test Issue #293 
1. Defined limited Characteristic Resources & generated the template
1. Ignored the interview detail tab
1. Entered test data for  the 3 tabs affected by #293 (Crops, Livestock Products & Wild Foods)
1. Saved

In HH Module:
1. Created new HH & Saved
1. Uploaded the spreadsheet & Saved
1. Parsed spreadsheet 
> ERROR: Impossible to execute Parse spreadsheet action: Cannot get a numeric value from a text cell

Realised i had not set price-per-unit for sold resources  in my first test,so retested with that specified (HH2)
Same result

**Comment by dbrownukk** [comment]
Spreadsheet downloaded from idaps and loaded into development app. Loads successfully. 

First time seen discrepancy between local and idaps

idaps catalina.out tail 

hhm tot now =0
first get = test Issue 293 2018
May 13, 2019 10:08:43 AM org.openxava.controller.ModuleManager manageRegularException
SEVERE: Cannot get a numeric value from a text cell
java.lang.IllegalStateException: Cannot get a numeric value from a text cell
	at org.apache.poi.hssf.usermodel.HSSFCell.typeMismatch(HSSFCell.java:654)
	at org.apache.poi.hssf.usermodel.HSSFCell.getNumericCellValue(HSSFCell.java:679)
	at org.apache.poi.hssf.usermodel.HSSFCell.getDateCellValue(HSSFCell.java:700)

**Comment by daiClegg** [comment]
Thanks David.
Agree interview date should be mandatory on the spreadsheet.


**Tested Ok**
