### ISSUE TITLE
HH member not parsed if Sex is blank??

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#299]
Instance:       EFD_HM
Study:            test Config Questions
HH Name:      3 test absence questions 
HH Number:  7

The attached spreadsheet contains data for 6 HH members, but only 5 are parsed.
The 6th HH member has not gender entered & invalid number of months absent (13)

**Expected Behaviour:**
- Error on number of months absent for HH member 6

**Actual Behaviour :**
- No error message; apparently successful parse.

**Comment by daiClegg** [comment]
See also HH number 8 which has the same number of HH members but the 6th now has gener entered correctly

**Comment by daiClegg** [comment]
Invalidperiod of absence is not the problem but should be validated (12 or less) will raise a separate issue for that.

**Comment by dbrownukk** [comment]
Problem was the check for no more HH in spreadsheet. 

Now checks if  age, gender, year of birth are not entered

**Comment by daiClegg** [comment]
**TestedOk**
