### ISSUE TITLE
Invoking 'Save' action  also performs 'New' Action

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#30]
I tested this on Cimmunities and on Livelihoods zones (admin user)

Steps to reproduce:

> Select a record, in detail view
> Perform an update to the record
> Click 'Save' (or press ctrl-S)

Result:

displays the "... modified successfully" popup
clears detail & displays blank record detail 

Validation actions:

> select list view

the update has been correctly captured.

**Comment by dbrownukk** [comment]
Added a new default Save in Detail mode that takes you back to a list - hope that makes things clearer
EFDSaveAction class and added to Application.xml and Controllers.xml

    <controller name="EFD">
		<extends controller="Typical"/>
		
    <action name="save" mode="detail"
      class="efd.actions.EFDSaveAction" 
      by-default="if-possible"
      image="save.gif"
      icon="content-save"
      keystroke="Control S"/>

	<default-module>		  
		<controller name="EFD"/>		
	</default-module>

**Comment by daiClegg** [comment]
Tested ok
