### ISSUE TITLE
HH Member Sex validation is overly rigid

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#301]
Instance: EFD_HM
Study: test Config Questions
HH Name: 3 test absence questions
HH Number: 7

HH Members 2 to 5 have Sex entered as male or female (lower case)
Parse renders them as Sex 'Unknown' because they are not init capped.
But the spreadsheet happily accepts these values.

Since there is no ambiguity, Parse should accept lower case as well as init capped versions of Male & Female

**Comment by dbrownukk** [comment]
done

**Comment by daiClegg** [comment]
Instance: EFD_HM
Study: test Config Questions
HH Name: Test Issue 301
HH Number: 10

**Tested ok **
