### ISSUE TITLE
Log in shows 2 nested menu bars

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#302]

**Comment by daiClegg** [comment]
Instance:  EFD_HM

Login (which user appears to be immaterial)
> login screen shows nested menu on left, nested signout controls on right and continuing 'Loading' message

![image](https://user-images.githubusercontent.com/30879677/58548591-86396f80-8201-11e9-9141-20c29cd240f5.png)

Despite 'Loading' indicator,  login has been successful & as soon as you invoke any module (from either menu) the spurious nested elements disappear.

**Comment by dbrownukk** [comment]
Before upgrade to OX 6.1 on login you would go to a previously used module. This is no longer available and should go to start screen. However, I skipped the startup screen in preference to starting in Study module, which clearly no longer works. 

Rest to default OX behaviour which is a nice big Arrow saying choose a module...

**Comment by daiClegg** [comment]
Tested Ok.
