### ISSUE TITLE
HH Interview Template includes incorrect name for Site

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#304]
S/Sheet V2, Interview details tab.

The Site field is derived from the District name not the Sub-District name.
Tha this normally the Village, which is the actual Site, The District may be a very larder area.

Spreadsheet:

![image](https://user-images.githubusercontent.com/30879677/58567542-6c605280-822a-11e9-9ba3-75dc5a260a06.png)

Site data record:

![image](https://user-images.githubusercontent.com/30879677/58567736-c2cd9100-822a-11e9-8045-cc94ccc42782.png)

**Comment by daiClegg** [comment]
btw the Study Start DAte field has no border; all the others do. 
not critical but nice to have ocnsistency

**Comment by dbrownukk** [comment]
Sub district now used in spreadsheet 'Site'
Fixed border on Study Start Date
deployed

**Comment by daiClegg** [comment]
**Tested Ok**
