### ISSUE TITLE
HH Interview Template lacks validation for LoV question

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#305]
Instance EFD_HM
Study: M2 Tutorial Test
HH Interview Template Spreadsheet V2, HH Config tab

The configured question is of LoV type (YesNo)

![image](https://user-images.githubusercontent.com/30879677/58568338-0248ad00-822c-11e9-92c4-49fb1e8f7114.png)

But in the spreadsheet there is no validation:

![image](https://user-images.githubusercontent.com/30879677/58568284-e6450b80-822b-11e9-8120-81827f299109.png)

**Comment by daiClegg** [comment]
Just discovered the validation is on the cell below:

![image](https://user-images.githubusercontent.com/30879677/58568725-a9c5df80-822c-11e9-9d84-0fbca1261624.png)

**Comment by dbrownukk** [comment]
fixed. LOV row value had extra ++

**Comment by daiClegg** [comment]
**Tested Ok**
