### ISSUE TITLE
HH Interview Spreadsheet is missing LoV for Food Transfer Food Type

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#307]
Instance: EFD_HM
HH Interview Template V2, Transfers Tab

The type of Food cell has no LoV; it should show Food types (Crops, LS Products, Wild Foods)

![image](https://user-images.githubusercontent.com/30879677/58570347-bd267a00-822f-11e9-94e5-7e7c6b0d2a86.png)

**Comment by dbrownukk** [comment]
fixed
deployed

**Comment by daiClegg** [comment]
**Tested OK**
