### ISSUE TITLE
Strange error when  creating a new synonym for an RST 

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#308]
Instance: EFD_HM
Module: Resource Sub Type
User: Testy

click new
enter data as per screenshot.
click save.

>strange error : uk4gyixekr36ftipta9p2ueumix

![image](https://user-images.githubusercontent.com/30879677/58571225-3d011400-8231-11e9-877c-cb6a33b25dcb.png)

Reproduces for admin user, so  doesn't appear to be role-based.

**Comment by dbrownukk** [comment]
Constraint raised is duplicate RST within RT
Changed message - "Resource Subtype within Resource Type already exists
deployed

**Comment by daiClegg** [comment]
**Tested Ok**
