### ISSUE TITLE
A Comma in the name of a Report Spec, causes a Tomcat exception

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#309]
Instance:        EFD_HM
Study:            M1 Workflow Study
Report Spec: Is a comma, in a spec name, fatal?

In Study 

1. In detail view for this Study click Reports
2. Select Report Spec "Is a comma, in a spec name, fatal?" from the drop down.
3. Click Run

> OIHM reports successful report creation.
> but the tab created to download the result shows this status and no report file is downloaded.

![image](https://user-images.githubusercontent.com/30879677/58576458-4b086200-823c-11e9-9bcf-5c50a5a6c910.png)

**Comment by dbrownukk** [comment]
Hmm. I use the 'spec name' in the spreadsheet file name that is created. The comma and question mark are not accepted by the file creation code. I know that you can have a comma in a windows file, but...

Will consider an alphanumeric validator

**Comment by dbrownukk** [comment]
specName now has @Pattern("^[A-Za-z0-9  ]+$") to restrict to alphanum
in CustomReportSpec class

to be deployed..

**Comment by dbrownukk** [comment]
deployed

**Comment by daiClegg** [comment]
Tested OK
