### ISSUE TITLE
Project module should include District & Sub-district of Communities

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#31]
District name and Sub-district name should be columns 2 & 3 of the list view of Communities in the Project module. They are currently omitted.
"Sequence" should be the first column, as now, but it would be better labelled "I/V Sequence" and should be the sort order for the display, rather than create order (which i think it is now).

**Comment by dbrownukk** [comment]
Changed EFD_v2-labels - Sequence to I / V Sequence
Added @ListProperties to Project class for Communities collection
@OrderBy("cinterviewsequence")

**Comment by dbrownukk** [comment]
Hang on - deployment did not see Sequence at beginning...

**Comment by daiClegg** [comment]
tested ok
