### ISSUE TITLE
Calculate Disposable Income for IHM

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#310]
Disposable income calculation for IHM differs in one point from the calculation for HEA ( Issue #145)
And that is the calculation of the Required Calories.
In HEA, RC = 2100 * 365 * No. of People in Household

In IHM, we can be more accurate, because we know the age and sex of each household member, and we know what proportion of the year they are present in the household.
So the calculation should reflect that additional information.

The FAO publishes a table (Energy Requirements) (TBA) for each Age & Gender combination.

Member Calorie Requirement
==

MCR = EnergyRequirements (Age,Sex ) * 365 * (12 - Months Absent)/12
                       
**the previous line had a typo - the '/12' was inside the bracket**

HH Calorie Requirement
==

Sum of MCR for all HH members

@celiapetty - can you confirm this is correct and where is the table we should use for this please?

**Comment by celiapetty** [comment]
Dai
That looks right to me. John, could you confirm?
The table used in the current version of Open-IHM is attached.
Celia

**Comment by daiClegg** [comment]
John,
You happy with this?

Celia, 
I'm not seeing the attachment.

**Comment by celiapetty** [comment]
Attaching again
[Kcal requirments reference table.docx](https://github.com/dbrownukk/EFD_v2/files/3236196/Kcal.requirments.reference.table.docx)

**Comment by daiClegg** [comment]
@DrJohnSeaman. Ok with you?

**Comment by daiClegg** [comment]
This is the same table that i already had in Issue #236. apologies for re-requesting it.
Will use these values.

**Comment by DrJohnSeaman** [comment]
Sorry my internet has been off. If that is the original table, and it must be it is OK. I derived it from the FAO values John

**Comment by dbrownukk** [comment]
table is now within dataset and in use
deployed

**Comment by daiClegg** [comment]
Awaiting real-world test data from Stella's testing.
Stella intends to compare OIHM with the old OpenIHM application, which is regarded as reliable in this calculation

**Comment by daiClegg** [comment]
Comparing OpenIHM with OIHM outputs depends on the KCal values of RSTs in OIHM matching those used in OpenIHM. 
That is being addressed in Issue #334

**Comment by stellangoleka** [comment]
To compare OIHM with the old OpenIHM application depends on the KCal values of Resource Subtypes in OIHM matching those used in OpenIHM. I added all the missing kcals values in the two software; I added all the kcal values in the O-IHM software into open IHM and vice versa to ensure that there are no omissions or discrepancies when testing old vs new output. 

Comparisons of O-IHM and OpenIHM outputs: 
The values for both food and cash income (raw) are the same.
The values for Disposable Income (DI raw) are NOT the same.

It looks like the problem is with the calculations in the software. 
The files- showing the identical values for food income and cash income from open-IHM and O-IHM and the HH spreadsheets used for this testing are attached.  
The household I've used here as an example is HH37 in OIHM 


[For comparisons.zip](https://github.com/dbrownukk/EFD_v2/files/3513581/For.comparisons.zip)
[katakwi comparison test.zip](https://github.com/dbrownukk/EFD_v2/files/3513583/katakwi.comparison.test.zip)

**Comment by daiClegg** [comment]
See #145 for original OHEA  DI calculation from which the OIHM DI calculation was derived.

**Comment by daiClegg** [comment]
I wrote:

Should have been:

MCR = EnergyRequirements (Age,Sex ) * 365 * (12 - Months Absent)/12

**Comment by daiClegg** [comment]
@celiapetty @DrJohnSeaman @stellangoleka  Can you collectively verify that the algorithm i documented above and in issue #145 is correct for calculating DI, please?
Note that the error i made in typing it up is now corrected here.

**Comment by daiClegg** [comment]
Instance:    EFD_HM
App:            OIHM
Module:       Study
Study:          Katakwi- NIMFRU Test
HH:               37

1. In Study Detail view, click run reports
2. In report spec drop-down select All Reports
3. In Household list (page 2) select Household Number 37
4. Click Run
5. Open the generated reports spreadsheet
6. On the Cash Income tab, note the sources of income add up to 1,065,000.00
7. On the Disposable Income tab, note the DI is 2,131,776.13

DI cannot be greater than Cash Income.
See @stellangoleka's  comment on the day before this comment re the calculation in existing production software (OpenIHM) - DI for this household is 775,154.06, which seems  more reasonable

**Comment by celiapetty** [comment]
Dai-see below

John-any comments on the algorithm we wrote up in the King's training
materials?

DI = sum(ACInc) -((HHFEnReq (Kcals) - sum(AFI) * FP)



DI = Household disposable income: can be a negative value. This is the
total from a whole year.

ACInc = All cash income from all sources (i.e. crop sales, sale of
livestock and livestock products, employment, cash transfers and the sale
of wild foods).

AFI = All sources of income as food consumed (from crops, livestock
products, payment in food, food gifts, transfers). This is expressed in
Kcals.

HHFEnReq = Annual household food energy requirement = Sum (Annual food
requirement of each individual in the household by sex and age). These
values can be found in the WHO reference table.

FP = The price of food (Input: 'Diet', i.e. the staple foods that form the
basis of the local diet).  A weighted price is calculated – for example, if
2,000 Kcals have to be purchased and the diet is 90% maize @ MK20 per Kg
(3630 Kcals per Kg) and 10% beans @ MK50 per Kg (5600 Kcals per Kg), the
price calculation would be: ((1,800/3630) *20) + (200/5600 *50). The price
of the food input here would be MK11.70.

 Household disposable income and the cash remaining after non-food
expenditure can then be standardised as disposable income per adult
equivalent. This allows direct comparisons to be made between the incomes
of different households

*Standardising disposable income for household size (Disposable Income per
Adult Equivalent*

 Each household differs in number, age and sex, so the household’s total
disposable income is unsatisfactory as a guide to the household’s economic
status. For example, a household of ten people and a household of one
person with the same disposable income would have a very different spending
power and potential standard of living. Disposable income must be
standardised for household membership. This is done using the 'adult
equivalent', i.e. the total requirement of the household, measured in units
of adult food energy requirements (2600 kcals per day, the daily energy
requirement of a young adult male or female).

The calculation is as follows:

No of adult equivalents in the household =household members' total energy
requirements/2600 ie adult energy requirement

Note-2600 kcals is the energy requirement of an adult male or female in
their mid 20s.  It is selected for the 'adult equivalent' reference
requirement as the kcal requirement is  the same for both sexes at this age

[For information, the summary  we use in training  to describe DI is:

 Disposable income=Sum of all household cash income-(Household food energy
requirement [kcal]-Sum of all household food income [kcal]) × Price per
kcal of staple diet)]

**Comment by daiClegg** [comment]
@celiapetty In the absence of this algorithm, i wrote up the one i documented above months ago from what i had deduced from all our conversations about DI. 
And i asked you and @DrJohnSeaman  to review it. I got no demur; admittedly no confirmation either.
So David implemented it.

I'd prefer not to throw all that away and start from scratch from your new algorithm. 
That would take significant time, trash the time already spent and provide an opportunity to introduce new bugs.

But right now we do have a bug, either of my algorithm or @dbrownukk's implementation.
I have written steps to reproduce for David to see the problem, so we'll see soon if he finds an error in implementation. 
Meanwhile, is there an error in the algorithm i have documented. I can see it is similar to the one you have posted here, but different enough to make a straight comparison not simple.

**Comment by celiapetty** [comment]
I've looked back over the issues and  responded to the query over reference
tables for IHM-calculation of household kcal requirements.
The DI calculation looks consistent-but I may be missing something
Is the query around the calculation of adult equivalents?

**Comment by celiapetty** [comment]
John Could you confirm the algorithms  I've posted (copied from guidelines we've produced) and if there are any conflicts with the algorithm for DI Dai had posted could you identify this. It looks as if we did not provide the algorithm for standardising DI per adult equivalent (DI per AE). 
Dai, you may recall the terms used in the old open-IHM: DI 'raw'  and DI 'standardised' ie per adult equivalent. Users should be able to chose if they want to report 'raw' or 'standardised per AE'

**Comment by DrJohnSeaman** [comment]
DI = sum(ACInc) -((HHFEnReq (Kcals) - sum(AFI) * FP)

DI = Household disposable income: can be a negative value. This is the
total from a whole year.

ACInc = All cash income from all sources (i.e. crop sales, sale of
livestock and livestock products, employment, cash transfers and the sale
of wild foods).

AFI = All sources of income as food consumed (from crops, livestock
products, payment in food, food gifts, transfers). This is expressed in
Kcals.

HHFEnReq = Annual household food energy requirement = Sum (Annual food
requirement of each individual in the household by sex and age). These
values can be found in the WHO reference table.

FP = The price of food (Input: 'Diet', i.e. the staple foods that form the
basis of the local diet).  A weighted price is calculated – for example, if
2,000 Kcals have to be purchased and the diet is 90% maize @ MK20 per Kg
(3630 Kcals per Kg) and 10% beans @ MK50 per Kg (5600 Kcals per Kg), the
price calculation would be: ((1,800/3630) *20) + (200/5600 *50). The price
of the food input here would be MK11.70.

Sorry about the delay, i have been away. The algorithm is correct. Also the standardisation.

**Comment by daiClegg** [comment]
OK. I think that's what i specified above, except i took Absences from the Household into account when calculating an individual's food requirement - 1/12th of the total for each absent month.

Also, in the DI summary line:

> DI = sum(ACInc) -((HHFEnReq (Kcals) - sum(AFI) * FP)

isn't there a closing bracket missing:

> DI = sum(ACInc) -((HHFEnReq (Kcals) - sum(AFI)) * FP)

  ----------------------------------------------------^

**Comment by stellangoleka** [comment]
The formula I used in my thesis is similar but has a significant difference in the use or place of brackets. Please see the word document attached.


[DI calculations.docx](https://github.com/dbrownukk/EFD_v2/files/3559016/DI.calculations.docx)

**Comment by DrJohnSeaman** [comment]
There is a closing bracket missing...

**Comment by stellangoleka** [comment]
From which open bracket?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by dbrownukk** [comment]
Does anyone have the DI calculation in a spreadsheet? This would be very useful to check my code and ensure I am on the right track. Many thanks. David

**Comment by stellangoleka** [comment]
Please find attached some information which I hope you find useful.
[HEACalcualtor.zip](https://github.com/dbrownukk/EFD_v2/files/3563890/HEACalcualtor.zip)

**Comment by stellangoleka** [comment]
@DAI CLEGG <dai.clegg@gmail.com> , I sent this spreadsheet 3 days ago, did
you get it? I have attached it again in case you didn't get it.

**Comment by daiClegg** [comment]
David is travelling; I don’t think he had time to action this before he departed. He’s back next week

**Comment by daiClegg** [comment]
@stellangoleka I've attached the calculator .xls from your .zip above, with some notes/questions.
Also, this is an HEA calculator. My first concem here is that we have implemented in OIHM matched what is implemented in OpenIHM, so does this algorithm matches OpenIHM, apart from the calculation of Individual requirements?

**Comment by daiClegg** [comment]
INstance:  EFD_HM
App: OIHM
Module: Household
Study: Katakwi- NIMFRU Test 2018
HH: 5 - Ocepa Patrick

- Ran All reports report spec for just this household (attached)
- Copied the  crops into another spreadsheet (attached)
- Copied in KCals from the RST record of each Crop
- Calculated the Food Income from each crop & summed it.


This does not match the Food Income from crops in the report.
Some things i noted are: 
- the Mango record has a blank Crop name
- there are some synonyms used; did the calculation correctly resolve the KCal value to that of the base RST of the synonym?


[All ReportsThu Sep 05 21_12_51 UTC 2019.xlsx](https://github.com/dbrownukk/EFD_v2/files/3584943/All.ReportsThu.Sep.05.21_12_51.UTC.2019.xlsx)
[DICalc.xlsx](https://github.com/dbrownukk/EFD_v2/files/3584946/DICalc.xlsx)

**Comment by celiapetty** [comment]
Green grams in the spreadsheet show a kcal value of 0
The kcal value of  is Green grams: 3290
Stella, this has been incorrectly logged as a synonym for Wild green leaves. 
Green grams  is a crop and should not be  entered as a wild food. I recall sending the kcal value of green grams while you were in Uganda so I'm not sure where the error came in.

**Comment by daiClegg** [comment]
Did a bit more digging Updated my notes in the DICalc spreadsheet
[DICalc.xlsx](https://github.com/dbrownukk/EFD_v2/files/3586721/DICalc.xlsx)

Looks like Synonyms are the problem, plus dodgy data (as raised in Issue #358)

**Comment by daiClegg** [comment]
@stellangoleka @celiapetty  please don't chance the RST values relating to this issue until David has a chance to look at my notes. If you correct Green Grams before then it will invalidate the data on which my testing and calculations are based. 

I'll raise a separate issue for correcting Green Grams, for actioning when this issue is closed

**Comment by dbrownukk** [comment]
reworking

MCR = EnergyRequirements (Age,Sex ) 365 (12 - Months Absent)/12

Found duplication of DI calculation array.

Need to check hh array for popualtion of configAnswer

**Comment by stellangoleka** [comment]
@DAI CLEGG <dai.clegg@gmail.com>  can I now correct the kcal value of Green
gram?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by stellangoleka** [comment]
I updated values a couple of weeks ago. It should be correct now.

**Comment by daiClegg** [comment]
We have an issue for Green Grams -  #359.

Can you please use that to discuss that issue and not this thread. 
I'll be happy to engage there.

**Comment by dbrownukk** [comment]
OK, DI calc fixes now deployed. Food Income calc also corrected. 

Ready for testing and updating of RST values. 

Apologies for delay! Post holiday catching up.

**Comment by celiapetty** [comment]
Dai, should Stella now resume open_IHM testing:  DI (ie not standardised per A/E)  and DI/AE?
Stella, are you available to do this now?

**Comment by daiClegg** [comment]
No. I defined the test case above; i will test whether it now passes.
Since at least some RST KCal values have been changed (Green Grams at least)  since the original test, it may now fail because we're not comparing like with like. I'll have to pick the nits out of that. It is unfair to ask Stella to do it.
I have Stella's original test data from Open-IHM (attached above).


As far as i know Stella has raised no other issues in testing the Reports and i thought she had completed her tests. It might be an idea for Stella and you (Celia) to have a conversation and decide whether you think her testing is complete enough or whether there is more that needs doing.
If there is it should be documented in new issues that each link to the report feature issue relevant to the Report she is to test. Or in the Reports Epic if they are general tests. These are all closed now but a search will find them (their issue numbers are actually in the report names in the report data extract file, so that provides an easy way to find them).
This issue relates to one specific bug. Let's keep it that way.

**Comment by daiClegg** [comment]
My minu=imum test case (documented above in early September) no passes.
Attached is the new spreadsheet showing the results.
[DICalc (2).xlsx](https://github.com/dbrownukk/EFD_v2/files/3680683/DICalc.2.xlsx)

I will now retest Stella's broader test and if that fails, i'll find the next place and document that in a minimal test case.

**Comment by stellangoleka** [comment]
@Dai note that there have changes made in the OIHM RST and including adding
synonyms which may or may not affect previous open-IHM output. Ofcourse in
a case of comparisons of the results as you have mentioned.

**Comment by daiClegg** [comment]
@stellangoleka: Yes, i realise the comparisons may not be valid. 
Synonyms won't make any difference as long as the base RST has the same KCal in both systems.
But can you check, please,  that for at least one household in the Katakwi data set the RST values for all the food income elements match between OpenIHM & OIHM?
If there are differences, then i can compensate for them in the testing. 
If you're sure that after yours and Celia's review of all the RSY KCal values that they are all aligned, apart from Synonyms, then just let me know.

**Comment by daiClegg** [comment]
Notes here for my testing (calculation stages from above & from #145).
Will enter results in line here plus separate commentary below.

**Food Income =**
 Sum (Units Consumed * KCal per Unit) for all Crops, Wild Foods and Livestock Products + 
 Sum (KCal per Unit of Food Type * No. of Units Paid) for all Employment paid in Food + 
 Sum (KCal per Unit of Food Type Transferred * No. of Units Consumed) for all Food Transfers

- **Crops - tested ok**

---------------------

**Cash Income =**
Sum (Units Sold * Price per Unit) for all Crops, Wild Foods and Livestock Products + 
Sum (Units Worked * No. of People Working * Cash Payment) for all Employments + 
Sum (Transfer Amount * No. of People Receiving * No. of Times Received) for all Cash Transfers


**Household Calorie Requirement =**
Sum EnergyRequirements (Age,Sex ) * 365 * (12 - Months Absent)/12 for all HHMs

---------------------

**Shortfall =**
Household Calorie Requirement - Food Income

---------------------

**Shortfall Cost**

---------------------

**Diet Cost per Kg =**

---------------------
**Disposable Income =**
Cash Income - Shortfall Cost

---------------------

**Comment by daiClegg** [comment]
Food Income now tests ok.

Cash Income calculation ignores the value of Livestock sales & only includes Proceeds of Livestock Product sales.

**Comment by daiClegg** [comment]
Meanwhile, i can continue to test the calculation as per the checklist above...

**Comment by daiClegg** [comment]
Livestock Cash income now tests ok
Employment Cash income now tests ok
Transfers not included - no Transfers in this HH

CAlculated and verified KCal requirement, next step, shortfall...

**Comment by daiClegg** [comment]
Just re-checked the full calculation. 
On OpenIHM (From Stella's test)
Household of Asaja Ingnitius 

has DI   775154.06

On OIHM the same household:
HH:          37
Study:      Katakwi- NIMFRU Test

has DI   622222.02

So i still have to keep on with my step by step testing through the algorithm...

**Comment by daiClegg** [comment]
My first pass through got a wildly  different number, so i need to re-check my incoding of the algorithm & my calculations.
tbc...

**Comment by daiClegg** [comment]
There was still invalid data (allowed by an old bug no fixed) in Stella's comparison household.
I corrected that & re-ran the reports.
The DI now for that HH, in OIHM is 707633.37.
In OpenIHM it is 775154.06

I found another invalid piece of data caused by that same bug, fixed it and re-ran.
OIHM now sows DI for that HH as 707633.37

So it's spot on.

I still want to find and correct whatever errors there are in my spreadsheet working of the DI calculation, because that may be valuable for regression testing later, but i'm now happy the OIHM DI calculation is correct, at least for all the data combination tested so far.
 
@stellangoleka - you can continue with whatever testing you and Celia have identified as outstanding.
I'll close this issue for the moment, but if you find the DI calculation for another HH  doesn't match, please re-open with the appropriate steps to reproduce.
If you find anomalies in other parts of reporting (e.g. AE calculation) please log as separate issues.
Thx.

**Comment by stellangoleka** [comment]
Celia, please provide me details of the testing I should do.

Dai, its great to see that the DI calculation is now fixed.

**Comment by celiapetty** [comment]
Stella,
I'm currently travelling, but could you go back to the original TOR for
this work and highlight any work that hasn't been done as part of this?
If all tasks are completed from  those TOR could you identify other testing
that's needed?
Many thanks
Celia
