### ISSUE TITLE
Complete Quantiles for OIHM reports

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#311]

**Comment by daiClegg** [comment]
Instance:        EfD_HM
Study:            M2 Tutorial Test
Report Spec: Testy Quantiles

-  Was able to create quantiles.

- Was able to run reports (note Test Quantiles Report Spec excludes 226 - which currently fails)

Some comments:

1. I created Poor, Middle & Better Off, but then decided to add Very Poor.
I was unable to reorder the sequence to accommodate my new quantile. 
I had to edit names & %ages for all the existing ones. 
It would be nice to edit the sequence numbers.

1. The 1st 2 columns of the report are 'Percentile ' & Percentile %'.
Should be 'Quantile' & 'Quantile %'

1. The name of the Quantile (Poor, Middle or whatever) should be in the report to make the displayed chart more meaningful

**Comment by daiClegg** [comment]
For this test, it is not clear to me which households are in which quantiles.
How is the calculation done?

**Comment by daiClegg** [comment]
Some notes on quantiles:

- Households are divided into quantiles in DI order. For example, if there are 3 quantiles (33% each) and 24 HHs, the poorest 8, by DI, go into the first quantile, the next 8 into the second quantile and the last 8 into the final quantile.
- Within each quantile, any value required for the report is the average (mean) of the corresponding value for all the HHs in that quantile.
- Where the number and percentages of quantiles do not result in integer numbers of HHs in each quantile (e.g. 4 quantiles of 25% and 11 HHs) some simple but sensible rule should be adopted to ascribe the borderline HHs. For example, ascribe to the quantile with the most members already. That way the additional HH will have less skewing effect. But if the number of HHs is so small that such skewing is likely to be significant, then maybe quantiles are not appropriate.
- Quantile reporting for Studies of less than 10 HHs is of dubious value, so a request for quantile reporting for such small studies should result in a warning (not prohibition) to the user.
- Quantile reporting is not needed for '238 Report Population by Age and Sex' nor for '237 Report HH Members Characteristics'.

**Comment by daiClegg** [comment]
The definition of quantile sand how to ascribe sample items into quantiles has been taken from here:

**Comment by dbrownukk** [comment]
@daiClegg I have deployed a quantile solution for DI and SOL

Before I go ahead and add the quantile functionality to the other reports can you cast an eye on the data. I know we only have a few HH but I believe the calc is correct from above.

M2 Tutorial Test
Report Spec = Test Quantiles on idaps is what I have been using

**Comment by daiClegg** [comment]
- I applied the formula on the web page linked above to see which HHs would be in which quantiles.
- I discovered it couldn't cope with the unequal quantiles we support. It ascribes no HHs to the first and only 6 out of 7 HHs altogether if rounding down from the raw calculation or 8 of the 7 if rounding up. 

- That's partly, i suspect, due to the small sample size, but also because that formula just ain't intended to work in the circumstances we want to apply it. A quick search doesn't turn up any other applications of unequal quantiles.
- But the application Celia and John describe seems reasonable and would appear to deliver value to a livelihoods data analyst, so we should support it.

- OIHM currently overcomes both the shortcomings of the formula, at least for the small sample currently tested, and appears to be a good solution to a tricky problem.

We should proceed with the current implementation and specifically test when we have real-world (large) data sets.

**Comment by daiClegg** [comment]
Quantiles should not be reusable; it should not be possible to 'Add' a quantile to a Report Spec.
A report spec should define 'New' Quantiles if it needs quantiles.

The thinking behind this is that although quantiles will often have the same names, "Poor", "Middle" & "Better Off" being the most obvious, they will usually have different percentages. So if i re-use them and change the percentages (e.g. from 35/45/20 to 40/50/10) i will affect the quantiles in other specs.
That can't be correct.

**Comment by daiClegg** [comment]
In fact the behaviour is not to reuse the quantile (ie have it appear in 2 specs), but to move it from one spec to the other one. That's definitely not desirable.

**Comment by dbrownukk** [comment]
Removed "Add" from Quantile tab within Custom Report Spec.

**Comment by dbrownukk** [comment]
deployed all Quantile reports with algorithm  from above q(n+1)

**Comment by daiClegg** [comment]
Instance:        EFD_HM
Study M2      Tutorial Test
Report Spec: test1

Run all reports.

In all reports except 227 & 228 the one included household is in the Poor Quantile (the others being empty).
But in 227 & 228 its in the Middle Quantile

Whilst it is clearly nonsense to report a single HH in Quantiles, the algorithm for apportioning HHs to Quantiles should be consistent for all reports.

**Comment by dbrownukk** [comment]
Was hoping the simple constraint check would be enough... You need to delete the sequences above the missing sequence and then re-enter. I was thinking that this would not be used very often once setup, but obviously not clear enough

Otherwise will create a sequence checker. 

Let me know if this needs simplifying

**Comment by daiClegg** [comment]
I had figured deleting and re-entering would fix it.
Not ideal, but i agree it should not be a frequent use.
I only needed it cos i was testing.

One anomaly (above) still there; will log that separately, otherwise...

**Feature Complete**
