### ISSUE TITLE
Complete OIHM Report Specification Usage

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#312]
Need to choose a RSU when running a report

RU is for a Study and for HH within Study

**Comment by daiClegg** [comment]
The requirement to manually specify households to be included is a backstop for if a household inclusion rule cannot be specified as part of the Report Spec.

As such, it can be transitory if necessary for efficient implementation.

**Comment by dbrownukk** [comment]
Now possible to select HH during report spec run
deployed

**Comment by daiClegg** [comment]
If i select HH manually when i have a HH inclusion rule already in the Report spec it is overridden by manual inclusion.
I can see that might be useful - comparing your subset of rule-included HHs with the full set.
But it makes me uneasy that part of the Report Spec is ignored.
I'd prefer that the user gets a warning.
Something like this would do the job - just tell the user there is a rule included- if they then override it, fine.

![image](https://user-images.githubusercontent.com/30879677/59621362-0da24080-9127-11e9-9610-277e8db3d346.png)

I'm wondering whether a short summary of the spec would be even more useful.
For example "HH Inclusion Rule, Selected Reports, Selected Resources".
But, with the exception of HH inclusion, there is no way to subvert the spec and it's an open-ended question what you include in the summary. So let's not go that route beyond what's necessary to stop them screwing up the report spec.

**Comment by daiClegg** [comment]
Also when i tested this:

Instance:    EFD_HM
Study:         M2 Tutorial test
Report Spec:  Test1

I ran the reports twice. Once overriding the spec to include all HHs in the run report dialogue.

The two outputs are attached, Just with the rule enforced:

[test1Mon Jun 17 16_16_49 UTC 2019.xlsx](https://github.com/dbrownukk/EFD_v2/files/3298070/test1Mon.Jun.17.16_16_49.UTC.2019.xlsx)

With all reports selected in the Run Reports dialogue:

[test1Mon Jun 17 16_17_17 UTC 2019.xlsx](https://github.com/dbrownukk/EFD_v2/files/3298071/test1Mon.Jun.17.16_17_17.UTC.2019.xlsx)

The data for the reports is the same in both files, so the rule has been enforced anyway.
But the second one includes all the HH numbers in the summary tab.

**Comment by dbrownukk** [comment]
You can no longer override a spec that contains a HH rule restriction.

**Comment by daiClegg** [comment]
Cannot get into this situation - manual inclusion of HH is prohibited. when there is a HH inclusion rule in the Report Spec, as noted above

** Tested OK **
