### ISSUE TITLE
Exception in Reporting

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#313]
Instance:        EFD_HM
Module:          Study
Study:             M2 Tutorial Test
HH:                  HH4
Report Spec:  All Reports: All Resources: All Households

To reproduce:
In HH Module: Set HH4 to be editable (ie excluded from reporting)
In Study Module: run reports
> success

In Study Module: Validate HH4
> success

In Study Module: Run Reports
> Error : java.lang.NullPointerException Errno = 106

will run more tests to try to isolate the problem

**Comment by daiClegg** [comment]
Tried removing other HHs to check it wasn't just the fact there are 4 HHs in this study - the most i have tested.
But the exception remains the same as long as HH4 is included

**Comment by daiClegg** [comment]
Need to try excluding reports - the spec i used runs them all

**Comment by daiClegg** [comment]
It's Report 226.
remove that, as in Report Spec 'Testing Issue 313, and it runs

**Comment by dbrownukk** [comment]
need to trap if no food payments rst exists as a payment type

done

deployed

**Comment by daiClegg** [comment]
Retested, same Study as above. 
Just ran report 226. 
Got this exception:

> ERROR: An exception occurred processing JSP page /xava/execute.jsp at line 90 87: manager.initModule(request, errors, messages); 88: manager.executeOnEachRequestActions(request, errors, messages); 89: if (hasProcessRequest) { 90: manager.execute(request, errors, messages);	91: if (manager.isListMode()) { // here and before execute the action 92: tab.setModelName(manager.getModelName());	93: if (tab.getTabName() == null) { Stacktrace:

doesn't seem to mastter wat HHs are included or not.

**Comment by dbrownukk** [comment]
don't test anymore - something askew with the version that was deployed.

**Comment by dbrownukk** [comment]
retested, seems to work ok.

**Comment by daiClegg** [comment]
**Tested Ok**
