### ISSUE TITLE
Age & Year of birth are not cross-validated in Spreadsheet Validation

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#317]
Instance: EFD_HM
Study: test Config Questions
HH Name: Test Issue 300
HH Number: 11

The ages & years of birth of the HH members of this HH are inconsistent.
They are loaded & Parsed without happily enough - no problem with that.

But Validate should not allow the data to pass.

We have options:
1.  require the user to correct manually if Age & YoB are inconsistent
1.  give one value (age or YoB) precedence and correct the other automatically as part of Parsing 
(Could Have) with a message to the user

**Comment by daiClegg** [comment]
@celiapetty  - which of the 2 options above do you prefer?

**Comment by dbrownukk** [comment]
Is Age or Year of Birth more commonly known?

Simplifying spreadsheet to enter Age or Year of Birth and let the parse calculate the other would work.

**Comment by celiapetty** [comment]
Age is more commonly used.

**Comment by daiClegg** [comment]
@DrJohnSeaman @celiapetty: So the requirement is to collect Age, at time of Study, have the software calculate the Year of Birth from that and store both?

Reporting should use the stored Age in the following reports/calculations:
- Population pyramid
- HH Member Characteristics (should include both Age and YoB)
- Calculate AE
- Calculate StoL (items may be age restricted)

to ensure that revisiting in an old Study and re-running the reports will still give the results as at the time of the Study.

@dbrownukk: Should these be logged as separate issues?

**Comment by dbrownukk** [comment]
Stored Age at time of survey is always used.

On template 
if age is filled in the age is used and YoB calculated
if age is empty and YoB is filled in then age is calculated.
if age and YoB are blank then raises an error on parse

deployed

**Comment by daiClegg** [comment]
That sounds like it has all the bases covered.

@DrJohnSeaman @celiapetty let us know if this is not acceptable

**Comment by daiClegg** [comment]
Instance:        EFD_HM
Module:          Household
Household:  10 

Tested first omitting both age & YoB -  parse fails as expected, but then i have to fix it in the spreadsheet.  Would be better to Parse, but fail Validation.

The calculation for YoB assumes the birthday has not yet happened in the current year.
It has to guess one way or another. What's the algorithm? Halfway through the year?

**Comment by dbrownukk** [comment]
Validate does not currently run through HH Member data. It is only validated on parse. 
Edit of HHM data, once parsed does apply validation rules.
YOB calc is (Study reference Year - Age)

**Comment by daiClegg** [comment]
**Tested Ok**
