### ISSUE TITLE
Report summary should contain the definition of the report spec used 

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#318]
The summary page includes the reports run and the HHs included.
But it should also include:

Household Inclusion rule                  Not Applicable
or
Household Inclusion rule                  <HH question prompt>        <HH question answer>
Number of Households included     <count of HHs incuded>
Specific Categories included           <comma delineated concatenation of Category names>
Specific Resource Types included   <comma delineated concatenation of RT names>
Specific Resources included            <comma delineated concatenation of RST names>
Quantiles                                            <1st quantile name>            <1st quantile %age>
                                                            <2nd quantile name>          <2nd quantile %age>
                                                            <3rd quantile name>           <3rd quantile %age>
 Reporting Currency                          <ISO code for reporting currency>

This additional data would allow better title and annotation of the various report visualisations.

**Comment by daiClegg** [comment]
I see the HH count, but if there are no constraints on resources or Inclusion Rule or Quantiles, those headers don't appear - they should appear with "N/A" as values.
That would be more helpful to the user, but also means that in the Visualisation Spreadsheet knows what rows which values are in to link them from elsewhere.

**Comment by daiClegg** [comment]
It makes the visualisation spreadsheet data links a lot easier if at least the start cell for any range is known.
Since there are now multiple variable length lists:

- Resources included - times 3
- Quantiles
- Included H

It would be helpful if they could either rin as horizontal series, with a fixed row,
or vertical series, in different columns.

**Comment by dbrownukk** [comment]
Moved the lists to start in a consistent cell across and down.

**Comment by daiClegg** [comment]
Column H of the Summary tab appears to be the HH questions but has extraneous values.
Looks like they are the %ages of the Quantiles in Column G that are not overwritten by HH questions?

Instance:     EFD_HM
Module:       Study
Study:          M2 Tutorial
Test Spec:   Test1

To reproduce, run reports for study above with test spec above.

**Comment by dbrownukk** [comment]
Correct, the Quantile % in Summary was missing an increment to the column position. Added exrta col++;

deployed

**Comment by daiClegg** [comment]
** Tested Ok **
