### ISSUE TITLE
Should get meaningful error message when creating duplicate Sites within LZ, from New Community

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#32]
There cannot be 2 Subdistricts with the same name within the same district within the same LivelihoodZone.

This constraint is missing from the design schema, but is required.

The Karamoja - Central Sorghum and Livestock LZ has such a duplication:

![sitesnotunique](https://user-images.githubusercontent.com/30879677/35047709-aa7004be-fb92-11e7-8fd5-b03baa71e891.jpeg)

I have now discovered how i should have specified that in [MySQL Workbench](https://stackoverflow.com/questions/11376413/creating-unique-constraint-on-multiple-columns-in-mysql-workbench-eer-diagram)

**Comment by dbrownukk** [comment]
Add constraint to Site class
@Table(name="Site", 
	uniqueConstraints=@UniqueConstraint(columnNames={"LZ","LocationDistrict","SubDistrict"}))

Checking how to manage client message from database constraint violation

**Comment by daiClegg** [comment]
David,

I appreciate all these issues means lots of mail notifications but it does make it easy to see what’s what and what i need to respond to - especially your “Testing" label. And of course it does give us an audit trail.
So i hope it’s not a big pain for you.


Do we need to have a conversation about milestones, deliverables & dates?  When we met you spoke abut a more detailed plan.
I don’t feel the need for minutiae, butsomemilestones would be good.


Celia and John are up for a review in February - haven; tworeked out all my commitments yet so i haven’t nailed a date.
Do you have Bristol days that week (5th Feb - 9th Feb)?


Cheers
dai

**Comment by dbrownukk** [comment]
Yep, need to get plan together and some milestones  - Github, Issues and 'For Testing' makes things easier, otherwise things het lost! No panic to Test, just gradually tackling the issues. We could do them all in one go over the phone. You can turn email alerts off I think.

Name the day in Feb and I will change things around if needed.

**Comment by daiClegg** [comment]
David,

I’m happy to get mail notifications, can always filter if they become a pain. 
And testing is so simple that it’s not a problem to respond case-by-case, if i’m at my desk.

I’ll get on with scheduling that review.

I think the milestones are:

Milestone 1:
Set up Project & LZ s; 
Define Communities and their Sites, plus  their Wealth Groups; 
Generate WG Interview spreadsheets
Milestone 2:

Load WG Interview Spreadsheets into existing projects

Milestone 3:

Produce Base set of reports from Project data

If you agree, I should write some more detailed descriptions of 2 & 3, since we’ve only discussed them qualitatively so far.
And if we can put rough target dates on them, that would be useful.


There will be more to do, for example:
John has now asked for Market Data to be collected - its in some of the spreadsheets, but he hadn’t requested it originally.
I want to get a bit imaginative with the analytics - some ideas, but nothing concrete yet.
And i’d like to identify some external data about crop yields and/or rainfall to load so we can do integrated reporting.

But that is outside the scope of what you have priced so far.

Am off to the Keys on Monday, so maybe a catchup call this week would be useful.



cheers
dai

**Comment by daiClegg** [comment]
This change is not in the deployed test instance 

See Sites module list view (LZ :TestZone1 9/1/18

**Comment by daiClegg** [comment]
.

**Comment by dbrownukk** [comment]
deploying to server via a script - exchanged 'unique' for 'index'
working now but still needs a better error message -  that is in another issue

**Comment by daiClegg** [comment]
Not fixed as deployed. I was able to add a duplicate district/subdistrict "Nakapiripirit/Nakala" to the Karamoja Project.

**Comment by daiClegg** [comment]
Steps to reproduce: Steps to reproduce:

1. In list view of Project module: Select "Karamoja - Central Sorghum and Livestock"  
     - displays as expected
2. In Community pane click New
    - pops up New Community, as expected
    BUT focus is in Interview frame, not, as expected, in Site frame
3. Click in Livelihood Zone of Site frame ad click "+"
   - pops up new site dialog, as expected.
4. select"Karamoja..." from LZ drop down. as expected. 
     (note it would be nice to default to the most recently used LZ in the project, cos normally that's 
       where the new site will be).
5. Enter Nakapiripirit/Cucu in the District/Sub-district fields. Click Create.
    - closes the pop-up as expected with the entered fields now displayed in the Site frame and focus 
       in the Interview frame, as expected.
6. Enter interview data as required. Click Save.
    - get "Community created successfully" pop up and list of communities displayed
       including the duplicate, **not** as expected

**Comment by dbrownukk** [comment]
Dai,

I still cannot get this unique constraint to fail. Checked the Reading server mysql database and the unique constraint on Site for LZ,LocationDistrict,SubDistrict is present - thus something else is at play here. I will continue to investigate.

However, the 'New' Community button screen from Project module does need some work. The Site restricted Lookup works from the Community module (cut down to valid Project/LZ sites as per model) but not from the Project/New Community screen. 

Investigating

**Comment by daiClegg** [comment]
So now i have managed to do the opposite;

Try the following steps and you trigger a constraint when there is no duplicate  - apparently.
(note i've used "Testissue36" throughout - it should have been "Testissue32" of course, but that ain't going to affect anything.



Add a new project (Testissue36)
Save
Add a new LZ (Testissue36)
Save
Add a New community
Click "+" (add) in Site frame.
Select project from dropdown (Testissue36)
Add District (testissue36)
Add Subdistrict (testissue36)
Add Interview details
Add participant details
Save.
 - creates successfully
 - returns to list view and displays newly created Community
Select newly created Community, click Remove Selected and confirm removal
 - works as expected.
 - Displays " Community deleted from database"
Repeat the creation of the Community (**with same values** for LZ, District & Subdistrict)
Save
 - displays:
"Impossible to execute Create action: org.hibernate.exception.ConstraintViolationException: could not execute statement"
 - **NOT** as expected, since the Remove appeared to work.

Sign out/Sign IN
Repeat
Same result ( i did not expect that!)


The previously added then deleted Community is still hanging around somewhere.

**Comment by dbrownukk** [comment]
Tested and confirmed - looks like the openxava cache holds the site info somewhere - will force a clear out on delete or change

**Comment by dbrownukk** [comment]
After a rework of the Look ups for Site and LZ within Project there is still a small issue with this that I have raised with the Forum

After Community Save, if you select the recently saved Community from the List you will get the wrong Detail or even a null community. 

However, if you reorder the Community List using any of the column headers and then select the detail you see the correct detail. Somewhere a Key is cleared. 

https://sourceforge.net/p/openxava/discussion/419690/thread/1266e842/

**Comment by dbrownukk** [comment]
Current fix is to remain in Detail view with fields populated - duplicate LZ,,district,subdistrict not allowed, though error message needs improving - covered in database error message enhancement#

Does this work for the moment, avoiding any 'corruption'..

**Comment by daiClegg** [comment]
Tested ok.
It confused me because when yuo remove a Community you are NOT deleting the Site, only the Community.
So the Site remainsin the database.
Hence adding a New Community with a New site with the same detailes will fail.
All correct, though there is no error message when ytuo try to create the same site twice from within Community.

Updating the subject line accordingly.

**Comment by dbrownukk** [comment]
Used i18n messages file to change unique constraint error message - also needed to redine dialect in persistence.xml to use Mysql 5 

Unique constrain message now reads "Sites must have uniqu District and Sub District within Livelihood Zone"

for reference - constrain name in Table definition in class must match name in database and name in i18n file

**Comment by daiClegg** [comment]
Tested as expected
