### ISSUE TITLE
Can add WG from another project to a Community

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#321]
Instance:    EFD_HM
Module:      Community
Project:      Test  Spreadsheet Gen exception 

To test i created this project, added an existing LZ (Z1)

1. In  WG panel, click Add.
Was offered every WG of every Community in the Database
1. Select one
Successfully added to the project

Should be no Add for WG in Community Module.

**Comment by dbrownukk** [comment]
removed Add Wealth Goup in Community OHEA

**Comment by daiClegg** [comment]
**Tested Ok**
