### ISSUE TITLE
Exception generating OHEA  template WGI spreadsheet 

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#322]
Instance: EFD_HM
Module:   Community

1. In list view, select any project, (i selected "UIPath Project")
Note the Project field is not populated.

1. Click Template Spreadsheet for in the WG panel.
Exception:

> Impossible to execute Template spreadsheet action: org.hibernate.hql.internal.ast.QuerySyntaxException: expecting EOF, found ')' near line 1, column 58 [from efd.model.ReferenceCode where ReferenceType = 'Area')]

Also in the drop down of projects only OIHM project appear - so it's not possible to select the correct project.

`

**Comment by dbrownukk** [comment]
JPQL query of referencecode had an extra closing bracket. Strange as is the same as in OHEA Prod -must be tighter checking in a java or X patch

fixed, deployed

**Comment by daiClegg** [comment]
**Tested Ok**
