### ISSUE TITLE
Unable to generate HH interview Spreadsheet

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#323]
Instance:    EFD_HM
Module:     Study

1. In List view, select any study
1. In detail view click Template Spreadsheet
Error Message:

> Template failed to be created - Null

I tried several existing Studies and also created a new one (TestSpreadsheetGenerate).

Same result.

**Comment by dbrownukk** [comment]
Seems to work for most Studies I tried, but not your new TestSpreadsheetGenerate.

M2 Tutorial Test definitely works. Investigating

**Comment by dbrownukk** [comment]
Site is empty. 
Should an empty site be allowed for the generation of template?

**Comment by daiClegg** [comment]
You're right - null site should not be allowed.
I cannot remember which other Studies i tried this on, apart from "Test Generate new Template" and "TestSpreadsheetGenerate", neither of which had Sites when i tested.
Both do now and generate ok.

But can the error message make it clear that null Site is what's making it fail, please?

**Comment by dbrownukk** [comment]
Allow save of Study. Site not mandatory but raise error message on gen of ss template

**Comment by dbrownukk** [comment]
Now checks for empty District - deployed

**Comment by daiClegg** [comment]
**Tested Ok**
