### ISSUE TITLE
Quantile apportioning not consistent

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#324]
Instance: EFD_HM
Study M2 Tutorial Test
Report Spec: test1

Run all reports.

In all reports except 227 & 228 the one included household is in the Poor Quantile (the others being empty).
But in 227 & 228 its in the Middle Quantile

Whilst it is clearly nonsense to report a single HH in Quantiles, the algorithm for apportioning HHs to Quantiles should be consistent for all reports.

**Comment by dbrownukk** [comment]
227 and 228 - calculation and apportionment was correct,. Output was to wrong quantile row.

Fixed. To be deployed

**Comment by daiClegg** [comment]
**Tested OK**
