### ISSUE TITLE
Status field for multiple resource types in Household Module is too small

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#326]
Instance:   EFD_HM
Module:     Household

In the multi-tab  resources pane of the HH module, the status field is wrongly sized on some (Crops through to  Inputs) but correctly sized on others (Assets)

Should be able to see the full Status

**Comment by daiClegg** [comment]
screenshot:

![image](https://user-images.githubusercontent.com/30879677/59932655-9549c100-943f-11e9-8a90-dbde469b74d0.png)

**Comment by dbrownukk** [comment]
This is a current OX feature. Overcome by making the field widths resizable, which kind of works. Certainly clear in validated RSTs

**Comment by daiClegg** [comment]
**Tested Ok**
