### ISSUE TITLE
Validation of Livestock product too strict

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#327]
Instance:     EFD_HM
Module:       Household
Study:          M2 Tutorial Test
Household: HH13

the uploaded spreadsheet includes 
- Livestock Type:       Chicken 
- LIvestock Product:  Eggs 
- Unit:                          unit

Parse fails to match this. I think this is because the database has the unit as Unit (init capped).
This is too strict; there is no ambiguity or genuine error.

![image](https://user-images.githubusercontent.com/30879677/59932997-6253fd00-9440-11e9-8e66-b37eae97bf75.png)

**Comment by dbrownukk** [comment]
Was much more than just units - the RST is a combination of 'Chicken '+'Eggs' which is now tested 

Units test for lowercase (entered unit) vs lowercase(rst unit)

**Comment by daiClegg** [comment]
**Tested Ok**
