### ISSUE TITLE
Reports dialog should prohibit explicit HH inclusion if there is a HH Inclusion Rule in the Report Spec

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#328]
Reporting currently allows the user to select HHs for explicit inclusion regardless of whether a HH Inclusion Rule is part of the Report Spec.
Reporting execution obeys the rule and ignores the explicit inclusions. This is the expected behaviour.

But the user could be confused or even deceived when they look at the report outputs since they will be based on a different set of HHs than they might have expected.

A better solution would be for the Reporting dialog to not allow explicit inclusion if an Inclusion Rule will be enforced at reporting runtime.
The visual cue might be:
1. Inclusion pane does not appear
But this might confuse the user, since they would not get any indication why the dialog appearance has changed and might think there is a bug.
1. The inclusion pane appears but is greyed out or other visual cue and is not editable
In this case it is pretty apparent that something has disabled explicit HH inclusion, but there is no indication why
1. The user gets an error message telling them they have a HH Inclusion Rule in force, if they click anywhere in the explicit HH Inclusion pane.
At least the user gets clear feedback, but they are invited to try something that is not valid.

Since none of these options is clearly the best, implementation simplicity should influence the choice of UI.

**Comment by daiClegg** [comment]
See also #329

**Comment by dbrownukk** [comment]
Try this

1. No report spec chosen and try to select a Household. Forced to select a report spec.
2. Select a report spec with no inclusion rule (using Category, RT, RST, Q&A) and you can select any of the Households
3. Chose a report spec with inclusion rule. Get a warning and cannot select any Hosuehold to include.

**Comment by daiClegg** [comment]
Tested as documented above, but if you do try to explicitly select Households you get an error for each selected HH :
>Impossible to execute H HA ction select action: It's required that the View represents a collection in order to call method isCollectionFromModel()

and if you go on to run the reports HHs explicitly included are still listed on the summary tab.

**Comment by dbrownukk** [comment]
Fixed, though still a small issue that I believe is an OX bug - for discussion with Javier..

If the Report Spec has rules that restrict to a set of HH then the selection of a HH in the dialog is disabled. 

If there is no rule then a HH can be selected from dialog. Note that a bug appears if you deselect the HH at this point. Cannot see how deselect is handled, possibly an OX bug as it loses current View context. But, not a show stopper..

deployed

**Comment by daiClegg** [comment]
** Tested OK **
