### ISSUE TITLE
Reporting always lists HHs explicitly listed on the Summary page,

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#329]
If a HH INclusion Rule is included in the Report Spec reporting correctly obeys it, regardless of whether HHs have been explicitly Included in the reporting dialog.

IN this case, the summary HH list should show those included by the rule.

See also Issue #328

**Comment by daiClegg** [comment]
**Cannot now reproduce**

 #328 has been fixed so this situation is prohibited from occurring

**Comment by daiClegg** [comment]
In testing #328 i found a way to get past the correction.
so this behaviour is still there.
see #328 for steps to reproduce.

**Comment by dbrownukk** [comment]
#328 should now be fixed
