### ISSUE TITLE
Question Prompt should be more than 50 characters

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#330]
Instance: EFD _HM
Module:   Study

1. Select or create any study
1. in the questions tab, click + for new question
1. enter "Are any household members unable to work through age or disability?" in the prompt
> question prompt is truncated at 50 characters

How long is a reasonable maximum for question prompts, bearing in mind that the interview spreadsheet will have to have a column of that width for all questions?

Current implementation is 50 characters

**Comment by daiClegg** [comment]
@celiapetty @DrJohnSeaman : Stella raised this in her testing and asked for your input

**Comment by celiapetty** [comment]
Ideally it should be possible to have short questions. But have I
understood this query correctly?

**Comment by daiClegg** [comment]
@celiapetty Stella wanted a longer prompt for questions.
The question above is a real one she wanted to use in her testing.

We have to have a limit, to size the column in the generated spreadsheet. 
And i'd have thought 50 was enough, but it's your (the domain experts') call.

**Comment by DrJohnSeaman** [comment]
Stella's question is ?76 characters and I cant see a way of shortening it. Excel shows the whole content of a cell if you click on it (in the entry box at the top). If so 100?

**Comment by daiClegg** [comment]
If we set the Prompt limit in the app to 100 characters & the cell size in the generated spreadsheet to be sufficient for 50 characters, is that ok?

**Comment by DrJohnSeaman** [comment]
I think so. Its a common problem with spreadsheets but it can always be read

**Comment by daiClegg** [comment]
OK. We'll go with this.

**Comment by dbrownukk** [comment]
Prompt is now 100 chars. 

Template spreadsheet now uses a wordwrap on prompts, which I think works and is clear.

**Comment by daiClegg** [comment]
**Tested Ok**

This is the result for the long-prompt question above:

![image](https://user-images.githubusercontent.com/30879677/60498021-c337cc80-9cad-11e9-9c0f-ceb6dbb790d8.png)

**Comment by celiapetty** [comment]
I think that question should read: 'are any adult household members unable
to work through age or disability? '
Otherwise, children may be added

**Comment by celiapetty** [comment]
..although I realise this is only a dummy question.

**Comment by daiClegg** [comment]
Yes, that's purely a methodological discussion.
Note that Topics exist just for this kind of issue - defining re-usable sets of questions once and copying them into a study.

I have created an issue for this  #335

**Comment by daiClegg** [comment]
@stellangoleka fixed this without further input from you  since everyone agreed with your suggestion
