### ISSUE TITLE
Should Study Name concatenate the reference year in the interview spreadsheet

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#331]
The OIHM HH Interview spreadsheet currently includes the reference year in the study name field.

- Is this correct?
- If not should they be in separate fields? 
- Or is it unnecessary to include the reference year in the HH Interview spreadsheet?

![image](https://user-images.githubusercontent.com/30879677/60346151-78b70700-99b2-11e9-9cc9-afa64632ce70.png)

**Comment by celiapetty** [comment]
That would avoid confusion in longitudinal studies. The date of data
collection also needs to be documented. Stella what are you views on where
this is best situated in the software?

**Comment by daiClegg** [comment]
Stella is in the process of creating her  Github ID and requesting access to the project.
I'll make sure she sees this when that's completed.

**Comment by DrJohnSeaman** [comment]
Sorry about the delay. The rererence year should apppear in a separate field and  ideally as a start dd/mm/yy and an end date dd/mm/yy. Both because (rarely) IHM is used for a part year.

**Comment by daiClegg** [comment]
@DrJohnSeaman, when we discussed the requirements i captured Reference Year as a Year.


Stella has now also raised this refinement.
She suggests it is actually a 12 month cycle from a start year and month.

The app currently has Study name & Reference Year as mandatory separate fields.
The spreadsheet doesn; thave reference year as a field; David added it as concatenation with the Study name, for exactly the use case Celia identified.

How about if in the App we capture Month as well as Year, with the prompt "Reference Year Start"
And add it to the Spreadsheet (mon yyyy) as a separate field with the same prompt.

**Comment by DrJohnSeaman** [comment]
That is a fair compromise - but is it the start of the month or the end? 'Reference year starts on 1st of ' mm/yy

**Comment by daiClegg** [comment]
Some further thoughts: 

1. Should we treat reference month & year the same in HEA and IHM. It seems to me we should.
2. @celiapetty :  you wrote:
>The date of data collection also needs to be documented.

We collect the interview date on each interview. The Study has a Start date. 
Are you talking about a 3rd date? Or do these 2 cover this requirement?

3. We collect the Interview date in the HH Interview spreadsheet.
We collect the Study Start date in the Study Setup.
Does the HH Interview Spreadsheet need to include it? Not sure what value it's adding there. Reference Year seems more relevant.

How about this as a revision to the HH Interview spreadsheet first tab:

![image](https://user-images.githubusercontent.com/30879677/60432558-7cd56580-9bfa-11e9-9cf8-4f96b629dda9.png)

**Comment by daiClegg** [comment]
@stellangoleka 
Added Stella to this as i will to all issues needing input from domain specialists, since she is the main user tester.

**Comment by stellangoleka** [comment]
My thought 

![OIHM Tab 1](https://user-images.githubusercontent.com/45176194/60688455-7a526480-9eb5-11e9-8fb0-b45dcf4fe1c8.png)

**Comment by stellangoleka** [comment]
I have highlighted my suggestions to the HH Interview spreadsheet first tab in blue: 

![Painted](https://user-images.githubusercontent.com/45176194/60688622-9f93a280-9eb6-11e9-9cd8-8c7acdedb784.jpg)

**Comment by daiClegg** [comment]
@stellangoleka , i made the changes above based on my discussion with @DrJohnSeaman & @celiapetty. You weren't connected then, so to save going round it all again, i'll summarise the conclusions we reached. If you want further changes, please can you discuss and resolve with J  & C (in this thread).

**District** - this appears to be usually the Study same, so it seems like duplication to include it in the spreadsheet.
**Village** - this is the Site filed in the current spreadsheet. we discussed what to call it since it may not be a village (e.g. urban or refugee camp). Site was the agreed compromise.
**Reference Year** John noted that month does not specify start end, so i used a specific date, and since the field is called Reference Year, the implication is that it is a year from then. Celia noted that although data collected might relate to a shorter period, the reference year is a full agricultural year
**HH ID** - this field is generated by the application to ensure uniqueness. It is not entered by the interviewer
**Study Start Date** there didn't seem to be any reason to add this to every spreadsheet, but are you thinking of a longitudinal study rteturning to the same site a year later?
**HH Name** - this is an additional, optional HH identifier that the interviewer can enter if required.

@celiapetty @DrJohnSeaman please pitch in to resolve this. And let me know when you three are in agreement.
Bear in mind every change costs and means we will lose something else later, so please constrain change requests to essential (must have) and high value (could have). It is very helpful if you classify them in that way for me. Thanks.

**Comment by DrJohnSeaman** [comment]
A few points. District often is but is not necessarily the study name. I would keep it

Reference year - Stella's suggestion is fine but it should be clear to the user e.g. 'Start date for Ref year dd/mm/yy'. 

HHID - a potential problem arises between the number allocated to a paper form (usually to keep some control over large numbers of interviews) and the number generated by the computer. If the computer generates another number it should be shown so that users can cross reference the two.

**Comment by celiapetty** [comment]
Just catching up on this. I agree with all the points John has made.


Celia

**Comment by daiClegg** [comment]
Attached proposed revision to HH INterview template spreadsheet INterview Details tab.

Note the generated HH Id is not available when the template is generated - the same template is used for all interviews. 
The Household Name is the interviewer's opportunity to ascribe their own identifier, which will then be x-referenced with the generated IDS on upload.


[HHInterviewSummaryTab.xlsx](https://github.com/dbrownukk/EFD_v2/files/3616972/HHInterviewSummaryTab.xlsx)

Ok?

**Comment by celiapetty** [comment]
Dai
Could you explain 'x referenced with the generated IDS on upload'?

Does this mean that the excel spreadsheet can include both a hhold name an
number eg '3 Smith'- both are useful during field work and follow up as
there may be several Smiths . Will it be possible  retrieve the individual
household spreadsheet (eg 3 Smith)  if this is needed for follow up?

C

**Comment by daiClegg** [comment]
The database will hold the Household Name ascribed by the interviewer and also the generated HHId - cross-referenced. 
This ensured there are no gaps nor duplicates in the HH Ids. which is what you asked for.
The reports are ordered by the generated HHId.

So if there is a HH with name 3 - Smith, that\s in the database record. 
You can see this in the Katakwi data Stella entered.
The names are also included in the report spreadsheet in the summary tab.

**Comment by daiClegg** [comment]
This has been superseded by #598 so closing as a duplicate
