### ISSUE TITLE
Cash Pay for Employment  validation in HH Interview S'Sheet is too strict

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#333]

**Comment by daiClegg** [comment]
The _Cash Pay:Amount per Unit of Work_ column on the  Employment tab in the HH Interview spreadsheet only allows a figure up to 1,000,000.
This is too limiting for some low-value currencies.
There is no need for an upper limit.

**Comment by dbrownukk** [comment]
added an extra 000 to upper limit. Used within POI code to check that this is a number. Would need a rewrite to do away with upper limit, and it is used a ot..

**Comment by daiClegg** [comment]
I suspected it would be a hassle to remove the limit. The new massively higher limit will be fine

**Tested Ok**
