### ISSUE TITLE
Status field for multiple resource types in WGI module is too small

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#337]
Instance:      EFD_HM
Application: OHEA
Module:        WGI

The same problem that is documented for POIHM in Issue #326 is apparent in WGI in OHEA as well.
It affects all the tabs from Crops to Wild Foods.

**Comment by dbrownukk** [comment]
reset resizeColumns=true in xava.properties.  This is application wide and is a compromise, but in general does give better column headings.

**Comment by daiClegg** [comment]
**Tested OK**
