### ISSUE TITLE
Household does not validate, but no error shown

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#340]
Instance:     EFD_HM
App:             OIHM
Module:       Household
Study:          M1 End2End Test
HH:               7

Status is Fully Parsed.
All Resources are status 'valid'.
But they all have 0 units produced or worked (apart from Inputs)
this is as in the spreadsheet attached.

In detail view click Validate
> no response.

HHH 3 has similar data, but 1 invalid resource - Validate runs, but correctly fails for that HH

**Comment by dbrownukk** [comment]
Validation was originally designed to just validate the RST.

Can we go through each field and work out what is valid and what should fail, rather than both of us on a discovery journey. Or did I miss a doc somewhere? I know it should be obvious what is valid/invalid but we know where that leads...

**Comment by daiClegg** [comment]
First draft column validation rules are in the attached:

[Validation rules.xlsx](https://github.com/dbrownukk/EFD_v2/files/3381184/Validation.rules.xlsx)

**Comment by dbrownukk** [comment]
completed validations based on validation rules xls above

yet to deploy

If pass testing then OHEA needs this.

**Comment by daiClegg** [comment]
Instance:    EFD_HM
App:            OIHM
Project:       Test #340
Study:         Test #340   
HH:              HH1



- Validation of numbers is done in the spreadsheet **Tested OK**
- Totals of %ages is only checked in the spreadsheet for Inputs tab - not the others. Should be consistent.
- Validation of totals of Units produced, sold, other use & consumed only validated in the app.  Fair enough, but no useful error message
- Validation of %age totals only done in app (except Inputs 0 see above). Fair enough, but no useful error message.
- Validation of %age totals sum is not done for Employment Work Locations
- Employment Food Payment Units Paid allows negative values 
- Employment Resource Type of Food not derived from uploaded Food Payment Food Type, but the is record validated 
- in the spreadsheet, the Validation tab should be hidden.

Other missing validation (not specced in the spreadsheet attached above cos i'm an incompetent): On a Food transfer Cash-related values should be zero and on a Cash transfer Food-related  values should be null or zero

**Comment by dbrownukk** [comment]
1.Totals of %ages is only checked in the spreadsheet for Inputs tab - not the others. Should be consistent.

Done - Deployed

2. Validation of totals of Units produced, sold, other use & consumed only validated in the app. Fair enough, but no useful error message

3. Validation of %age totals only done in app (except Inputs 0 see above). Fair enough, but no useful error message.

4. Validation of %age totals sum is not done for Employment Work Locations


5. Employment Food Payment Units Paid allows negative values

6.Employment Resource Type of Food not derived from uploaded Food Payment Food Type, but the is record validated
in the spreadsheet, the Validation tab should be hidden.

**Comment by daiClegg** [comment]
From above:

5. Employment Food Payment Units Paid allows negative values

     Which column is this on the Employment Tab? Must be missing something

On the employment tab of the uploaded spreadsheet the column "Food Pay:Units Paid / Work Unit" has the value -9. This is parsed into the " Food payment units paid work " filed on the Employment tab of the HH record.

It validates successfully implying that this person got paid 100 in cash and -9Kg of apples every time they babysat.

Leaving this in Test until i have tested the other cases.

**Comment by daiClegg** [comment]
Instance: EFD_HM
App: OIHM
Module: HH
Study: Test #340
HH: HH3

1. Reset Status to Uploaded
1. Click Parse INterview Spreadsheet
 - Warning "Problem parsing Employment worksheet"

This is an invalid record (1ive paymentin food & invalid sium of location %ages.
Need to do more investigation to pin down the problem.

**Comment by daiClegg** [comment]
All the other invalid data i included in the test spreadsheet are now caught in parse and highlighted with helpful messages.
Looks good modulo the 2 anomalies above i'm still investigating

Also need to test what has changed in the spreadsheet

**Comment by daiClegg** [comment]
No correct reaction to property change

Instance: EFD_HM
App: OIHM
Module: HH
Study: Test #340
HH: HH3 - HH7

The problem is that the Employment tab column 'Food  Pay:Units Paid / Work Unit' expects a unit of work. (Day, Week, Month, Year).
It should expect the number of units of the Food payment per unit of work .
If you enter an amount, the spreadsheet correctly accepts it, but Parse rejects the record - as noted yesterday.

HH3 - HH7 was me fixing one thing at a time in the Employment tab to see what was wrong. Needless to say it was the last test on my list.

This is linked to the other anomaly still outstanding. So there's a complicated thread of comments here. If you need a conversation to resolve, just ping me.

**Comment by dbrownukk** [comment]
Summary of what needs fixing - I believe:-

1. OIHM spreadsheet creation - Employment Tab, Food Pay Unit should have LOV of Day, Week, Month, Year
2. OIHM Spreadsheet creation - Emp Tab, Food Pay: UnitsPaid / Work Unit is a Positive Integer
3. OIHM spreadsheet parse - load the above two into correct fields and validate

Dai - before I fix is this correct? My only doubt is the Food Pay Unit being Day/Week/Month/Year

**Comment by daiClegg** [comment]
Comments inline above...

**Comment by dbrownukk** [comment]
Emp Tab, Food Pay: UnitsPaid / Work Unit is a Positive Integer - Change to Database, validations and parsers for both OIHM and OHEA. Note change from String to Double in class and database

deployed

**Comment by daiClegg** [comment]
Instance: EFD_HM
App: OIHM
Module: HH
Study: Test #340
HH: HH3

The Employment (Baby Sitting) payment is -ive  (paid -9kgs of Apples) but it parses as valid. Should be invalid because Food Payment Unit Paid should be a non-negative integer.


On the Crops, LS Products, Wild Foods & Transfers tabs, sold & other use  more than received, resulting in -ive amount consumed are correctly handled

On the LS sales tab, invalid sum of market percentages is handled correctly.

Just this one anomaly o/s i think.
Have i misled you on this ne?

**Comment by dbrownukk** [comment]
As per notes on #350

Validate routine is now called after the Parse of WGI and HH  (seems sensible to me).

Thus anything that is wrong in spreadsheet is picked up by the standard Validate routine. 

Fixed the Employment negative amount  (-9 kgs) above

**Comment by daiClegg** [comment]
**Tested OK**

the -ive payment was handled correctly in Parse, which was the remaining outstanding anomaly.

Still need to test the wider Parse/Validate changes, but that is #350 .
