### ISSUE TITLE
Report run appears to hang

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#341]
Instance:   EFD_HM
App:           OIHM
Module:     Study
Study:        Katakwi- NIMFRU Test

This study has 20 HHs with real data, all validated.

In detail view, click reports
Select Report Spec (i  tested 'All Reports' and also '226 Only')
Click Run
> Processing icon appears  & page loading icon, but report does not complete.

I left it at least 2 minutes for just the one report.
Testing on M2Tutorial Test Study (about 12 - 15 households) it takes about 10 seconds for All Reports.

**Comment by daiClegg** [comment]
Because other Study tested ran to completion ok, i am guessing this is not connected to #339

**Comment by dbrownukk** [comment]
missing controller in controllers.xml

fixed

deployed

**Comment by daiClegg** [comment]
**Tested OK**

took about 3 seconds to run a 20 HH study report for all reports.
