### ISSUE TITLE
OIHM Quantile Reporting producing dubious results

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#342]
Instance:         EFD_HM
App:                 OIHM
Module:           Study
Study:              Katakwi- NIMFRU Test   
Report Spec:  Test Quantiles & All Reports

1. In detail view of 'Katakwi- NIMFRU Test' study, click Reports menu item
1. In Report Spec dropdown select 'All Reports' report spec
1. Click Run
1. In Report Spec dropdown select 'Test Quantiles' report spec
1. Click Run
1. Open the 2 downloaded report files
1. View 'Disposable Income' tab in "All Reports" report file 
> Note DI values and range
8. View 'Disposable Income' tab in "Test Quantiles" report file
> Note 2 of the 3 values are 0

Other reports are similarly unexpected.
The 'Test Quantiles report spec appears to have 3 valid quantiles.

**Comment by stellangoleka** [comment]
Dai, I wanted to add salt under the standard of living  Element. I don't have an option for food purchase where I can add salt.  
![image](https://user-images.githubusercontent.com/45176194/61295413-468e0d80-a7d8-11e9-80af-e561e39659f2.png)

**Comment by stellangoleka** [comment]
Celia and John. There are a number of crops and livestock product with no Kcal value. I wonder who should enter the Kcal values. Should I go-ahead to enter the numbers or one of the experts is assigned to do this? 
![image](https://user-images.githubusercontent.com/45176194/61295667-e0ee5100-a7d8-11e9-8fbb-26376adc57cd.png)

**Comment by stellangoleka** [comment]
Dai, Is it necessary to have multiple messages of 'Validation Complete'. Will be possible to have only one message? 
![image](https://user-images.githubusercontent.com/45176194/61295880-4d695000-a7d9-11e9-81d9-afb43960fa4f.png)

**Comment by stellangoleka** [comment]
Similarly, only one item was invalid but the message came in a mulitiple way. 

![image](https://user-images.githubusercontent.com/45176194/61296168-e7c99380-a7d9-11e9-9248-9e2d3986bda7.png)

**Comment by dbrownukk** [comment]
Seem to have two issues in under this banner. 

I will raise new Issue to reduce number of alert warnings. They were helpful during testing. 

The original issue is now fixed. Cannot rely on sql to return dat in correct order! Now quatiles are sorted before processing starts...

deployed.

**Comment by daiClegg** [comment]
** Tested OK **
