### ISSUE TITLE
Adding Food purchase under the standard of living Element

### ISSUE THREAD

**Issue by stellangoleka** [dbrownukk/EFD_v2#344]
I wanted to add salt under the standard of living Element. I don't have an option for food purchase where I can add salt.
![Uploading image.png…]()

**Comment by daiClegg** [comment]
@stellangoleka  Please add steps to reproduce 
I think i know what you're talking about, but someone else might not and it is common courtesy when logging issues to provide steps to reproduce so an engineer can quickly see exactly what your problem is.
I gave you an example of a set of steps to reproduce. Thanks.

**Comment by daiClegg** [comment]
@stellangoleka did you miss this?

**Comment by stellangoleka** [comment]
No, I will. Thanks

**Comment by stellangoleka** [comment]
EFD_HM
App: OIHM
Module: Study
Study: Katakwi- NIMFRU Test
Site: Standard of Living Element  
In detail view of 'Katakwi- NIMFRU Test' study, under 'Site' click Standard of Living Element  
Below ‘Site’ click New to enable ‘Create a new entity - Standard Of Living Element’
In Resource Sub Type dropdown search ‘Food Purchase’ to add food costs eg salt, sugar, etc
The ‘Resource Sub Type’ appears to have no Food Purchase

**Comment by daiClegg** [comment]
Thanks Stella.

This is the question asked in #220 on 25th February.
I didn't get an answer, so StoL items are more restricted than maybe they should be.

Can you confirm, in consultation with @DrJohnSeaman & @celiapetty  what the full set of Resource Types that can be StoL items please?

It is currently only Non-Food Purchases. You want to add 'Food Purchases'.
Might there be any others, e.g. 'Other Tradable Goods'

**Comment by celiapetty** [comment]
SOLT items are defined at each site in consultation with poorer households.
The list will always include basics such as clothes, soap and primary
school costs and will usually include items such as fuel and matches. In
some places it's necessary to add items such as transport costs, rent,
water charges etc. Although most 'standard of living'  items  will be non
food,  in some places, 'social inclusion' requires households should be
able to offer coffee (or tea, or betel).

**Comment by stellangoleka** [comment]
It's only 'Food Purchases' we should add.  'Tradable Goods' are not part of 'social inclusion'

**Comment by celiapetty** [comment]
Just to be clear only those very few 'food purchases' (such as tea or
coffee required in some places for reciprocal hospitality) would be
included in the SOLT. An example of a tradable good that might be included
in the SOLT is a cooking utensil.
If a call is needed for clarification, please let me know and I'll
coordinate with John and Stella.

**Comment by stellangoleka** [comment]
@daiClegg Please add both 'Food Purchases' and 'Other Tradable Goods'

**Comment by daiClegg** [comment]
@celiapetty I don't need a call, i just need a decision.  @stellangoleka has made two different requests in the last day, so i need to know that you're happy with the latter and that there won't be another change requested. 
Tricky stuff this software; it does demand nailing all the tiny details. And every time we have to change something, something else drops off, further down the line. Which is why i put the emphasis i do on clarity up front.

**Comment by celiapetty** [comment]
It sounds as if details was missing in the  SOLT specification and there still may not be absolute clarity. Apologies for this-I realise there is a cost. I've also been reviewing O-IHM Standard of Living Element, and just want to cross check age ranges etc can be logged here. I haven't been testing so am not entirely clear how this works-will request a tutorial later if needed.
For information, this is a description of the way the current  version of open-IHM is configured  to record Standard of Living data-hopefully it’s useful for reference.
Level: Household or individual-this corresponds with the set up in O-IHM
There is a drop down of **‘Household’** level items eg fuel, soap, coffee, rent, water charges. User can add new items /resource types

If the item relates to an **individual** the user selects one of 5  options: Child female; child male; adult female; adult male or 'Both' -then selects the relevant age range (see below)
Child female:
Select item from drop down eg clothes : user then selects the age range for this item eg 3-14yrs (In this community there is zero clothing cost for girls under 3). If there is a  female child in the household under 3 years no clothing cost will be assigned . And all females over 14 years will be assigned the adult female cost of clothes
Child male: Select from drop down eg clothes: user selects age range for this standard of living item -as above 
Child female: Select item eg ‘Primary school costs’ “ user selects age range for child female primary school costs eg  5-14 years
Child male: As above. Select item Primary school costs . These . may be different for boys and girls eg school uniforms may cost more for girls. 
Adult female: Select item eg ‘lotion’: user selects age range eg 14-100 years
Adult male: Select item eg ‘clothes; User selects age range eg 15-100 years.
(Note : there is also an option to select ‘Both’ if the item relates to males and females-the age range would also need to be added.

[Screenshot OpenIHM SOLT.pdf](https://github.com/dbrownukk/EFD_v2/files/3437188/Screenshot.OpenIHM.SOLT.pdf)
[SOLT output example, Katakwi.xlsx](https://github.com/dbrownukk/EFD_v2/files/3437192/SOLT.output.example.Katakwi.xlsx)

A screenshot of the current set up is attached for information, plus an examples of output, taken from the recent Katakwi study

**Comment by daiClegg** [comment]
Since, in OpenIHM,  you have to input the age range anyway, what is the point of specifying 'Adult' or  'Child' first?
OIHM doesn't make any blanket distinction between Child & Adult - it just allows you to input the age range - and Gender for any HH member-specific StoL item. I'm not seeing any restriction. Have you tried it in OIHM? @stellangoleka didn't raise any issue when she specified the SolT for Katakwi in her testing, apart from the issue, discussed above.

**Comment by celiapetty** [comment]
Dropping 'adult' and 'child' is an improvement-thanks for this.

**Comment by daiClegg** [comment]
So, having resolved the discursion into age & gender, back to the types of things that can be a StoL item.

Can you confirm that it can be any of  

- Non-Food Purchases, 
- Food Purchases
- Other Tradable Goods 
- and nothing else?

**Comment by celiapetty** [comment]
That would work if  items such as rent, water charges and mandatory
universal taxes (eg a poll tax)  are classified under 'non food purchases'.

**Comment by stellangoleka** [comment]
In my opinion, I can confirm that nothing else, but those three.

**Comment by daiClegg** [comment]
@David this fell down the back of the sofa (my fault)

but Celia & Stella have confirmed that the LoV for Standard of LIving items should include 
(as noted above but repeated here):

- Non-Food Purchases,
- Food Purchases
- Other Tradable Goods

currently only Non-Food Purchased are allowed.

**Comment by dbrownukk** [comment]
fixed. 

Note that type is defined in singular not plural

Non-Food Purchase
Food Purchase
Other Tradable Good

Purely for my memory...

deployed

**Comment by daiClegg** [comment]
**Tested OK**
