### ISSUE TITLE
Adding Kcals

### ISSUE THREAD

**Issue by stellangoleka** [dbrownukk/EFD_v2#345]
Celia and John. There are a number of crops and livestock product with no Kcal value. I wonder who should enter the Kcal values. Should I go-ahead to enter the numbers or one of the experts is assigned to do this?
![image](https://user-images.githubusercontent.com/45176194/61304829-10598980-a7ea-11e9-98df-2dcc06b56772.png)

**Comment by daiClegg** [comment]
Please search for a topic in open issue before logging a new issue.
This is a duplicate of the issue i mentioned - #334
