### ISSUE TITLE
Edit and Addition of resource Subtypes is allowed from OIHM Study Module

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#347]
Instance:     EFD_HM
App:             OIHM
Module:       Study

1. For any study invoke detail view.
1. Click on Standard of Living Element or Default Diet Item
1. Click on New
> Resource Sub Type field has Add & Edit operators. 

It should not be possible to add new resource subtypes here, because that would be available to field operatives who should not have that capability. The importance of getting the Kcal value right means adding Resource Sub-Types should only be done by more senior people.

**Comment by dbrownukk** [comment]
added @NoCreate to RST in StdofLiving and Default Diet Item mods

**Comment by daiClegg** [comment]
Same test, can still see and use the edit icon.

I realise i did not state the requirement properly last time. 
The user should not be able to edit the RST from here either.

**Comment by dbrownukk** [comment]
added @NoModify to each RST

**Comment by daiClegg** [comment]
** Tested Ok **
