### ISSUE TITLE
Apparently valid Crops data record does not parse.

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#348]
Instance:      EFD_HM
App:              OHEA
Module:        WGI
Project:         General Test Project
LZ:                TestZone1 
District:         OtherTestDistrict
Community:   OtherTestSubDistrict
WG:                Poor

1. In detail view, click Parse;
> Parse status message: " Problem parsing Crops worksheet - Percent Trade Market 3"
> No Crop data records created
2. Open the attached spreadsheet
> In the Crops tab note 2 recordes with no data in the Market columns

**Comment by dbrownukk** [comment]
localUnit NPE when checking for localUnit in Crop RST and LZ

deployed

**Comment by daiClegg** [comment]
**Tested Ok**
