### ISSUE TITLE
Currency is defined twice

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#349]
Currency appears within Entity Country and as Name value within ResourceType (Cash).

 Am sure will cause issues somewhere along the journey.

Definitely needed in ResourceSubType. Perhaps could be a lookup when a country is created so that Currency only appears in RST under Cash.

**Comment by daiClegg** [comment]
Agree; Currency is a lookup/validate for  Cash Assets; should also be for Country.
My error initially, since i was assuming currency & country are 1-to-1 (not so, e.g.  Euro).
And even if it were so it's more consistent to move it into the reference data.

**Comment by daiClegg** [comment]
The cost of rationalising the use of Curencyis not negligible.
The benefit is very little since Countries and Currencies are defined only once and are unlikely to be changed subsequently.

So let's live with this as it is.
