### ISSUE TITLE
Sort order for list view in Site module

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#35]
Not sure what the sort order is, but it should be SubDistrict, within District within LivelihoodZone

**Comment by dbrownukk** [comment]
@Tab defines the List properties - you can add a default order by - you can still change in runtime
@Tab ( editors ="List, Cards", rowStyles=@RowStyle(style="row-highlight", property="type", value="steady")
,properties="livelihoodZone.lzname,locationdistrict,subdistrict,gpslocation", 
defaultOrder="${livelihoodZone.lzname} desc,${locationdistrict} desc,${subdistrict} desc")

**Comment by daiClegg** [comment]
It would have been a bit smarter if i had specified **ascending** alphabetic sort order...

Default appears to be _descending_ for each of LZ, District & SubDistrict.
Can that be _ascending_ please? Still sub, within district, within LZ.

**Comment by daiClegg** [comment]
Tested ok.
