### ISSUE TITLE
Standard of Living calculation and Output

### ISSUE THREAD

**Issue by stellangoleka** [dbrownukk/EFD_v2#351]
A standard of living threshold is calculated as the cost of a basket of goods, this includes the cost of clothing, soap, basic fees, school costs and other. 
These are usually universally used with a minimum level of dignity in the location concerned. These costs are allocated to each household individually e.g. school costs only apply to households with school age children; fuel costs are calculated per household, clothes costs are calculated per individual. 
Households that cannot afford the full set of items are described as being below the standard of living threshold.
The IHM software described a household being below the standard of living threshold if its DI is below its Standard of Living Requirement cost. Household will be below SOLT if it’s DI < Standard of Living Requirement cost.
Or
Example from two different HHs, ‘HH1 and HH2’ using the formula
 ‘If Disposable Income - Standard of Living Requirement = +   'the HH is Above STOL'
 HH1’ above the Food Poverty line with DI = 4000 and Standard of Living Requirement cost = 2000
 Using the formula. The calculation will be
4000-2000=2000
 HH2’ below the Food Poverty line with DI = -4000 and Standard of Living Requirement cost = 2000
Using the formula. The calculation will be
-4000-2000= -6000.
i.e 
If Disposable Income minus Standard of Living Requirement is negative then the software should automatically show this household under Household below standard of living

Attached is an example of OpenIHM output showing HH below and above SOLT
[OpenIHM Standard of Living output.xlsx](https://github.com/dbrownukk/EFD_v2/files/3430557/OpenIHM.Standard.of.Living.output.xlsx)

**Comment by DrJohnSeaman** [comment]
Stella, some minor adjustments

A standard of living threshold is calculated as the cost of a basket of goods, this includes the cost of clothing, soap, basic fees, school costs and other items
The basket of goods is usually selected  as that which ensures 'social inclusion'. 
These costs are allocated to each household individually e.g. school costs only apply to households with school age children; fuel costs are calculated per household, clothes costs are calculated per individual.
Households that cannot afford the full set of items are described as being below the standard of living threshold.
The IHM software described a household being below the standard of living threshold if its DI is below its Standard of Living Requirement cost. Household will be below SOLT if it’s DI < Standard of Living Requirement cost.
Or
Example from two different HHs, ‘HH1 and HH2’ using the formula
‘If Disposable Income - Standard of Living Cost = + 'the HH is Above STOL'
HH1’ above the Food Poverty line with DI = 4000 and Standard of Living Requirement cost = 2000
Using the formula. The calculation will be
4000-2000=2000
HH2’ below the Food Poverty line with DI = -4000 and Standard of Living Requirement cost = 2000
Using the formula. The calculation will be
-4000-2000= -6000.
i.e
If Disposable Income minus Standard of Living Requirement is negative then the software should automatically show this household under Household below standard of living

Attached is an example of OpenIHM output showing HH below and above SOLT
OpenIHM Standard of Living output.xlsx

**Comment by daiClegg** [comment]
Issue #224 describes the reporting of StoL.
Issue #220 includes a description (around 20th February) of how defining StoL.

Is there an issue with the implementation? 
Or is this just clarification of the meaning and use of StoL?

**Comment by celiapetty** [comment]
The implementation at this point  calculates standard of living costs per
household. The full implementation requires a chart showing households
above and below the SOLT - formula described in this thread.

**Comment by daiClegg** [comment]
> The implementation at this point  calculates standard of living costs per
household.

why do you say this? 
The current implementation has a chart comparing DI & DI with StoL on a per HH basis.
@stellangoleka is there an issue with the DI with StoL visualisation?

**Comment by stellangoleka** [comment]
If it was agreed that 

> report should include SOLT & DI for each HH, or quantile, in ascending order of DI

and 

> Standard best practice shows negative and positive DI - SOLT in different colours in the chart.
> The data is arranged in two columns - one for the negatives and one for the positives, to make that easier for the user.
> 
> Reporting the data in this format is not the requirement.
> Making it easy for the user to create the chart from the raw data is.

Then Visualisation charts analysis are very great. 

Then the issue is, in addition to these analyses, we may need to consider maintaining the charts we were getting from OpenIHM, that is: 
The OpenIHM-SOLT output shows HH below and above SOLT in different columns in ascending order of DI/AE and the analysis shows HH below and above SOLT in different colors in ascending order of DI/AE in the chart which is not the case with the visualization charts.

**Comment by daiClegg** [comment]
Have you tested with a HH that has -ive DI with StoL? 
In my testing, i see exactly what the old OpenIHM chart shows - different coloured negative column 
Can you give me steps to reproduce the incorrect output please so i can debug it.
Thanks.

**Comment by stellangoleka** [comment]
I tested with a HH that has -ive DI with StoL. Do you mind attaching the
results you are getting. My understanding is that we have figures in
different columns but not in ascending order of DI/AE in both columns
before deducting the SOLT in each HH.

Ideally the first column displays the DI/A for only HH below the STOL the
second column displays the DI/A for only HH above the STOL. In this case if
the HH is below the SOLT  its DI/AE will not appear in the second column a
zero will show up in the second column for this particular HH and vis-a-vis.

This does not mean that the OIHM SOLT output is wrong. That one should be
maintained. The one we are discussing is an additional analysis we think it
has been important for stakeholders and users to understand HH above and
below the SOLT in ascending order of DI/AE.

**Comment by daiClegg** [comment]
Is the issue here about sort order of the reports,  not visualisation of -ive values?

The DI per AE & DI per AE with StoL reports do **not** sort by DI per AE; they sort by DI.
This was the original request - all reports to display in order of ascending DI.

Are you saying that the reports that show DI per AE, with and without StoL, are to be sorted by DI per AE? If so please change the title of the issue accordingly and write up what is required here.

If there is also an issue about the display of -ive DI with StoL?
If so,  that's a separate issue.  Can you log that as a separate issue with steps to reproduce please?

**Comment by celiapetty** [comment]
The original request should have read 'All reports to to show DI/AE in ascending order'. This  was our error. In the visualisation of SOLT, households below the SOLT should be identified in a different colour. Note that researchers may wish to see each household's Standard of Living costs-will this be available in an excel spreadsheet/data dump?

**Comment by stellangoleka** [comment]
-In the visualization of SOLT, households below the SOLT are identified in
a different colour.  This was my error, I focused on the excel spreadsheet.

-Sorting reports by DI per AE or by DI is another issue. Reports sorted by
DI looks interesting, but we can consider also sorting by DI per AE. This
can also give a great comparison of the two and contexts for development
planning.
