### ISSUE TITLE
OIHM Study Must have an associated LZ

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#352]
Just as an OHEA Project must have a LZ, this is a requirement for OIHM - which is not the case in the current implementation, which allows Sites to be in LZs but also supports a Site not in an LZ.

I see this as an opportunity to homogenise OHEA & OIHM processing - by insisting an OIHM Study is in a Project.
Then we use the same Project Module for both Apps, and simplify the Study module/data structure.
The Project then defines the locality (the LZ & country). It can also define the alternative currency & exchange rate, which currently has to be in Study for the occasions when the Study has no Project.

The lifecycle for OHEA is...
1. Create project & add LZ (Project module) 
1. Define Sites, selecting the Project to define the locality (Communities Module)
1. Define Characteristic Resources (Communities Module)
 
OIHM could have 
1. Create project & add LZ (Project module) 
1. Define Site, selecting the Project to define the locality (Study Module)
1. Define Characteristic Resources (Study Module)
1. Define other properties - Diet, etc (Study module)

**Comment by daiClegg** [comment]
I think the advantages of this approach are:

- Simpler to learn and less complex to use.
- Less code to maintain?

Disadvantage might be:
 -  more work to implement than simply patching up the existing Study Module.
Although actually, it might just be a change to the lifecycle more than to the code.

**Comment by dbrownukk** [comment]
to be implemented as per issue heading

**Comment by dbrownukk** [comment]
removed Country from Site and Site form Country 
removed usages

**Comment by daiClegg** [comment]
**Tested OK** from Study Create (modulo discussion of #357)

Other test components still o/s

**Comment by daiClegg** [comment]
Instance:   EFD_HM
App:  OIHM
Module: Site

1. In list view, click New
> in resulting Site create dialog, LZ is choose only - no create
2. Click torch icon to select LZ
3. In LZ list click Choose on any LZ
> ERROR: Impossible to execute Choose action: null

It appears to be impossible to create a site in the Site module.
That might be reasonable since sites are normally created in Study or Community module.
In which case it should not be visible to any user except Admin.

**Comment by daiClegg** [comment]
Tested Site  create & select from Community & Study **Tested OK**

Only the anomaly above outstanding

**Comment by daiClegg** [comment]
Problem is now that the first step in OIHM  & OHEA is to create a Project.
But OX appears to only allow any module to be in one folder.
So Project can't be in OIHM Core & OHEA Core, but really it is a core module for both, essential to the workflow of the Project/Study.

- The ideal resolution of this would be to have it in both Core folders, but i couldn't find a way to do that. 
- Failing that we need to be able to create a new project from within the Study module. The Project module can then be in OHEA Core, and since most OIHM Projects only have one Study (unlike OHEA projects with multiple Communities) it's a not unnatural workflow.
- Failing that Project module must be in the HM Common Folder, and that's not an ideal workflow for either App.

to be discussed.

**Comment by dbrownukk** [comment]
- confirm that a module can only exist in one folder

- Can now create a new Project from Study

**Comment by daiClegg** [comment]
Instance: EFD_HM
App: OIHM
Module: Study

1. In Study List view, click New
1. Enter Study name
1. In Project Name field click + to create new project.
1.  in Project create pop-up dialog, enter Project name & Start Date
1. In Livelihood Zone lock, click Add to add a LZ to the project 
 - ERROR:  Impossible to execute Add action: null
6.  Click Create to create Project wth no LZ
 - ERROR  - see screenshot:
![image](https://user-images.githubusercontent.com/30879677/64544502-0736f580-d31f-11e9-92ed-6a17fec58285.png)
7. Click x (top right) to close popup
8. In Study Create view, enter Reference year
9. Click Save to create study - successfully

Can now successfully edit the Project to add an LZ, and then add a site.

**Comment by dbrownukk** [comment]
Removed special (livelihoodzone.add) function from Project module - this was in due to an earlier OX bug, which appears fixed. 

As you add an LZ to a Project the Project is saved, but not the Study. You then need to save the Study. This is now all default OX behaviour. 

Note that New Study, New Project, New LZ sequence is not permitted without creating (saving) project. Again, is default OX behaviour.  New Study, New Project, Add LZ is allowed. Slightly different but do not want to code around this. 

deployed

**Comment by daiClegg** [comment]
**Tested OK**
