### ISSUE TITLE
Projects can have multiple parallel studies

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#353]
Having consulted with partner user of IHM SHA, it appears that multi-site studies are part of their standard practice. @celiapetty confirms these should be set up as multiple Studies in 1 project.
In a separate conversation, we established that all Studies are in a LZ.

This indicates that the OHEA stricture of Project made up of Communities, each at a Site in a LZ, should be mirrored in OIHM for Projects made up of Studies, each at a site in a LZ.

The commonality should be an improvement in usability and consistency, so it seems lie a positive thing.

But it raises other issues that i want to document before i forget them.
would the same StoL, default diet, questions, coping strategy apply to both?
Always? Sometimes? Yes but with some changes?

Would all the studies be reported together? modelled together? 

These need to be clarified and then a response formulated to each potential change.
Copy Study might provide a short cut for some of these requirements.
And it might be all we can afford to do in current budget.

**Comment by celiapetty** [comment]
Thank you for raising the questions: 'Should the same StoL, default diet,
questions, coping strategy apply to both?
Always? Sometimes? Yes but with some changes? '
 The answer is 'often but there may sometimes be some differences.' This
will depend mainly on the size of the LZ and amount of variation within it.
Typically, SHA and other NGOs will be working across a fairly large
population, and will be doing in-depth studies in sites chosen either
randomly or purposively (depending often on donor requirements) to
demonstrate impact/any changes in variables (eg disposable income) they are
required to monitor.
For the type of study Simon is doing with SHA, I would expect the studies
would need to be written up in a common report and modelled together.
I agree that 'Copy Study' could provide a shortcut for some of the
requirements.

**Comment by daiClegg** [comment]
This is now implemented, with Studies being independent even in the same Project wrt Diet, StoL  & Coping Strategy.

Joint modeling of Studies in a project will be discussed as part of the Modelling requirement
