### ISSUE TITLE
OIHM All Reports not producing results

### ISSUE THREAD

**Issue by stellangoleka** [dbrownukk/EFD_v2#354]
Instance: EFD_HM
App: OIHM
Module: Study
Study: Katakwi- NIMFRU Test
Report Spec: All Reports

In detail view of 'Katakwi- NIMFRU Test' study, click Reports menu item
In Report Spec dropdown select 'All Reports' report spec
Click Run
In Report Spec dropdown select 'All Reports' 
Click Run

The 'All Reports' report spec appears to run with error message 'Impossible to execute Run action: could not extract ResultSet.'

There is no downloaded report file produced.

**Comment by dbrownukk** [comment]
household_assetcash missing exchangeRate in database definition

fixed in wealthgroup interview assetcash but not in household assetcash 

deployed

**Comment by daiClegg** [comment]
**Tested OK**

@stella i was able to follow your precise steps-to-reproduce and it now works fine, so i closed the bug.
