### ISSUE TITLE
Unable to generate OIHM HH Interview template spreadsheet 

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#355]
Instance:  EFD_HM
App:          OIHM
Module:     Study

Study:        Currency Test B

In  Study detail view, click 'Template Spreadsheet' menu option

> ERROR: Impossible to execute Template spreadsheet action: Invalid column index (256). Allowable column range for BIFF8 is (0..255) or ('A'..'IV')

**Comment by daiClegg** [comment]
This error replicates in other studies tested (including 'Currency Test A', 'A new Study', 'A Study')

However, for 'Chileka Project' a different error message is delivered:

> Template failed to be created 0

'further test of topic copy' study also gives this alternative error

**Comment by dbrownukk** [comment]
cannot reproduce in development copy - error is saying that spreadsheet generation limit is exceeded, but suspect this is not the case.

Need to export from idaps onto local dev machine and compare databases

**Comment by dbrownukk** [comment]
The Category/RT/RST have been populated with more data. The spreadsheet validation is on a validation Tab with cells proving the list of values. The spreadsheet creation library from apache, in the version I am using, has a limit of 256 columns. The CAT/RT/RST is now size 360. 

However, this LOV is not used..   temp fix, as this will need to be addressed if any of the RSTs reach beyond 256 records, but this would not make the spreadsheet drop downs usable.

**Comment by dbrownukk** [comment]
Fixed by putting a limit of 256 on the InputResource LOV

Not ideal but the change to .xlxs from .xls generation will need a lot of changes. OX defaults to creating .xls, thus that was used....

**Comment by daiClegg** [comment]
Initial problem **Tested Ok**

However the second error message, 

> Template failed to be created 0

is observed in Chileka Project, and others,  for the same action and as noted above, still remains.

**Comment by dbrownukk** [comment]
Missed that - one bug per issue...

Symtoms different for Chileka Project - is missing a Site - need to add check to ensure Site exists within Study before running Spreadsheet gen

**Comment by daiClegg** [comment]
Sorry, i should not have presumed the same bug was generating different error messages in different Studies.

**Tested OK**
