### ISSUE TITLE
Alternative Currency & Exchange Rate are unnecessarily duplicated on Study & Project

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#356]
OHEA needs Alt Currency & Exch Rate on Project. 
Initially, a Project context was not deemed necessary for OIHM.
It is now. So we don't need these 2 fields in both places.

Action:
- remove the fields from Study
- change any code that references them in Study to use Project instead

**Comment by dbrownukk** [comment]
removed from Study class and from database

Still need to work on parse of assetcash as this change impacts the assetcash parse routine.

**Comment by daiClegg** [comment]
**Tested OK**

Need to test whether alternative currency is correctly processed, but that's not in the scope of this issue,
