### ISSUE TITLE
Apparently invalid record successfully validated 

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#358]
Instance: EFD_HM
App: OIHM
Module: Household
Study: Katakwi- NIMFRU Test 2018
HH: 5 - Ocepa Patrick

In Detail view of this household navigate to Crops tab
Note Mango Crop Type record has no Name, but the record and the HH are valid.

I do not know how this occurred and i'm not going to touch it in case i destroy the evidence.
Will try to reproduce in a new record

**Comment by daiClegg** [comment]
I notice that there are 2 base RSTs called Mango.
One is under Crops and the other is under Trees.

Both are offered as synonyms and one of them is used by Mangoes - the record in this case.
Before i change the 'Mango' under Trees to be called 'Mango Tree' and raise a data issue for always adding 'Tree' - to make such distinctions, i'll wait for the investigation of the issue.

**Comment by daiClegg** [comment]
Did a bit more digging Updated my notes in the DICalc spreadsheet
[DICalc.xlsx](https://github.com/dbrownukk/EFD_v2/files/3586721/DICalc.xlsx)

Looks like Synonyms are the problem, plus dodgy data (as raised in Issue

**Comment by dbrownukk** [comment]
Validate (unlike the parse) did not check for null RST for any of the assets.. fixing

**Comment by daiClegg** [comment]
I was able to set the HH to editable, correct the data and re-validate successfully.
Cannot reproduce creating a record with a blank RST, soclosing the issue
