### ISSUE TITLE
RST Green Grams KCal value is incorrect

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#359]
@celiapetty noted in issue #310:

Green grams in the spreadsheet show a kcal value of 0
The kcal value of is Green grams: 3290
Stella, this has been incorrectly logged as a synonym for Wild green leaves.
Green grams is a crop and should not be entered as a wild food. I recall sending the kcal value of green grams while you were in Uganda so I'm not sure where the error came in.

This should not be corrected until #310 has been fixed or it will change the test data for that issue.

**Comment by stellangoleka** [comment]
Noted

**Comment by celiapetty** [comment]
Note green grams is now in the dbase.

**Comment by daiClegg** [comment]
I had documented this blocked by the DI calc, because fixing this screwed up my test data for that issue. I have now fixed that. So the dependency is broken. And this issue can noew be closed as done.

Note if you complete an issue - ie there is no reason for anyone to do anything more with it, then close it.
