### ISSUE TITLE
Adding Communities to  a Project/ProjectLivelihoodZone is missing integrity checks

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#36]
In Communities block/frame, click New.
<Community form pops up - as expected>
In Community form,  in Site block, click search icon.
<list of all Sites known pops up>

Problems:
 - Should not offer Sites already associated with Communities in this Project
 - Should only offer Sites in the Livelihood Zonethat is the current focus
 - Will allow you to add a Community based on a Site in a different LZ
 - Will allow you to ad the same site twice

Site should be unique within a project
Within a Project LivelihoodZone, all COmmunities must be at Sites in the same LIvelihood Zone

**Comment by dbrownukk** [comment]
Interesting problem 

Needed a new search from the Site entity in on the Community module

public class FileteredSite extends ReferenceSearchAction {

	public void execute() throws Exception {
		
		super.execute(); 

		String locid = getPreviousView().getValue("site.locationid").toString();
		String cprojectid = getPreviousView().getValue("projectlz.projectid").toString();

to get the current site id and current project id

The filtering of the lookup is done with a setbasecondition statement - at least to ignore current Site

getTab().setBaseCondition("${locationid} != '" + locid + "'" )");  

alternatively this can be set in the SIte class as a new Tab definition but proved less successful and flexible

getTab().setTabName("Filtered");

HOWEVER to filter out to sites in current LZ is proving more difficult - the intersection entity ProjectLZ is not implemented as a class and the filtering is done via JPQL which does not recognise the ProjectLZ table, OO meets RDBMS problem and a learning curve that is consuming time to master

**Comment by dbrownukk** [comment]
Something still wrong with filtered lookup..

**Comment by daiClegg** [comment]
From Communities List view, click +
In Communities popup, select Project from dropdown
I Communities block, select search icon; 
List is correctly constrained to the same LZ
But does include all Sites in the LZ associated with the project.
Not just ones currently excluded from the project.
And can add an already associated one again.
Is this intended behaviour? It's not desirable for the user.

**Comment by dbrownukk** [comment]
Need to filter out LZs + Site already used in a Community for this project

**Comment by daiClegg** [comment]
List filtering is correct, 
but duplicates still allowed (look at GeneralTerstProject)

**Comment by dbrownukk** [comment]
Very strange - efd.site table

SELECT * FROM efd.site where locationdistrict='x'

returns 1 row and the unique constraint on LZ, District, SubDistrict is in place and valid

looking into this..

**Comment by dbrownukk** [comment]
emailed javier and sending test case

**Comment by daiClegg** [comment]
Checked the test project (TestZone1 in GeneralTestProject.
And there are duplicate sites.
I seem to remember this happening before - the cache gets out of sync with the database and takes a while to settle down (log-off.log-on not fixing it.

when  we have an OPenZava issue reference for can it be added here,

**Comment by daiClegg** [comment]
Any update on this? Should i re-test for the latest version (we've had 2 updates since this was logged)

**Comment by dbrownukk** [comment]
tested adding duplicate site to a LZ and gets error message - not friendly, but duplicate not allowed.

LZ filtering in community looks correct for search and add. 

For Add of a new SIte the Search of LZ does retrieve existing used  LZ , but do not see this as a problem as you are creating a new site associated with LZ

A thought - should Community data be frozen once WGI is validated, or is this opening up a can of worms.. for discussion

**Comment by daiClegg** [comment]
The Order of the WGs dictates the display order in the charts, so it is actually helpful to be able to edit these - a project team might not notice they'd got it wrong til they see the charts.

and i can't see anything else that it would be dangerous to edit, so i say let's not freeze it.

Tested the duplication issue - fixed as described.
I agree it's not a user friendly message, but the feature works fine.
