### ISSUE TITLE
Produce HEA reports based on OIHM Reports

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#360]
Current OHEA reports are a very basic set available only as pdfs
OIHM reports (See Issue #230) are a more comprehensive set, delivered as  a multi-tab data extract spreadsheet with an associated visualisation spreadsheet that presents the data as charts.

This task is to back-port this capability onto OHEA.

But first some assumptions need to be confirmed:

1. I assume Quantile reporting is to be excluded since HEA studies are targetted on Wealth Groups that are effectively Quantiles
1. I assume the Population Pyramid report is to be excluded since we don't know the ages of participants.
1. Calculations are different, but equivalent for Disposable Income, Adult Equivalent. These will be implemented as documented already

Are there any more reports that are not needed?
Are there any new desirable reports?
Are there any other differences in reporting between the two methodologies?

@celiapetty @DrJohnSeaman @stellangoleka  - Comments, please. 
If there is any complexity we should have a call to review.

**Comment by celiapetty** [comment]
I agree that we should have a call to confirm as these are critical points.
Dai, could you indicate days and times this week that work for you? (I am
in Reading tomorrow so preferably not before 5pm tomorrow)
Celia

**Comment by daiClegg** [comment]
I would prefer that people comment on matters of fact, data and preferences beforehand so everyone can read these, has the opportunity to ask for clarification or ask other questions and then we're all fully up to date before we meet.

It requires an effort upfront, but it shortens the amount of time needed for discussion and it gives everyone time to consider proposals or other inputs rather than have to make decisions cold without having time to think through the implications.

**Comment by DrJohnSeaman** [comment]
Correct. John

I assume Quantile reporting is to be excluded since HEA studies are targetted on Wealth Groups that are effectively Quantiles
I assume the Population Pyramid report is to be excluded since we don't know the ages of participants.
Calculations are different, but equivalent for Disposable Income, Adult Equivalent. These will be implemented as documented already

**Comment by celiapetty** [comment]
Could you confirm how the adult equivalent calculation is made in O-HEA? Is
this based on the number of people in a typical household for the wealth
group and an assumption of 2100kcal per person requirement? I may have
missed this earlier.
I think a screen shared session with Dai presenting all the reports
available so far would be useful- I will certainly review beforehand and
post questions, but more might arise  during the presentation.

**Comment by daiClegg** [comment]
Disposable Income calculation for OHEA is defined in #145 and of OIHM in #310.
The calculation of calories required is part f each of those.
It's 2100KCal per household member per day for OHEA.

**Comment by celiapetty** [comment]
Thanks for pointing to relevant issues...

**Comment by daiClegg** [comment]
The reports in OIHM are defined in #230 

The video tutorial for running reports in OIHM is here:
https://www.dropbox.com/s/oumbdybtut358fi/Reports.mov?dl=0
It's a mac .mov file but Windows Media player can import and convert it.
I prepared it for Stella when she was initially testing reports.

**Comment by daiClegg** [comment]
The visualisation spreadsheet referenced in the tutorial and necessary to get charts is here:

https://www.dropbox.com/s/3h9jn89uy96ou03/ReportVisualisation.xlsm?dl=0

**Comment by daiClegg** [comment]
@dbrownukk some thoughts:
1. Category-constrained reporting should be in scope. 
1. Would a Report spec be re-usable between OHEA & OIHM? Ideally yes, but what about reports available in one but not the other, for example Population pyramid? Reporting could just ignore inapplicable reports and the Report Spec module could show (additional field in Report admin table) which app or apps the report is applicable to.

**Comment by daiClegg** [comment]
@celiapetty @DrJohnSeaman  Any further thoughts? do we still need a call?

**Comment by daiClegg** [comment]
@celiapetty @DrJohnSeaman  OIHM has a mechanism for recording Standard of Living elements - which are then used in the with StoL variants of some reports. OIHM does not have Food & Non-Food Purchases  - apart from StoL elements. 
Is it time to harmonise the methodologies around StoL? You've already explained to me that Food Purchases should be excluded from from Food Income reporting in OHEA (they now are), so they don't get reported anywhere in OHEA, nor do Non-Food Purchases.
The concepts do not exist in OIHM, so would also be excluded from the back-ported OIHM reports.

We could continue to collect and store the data without exposing it in the standard reports.
A user can always export the data for their own analysis anyway.
Thoughts please

**Comment by DrJohnSeaman** [comment]
As ever I am not entirely suure I understnd the question..

OHEA. My understanding, was that OHEA would
1. Allow expenditure, food and non food, to be stored but not used directly in analysis. This was discussed ie because historical data does include expenditure and it would be a loss to dump it. Non-food expenditure would not be collected in future HEA surveys.
2. Allow a specified diet, and prices to be entered and used for the DI calculation (same as OIHM) 
3. Allow 2 estimates of non food expenditure  (a 'survival' and a higher 'standard of living' estimate) to be entered and subtracted from DI under user control ie could be subtracted or not. If added to  OIHM this would standardise OIHM and OHEA. 

John

**Comment by daiClegg** [comment]
@DrJohnSeaman. In response to your points;

1. Allow expenditure, food and non food, to be stored but not used directly in analysis. This was discussed ie because historical data does include expenditure and it would be a loss to dump it. Non-food expenditure would not be collected in future HEA surveys.

> Ok. That's as it is. You make a good point that maintaining the historical data collected provides a potential value. No change required. 

2. Allow a specified diet, and prices to be entered and used for the DI calculation (same as OIHM)

> That was not part of OHEA phase 1, since that had no modeling. But, as i thought,  it needs to be added to support modeling, as in OIHM.
3. Allow 2 estimates of non-food expenditure (a 'survival' and a higher 'standard of living' estimate) to be entered and subtracted from DI under user control ie could be subtracted or not. If added to OIHM this would standardise OIHM and OHEA.

> I've not heard a requirement for 2 levels of Standard if Living measurement before. OIHM has one level only. The OIHM reports already support with/without StoL variants and the instructions are documented above on how to test those reports. Currently no plan to support 2 levels of StoL.

**Comment by DrJohnSeaman** [comment]
OHEA. The two levels have been mentioned - as a feature it makes the model a bit easier to use although it is always possible to enter new values if a 'survival' calculation is required. Realistically it would only be used with HEA, not IHM

**Comment by daiClegg** [comment]
@DrJohnSeaman , that explains it. When you, Celia, David & i discussed modeling at the OIHM requirements workshop, only IHM was in scope at that point - so the issue of 2 levels didn't arise. At least if it did, it's not in David's or my notes. 
Since this means a change to the data collection functionality as well as Reporting, i'll open a new thread for that part of it. (Issue #363)
Meanwhile, the Reporting requirement is that OHEA reports for Disposable Income will need to incorporate two, not one, set of Standard of Living elements in the equivalent report for DI with Standard of Living (#224)

You can see how this is done in OIHM, with one level, by running the reports as discussed above. 
I'd appreciate it if you could do that. Stella'sKatakwi data set is probably the best one to use.

**Comment by daiClegg** [comment]
All the OHEA reports will be at Community level, and for all WGs in the Community.

**Comment by daiClegg** [comment]
An issue is closed when the software is implemented & tested.
I think we're done discussing the requirement here, so i'll take the discussion label off and remove John, Celia & Stella from assignment so they don't get unnecessary updates

**Comment by daiClegg** [comment]
#380has a  brief discussion of the treatment of Default Diet.
Net-net is OIHM does it right, so OHEA should echo that.

**Comment by daiClegg** [comment]
Design Data Model is here: https://github.com/dbrownukk/EFD_v2/blob/master/DesignDoc/IHM%26HEADesignModel12.mwb

**Comment by daiClegg** [comment]
@DrJohnSeaman : At the moment the reports will run for all WGs in a Community (Site/Village).
And a separate set of reports for each Community.
Two questions:
1. Would it be helpful to be able to run the reports for all the Communities in the Project in a single run that would then create the reports for each Community as a separate spreadsheet. This is just to save the user having to go through the set-up and run for each community in turn.
1. Is there a requirement to run a single aggregated set of reports for the whole project? For example to report Average DI for all the Poor/Middle/Better Off WGs across the Project as a single 3-bar chart?

**Comment by daiClegg** [comment]
So for this release, we'll prioritise:

**Must Have:**     Reporting for a Community, similar to OIHM's reporting of a Study,  for all WGs
**Should Have:**  Feature allowing reports for all communities in a LZ/Project to be run in a single request.
**Could Have:**    Single aggregated set of reports for a LZ/Project

**Comment by daiClegg** [comment]
#383 records the deferred possible requirement for aggregated reporting

**Comment by celiapetty** [comment]
Re Must have/should have/could have
John, could you clarify for my benefit: Am I right in thinking that in standard HEA reports, the results of all the  selected interview sites (ie communities) are aggregated  in a set of reports for the LZ? And that one of the great benefits of using software is that it's also possible and could be very useful, to compare individual sample sites (This function made an impression when you gave a demo of your software a year or so ago.) So both aggregated and individual community outputs are equally important?

**Comment by DrJohnSeaman** [comment]
Re Must have/should have/could have

Am I right in thinking that in standard HEA reports, the results of all the selected interview sites (ie communities) are aggregated in a set of reports for the LZ? Correct. For each WG of course. A WG report is the average of all the community interviews for the LZ 

And that one of the great benefits of using software is that it's also possible and could be very useful, to compare individual sample sites (This function made an impression when you gave a demo of your software a year or so ago.)  Yes - useful I think 1. because it allows users to examine the individual components of the WG results. Unexamined data is not data.. 2. Potentially ( I am trying the decide the best way of doing this) it allows (we have the % in each wealth group) the reconstruction of a complete income distribution.

So both aggregated and individual community outputs are equally important? If it is a choice, aggregated is the most important - it provides the quantitative basis for the development of a narrative used to argue the case for action e.g. so many tonnes of food,

**Comment by daiClegg** [comment]
So revising the priorities:

**Must Have:** Single aggregated set of reports for a LZ/Project
**Should Have:** Reporting for an individual Community, similar to OIHM's reporting of a Study, for all WGs
**Could Have:** Feature allowing reports for all communities in a LZ/Project to be run in a single request.

**Comment by daiClegg** [comment]
And for confirmation when aggregation Communities, do you always take the mean for any number relating to WG? E.g. Cash Income for Better Off WGs or DI for Middle WGs. There is no weighting for the percentage of the population in the WG in a particular Community? Nor any other weighting factors in the calculation?

**Comment by daiClegg** [comment]
Thanks John. Would you expect OHEA to support the deficit calculation? If we store a population estimate for the LZ we could calculate absolute deficit and degree of deficit for each WG and produce the colour-coded map. That would be outside the current budget, but it's perfectly doable if we find a project that values it. And we could specify it as a use case and look for the stakeholder would want it.

**Comment by DrJohnSeaman** [comment]
Adding some output in due course for the more common operational calculations - the deficit is the main one - would be very useful.

**Comment by daiClegg** [comment]
Example data extract spreadsheet attached.


[OHEAReportsTemplateDataExtract.xlsx](https://github.com/dbrownukk/EFD_v2/files/3786058/OHEAReportsTemplateDataExtract.xlsx)

**Comment by DrJohnSeaman** [comment]
Small points - aggregate ? average

Headings. For food and cash income could the headings be simlified to not include 
'food (or cash) income in each heading. Just once on each sheet would do. It cuts down the need for editing if the data is cut and pasted elsewhere.

Did we agree that we should also have this standardised per person?

**Comment by daiClegg** [comment]
@DrJohnSeaman : in respoinse~~~~:

Small points - aggregate? average

> When i started i thought some of the summary numbers might be counts or sums, but in fact, they are all Averages, so i've changed that now. 

Headings. For food and cash income could the headings be simplified to not include
'food (or cash) income in each heading? Just once on each sheet would do. It cuts down the need for editing if the data is cut and pasted elsewhere.

> I used the full titles to be clear for David, implementing. In the Visualisation Spreadsheet, where the charts all be displayed, the titles will be more user-friendly. See instructions above for how to see how this works in OIHM already.

Did we agree that we should also have this standardised per person?

> Yes. The per-person numbers to be worked out using the HH size, defined for the WG. That number was missing from this template; it's fixed now.  Again, the OIHM Visualisation Spreadsheet shows how this is presented.

[OHEAReportsTemplateDataExtract.xlsx](https://github.com/dbrownukk/EFD_v2/files/3803859/OHEAReportsTemplateDataExtract.xlsx)

**Comment by dbrownukk** [comment]
Infrastructure in place and first cut of spreadsheet front page done - (yet to remove quantiles and tidy)

Go Community module. Select a Community. On Project click on Edit button.

You will see a Project + LZs.
In LZ List there is a Report button against each LZ. Select and you will be able to select Report Spec and 
Sites/Communities. Click run as per OIHM reports.

OHEA Custom Report Spec is on OHEA Core menu and behaves the same as OIHM. 


Now on to the individual reports. 

 deployed

**Comment by daiClegg** [comment]
Revised the template to move Averages to the top of the tabs.
This will make it easier to implement the visualisations.
[OHEAReportsTemplateDataExtract.xlsx](https://github.com/dbrownukk/EFD_v2/files/3835882/OHEAReportsTemplateDataExtract.xlsx)

**Comment by daiClegg** [comment]
The Epic is essentially complete.
Only testing of the visualisation is outstanding but that is blocked.

Will close this as feature-complete and open issues if any emerge from the final testing.

**Feature Complete**

**Comment by daiClegg** [comment]
The reports all produce outputs as a data extract spreadsheet; you need the visualisation spreadsheet, as in issue #373.
As of this comment date, that's still awaiting fuller testing, but the latest development version is attached to that issue.
How you use the data extract and the visualisation spreadsheets together is documented in the issue as well.
