### ISSUE TITLE
OHEA Standard of Living needs to have two levels.

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#363]
In OIHM, the Standard of Living is specified as a number of items (food purchase, non-food purchase or other tradable goods).
They may be specified for the household (e.g Soap) or for individual HH members ( e.g. clothes). In the latter case the gender and age range of the element can also be specified (e.g. school fees).

Currently, OHEA has no specification of Standard of Living.
The requirement, to support the necessary reporting, is that OHEA has the same requirement as OIHM, but in addition there is an additional Survival level as well.

@DrJohnSeaman @celiapetty Is the Survival level StoL just a subset of the Social Inclusion StoL definition or might it include elements not in the Social Inclusion StoL?

**Comment by celiapetty** [comment]
In IHM studies we look at a household's disposable income ie the cash remaining after it has met its food energy requirements from its food income  and cash income.  My understanding is that this in HEA studies this would be referred to as meeting  'survival needs'-John is that correct? In IHM we refer to the x axis as the 'food poverty line'.Households below the line don't have sufficient DI/AE to meet basic survival/ food energy needs. Above the line some of the poorer households may meet food energy needs, but depending on household composition, may not have sufficient income to meet all the items needed to meet the 'standard of living' threshold. The standard of living threshold is defined locally as the goods needed to meet the norms for social inclusion (soap, primary school, fuel etc) . John could you explain the thresholds used in HEA for different wealth groups? Let me know if a phone all would be useful .

**Comment by celiapetty** [comment]
Re reading this may not by crystal clear. Negative DI/AE in IHM means a household can't meet its basic food energy survival needs. All households with negative DI/AE will also be below the STOL. Some poorer households that have sufficient food energy may however be below the STOL.  John, please add notes on terminology used in HEA.....

**Comment by DrJohnSeaman** [comment]
OHEA

OHEA is used chiefly for early warning - and therefore has to be able to be used to argue a case for food aid or other intervention with parties who may be reluctant to stump up. Two levels of food and non-food requirement have been used e.g. on the original software, in the FEG spreadsheet

1. A 'survival' level e.g. 1600 kcals (it happened once on Malawi - the donors said 1600 take it or leave it) and a bare minimum of non-food goods - a moveable feast but might leave out health and education costs, reduce kerosine soap and other costs.

2. A 'normal' (we have to decide on a word for this) level (usually 2100kcals and a fairly full list of non food basics). 

Realising this in software ideally allows the user to enter both and choose which one to use. It is possible although annoying as it requires some data entry, to simply change the values used.  

My sense is that it would be helpful to be able to have more than one level of non food costs, either as a seperate reduced list of items OR allowing the user to change the proportion of a 'normal' list to be included. The ability to vary the kcal requirment is less important I think. Cases liike  Malawi above are very rare and it is questionable whether this should be done - if it had to be done this would just involve adjusting the estimate of e.g. food aid, not difficult

**Comment by daiClegg** [comment]
The attached spreadsheet shows:

1. an example taken from the Katakwi OIHM data, as is now, for StoL definition.

1. a second table with a modification that would support 2 levels (default - Social Inclusion) and a subset (Survival). The additional data entry would only be to specify whether the item was in the Survival list.  The default could be set either way.
[PossibleStoLDataSets.xlsx](https://github.com/dbrownukk/EFD_v2/files/3685332/PossibleStoLDataSets.xlsx)


**Note** i've just used a spreadsheet as a simple way to represent a table here. The actual data is entered directly into the app.


Thoughts? Please feel free to upload a revisionor alternative input dataset

**Comment by DrJohnSeaman** [comment]
The spreadsheet. 

This would be sufficient to meet most needs I think. 

If it has a limitation it is that the selection for the survival level uses the same costs as the SOLT.  The addition of an additional cost column would solve this (eg would allow a reduced cost for say clothing) - if it is not complicated to do.

**Comment by daiClegg** [comment]
Attached revised spreadsheet with 3rd option - for each SOLT item, the user can specify the Survival cost as a %age of the Social Inclusion Cost. So 0% means it's not included in the Survival Cost, 100% means it is & anything else represents a reduction.
Could default to 100% or 0% whichever you think would result in less (ie are more things in or out).
wdyt?

[PossibleStoLDataSets2.xlsx](https://github.com/dbrownukk/EFD_v2/files/3697798/PossibleStoLDataSets2.xlsx)

**Comment by DrJohnSeaman** [comment]
That should do it I think. Default to 100 would be best.

**Comment by daiClegg** [comment]
To Summarise: Standard of Living is specified at 2 levels in HEA, not 1 as in IHM.
These are Social Inclusion (the equivalent of the single level in IHM) and Survival, a lower-level StoL.
What they represent in the real world is reflected accurately in their titles.

So the software change requirement is:

- Add a column/field the Standard of Living Element to represent what %age of that Element is represented in a Survival-level Standard of Living. The title of the column on display should be 'Survival'.
- add maintenance of Std of Living to the Community module
- Ensure the newly added Survival column does not appear by default in the Study module
- Add calculation of both StOLs to OHEA reports.
- Revise design data model revision to  have the additional column in the database definition

These changes will be logged as separate issues each as part of the OHEA reports Epic (TBD)

The attached spreadsheet shows the alternatives disucces abovce and the chosen option highlighted (boxed)

[PossibleStoLDataSets2.xlsx](https://github.com/dbrownukk/EFD_v2/files/3703071/PossibleStoLDataSets2.xlsx)

**Comment by daiClegg** [comment]
@DrJohnSeaman Can you confirm please John, that the Standard of Living definition applies to the whole community in HEA? It doesn't vary by wealth group does it?

**Comment by DrJohnSeaman** [comment]
Dai, The whole community  John

**Comment by daiClegg** [comment]
@DrJohnSeaman @celiapetty David & i were looking at the Standard of Living calculation.
IN IHM Std of Living Elements are either HH or HHM level and if the latter, they may only be applicable to one or other by gender and/or age group (e.g. school fees).
How does that calculation work in HEA where we don't know the age & gender of HH members - we just have the average HH size for the WG.

**Comment by DrJohnSeaman** [comment]
We have the calcuated DI/person for the wealth group and the cost of meeting the SOLT - so it is a calculation of the ability of the average household to afford the SOLT. A bit crude, but so is HEA. It gives a sense of the ability to pay, and allows food and nonfood needs to be separated.

**Comment by daiClegg** [comment]
John, What is the SOLT calculation in HEA please, an what additional data needs to be recorded to make the calculation?

**Comment by DrJohnSeaman** [comment]
WG DI - SOLT cost where SOLT cost may be 'normal' (a basket of goods as in IHM) or 'survival' (a reduced basket of goods). 'Normal' and survival SOLT are set for the LZ. OR standardised / person

**Comment by daiClegg** [comment]
@DrJohnSeaman My question is how do you price the basket in HEA In IHM you maight rely on age and/or gender of individual household members to price some purchases (e.g. 1 set of clothes per adult at one cost one set per child at a lesser cost). Since you don't have the age and gender breakdown how do you cost things that are definitely based on age or gender?
Do you have some examples of Standard of Living 'baskets'?

**Comment by DrJohnSeaman** [comment]
You dont - it is a number per wealth group. The number is derived from school, fuel etc costs. Its an average cost for an average household.

**Comment by daiClegg** [comment]
@DrJohnSeaman,  In OIHM the Std of Living basket is defined as a collection of purchases.
Each one specifies the item purchased (Food Purchase, Non-Food Purchase or Other Tradable Good), the quantity purchased and the cost per unit purchased.
In addition, the user can specify for each item whether it is only applicable for Household members of a specific gender and/or within a specific age range.
The software then calculates the whole cost from these parameters; because the age & gender of all HH members is known, the costs are only included where relevant.
I just assumed we'd do the same itemisation in OHEA, albeit without the fine tuning for age/gender.

I guess whoever calculates the lump sum must know the list with a cost per item.
So it makes sense to record that data and automate the calculation to avoid any error.

My question was how the methodology deals with items such as school fees where the number of school-age children is not known. It's the assumptions made for such items that we need to capture to avoid it being a black art.

Ideally, i'd like the software to record all the data is needed or is assumed and to do the same calculations. That way it's easier to use and the datasets have greater transparency for later analysis of the data. It is also more consistent with how OIHM works, which again makes for a shorter learning curve for the user. 

Once we have the itemisation, we can apply for each item, as i think we discussed somewhere, the %age of the Social Inclusion cost for Survival. That bit i'm clear on, it's just the assumptions to be made for the items that are not 'per HH' nor 'per HH memeber'. Thanks.

**Comment by celiapetty** [comment]
John-the discussion raises the question whether we should review the terminology used in HEA and IHM to avoid confusion, as they are not interchangeable in the 2 methods(ie in IHM the x axis is the 'food poverty line' and the SOLT is a very basic minimum additional expenditure required for social inclusion, reflecting
[Draft Homa Bay HEA report_JS reviewed (1).docx](https://github.com/dbrownukk/EFD_v2/files/3784763/Draft.Homa.Bay.HEA.report_JS.reviewed.1.docx)
 the expenditure of the poor but not destitute. So slightly different from  'survival' and 'normal'  in HEA as described above.
I've also just re-read the Homa Bay paper(attached) -

**Comment by celiapetty** [comment]
Note-see p p12-13  Standard of living, Homa Bay report, previous posting.
Does this suggest a move away from  the use of 'Survival' and 'Normal ' in HEA work?

**Comment by daiClegg** [comment]
**Note(2)** Table 1 on page 12 of the referenced document, attached above (same date), has the Standard of Living definition for the Homa Bay study.
Every item is expressed as a per-person cost. 
But it is not apparent how items such as 'primary school costs' are calculated as an equivalent per-person cost. 
Is there an assumption/estimate of how many school-age children there are in an average family group? This data is not available in OHEA. It should be.

@DrJohnSeaman @celiapetty  :  How is the assumed/estimated number of children arrived at? Are there any other estimations that might be needed to calculate Std of Living costs?

**Comment by DrJohnSeaman** [comment]
We are making heavy weather of this...

I just assumed we'd do the same itemisation in OHEA, albeit without the fine tuning for age/gender...
that is correct
calculation of the the lump sum needs a list with a cost per item.

So it makes sense to record that data and automate the calculation to avoid any error. Correct

My question was how the methodology deals with items such as school fees where the number of school-age children is not known. A judgement made by the person who compiles the list. - actually not a black art as the proportion of school age children is roughly known (in countries where primary education is compulsory, the % of school age children); the cost/ child is known etc

The software should record all the data  needed - as you say it's easier to use and the datasets have greater transparency for later analysis of the data. Things written on paper dissappear

**Comment by daiClegg** [comment]
@DrJohnSeaman , i've re-attached the spreadsheet from above in which we worked through the refinement for Survival StoL.

I realise that we can already specify the number and whether it is per HH or per HH member.
So for example for Clothes, we just say 1 per HHM at an average cost & the software, knowing the average HH size for that WG, works out the total cost of the item. 
Similarly we can specify, for example 5 Kg Tea for the  HH.

So for something like School costs, which is contingent on unknowns, we can just say 2 per HH if we estimate that an average HH in that WG would have 2 school-aged children.

That would require the user to know the HH size in order to make the estimate. 
It might be easier to say 0.3 per HH member (ie on average, one in 3 HH members is a school kid). That seems counter-intuitive, but it means the user only has to know the average for the country/region and maybe wealth level. 

Either way the current data structure allow us to use whatever knowledge the user has  to arrive at the right number and keep a record of how they did it.

Is that ok?

[PossibleStoLDataSets3.xlsx](https://github.com/dbrownukk/EFD_v2/files/3796032/PossibleStoLDataSets3.xlsx)

**Comment by DrJohnSeaman** [comment]
That is OK. 0.3 should be clear John

**Comment by daiClegg** [comment]
Thanks @DrJohnSeaman .

**Comment by dbrownukk** [comment]
Added survival and relationship of STOL to Community
Displays the same as Study but shows survival - default 100, min 0, max 100

deployed

**Comment by daiClegg** [comment]
**Feature Complete**

will log issues separately
