### ISSUE TITLE
RST Synonym needs to read in parent KCal 

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#365]
Modified RST Module. WHen Synonym is changed then KCal value for parent is copied in and set to no edit. Remove Synonym and KCal value is edittable.

**Comment by daiClegg** [comment]
fyi, i have been testing DI calculation (#310) on data that did include synonyms which are now being correctly calculated.  Is this fixed?

**Comment by dbrownukk** [comment]
RST KCal value via a synonym is fixed in calculations

Also, in RST Module Detail view, if the RST is a synonym for a parent RST then eth KCal value is populated from the parent and set to read only. 

To change back to a non Synonym set the Synonym field to empty and the KCal value will be editable.

deployed

**Comment by daiClegg** [comment]
Nice, but the synonym should also adopt the same unit as the base RST.
Otherwise, you could have the same KCal value for 2 different sized units

See:
Instance: EFD_HM
Module: RST
RST: Test Item: delete if issue 365 is closed 
& other test item: delete if issue 365 is closed

**Comment by dbrownukk** [comment]
Yep, missed the big picture... 

Will set Unit to same as the parent and make non editablle

**Comment by dbrownukk** [comment]
deployed the fix as above

**Comment by daiClegg** [comment]
**Tested OK**
