### ISSUE TITLE
Exception Thrown when accessing Project Module

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#37]
I had been testing Issue #32 and issue #22 .
I was displaying sites of the Karamoja project , having successfully added a duplicate (as noted in issue #32 )
Then i tried to list all the projects by selecting Project module the list of recently accessed module.
And got this exception:

ERROR: An exception occurred processing JSP page /xava/core.jsp at line 78 75: 76: 77:
style='padding-top: 2px;'> 78: 79:
80: 81: <%@include file="viewExt.jsp"%> Stacktrace:

Attempted to open the Project module by searching for itin the 'Open' drop-down; same result.

Logged off and on: the problem does not reproduce - Project module invokes, as expected.

I have now entered full steps to reproduce in issue #32 because i expected them to reproduce this problem. But it didn't. Though i did do something like that to reproduce it once

If this is not enough to isolate the problem, assign to me and i will test further, because i think this is reproducible - just not quite sure how i did it now.

**Comment by daiClegg** [comment]
When i did manage to reproduce it - not sure how i got this display:

![image](https://user-images.githubusercontent.com/30879677/35693380-f5f8cd96-0775-11e8-811f-4805ce016609.png)

but i can't get to it with documented steps.

**Comment by dbrownukk** [comment]
Thanks Dai - yes, I did see this and is the same as issue #34. I recoded the 'Add LZ' button to check that the Project had been committed, but there seems to be an OpenXava bug that confuses which View to redisplay. I will set back to default behaviour for the moment.

**Comment by dbrownukk** [comment]
realted to https://sourceforge.net/p/openxava/discussion/419690/thread/1266e842/

reorder Community List after a Community Save and all appears well

**Comment by dbrownukk** [comment]
For testing - Post save returns to current detail record. For List view use List button

**Comment by daiClegg** [comment]
Cannot reproduce.
