### ISSUE TITLE
Report Community Land Assets in order of WG

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#370]
Based on OIHM report #227

**Comment by daiClegg** [comment]
Just realised we ought to display the unit that is being used for Land 
Uploaded template extract defines where this should be included.
Everywhere else uses currency (already included) or unit (Livestock) so there's only this report that needs its unit specifying,

But, the question then arises, how do we know all the data is in the same measure?
Any given study will use Hectares or Acres. So it should be consistent.
But we don't enforce that anywhere do we?

Should the Project define its standard unit of area?
And any data entered in the other be converted.
This sounds like a bloody complicated solution for a minor problem. 
But however we resolve this, the user needs to know the unit on their report

Let's discuss

**Comment by dbrownukk** [comment]
deployed first cut of Land report. Needs units. Tested on dev data and seemed ok. Now deployed there does not seem to be a validated set of 3 WGs for a Community. 

Need to pull data again to dev environment to test

**Comment by daiClegg** [comment]
Tested on Project 'Mukono - New Test'.
I valIdated WGs in 4 Communities to provide decent test data.
Ran 'All Reports' but only got data, in the Land Assets report, for one Community (Ntenjeru)
The data was correct for that Community (all three WGs)
And the Averages were correct.

As noted, missing data for the other communities.

**Comment by dbrownukk** [comment]
Thanks for the test data. Namakwa is missing for Land. Ntenjeru is correct.

The other communities in Mukono - New Test do not have 3 Validated WGIs.

Thus, need to debug the Namakwa missing data.

**Comment by daiClegg** [comment]
will work on more test date - more complete villages.

**Comment by daiClegg** [comment]
Returning to the thread above re Land units - Acre & Hectare:

- Adding support for Hectare in the reports is currently unresolved. 
- So for the moment the Visualisation spreadsheet will look in Cell B2 of the Land Asset tab of the report data extract spreadsheet for the reporting land area unit.
- If it is blank the default will be Acre.

**Comment by daiClegg** [comment]
Issue #390 discusses howe the Land Asset unit use could be supported fully.

**Comment by daiClegg** [comment]
Mukono - Net Test project now has 5 villages each with 3 validated wealth groups.
Should provide reasonable test data

**Comment by dbrownukk** [comment]
Thanks, very helpful. Pulled down to Dev environment

**Comment by daiClegg** [comment]
**Feature Complete**
pending resolution of unit of area
see issue #390
