### ISSUE TITLE
Produce visualisation (spreadsheet charts) of OHEA report data extract

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#373]
Based on OIHM data visualisation spreadsheet, issue #320

**Comment by daiClegg** [comment]
@DrJohnSeaman  @celiapetty It's not obvious to me how best to display OHEA DI with Std of Living costs factored in, since there are 2 levels (Survival & Social Inclusion).

The image below shows each Village separately. The averages for the LZ will be a separate chart that i'll do when we've got consensus on the layout.


As you see, there's a column for each of DI/AE, DI/AE with survival costs subtracted & DI/AE with social inclusion costs subtracted.
And you can see (just) that where that goes negative, the bar changes colour & of course goes below the axis.
This is the per AE chart. There will also be a pair (Detail & Averages) of charts for gross DI/ DI less survival costs/DI less social inclusion costs.

The data is made up, so take no notice of that - it's just there to allow me to mock up a chart.

Do you like this layout? Do you have examples of other layouts you prefer? Or just ideas for improving this.

![image](https://user-images.githubusercontent.com/30879677/69477776-5949cc00-0de2-11ea-8ff6-5d07bc1e5c6b.png)

Note that the user creates a Data Extract spreadsheet (raw data) from the application - as in OIHM and then uses a separate Visualisation spreadsheet, which the user links to the data extract, to view it in the charts. This allows the user to take the raw data and do whatever they like with it, ignoring the Visualisation spreadsheet. But it also means that there is a standard set of high-value charts 'out of the box' for users who don't have any special requirements for their project.

**Comment by celiapetty** [comment]
This looks good to me-especially as users can easily access raw data in addition to these clear visualisations. I wonder if now is a good time to bring in James for comments? I'm attaching for information the charts he produced for NIMFRU/Katakwi showing 'survival' and 'livelihood' thresholds across wealth groups-data aggregated. He will need to make the transition to the new 
[James slides Survival&Livelihoods levels.pptx](https://github.com/dbrownukk/EFD_v2/files/3886245/James.slides.Survival.Livelihoods.levels.pptx)
(and I think less obscure) presentation. Views?

**Comment by daiClegg** [comment]
@celiapetty we can add James as a contributor to the project if you like, but he can read the issue thread without having a user id and logging in; he just needs the URL of this page. He can't comment in the thread without being logged in; he'd have to mail comments and have a registered contributor add them for him. If he's only rarely going to contribute that's not too much overhead for us. wdyt?

**Comment by celiapetty** [comment]
Ok-so I just need to let him know that from time to time I'll forward for his comments  relevant  issues -and if he can responds to these emails I'll copy them into the thread.

**Comment by daiClegg** [comment]
:o)

**Comment by daiClegg** [comment]
This is feature complete and i was about to close it when a test showed incorrect definition of a range in Land &  Livestock Assets Summary charts when changing source.
Not consistently reproducible, but keeping this open until i've done enough further testing to convince myself it was a transitory glitch or it's a bug and i've fixed it.

**Comment by daiClegg** [comment]
@celiapetty did you ask James for his views?

**Comment by daiClegg** [comment]
Will retest this when we have the one OHEA production project in the new OHEA format. That is WIP

**Comment by celiapetty** [comment]
He's out of Kampala now I thi k. Cant get into github right now

**Comment by daiClegg** [comment]
@celiapetty : ok, will not wait for James' input, but i'm stalled on final testing until the OHEA production data has been cleaned up and upgraded anyway, so there's probably plenty of time for him to respond.

**Comment by daiClegg** [comment]
Issue #408 will provide really good test data for this.

**Comment by daiClegg** [comment]
The latest version of the Visualisation Spreadsheet for OHEA reports can be downloaded from: [here](https://github.com/dbrownukk/EFD_v2/blob/master/src/efd/reports/OHEAReportVisualisationDev6.xlsm)

**Comment by daiClegg** [comment]
To visualise reports:
1. download the visualisation spreadsheet.
1. open the Project you wish to report in in OHEA
1. In the Livelihood Zone data panel at the bottom of the detail view of the project you will see a small icon next to the LZ name that looks like a document; click it.
1. in the pop up panel, select All Reports in the Select Report Spec drop down,
1. select all the Communities you wish to report by click in in the little open square next to the Communities you want reports for
1. Click Run 
> a data extract file will be creatd & downloaded.
7. open the visualisation spreadsheet you have down loaded (see above)
1. click yes to enable macros (if asked)
1. click don;'t update for the linked data.
> the last report run wil be displayed; ignore it.
10. in the Data menu item (main menu) select Edit LInks.
1. click change source
1. in the file finder popup navigate to the data extract you just downloaded (see above); it will be in your usual download folder; select it and click Change.
> the Edit Links dialog will now display the filename of the data extract you selected
13. Click Update Values
1. Click Close
> your report will be displayed (whichever tab you last looked at) 
15. Navigate to the 1st tab - Summary to see a summary of the reports.
> you can navigate to the other visualisations
> if you want to look at the raw data, that is in the data extract spreadsheet.

**Comment by daiClegg** [comment]
Tested on Production data sets 

**Feature Complete**
