### ISSUE TITLE
Add Default Diet to Community

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#374]
To support Disposable Income calculation & reporting OHEA we need to know the default diet for a Wealth Group.

This is assumed to be the same for all WGs in a Community (to be checked)

So we need to add Default Diet specification to the Community module
This is analogous to Default Diet specification in  OIHM issue #221

**Comment by daiClegg** [comment]
@DrJohnSeaman am i correct in assuming that the default diet in HEA is specified at the community level rather than individually for each WG?

**Comment by DrJohnSeaman** [comment]
Correct - its just a way of standardising the DI results

**Comment by daiClegg** [comment]
Instance: EFD_HM
App: OHEA
Project: Test Common Validation #350 
Module: Community
District: Berkshire
Village: Knowll Hill


OHEA Default diet  element percentages can add up to >100:

![image](https://user-images.githubusercontent.com/30879677/67380201-e39fd580-f581-11e9-8c76-8903484925b3.png)

in OIHM an error is issued in such cases.
OHEA should do the same.

**Comment by dbrownukk** [comment]
now has warning if total ddi percent is above or below 100

**Comment by daiClegg** [comment]
**Tested Ok**
