### ISSUE TITLE
OX 6.2 Notes field now spans page and makes a mess of layout 

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#375]
Have bugged with Javier. For time being will remove Notes from HH and WGI 

Also, note that the behaviour of Spreadsheet upload is slightly different. OX now uses a new Ajax routine. Think that something was fixed that was not broken 

Dai, fyi

**Comment by dbrownukk** [comment]
Further testing of OX 6.2 and the change of file upload to use Ajax causes problems with spreadsheet upload workflow. Have backtracked to 6.1 for the moment awaiting response

**Comment by dbrownukk** [comment]
Have fix from Javier - will upgrade to OX 6.2.1 and test again

**Comment by dbrownukk** [comment]
Review and correct

**Comment by dbrownukk** [comment]
Notes now in Project, Community, Study, WGI, HH and Modelling Scenario

deployed to IAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
**Tested Ok**

nice touch to add it to Modelling Scenario as well

Also available on Community
