### ISSUE TITLE
Unable to delete WG

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#376]
INstance: EFD_HM
App: OHEA
Module:  Project/Community/WGI
Project: NewTestProject
Community: SD Z11
WG: Poor

I was attempting to clean up some old test data. So i started on this project:

1. tried  delete of project - but that was prohibited, as expected:
> Error: Cannot delete object in row 0 with key {projectid=8a8084846190b2230161941a1e77000d}

2.  i deleted the WGIs: - successfully
3. attempted to delete the Communities, first in list view:
> Error: Value for Community in Wealth group is required

4.. then in detail view:
![image.png](https://images.zenhubusercontent.com/5a81590c4b5806bc2bc688fc/963c5ec0-1f48-4184-a48a-907c669026bf)

Not surprised that top-down project delete is not allowed; i think a power-delete feature would be a mistake anyway, though useful for testing.
BUt i had expected to be able to work bottom-up through the project and delete it.

**Comment by dbrownukk** [comment]
Now deletes Community and any Wealthgroups and Community Year Notes 

Deployed - tested by deleting SD Z11 in NewTestProject

**Comment by daiClegg** [comment]
Tested Ok.

Can delete a Community if it has WGs but no WGIs.
Cannot delete Community if it has WGIs

**Tested Ok**
