### ISSUE TITLE
Negative cost of default diet items is permitted

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#377]
Instance: EFD_HM
App: OIHM
Study: M1 Workflow Study
Module: Study

Negative values are allowed for the cost of a default diet item.

See also #374

**Comment by dbrownukk** [comment]
fixed - in next deploy 
added @Min(0) to cost

**Comment by dbrownukk** [comment]
deployed

**Comment by daiClegg** [comment]
**Tested OK**
