### ISSUE TITLE
Exception thrown generating WG Interview template spreadsheet

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#378]
INstance: EFD_HM
App: OHEA
Module: Comunity
Project: Test Common Validation #350
District: Berkshire
Village:  Knowl Hill:

Had already created and generated spreadsheet for the Comfortable Wealth group, some days ago.
Returned to test Anomaly 1 in Issue #350

1. Created new WG (Other Group)
1. Click Generate Spreadsheet:

> ERROR: An exception occurred processing JSP page /xava/execute.jsp at line 90 87: manager.initModule(request, errors, messages); 88: manager.executeOnEachRequestActions(request, errors, messages); 89: if (hasProcessRequest) { 90: manager.execute(request, errors, messages); 91: if (manager.isListMode()) { // here and before execute the action 92: tab.setModelName(manager.getModelName()); 93: if (tab.getTabName() == null) { Stacktrace:

**Comment by daiClegg** [comment]
Appears to be repeatable with existing WGs; tried Comfortable WG in this project and one in another project

**Comment by dbrownukk** [comment]
Aha, generation of spreadsheet uses local unit code from validation and parse routines. On consolidation of validation I missed one call in the OHEA spreadsheet template generation. 

Fixing now.

**Comment by dbrownukk** [comment]
deployed

**Comment by daiClegg** [comment]
**Tested OK**
