### ISSUE TITLE
Unable to delete characteristic resources from  Wealth Group

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#38]
Test project is "TestProject180203"
Community is "Mukono/Bugoye Ntenjeru"
WG is "Middle"

I added 6 characteristics (see screen grab below)
Attempted to delete a Resource Subtype.
Got error message:

 - "Value for Wealthgroup in W GC haracteristics resource is required"

I tried deleting different Resource Subtypes including one i had created as part of the New Resource Subtype dialog i.e. "Employment/Fishing"
The behaviour is the same.
|
Tried logging out and back in and the behaviour is the same.

Screen Grab:

![image](https://user-images.githubusercontent.com/30879677/35767722-86a0bc36-08e9-11e8-9599-2bf956be04be.png)

**Comment by dbrownukk** [comment]
@OneToMany of Colllection WGCharacteristicsResource  also has FK to ResourceSubType (as well as WelathGroup) thus needs a cascade Remove to force remove of this end of the FK. Does not remove parent

Added case=cascadetype.Remove to wgcgaracteristicsresource in Community class

deployed and tested

**Comment by daiClegg** [comment]
Tested ok.
