### ISSUE TITLE
Unable to run OIHM reports (case 1)

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#381]
Instance: EFD_HM
App: OIHM
Study: Test Wild Food as Product
Module: Study

1. Click Reports
1. In report spec drop-down, select All Reports
1. In Household panel click select all box to select all HHs
1. Click Run

> Exception thrown:

![image](https://user-images.githubusercontent.com/30879677/67382301-2b742c00-f585-11e9-8d8b-989f9dc86c32.png)

**Comment by dbrownukk** [comment]
Aubergine still has KCAL value of 0. Causing divide by 0. 
Need to go through and check no 0 KCals for foods

Put a check in to get syn kcal if 0 val. Syn kcal set during save, but not for old data. 

Need more checking of 0 KCal. RST can have 0 KCal for some RTs, thus needs coding not a constraint

**Comment by daiClegg** [comment]
I'll correct that, and review Crops, Wild Foods, Livestock Products and Food Purchases.
Will also review RTs to check no others need KCal

Will leave this issue open pending the hardening of validation.

**Comment by daiClegg** [comment]
Checked RT table. Only those 4 RTs have  non-zero KCal values 
But some food purchases legitimately have 0 calories (Coffee, Tea, Salt) 
How do we deal with that?
Perhaps it's not a problem, since Food Purchases are not included in any reporting are they?

**Comment by daiClegg** [comment]
Coffee & Tobacco are legitimate crops - with KCal zero!
So we do need a way to deal with this in reporting.

**Comment by daiClegg** [comment]
Went to correct Aubergine and found it is a Synonym of Egg Plant (no surprise) which does have a non-zero KCal value. So the reports should not have failed.

Will still check for other non-legit 0 KCal values

**Comment by dbrownukk** [comment]
Thanks for the clarification on 0 Kcal -Coffee etc. This and case 2 of OIHM reports are proving somewhat tricky, but getting there...

**Comment by dbrownukk** [comment]
fix deployed.

**Comment by daiClegg** [comment]
**Tested Ok**
