### ISSUE TITLE
Unable to Run OIHM Reports (case 2)

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#382]
Instance: EFD_HM
App: OIHM
Study: Katakwi- Nimfru Test

Module Study

1. Click Reports
1. In the Report Spec drop-down select All Reports
1. In the Household panel click select all box to include all HHs
1. click Run:

> Error message reported:

![image](https://user-images.githubusercontent.com/30879677/67383316-e4873600-f586-11e9-88bf-63ce7d7c9a5e.png)

I was trying to reproduce #381 on a Study with real data, but got a different failure

**Comment by dbrownukk** [comment]
fix deployed - java stream issue with 0 value DI

**Comment by daiClegg** [comment]
**Tested Ok**
