### ISSUE TITLE
Unable to Validate Household

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#384]
Instance: EFD_HM
App: OIHM
Module: Study
Study: Katakwi- NIMFRU Test
HH number: 8

This household is fully parsed, all the resources are marked as valid and appear to be valid.
Click Validate

> Error: Impossible to execute Validate action: null

**Comment by daiClegg** [comment]
Tested on a new HH:

Study: A Study
HH Number: 6

1. created a new household in an existing study
1. uploaded existing test spreadsheet
1. parsed - ok with expected errors
1. fixed all the resources
1. click validate

Success.

Also tried another HH in the Katakwi Study - same failure.
I have been editing the Katakwi HHs to try to eliminate their use of incorrectly named RSTs, but i can't see anything wrong with the data

**Comment by daiClegg** [comment]
Another test:

Study: Katakwi - NIMFRU test
HH number: 5

This household was in the Validated state.
So i:
1.  set it editable
2. Clicked Validate

Same error

**Comment by dbrownukk** [comment]
No default for FoodPaymentUnitsPaidWork - now defaults to 0
checked other Doubles..

deployed

**Comment by daiClegg** [comment]
**Tested Ok**
