### ISSUE TITLE
Unable to edit Default Diet item Unit Price

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#385]
Instance: EFD_HM
App: OHEA
Module: Community
Project: TestIssue36
LZ: TestIssue36
District: district 36_1
SubDistrict: sd 36_1

1. In Community detail view, Click Default Die tab
1. Click any Diet item to edit
1. Change value in Unit Price field to any valid value
1. Click Save

> Error: Impossible to execute Save action: null

Repeated in other communities.
Does not reproduce in OIHM.

**Comment by dbrownukk** [comment]
pre_update was checking for STudy diet percentage > 100 - needs to handle community as well

fix deployed

**Comment by daiClegg** [comment]
**Tested Ok**
