### ISSUE TITLE
OHEA SToL Items should be allowed to be fractional

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#386]
In OHEA we know the average size of a family group (WG HH Size) but not the makeup of ages & genders, so we cannot price such items as School Fees accurately.
However, we can make a reasonable estimate. For example, an HEA interviewer would know that in a particular country the number of children of school age in a family is typically 1 in 3. So they could price School Fees as a Household Member item, requiring 0.3 per HH member (see discussion in #363 in October 2019). 

Currently, the validation of OHEA Community Standard of Living Element Amount is positive integer. It should allow positive decimals.

**Comment by dbrownukk** [comment]
The problem is that the Minimum was set to 1. The datatype is a decimal but could not go below 1.

**Comment by daiClegg** [comment]
**Tested Ok**
