### ISSUE TITLE
OHEA StoL HH Member Elements  do not need age range & gender

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#387]
In OHEA we know the average size of a family group (WG HH Size) but not the makeup of ages & genders.

So there is no point capturing whether an expense only relates to HH members in a specific age range or of a specific gender. The fields should not be displayed.

**Comment by dbrownukk** [comment]
Changed view for Community STOL and set Onchange to only fire in Study STOL

Deployed

**Comment by daiClegg** [comment]
**Tested Ok**
