### ISSUE TITLE
List view of CharacertisticResources does not show the ResourceType

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#39]
In list view, i only see the Resource Subtype, not the Resource Type.
So, for example, i can see 'Goats', but not that they are 'Livestock'.

It's important because there are 2 Resource Types - "Crops - mainly for sale" and
"Crops - mainly for consumption" so if i create one of each for "Bananas" and add them for a WG, then all i see in the list is "Bananas" apparently duplicated.

I tried to customise the layout but i couldn't find the right column to add

**Comment by dbrownukk** [comment]
Fixed - added Resource Type to list and deployed.

**Comment by daiClegg** [comment]
Tested Ok.
