### ISSUE TITLE
Unable to generate spreadsheet for new WG

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#391]
INstance: EFD_HM
App: OHEA
Module: Community

Template Spreadsheet control has disappeared from the WG 'block' of the Community module

![image](https://user-images.githubusercontent.com/30879677/69383473-9ebaac00-0cb1-11ea-9eca-70eea4992d31.png)

**Comment by daiClegg** [comment]
This is blocking me from creating more test data for the OHEA reports testing

**Comment by dbrownukk** [comment]
fixed - I had set the spreadsheet not to show when displaying the WG list in the new OHEA reports using the ForView option but had used 'default' not 'Default'

Now fixed and deployed.

**Comment by daiClegg** [comment]
**Tested OK**
