### ISSUE TITLE
WGI Interviewees count - calculate from male + female interviewees

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#392]
@Column(name = "WGIntervieweesCount", nullable = false)
	@Required
	@Positive
	@Depends("wgFemaleIVees, wgMaleIVees")
	private Integer getWgIntervieweesCount() {
		return(wgFemaleIVees+wgMaleIVees);
	}

**Comment by daiClegg** [comment]
**Tested Ok**
