### ISSUE TITLE
Apparently valid Community dataset does not appear on reports

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#395]
Instance: EFD_HM
APP: OHEA
Project: Mukono- New Test
District: Mukono
Community: Namakwa

1. In WGI module, filter list view to show only this project
> note there are 5 villages, 15  WGs, all in 'validated' status
2. In Project module, select this project and in LZ frame, click the Print icon
> note only 4 villages are in the select list Namakwa is omitted,
3. Select a report spec, select all villages and run reports
> note run is successful -  for the other 4 villages in the LZ.

The old OHEA charts also do not run for this village but do for the others.
I tried setting one of the WGs in Namakwa to editable and re-validating; worked fine but didn't fix the problem. 

Seems to be a data problem, but i have inspected all the visible WG data and i can't see what's wrong with it.

**Comment by daiClegg** [comment]
also:

Project: Karamoja - Central Sorghum and Livestock
District: Nakapiriprit
Community: Cucu

3 validated WGs, but reports says no valid community in the project

**Comment by daiClegg** [comment]
Old OHEA Charts ***do*** run for this Community.
So this is beginning to look like 2 different problems.
I suggest ignoring the old charts for the moment, investigate the new reports and then i'll re-test the old charts and log anew issue for that if it's still there when the new reports anomaly is fixed.

**Comment by daiClegg** [comment]
I tried again by validating one village of the Mukono - Trial project:

Project: Mukono - Trial
District: Mukono
Community: Butere/Mpatta

It worked - although the data for these WGs is very skimpy.

**Comment by dbrownukk** [comment]
Found the problem, looks like a data issue somewhere.

Project 'Mukono - New Test' only has one LZ - 'Banana Coffee Piggery' with 4 Sites

How did a Wealthgroup end up with a Project of 'Mukono - New Test' and an LZ of 'Coffee-Banana-Pigs'

Have tried to recreate a new WG but cannot force a non Project LZ.

Old data glitch?

**Comment by daiClegg** [comment]
Added Coffee-Banana-Pigs LZ to Mukono - New Test and ran reports for it.
Produced Namakwa village extract, as expected.
Looks like that was invalid data.

Mukono - Trial, which behaved as expected y'day, has indeed got the right LZ for the valid Community.

**Comment by daiClegg** [comment]
The other problem Project i found (as documented above) was:

Project: Karamoja - Central Sorghum and Livestock
District: Nakapiriprit
Community: Cucu

That appears to have the correct LZ associated, but on running the reports i did still get the 'No validated Community in the LZ & Project'.
Then i crawled all over the data for this project in the  LZ module, the Project module, the Community module and the Wealth Group Interview module. Then ran the reports again and it worked.

Possibly it was a funny state in the data that was reset by accessing it. Is that even feasible?
I did try to run the reports from the LZ module. The Reports icon is there and live but it produces an error message:
`Impossible to execute Report action: Impossible to get object from row 0

Anyway there is no problem now, so closing this until/unless it reappears elsewhere.
`
