### ISSUE TITLE
No Of Wives field of  has disappeared from WG popup in  Communities module

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#399]
Instance: EFD_HM
App: OHEA
Module: Community

in detail view of any community note that the list of WGs shows No of Wives as a field,
click on any WG to invoke the editor pop up and the field is not visible.

**Comment by dbrownukk** [comment]
Added wgwives to edit dialog for Wealthgroup.

**Comment by daiClegg** [comment]
**Tested OK**
