### ISSUE TITLE
Entering Resources directly in the app demands value for redundant uploaded field 

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#400]
Instance: EFD_HM
App: OHEA
Module: WGI

When entering a new Resource for the RTs listed below, the field 'xxx type entered name' is mandatory, but is not necessary because you have already selected the resource type & unit in the 'Name' field

Affects:

Assets - Livestock

**Comment by dbrownukk** [comment]
Fixed, deployed

**Comment by daiClegg** [comment]
**Tested OK**

**Comment by daiClegg** [comment]
also required for Food Purchases, so re-opening,

**Comment by daiClegg** [comment]
also Non-Food Purchases

more to be tested...

**Comment by dbrownukk** [comment]
Been through them all.. All asset types should be ok now. Numeric defaults are 0 or 0.0

deployed

**Comment by daiClegg** [comment]
**Tested OK**
