### ISSUE TITLE
Units Sold & Units Other Use are required fields when entering Crops in WGI 

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#401]
Instance: EFD_HM
App: OHEA
Module: WGI
Project: NIMFRU
Community: Okorio
WG: Poor

1. In detail view of the WG, click on Crops tab
1. Select a new crop to add.
1. Enter a value for  Units Produced
1. Select "Valid"  in the Status field
1. Click Save

Message is " Wealth group interview modified successfully" but the record is not added

6. repeat steps 1 - 4 but also  enter a value for Units Produced then click  Save

Same result

7. Repeat steps 1 - 4 but also enter a value for both Units Produced and Units Other Use then click Save

The Save now works as it should.

**Comment by daiClegg** [comment]
Default to 0 for non-entry of either filed would be the desired behaviour

Will test on other Resource types and update this issue with the results

**Comment by daiClegg** [comment]
also true for Livestock Products

**Comment by daiClegg** [comment]
also true for Transfers of Food

**Comment by dbrownukk** [comment]
defaults now set for all asset types - deployed.

**Comment by daiClegg** [comment]
**Tested Ok**
