### ISSUE TITLE
Unable to enter Cash Transfer record

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#403]
Instance: EFD_HM
App: OHEA
Module: WGI
Project: NIMFRU
Community: Okorio
WG: Poor

1. Click on Transfers tab
1. Select Cash from Name filed dropdown
1. Enter 'Kin' in Source Filed
1. Select Cash from Transfer Type field dropdown
1. Enter 1 in People Receiving field
1. Enter 1 in Times Received field
1. Enter 10000 in Cash Transfer Amount field
1. Click Save

Message received is: "Wealth group interview modified successfully"
But the record is not saved.

It's not apparent to me what other field i should be entering; this appears to be a valid cash transfer entry.

**Comment by dbrownukk** [comment]
fixed, not all defaults were set..

deployed

**Comment by daiClegg** [comment]
**Tested Ok**
