### ISSUE TITLE
Unable to delete RST

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#404]
Instance: IDAPS_Livelihoods
App: HM Common
Module: RST

1. Search for 'Jack Fruits' (note spelling)
1. Delete the record
 
> Error:  Cannot delete object in row 0 with key {idresourcesubtype=8a80848464c6e6f80164c819e3660020}

I have been deleting other RSTs successfully to clean up the list before loading the Katakwi data.
But this one just keeps hanging on and i can't see why. 
It is not the target of a synonym, nor can it be used anywhere, since there are no Studies or Projects.

**Comment by dbrownukk** [comment]
Localunit, WG Characteristics and WGI Wildfood had references. 

Deleted JackFruits

Also deleted in Prod idaps_livelihoods

**Comment by daiClegg** [comment]
JackFruits gone in both instances.

**Comment by daiClegg** [comment]
caused by corrupted data, marked as such  closed
