### ISSUE TITLE
Unable to delete Local Units

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#406]
Instance: IDAPS_LIvelihoods
App: HM Common
Module: Local Units

There are 4 Local Units defined.
The same 4 as were defined in the test instance.
But while i can delete them in the test instance ( one has gone to prove that), in the production instance they throw the error: 

> "Cannot delete object in row 0 with key {...}

I suspect it is because the LZ they reference is not there.
Another corrupt data issue,i fear but i can't find a way to fix it from within the app.

**Comment by dbrownukk** [comment]
Yep, referenced LZ is missing. Missed this when clearing eth Prod data..

Can now add and delete

**Comment by daiClegg** [comment]
Created & successfully deleted a new local unit.

**Tested Ok**
