### ISSUE TITLE
Report control is available in LZ module, but inoperable

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#407]
Instance: IDAPS Livelihoods
App: HM Common
Module: LZ

In list view the report control is displayed in each row but if you click it it throws error:

> Impossible to execute Report action: Impossible to get object from row

This is a low priority since the user should not be attempting that in this context and if they do the failure is clear and not destructive.

 It should be logged, but can be put into the IceBox if t's not simple and convenient to fix

**Comment by daiClegg** [comment]
The error message is now:
> Impossible to execute Report action: Subview project not found in view of LivelihoodZone. Try to use this.project

possibly due to an XO update.

**Comment by dbrownukk** [comment]
Review and fix

**Comment by dbrownukk** [comment]
Checks if there is a Project context. If not, remove Report icon action button

**Comment by daiClegg** [comment]
**Tested Ok**

**Comment by dbrownukk** [comment]
Deployed to QA and Prod
