### ISSUE TITLE
Report HH DI before & after Change Scenario

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#410]

**Comment by dbrownukk** [comment]
Available off the  HM Common menu / Modelling Scenario

I have been using Katakwi - Nimfru Test 2018 Study and set Price Yield Variation for Crop - Cowpeas dry Yield 125% Price 85%

This applies to all OIHM Modelling Change Scenario reports that I will push over for testing. Cracking on with OHEA modelling..  

deployed

**Comment by daiClegg** [comment]
**Tested OK**

**Comment by daiClegg** [comment]
Re-opening this after testing with a different Change Scenario

Instance: EFD_HM
App: OIHM
Module: Modelling Scenario
Modelling Scenario: aa

Test 1
------
Scenario:                      
> Tomatoes Yield 80% : Price 150%

Households Affected: 
> HH5 - Ocepa Patrick

Actual Result:
> 119809

Expected Result:
> 12000

Comment
> rounding error somewhere?

**Comment by daiClegg** [comment]
Instance: EFD_HM
App: OIHM
Module: Modelling Scenario
Modelling Scenario: Mangoes havin a hard time

Test 2
------
Scenario:

> Mangoes Yield 90%: Price 125%

Households Affected:

> HH5, 6, 8, 12, 15, 16, 33

Results

There were some discrepancies, so i compared the cash income report to see if that was the cause of the DI discrepancy 
The following image shows the results spreadsheet annotated by calculations to compare.
I hid the columns reporting the types of food income to make the screenshot more readable and the only changes are in the crop income columns - which correctly correspond to the totals.
The column 'Actual Yield' is 'Units Produced' in the data

![image](https://user-images.githubusercontent.com/30879677/75359318-282edb00-58ac-11ea-9992-c7ba439d7e5f.png)

Comment

> Some of these are correct, but some do not match.

**Comment by daiClegg** [comment]
I think the problem is that some of the HHs use Mango and others use Mangoes.
These are synonyms.
Change Scenario specifies Mangoes - and the synonyms are not being picked up.

**Comment by daiClegg** [comment]
Instance: EFD_HM
App: OIHM
Module: Modelling Scenario
Modelling Scenario: Multi-element

Scenario:

> Mangoes: Yield 90%: Price 125%
>Groundnuts, dry: Yield 85% Price 130%

Households Affected:

> HH5, 6, 8, 12, 15, 16, 33

Results

**Comment by dbrownukk** [comment]
need to pull your data over to test env

**Comment by daiClegg** [comment]
Yes;  not only did i define new change scenarios i also adjusted the HH data for my test Study

**Comment by dbrownukk** [comment]
TEST 1

The difference is not rounding issue. Seems to be due to a change in shortfall.

shortfall = requiredCalories (forHHMembers) - output. 

Output is down, thus shortfall is greater, which needs to be accounted for in DI

make sense? Need a PhD in numbers....

yet to look at Synonym issue,

**Comment by dbrownukk** [comment]
Synonyms resolved - the price/yield calc was not being picked up if a synonym was involved for RST
deployed

**Comment by daiClegg** [comment]
Re. Test 1 agree; i realised this later when i was beginning to look at Food Income - not tested properly yet.

**Comment by daiClegg** [comment]
Is this ready for testing yet?

**Comment by dbrownukk** [comment]
Yes, ready for testing and deployed now

**Comment by daiClegg** [comment]
For Test 2 above:

HH Mango/Mangoes
5  Mango - sells none so cash income not affected
6  Mangoes 
8 Mango
12 Mangoes
15 Mangoes
16 Mangoes
33 Mango

**Comment by daiClegg** [comment]
For Test 2 above, i'm seeing the same results for Cash Income - HH 8 & HH 33 are unaffected by the scenario.
They are the ones using 'Mango' - the base RST. 
The others use 'Mangoes', which is a synonym for 'Mango'.

Note also that the pre-scenario cash income of HH5, 6, & 8 are different - thought the Scenario has the same effect on them. Did something change in the data?

**Comment by dbrownukk** [comment]
Cut this down to a single Crop in HH 6
Units Produced = 720
Units Sold = 180
Units Consumed = 540
Price 8000
RST name = Mangoes (this is a synonym but should be picked up as a Price / Yield Var)

Aha - am handling Crop income RST of Mangoes (a Syn) but not all possibilities - only fixed half the issue..

Crop Income RST is and is not a Synonym
Price / Yield RST is and is not a Synonym

**Comment by dbrownukk** [comment]
Now handles Mangoes(Synonym) and Mango as Price /Yield changed RST and
Mangoes / Mango in HH Crop sales

Much testing, thinking it is there now...

deployed

**Comment by daiClegg** [comment]
All 3 tests now pass for Cash Income.
Need to check them for Food Income .
Then for DI.
Then forDI with StoL.

When each report passes the 3 tests i'll close them Feature Complete

**Comment by daiClegg** [comment]
Instance: EFD_HM
Application: Modelling (IHM)
Study: Katakwi - NIMFRU Test
Module: Livelihoods Modelling

1. Select Multi-element Change scenario
1. Click Reports
1. Select Change Scenario in MOdel Run Operation
1. Select All Households
1. Click Run
1. Open the resulting Data Extract Spreadsheet.

Attached my annotated copy of this file, with expected & actual results added for Cash Income report, Food income report & DI report
Note the Cash Income & Food Incomes changes reported match exactly what my calculations say they should for all HHs. 
I figure it's unlikely we'd both make the same mistake, soi i'm happy with those results.

But the DI reported change is about 1% out for them all.
I'm calculating DI change as the cost of making up additional food income shortfall less the increase in cash income.

i calculate the cost of makeing up the additional food income shortfall as the cost of the default diet to make up the loss of food income.

What am i getting wrong?

**Comment by daiClegg** [comment]
[ModellingReportsFri Feb 28 17_11_25 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4275287/ModellingReportsFri.Feb.28.17_11_25.UTC.2020.xlsx)

**Comment by daiClegg** [comment]
Note i have re-sorted the data in the attached, in order of HH number. 
That was just to make transcribing actual values from the HH records easier.

**Comment by dbrownukk** [comment]
How have you calculated dietary requirement? Using WGI (2100* 365 * average number of people in Household) or the more complex calc using the WHO data taking into account age and sex?

My calc for IHM dietary req:-

		for (HouseholdMember hm : household.getHouseholdMember()) {
			age = hm.getAge();
			gender = hm.getGender();
			monthsAway = hm.getMonthsAway();
			whoEnergy = WHOEnergyRequirements.findByAge(age);

			if (gender == Sex.Female) {
				energyNeed = whoEnergy.getFemale();
			} else if (gender == Sex.Male) {
				energyNeed = whoEnergy.getMale();
			}

			requiredCalories += energyNeed * 365 * (12 - monthsAway) / 12;

		}

**Comment by daiClegg** [comment]
Ok, i calculated the proper IHM KCal requirement.
Added in annotation in the attached data extract (latest version)

And we should discuss.
In my original calculations, i  realise i **didn't** use AE.
I just calculated the drop in food income and the additional cost of that in default diet.
And then subtracted that from the Cash Income - after the change scenario was applied.

**Comment by daiClegg** [comment]
test results as annotations

[ModellingReportsFri Feb 28 17_11_25 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4288462/ModellingReportsFri.Feb.28.17_11_25.UTC.2020.xlsx)
:

Note the absence of one HH member is not reflected in the AE calculation
And the Unknown sex of one HH Member will take them out of the app calculation, according to the code snippet above

**Comment by dbrownukk** [comment]
Some refactoring - had two ways of calculating food and cash incomes - never good... clearly causing problems today and more than likely in the future.

Concerns raised since, somehow,  wildfood with zero price was giving a result of >0 wildfood cash income, which seemed to give correct results - ref your calculations. Thus need to refactor.

Now doing further checking

**Comment by dbrownukk** [comment]
deployed fix

**Comment by daiClegg** [comment]
**Tested Ok**
