### ISSUE TITLE
Report HH DI with StoL before & after Change Scenario

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#411]

**Comment by dbrownukk** [comment]
deployed

**Comment by daiClegg** [comment]
**Tested Ok**

**Comment by daiClegg** [comment]
Tested with the Multi-element change scenario, as for #410, #412 and #413.
tests results as annotations to the original
[ModellingReportsFri Feb 28 17_11_25 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4278260/ModellingReportsFri.Feb.28.17_11_25.UTC.2020.xlsx)
 data extract file in the attached
