### ISSUE TITLE
Report HH Cash Income before & after Change Scenario

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#412]

**Comment by dbrownukk** [comment]
deployed

**Comment by daiClegg** [comment]
**Tested Ok**

**Comment by daiClegg** [comment]
**Feature Complete**

**Comment by daiClegg** [comment]
Tested with the Multi-element change scenario, as for #410, #411 and #413.

Test results in the uploaded spreadsheets as annotations
[ModellingReportsFri Feb 28 17_11_25 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4278255/ModellingReportsFri.Feb.28.17_11_25.UTC.2020.xlsx)
 to the original report
