### ISSUE TITLE
Report HH Food Income before & after Change Scenario

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#413]

**Comment by dbrownukk** [comment]
deployed

**Comment by daiClegg** [comment]
Instance: EfD_HM
App: OIHM
Module: Change Scenario
Modelling Scenario: aa
Study: Katakwi - NIMFRU Test 2018
HH: 5 Ocepi Patrick

In this (modified) change scenario there is just one variation - Tomatoes, 
For this Household


Grew 40kg of tomatoes at 200Kcal/Kg.
Consumed 20Kg 
Sold 20Kg @ 12,000/Kg = 240,000

Under this Change Scenario:
Tomatoes Yield is down to 80%, Price is up to 150%  
Yield should be 32Kg. 
Still selling 20Kg, so consumed is 12Kg   
Sale proceeds should be 360,000 **Correct**
Cash income gain should be 120000 **Correct**
Food income loss should be 1600Kcal **Incorrect**

**Comment by dbrownukk** [comment]
Reduced my Dev instance with this data down to this Household just having Crop of Tomatoes. 

Crop Food Income is reported as 4000KCals from Consumed Units * 200 KCals / Kg 

The yield reduction of 80% results in a multiplier of 0.8 (is that correct or should it be 'reduced by 80%' so that multiplier is 0.2 ?)

The Food Income is then reported as 3200 KCals which I think is correct. 

For discussion

**Comment by daiClegg** [comment]
Yes, production is down to 32kg. 
But the sale is still 20kg.
So consumption is down to 12kg.
So loss of food income is 8kg at 200Kcal/Kg.

Make sense?

**Comment by dbrownukk** [comment]
Understood. 

production after yield change = yieldchange * unitsProduced
consumption = production - unitssold

fixed in WGI and HH

**Comment by daiClegg** [comment]
Tested with the Multi-element change scenario, as for #410, #412 and #414.
Modulo the issue with DI calculation in #410, no further anomalies occur here.
So assuming (is this correct?) that any change to DI calculation to resolve #410 will be reflected in this issue, then this issue can be regarded as 

**Feature Complete**

**Comment by daiClegg** [comment]
Test results, ass annotations to the original report, in  the attached

[ModellingReportsFri Feb 28 17_11_25 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4278226/ModellingReportsFri.Feb.28.17_11_25.UTC.2020.xlsx)
