### ISSUE TITLE
Report WG Cash Income before & after Change Scenario

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#414]

**Comment by dbrownukk** [comment]
deployed

**Comment by daiClegg** [comment]
Instance: Efd_HM
App: Modelling (HEA)
Project: Karamoja - Central Sorghum and Livestock
LZ: Karamoja - Central Sorghum and Livestock
District/Village  Nakapiripirit/Cucu
Modelling Scenario: HEA Multi-Element

Test results in the attached spreadsheet
[ModellingReportsThu Mar 05 15_15_41 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4293844/ModellingReportsThu.Mar.05.15_15_41.UTC.2020.xlsx)

**Feature Complete**
