### ISSUE TITLE
Report WG DI with StoL before & after Change Scenario

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#416]

**Comment by dbrownukk** [comment]
WG has StOL  Inclusion and Survival - using Inclusion as single StOL value - do we need both?

**Comment by daiClegg** [comment]
IHM only has one set of Standard of living elements.
HEA has two; inclusion is the full set of defined STOL elements. This is  analogous to the IHM STOL. The HEA Survival STOL is calculated by summing the Survival percentage of each STOL element. 
I would like to include  both StoLs

**Comment by dbrownukk** [comment]
StOL Inclusion and Survival added to #416

**Comment by daiClegg** [comment]
Instance: Efd_HM
App: Modelling (HEA)
Project: Karamoja - Central Sorghum and Livestock
LZ: Karamoja - Central Sorghum and Livestock
District/Village  Nakapiripirit/Cucu
Modelling Scenario: HEA Multi-Element

Test results in the attached spreadsheet

[ModellingReportsThu Mar 05 15_15_41 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4293844/ModellingReportsThu.Mar.05.15_15_41.UTC.2020.xlsx)

The calculation of DI with Survival Stol After Change Scenario is not included in the report (omission in the spec), but since the base data (DI after Change Scenario & Survival Stol) are both included it can be calculated & taken care of in the Visualisation spreadsheet.

The results are as expected, modulo the remaining anomaly in DI calculation (#417).

**Feature Complete**
