### ISSUE TITLE
Report WG DI before & after Change Scenario

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#417]

**Comment by dbrownukk** [comment]
deployed

**Comment by daiClegg** [comment]
Instance: EFD_HM
App: OIHM
Module: Modelling Scenario

Tests & results:
----------------
Scenario:                      
> Tomatoes Yield 80% : Price 150%

Households Affected: 

> HH5 - Ocepa Patrick

Actual Result
> 119809

Expected Result
> 12000

Comment
> rounding error somewhere?

**Comment by daiClegg** [comment]
Instance: EFD_HM
App: OIHM
Module: Modelling Scenario

Test 2
------
Scenario:

> Mangoes Yield 90%: Price 125%

Households Affected:

> HH5, 6, 8, 12, 15, 16, 33

Results

There were some discrepancies, so i compared the cash income report to see if that was the cause of the DI discrepancy 
The following image shows the results spreadsheet annotated by calculations to compare.
I hid the columns reporting the types of food income to make the screenshot more readable and the only changes are in the crop income columns - which correctly correspond to the totals.
The column 'Actual Yield' is 'Units Produced' in the data

![image](https://user-images.githubusercontent.com/30879677/75359318-282edb00-58ac-11ea-9992-c7ba439d7e5f.png)

Comment

> Some of these are correct, but some do not match.

**Comment by daiClegg** [comment]
Ignore this - i was testing HH  nit WG. D'oh
Will transfer results to the correct issue.

**Comment by dbrownukk** [comment]
it s getting complex to test! Just about to release the STOL modelling reports with Coping Strategy, when I can convince myself they are heading in the right direction...

**Comment by daiClegg** [comment]
Agree, my head is aching just planning useful test scenarios.

Since one run produces multiple reports and the reports have interdependencies (e.g. cash income affects DI) i will run tests of multiple Change Scenarios on all reports:

1. aa - affects 1 HH in my test study with 1 element
1. mangoes havin a hard time -affects multiple HHs but still only one ewlement
1. multi-element scenario (tbd) - multiple households affected by combinations of multiple entries.

And i will try to write up notes in the different reports that i notice are impacted.

**Comment by daiClegg** [comment]
Leaving aside the discussion y'day (yet to be documented) about how modelling should be accessed, navigated and run. The structure (select change scenario, select just change or change & coping, select HHs/LZ is all very intuitive and works fine.

So at least we're down to testing actual calculations!

And i'm going to pursue the strategy of annotating the results with my own calculations to compare.

**Comment by daiClegg** [comment]
Instance: Efd_HM
App: Modelling (HEA)
Project: Karamoja - Central Sorghum and Livestock
LZ: Karamoja - Central Sorghum and Livestock
District/Village  Nakapiripirit/Cucu
Modelling Scenario: HEA Multi-Element

Test results in the attached spreadsheet
[ModellingReportsThu Mar 05 15_15_41 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4293844/ModellingReportsThu.Mar.05.15_15_41.UTC.2020.xlsx)

DI appears to have similar small variations in OHEA modelling as in OIHM Modelling (#410)

**Comment by dbrownukk** [comment]
deployed fix

**Comment by daiClegg** [comment]
Same test, spreadsheet attached.

[ModellingReportsTue Mar 10 22_19_17 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4315130/ModellingReportsTue.Mar.10.22_19_17.UTC.2020.xlsx)

Food Income calculation comes up with the same results before and after the change scenario.

**Comment by daiClegg** [comment]
This appears to be a regression, #415 tested ok.

**Comment by daiClegg** [comment]
**Tested Ok**

i had errors in my calculation of the KCal value of the standard diet

**Feature Complete**

**Comment by daiClegg** [comment]
Annotated test data extract attached:

[ChangeScenarioNakapiripirit.xlsx](https://github.com/dbrownukk/EFD_v2/files/4323710/ChangeScenarioNakapiripirit.xlsx)
