### ISSUE TITLE
Report HH DI  after Change Scenario with Coping Strategy

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#418]

**Comment by dbrownukk** [comment]
Deployed

**Comment by dbrownukk** [comment]
Query on definition in OHEA.OIHM.ModellingV1.4

The Coping Strategy includes an Expandability Rule: 
•	Rice: ExpandabilityLimit 0%; ExpandabilityIncreaseLimit 0% (i.e. no limits)
•	The amount of Rice HH1 can sell under the expandability rule is the lesser of:
•	Total Production = 1000kg
•	So, execution of this Expandability Rule for HH1 results in the sale of 700kg Rice, materializing a cash gain of 700 * 150 = 10500 units of currency.

Is UnitsOther or UnitsConsumed used to calculate what could be sold? i.e. in this case, if 300 of the 1000 is sold and unitsOther or unitsConsumed > 0 then there would be less to sell.

Also, a little more on the 'lesser of' clause.

This applies to all the Coping Strategy reports

**Comment by daiClegg** [comment]
The words “  the lesser of“ are superfluous.
They were left behind misdated ly when I last edited this example.

So the coping strategy in this case would result in increased income from the additional sale, and decreased food income, which would have to be compensated for by additional purchase of default diet items, just as when a change scenario reduces food income.
Make sense?

**Comment by dbrownukk** [comment]
Deployed latest version of this report, to add to the Change Scenario reports. Needs more sensible data to test, just tested a few examples before departing south..

Simple testing of this report looks correct, though plenty to discuss once I can think through the many scenarios. 

Reports 419, 420 and 421 are in the reports spreadsheet but are not complete. They will drop out easily once 418 is proven.

To run the reports go to the HM COMMON menu, and you will see Expandability Rules and Modelling Scenario. In Modelling Scenario select a Project or Study, go to the detail and select Report on top menu. 

Select between Change Scenario or Coping Strategy radio button and select appropriate sites or HH

Hopefully clear enough. Will have email but no dev env.

**Comment by daiClegg** [comment]
Instance: EFD_HM
Application: Modelling (IHM)
Study: Katakwi - NIMFRU Test
Module: Livelihoods Modelling

1. Select Multi-element Change scenario
1. Click Reports
1. Select Change Scenario in MOdel Run Operation
1. Select All Households
1. Click Run
1. Open the resulting Data Extract Spreadsheet.

Attached my annotated copy of this file, with expected & actual results added for Cash Income report, Food income report & DI report
Note the Cash Income & Food Incomes changes reported match exactly what my calculations say they should for all HHs. 
I figure it's unlikely we'd both make the same mistake, soi i'm happy with those results.

But the DI reported change is about 1% out for them all.
I'm calculating DI change as the cost of making up additional food income shortfall less the increase in cash income.

i calculate the cost of makeing up the additional food income shortfall as the cost of the default diet to make up the loss of food income.

What am i getting wrong?

**Comment by dbrownukk** [comment]
Will investigate the spurious 1%

Couple of thoughts 

1. This current Issue #418 is for HH DI + Change Scenario and Coping Strategy. The report you tested is #410 I believe. 

Not that this should make a difference to the query on DI as the calculation for DI is the same across all reports.

2. Thanks for updated Coping Strategy results spreadsheet. Just built first of them and have a 
query, which refers to this issue report #418.   In the HH Cash Income, Column N for First Rule I 
am struggling to set a negative value so that Rule is triggered.  This is based on Total Cash Income after Change Scenario. For discussion

**Comment by daiClegg** [comment]
Re point 1 - have moved those test results to the correct issue.
Re pint 3 will upload the annotated results to that issue (#410)

**Comment by daiClegg** [comment]
Re Point 2 - Coping strategy rules are triggered as long as the Disposable INcome is negative - not Cash Income.
Have i misdescribed this in the spec document? Will check.

**Comment by daiClegg** [comment]
INstance: EFD_HM
App: Modelling (OIHM)
Study: A Study
HH: 8 Ocepa Patrick
Change Scenario: Sweet Potato & Groundnuts

Change Scenario is:
Sweet potatoes: Yield 50%, Price 150%
Groundnuts: Yield 55%, Price 160%

Coping strategy Expandability Ruyle is Sell More Mangoes (no limit)

Results attached.
[CopingAn oihm prSat Mar 14 18_20_26 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4333175/CopingAn.oihm.prSat.Mar.14.18_20_26.UTC.2020.xlsx)

Some observations:
1. the DI & the DI with StoL increase by the amount realised by selling all the remaining Mangoes
1. Tne Cash income increases by the amount realised by selling only some of the Mangoes.
1. the food income doesn't change

But the food income should decrease by the number of Kcals lost from the additionally sold Mangoes.
The DI & DI with StoL should increase by the amount of the sold Mangoes less the cost of the purchase of additional Default Diet to cover the Kcal loss from the sold Mangoes.
It's not clear to me whare these discrepancies arise.

Additionally, and this is probably an ambiguity in the spec, only sufficient Mangoes should be sold to take the DI with StoL +ive. 
The rule isn't 'sell up to the limit, the rule is 'sell as much as is necessary, up to the limit'.

Will reference this note in the other affected issues, since they are all connected.

**Comment by dbrownukk** [comment]
Food income now decreases by the number of Kcals lost from the additionally sold Mangoes.
This is deployed. I will just set this issue for testing, leaving associated issues at 'In Progress'

Your note-
_Additionally, and this is probably an ambiguity in the spec, only sufficient Mangoes should be sold to take the DI with StoL +ive.
The rule isn't 'sell up to the limit, the rule is 'sell as much as is necessary, up to the limit'._

My Thoughts:-

This would need a goal seek to find out how much needs to be sold to turn DI+SToL positive. If sold as much as they have, then and only then move onto next expandability rule? Where would we report number of mangoes sold to achieve positive DI+SToL?

**Comment by daiClegg** [comment]
Re Goal Seeking - yes, i agree. Let's keep goal-seeking for a wider scope, where we're trying to optimise the whole Coping Strategy, rather than the execution of one rule.

Test results to follow...

**Comment by daiClegg** [comment]
Test results spreadsheet uploaded here, with some annotations.
The changes in Cash Income & Food income are not what i calculated.
Time to discuss?

[CopingAn oihm prMon Mar 16 21_30_03 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4340667/CopingAn.oihm.prMon.Mar.16.21_30_03.UTC.2020.xlsx)

**Comment by dbrownukk** [comment]
Thanks for annotated spreadsheet. Think I see what is happening. Hold discussion for the moment..

**Comment by dbrownukk** [comment]
As discussed, have redeployed this report - same applies to all Food/Cash Coping Strategy reports

**Comment by daiClegg** [comment]
Cash Income (#420) & Food Income(#421) appear to be correct on basic testing.
DI does not account for the spend on additional default diet items needed.

DI with Stol (#419) tbd...

**Comment by daiClegg** [comment]
Annotated test results here:
[CopingAn oihm prTue Mar 17 16_16_13 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4344788/CopingAn.oihm.prTue.Mar.17.16_16_13.UTC.2020.xlsx)

**Comment by dbrownukk** [comment]
#418 now correct as per test results. Reworked the point of calculation of some of the values to further simplify. Still supports individual reports if they were needed in the future

**Comment by daiClegg** [comment]
**Feature Complete**

Annotated test results attached:

[CopingAn oihm prThu Mar 19 15_19_31 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4355444/CopingAn.oihm.prThu.Mar.19.15_19_31.UTC.2020.xlsx)

**Comment by daiClegg** [comment]
Correct results here, not annotated, but the reports now all match the annotation calculations above:

[CopingAn oihm prTue Mar 24 22_42_53 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4377983/CopingAn.oihm.prTue.Mar.24.22_42_53.UTC.2020.xlsx)
