### ISSUE TITLE
Report HH DI with Stol after Change Scenario with Coping Strategy

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#419]

**Comment by dbrownukk** [comment]
deployed

**Comment by daiClegg** [comment]
See note in #418

**Comment by dbrownukk** [comment]
Included DDI cost of deficit in Expandability calculation ( - cost of deficit purchase)

deployed

**Comment by daiClegg** [comment]
**Feature Complete**

Annotated test results attached:

[CopingAn oihm prThu Mar 19 15_45_53 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4355507/CopingAn.oihm.prThu.Mar.19.15_45_53.UTC.2020.xlsx)

See also test results attached to #418 for validation of the component calculations this is dependent on.
