### ISSUE TITLE
New  Communities should constrain the LZ pick list to LZs already in theProject

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#42]
Invoke Communities module in List view 
Scroll to see Communities of project "TestIssue36"
 - none visible
Add new Site to Project TestIssue36 in LZ 'TestIssue36' with district/subdistrict 'TestDistrict'/'TestSubDistrict'
Save
 - Save reports successful execution

Scroll through List view
 - new Community is not there

Repeat
 - get constraint violation exception.
  - " Impossible to execute Create action: org.hibernate.exception.ConstraintViolationException: could not execute statement"

Apparently the site is there but not visible.
Logged off and on, still no sign of my test site

**Comment by daiClegg** [comment]
Also if i assign the new Community to a site in a different LZ to the newly created site then in the Project view the second LZ now apparently associated with the project is not shown,

**Comment by daiClegg** [comment]
If i select an existing Community from the list view, then switch to Detail view and add a new Site, the new Site, Interview & Participants data is displayed.

But if the Community that was originally displayed had WGs, they are still displayed now - apparently associated with the new Site

I suspect this is related to this issue, so i did not log as a different Issue. 
Just noting this here to test when this issue is fixed,

**Comment by dbrownukk** [comment]
Definitely something strange here. 

The first issue - You create a new Site, within Community and a Project.

After New button pressed in Community you assign a Project and then add a New Site with + in Site block. Pick a LZ - should be within current Project. Add District and Sub District names, click create. The Site is created and associated to the Project and LZ but the community is not saved at that point - you need a mandatory Interview Date and Sequence - then Save the community. Suspect need to discuss..

Second issue

_Also if i assign the new Community to a site in a different LZ to the newly created site then in the Project view the second LZ now apparently associated with the project is not shown,_

Aha. If you search for a new Site it is correctly in the context of Project and will list all Sites and LZs in the current project. However, if you 'edit' or select + (new) you can select any LZ from any Project, thus is missing the restriction.
 
Third Issue

Is that desirable behaviour? Was the Site defined wrongly but the WGs were correct? We could clear the WGs if the Site is changed.

**Comment by daiClegg** [comment]
WGs belong to a Community, which is at a site. If i changed the Site (New or different existing one) that would seem strange.
But it might be the user correcting an earlier error (i thought these WGs was in VillageX, it’s actually VillageY, i just made a mistake in data entry). In which case we keep the WGs.

I think i was confusing myself. I’m going to do some more testing and possibly just close this issue.

**Comment by daiClegg** [comment]
Retested this and it works as expected (when i included the Interview & participants data), except, if you add a site in an LZ that is not in the project that is not added to the project. 


To see this: 

> See Project "TestIssue36"; 
> View in Communities module, List view: it has 5 sites, in 2 LZs (one in Z1 & four in  TestIssue36).
> But in  Project module, detail view of Project "TestIssue36" 2 LZs are listed
> Z1 is not one of them. The spurious one (Zone44) was included before i added the Site in LZ "Z1".


Either the drop down should only allow LZs already in the project, or it should add the LZ.
I think we agreed that it is acceptable UX to constrain to already included LZs.

So the issue here is not constraining the LZ dropdown.
I will change the issue title accordingly. OK

**Comment by dbrownukk** [comment]
In Community Detail

Site Block 

Search with the spotlight restricts to 
'not current site if there is one' 
and
Only Sites in this LZ in this Project

Add + brings up an 'Add Site box

Search brings back LXs for current  project 


TODO
Still small issue with a missing ID on Save of Community afre clearing Views after changing Project.

**Comment by daiClegg** [comment]
Works are required for Search.

if you click  + in Site block, you get new Site popup.
LZ dropdown is not constrained to LZs already associated with the  Project.
And if you pick another LZ, it will create a new site (can see it in Site module).
But it is not associated with the Project (can't see in the Communities module)

**Comment by dbrownukk** [comment]
New site within Community now has a filter on Livelihoodzone within Project

**Comment by daiClegg** [comment]
Tested Ok.
