### ISSUE TITLE
Report HH Cash Income after Change Scenario with Coping Strategy

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#420]

**Comment by dbrownukk** [comment]
Any thoughts on results spreadsheet presentation of Cash/Food Income with Change Scenario and Coping Strategy? Not in example Coping Strategy spreadsheet. 

Assuming Rule1, Rule2, Rule3 columns after existing column of Total Cash/Food Income After Change Scenario ?

**Comment by daiClegg** [comment]
The example spreadsheet is clearly incomplete. Whoops.
And it only deals with IHM - OHEA with its 2 stage StoL is not shown.
I need to update the sample before we discuss, i think.

**Comment by daiClegg** [comment]
Revised Sample data spreadsheet attached.
[CopingStrategyExampleDataV1.4.xlsx](https://github.com/dbrownukk/EFD_v2/files/4270662/CopingStrategyExampleDataV1.4.xlsx)

**Comment by dbrownukk** [comment]
deployed

**Comment by daiClegg** [comment]
Instance: EFD_HM
App: Modelling (OIHM)
StudY:  Katakwi NIMFRU - test
Change Scenario: Multi-element
HH: 5 Ocepa Patrick

The only Coping Strategy Rule for this study is Tomatoes, with no limit specified (default).
The Change Scenario i have previously tested satisfactory, so i'm not going to go into that here.

I ran all the Coping strategy reports. 

This household consumes 20Kgs and sells 20Kgs of Tomatoes.
The price is 12,000/Kg
The nutritional value of Tomatoes is 200KCal/Kg

Tomatoes are not affected by the change Scenario.

So i expected the Coping strategy to affect the HH Cash income (20*12000 = 240,000)
And the food income to diminish by 20*200 - 4,000KCal
But food income does not change (will post this same test result in #421 )
Cash income is not reported - what is in the column (N) labelled 'INcome after Change Scenario and Rule 1 is the Disposable INcome, not the Cash Income (possibly ambiguity in the spec)

results spreadsheet uploaded here> Since there is only 1 HH, and hence very simple results i haven't done the comparison annotations

[CopingNIMFRUThu Mar 12 22_06_37 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4326913/CopingNIMFRUThu.Mar.12.22_06_37.UTC.2020.xlsx)

**Comment by daiClegg** [comment]
See comment in #418

**Comment by daiClegg** [comment]
**Feature Complete**

Annotated test results:
[CopingAn oihm prTue Mar 17 16_16_13 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4344791/CopingAn.oihm.prTue.Mar.17.16_16_13.UTC.2020.xlsx)
