### ISSUE TITLE
Report HH Food Income after Change Scenario with Coping Strategy

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#421]

**Comment by dbrownukk** [comment]
as per #422 - may need discussion, but deployed

**Comment by daiClegg** [comment]
Instance: EFD_HM
App: Modelling (OIHM)
StudY:  Katakwi NIMFRU - test
Change Scenario: Multi-element
HH: 5 Ocepa Patrick

The only Coping Strategy Rule for this study is Tomatoes, with no limit specified (default).
The Change Scenario i have previously tested satisfactory, so i'm not going to go into that here.

I ran all the Coping strategy reports. 

This household consumes 20Kgs and sells 20Kgs of Tomatoes.
The price is 12,000/Kg
The nutritional value of Tomatoes is 200KCal/Kg

Tomatoes are not affected by the Change Scenario.

So i expected the Coping strategy to affect the HH Cash income (20*12000 = 240,000)
And the food income to diminish by 20*200 =  4,000KCal
But food income does not change 

Results spreadsheet uploaded here> Since there is only 1 HH, and hence very simple results i haven't done the comparison annotations

[CopingNIMFRUThu Mar 12 22_06_37 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4326913/CopingNIMFRUThu.Mar.12.22_06_37.UTC.2020.xlsx)

**Comment by dbrownukk** [comment]
Would the expandability rule only be triggered if the DI (after change scenario) is negative?

In this case DI is positive, thus it is not triggered. 

The calculation of -4000KCal  is correct when I debug the expandability calculation. It is just not shown.

**Comment by daiClegg** [comment]
Of course, you're right. I had forgotten the vital last step of forcing the DI to go -ive in the Change Scenario. My first effort at that (removing paid employment) had not been enough.

Encouraging,that the calculation in the debug and my calculation match.

Will return to testing at the weekend.

**Comment by daiClegg** [comment]
See comment in #418

**Comment by daiClegg** [comment]
**Feature Complete**

Annotated test results:
[CopingAn oihm prTue Mar 17 16_16_13 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4344791/CopingAn.oihm.prTue.Mar.17.16_16_13.UTC.2020.xlsx)
