### ISSUE TITLE
Report WG Food Income after Change Scenario with Coping Strategy

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#422]

**Comment by dbrownukk** [comment]
deployed - may need discussion on understanding of  displaying expandability rule results for food

Can food income as reported be negative? Expandability food results are calculated and output if previous value was not  > 0, not sure if this makes sense. 

Take a look and for discussion

**Comment by daiClegg** [comment]
The trigger for executing the next expandability rule is if the **DI** is negative.
Food income itself can't be -ive but it will be affected by the execution of expandability rules - because they often involve selling more of what otherwise would have been consumed.
That then becomes the trigger for buying more of the default diet, which diminishes the DI - hopefully by less than the rule increased the cash income.

Make sense?

**Comment by daiClegg** [comment]
I will test this as is as part of the WG Coping Strategy.

**Comment by daiClegg** [comment]
See test notes and results in Issue #425

**Comment by dbrownukk** [comment]
deployed as per #425

**Comment by daiClegg** [comment]
**Feature Complete**

Annotated spreadsheet attached.
Also has some partial results for Cash income (Issue #423); not relevant to this issue.

[CopingKaramoja -Sat Mar 28 16_41_47 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4398681/CopingKaramoja.-Sat.Mar.28.16_41_47.UTC.2020.xlsx)

**Comment by daiClegg** [comment]
Re-opening, because although the calculations were correct, they should not have been applied, in the case of the MIlk Rule, which wasn't needed as all the WGs were +DI by then.

Revised annotated results spreadsheet attached here:

[CopingKaramoja -Sat Mar 28 16_41_47 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4398751/CopingKaramoja.-Sat.Mar.28.16_41_47.UTC.2020.xlsx)

**Comment by daiClegg** [comment]
I ran further tests for #423.
I noted some impact on this issue, so added annotations in the data extract file accordingly.
Uploaded here as well.

[CopingKaramoja -Mon Mar 30 14_36_30 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4403671/CopingKaramoja.-Mon.Mar.30.14_36_30.UTC.2020.xlsx)

**Comment by dbrownukk** [comment]
fixed Expandability values

deployed

**Comment by daiClegg** [comment]
Unable to run Livelihoods reports with coping on HEA Projects.
Note if the Project has no expandability the reports run (with no coping)
But if at least one expandability rule exists, the report run fails:
> Impossible to execute Run action: null

**Comment by dbrownukk** [comment]
Fixed. Deployed. (damn debug statement caused issue)

However, noticed that the Mukono New Test has Extensibility rule for Butere but not for other Communities you can select in an HEA Coping Strategy report. 

At the moment, the Expandability rule is then ignored as it is not applied to all communities. 

What should it do? Various approaches. For discussion.

**Comment by daiClegg** [comment]
You're right that it makes no sense to calculate Coping Strategy impact for a Community that has no Coping Strategy. 
But equally, it might be that the user only wants to model the impact on a subset of the Communities. They can do that by selecting Communities individually - so that is supported, but the dialogue doesn't tell the user which ones can be usefully included. 

Maybe the list that offers Communities for inclusion in the model run should grey out the Communities for which no expandability rules exist?
But they can still be included for the change scenario, so in that case, they should grey out only when the Coping Strategy option is chosen.

Sounds like complex logic in the dialogue, but i think we need to help the user.

**Comment by daiClegg** [comment]
Is this ready for testing? The notes suggest it is, but the status not so.

**Comment by dbrownukk** [comment]
It is now. New PC in action now. Also have ordered the Modelling Scenarios List view and the Expandability Rules List (in Community and Study) 

deployed.

Note that in Modelling Scenario Module if you change an LZ you need to Save changes before running Report. Neatly, have added a check that highlights the fact that you are throwing away changes if you run report before saving any changes. 

Deployed

**Comment by daiClegg** [comment]
Some notes above really relate to the dialogue used to invoke the reports, not the subject of this issue. That's Issue #450.
Will reference this thread from there and test..

**Comment by daiClegg** [comment]
re-did the test from 21 days before this comment.
**Tested Ok**

Latest results attached (with annotations, just for #422)
[CopingKaramoja -Mon Apr 20 19_27_44 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4505743/CopingKaramoja.-Mon.Apr.20.19_27_44.UTC.2020.xlsx)

No other outstanding anomalies

**Comment by daiClegg** [comment]
**Feature Complete**
