### ISSUE TITLE
Report WG Cash Income after Change Scenario with Coping Strategy

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#423]

**Comment by dbrownukk** [comment]
deployed

**Comment by daiClegg** [comment]
See test notes and results in Issue #425

**Comment by dbrownukk** [comment]
deployed as per #425

**Comment by daiClegg** [comment]
Instance: EFD_HM
App: Modelling
Module: Livelihoods Modelling
Project: Karamoja - Central Sorghum and Livestock
Village: Cucu

Ran the reports with Coping Strategy.
Annotated results spreadsheet uploaded.
Unnecessary expandability Rule appears to have been applied.

[CopingKaramoja -Sat Mar 28 16_41_47 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4398747/CopingKaramoja.-Sat.Mar.28.16_41_47.UTC.2020.xlsx)

**Comment by dbrownukk** [comment]
Annotations really help

fix deployed

**Comment by daiClegg** [comment]
Ran the same test again.
Results for Cash INcome as expected.

Annotated results data extract uploaded here:

[CopingKaramoja -Mon Mar 30 14_36_30 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4403642/CopingKaramoja.-Mon.Mar.30.14_36_30.UTC.2020.xlsx)

Additional annotations related to testing of #425  & #422 are included, but not relevant for this issue. They are documented in those issues.

**Feature Complete**
