### ISSUE TITLE
Report WG DI after Change Scenario with Coping Strategy

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#425]

**Comment by dbrownukk** [comment]
deployed

**Comment by daiClegg** [comment]
Instance: EFD_HM
App: Modelling (HEA)
Project: Karamoja - Central Sorghum and Livestock

Having edited the Poor  WG data fairly savagely i managed to get theri DI to be -ive.
Reports attached here:
[All ReportsWed Mar 18 18_21_42 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4350661/All.ReportsWed.Mar.18.18_21_42.UTC.2020.xlsx)

So then i ran the coping strategy reports, annotated spreadsheet attached:
[CopingKaramoja -Tue Mar 17 22_10_34 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4350666/CopingKaramoja.-Tue.Mar.17.22_10_34.UTC.2020.xlsx)

- The base reported data (DI, StoL, Cash & Food Income all match up.
- I didn't check the Change Scenario impacts. I take those on trust, since i just tested all that. Is that safe?
- The Coping Strategy numbers i did check and they don't seem to be right.

There are some more detailed notes in the uploaded spreadsheet.
We should discuss, i think.

**Comment by daiClegg** [comment]
In case it's useful, Uploaded latest test.

Same Village as above. To test #449 i changed the expandability limit to 50% of herd, so i just ran the coping strategy reports anyway:

[CopingKaramoja -Fri Mar 20 15_55_32 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4360774/CopingKaramoja.-Fri.Mar.20.15_55_32.UTC.2020.xlsx)

The results are not what i expected. expandability limit of 50% on a herd of 20 is 10.
6 sold already so i would expect 4 more to be sold.
10 appear to have been sold.

I assume this is still wip, since you hadn't assigned it to Testing.
But i did the test and so thought i'd update here anyway.

**Comment by dbrownukk** [comment]
deployed a small rework of the WGI expandability reports. Pig income change should be 60000 and Milk 19200 in the above example. 

Is it correct that a Livestock Sale makes no change to Food KCal income/loss? It does increase cash income.

**Comment by daiClegg** [comment]
As discussed: Livestock Sale makes no difference to Food Income.
It is disposal of an Asset.

**Comment by daiClegg** [comment]
I ran further tests for #423.
I noted some impact on this issue, so added annotations in the data extract file accordingly.
Uploaded here as well.

[CopingKaramoja -Mon Mar 30 14_36_30 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4403671/CopingKaramoja.-Mon.Mar.30.14_36_30.UTC.2020.xlsx)

**Comment by daiClegg** [comment]
Repeated previous test
**Tested Ok**

Annotated results uploaded:

[CopingKaramoja -Mon Apr 20 19_27_44 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4505836/CopingKaramoja.-Mon.Apr.20.19_27_44.UTC.2020.xlsx)

**Feature Complete**
