### ISSUE TITLE
Irrelevant error messages in Households module

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#426]
Instance: IDAPS Livelihoods
App: OIHM
Module: Households

1. select HH module
> See attached screenshot

![Screenshot 2020-01-14 at 16 21 47](https://user-images.githubusercontent.com/30879677/72368192-78cfe780-36f5-11ea-914b-abc348b86c45.png)

**Comment by dbrownukk** [comment]
Looks like an OX bug. Not an error message that I have added. Occurs on 'New' 

The error is a result of trying to set defaults in the Assets i.e. 0 for crops  unitsSold.

**Comment by daiClegg** [comment]
**Tested OK**
