### ISSUE TITLE
Employment Recording is not aligned with field practice for data collection 

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#428]
The attached Obarute, Poor interview data, record employment data in a way that is not meaningful for OHEA.
Celia, James & Dai discussed.

The points that emerged from that discussion are:
The interviewer is recording Employment as the number people working, number of days worked per month, the number of months this employment is available and the day rate per person. 
They are not recording the unit of work explicitly. And they are recording the seasonality of the employment. 
But the product of:  

> (number of people working * number of days per month worked * number of months worked * day rate) 

correctly calculates cash income. So there is no loss of semantics **if** work can always be expressed as days/month. Also  there is additional seasonal information captured that could be used for a full Seasonality Analysis - although other information would also be needed for that (seasonality of employments and seasonality of produce sales).

The question is, should this alternative method of encoding employment be implemented or not?
Note that it adds no value unless Seasonality Analysis is needed. OHEA does not currently support Seasonality Analysis. 
And if this is adopted there is a cost just to accommodate the change of encoding, which is incurred regardless of whether Seasonality Analysis is added, at further cost, later.

For discussion by domain experts

[Obarute poor.xlsx](https://github.com/dbrownukk/EFD_v2/files/4067771/Obarute.poor.xlsx)

**Comment by DrJohnSeaman** [comment]
I introduced this originally to avoid the problem of errors in calculation by field workers - let the software do the calculation and give an analyst the detail to judge if the record appears to be reasonable. Otherwise all there is is a number, in some currencies a very large number sometimes with more zeros than seems reasonable. So a number is OK - really this is a discussion about proper training of field workers.

**Comment by daiClegg** [comment]
After discussion, Celia, James, John agreed that the current treatment in OHEA is fine.
