### ISSUE TITLE
Exception running OHEA reports

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#430]
Instance: EFD_HM (test)
App: OHEA
Module: Project
Project Homabay Test

1. In detail view of Homabay Test project, click reporting icon on Sugar cane & bricks LZ record.
1. In pop-up Report dialog, select All Reports report spec from Report Spec drop-down.
1. Select Sugar cane & bricks (the only) LZ
1. Click Run

> ERROR: java.lang.ArrayIndexOutOfBoundsException: 3 Errno = 1108

Ran the same scenario successfully for both LZs in Mukono - New Test project,

**Comment by dbrownukk** [comment]
Homabay Test Project has two LZs for Villages Homabay and Kabonyo.

Homabay LZ creates report, Kabonyo fails, stating that no Valid Wealthgroups meet the criteria - investigating this

**Comment by daiClegg** [comment]
Hmm.

The exception no longer reproduces.
But the results are puzzling:

This is a screenshot of the WGIs for this LZ:
![image](https://user-images.githubusercontent.com/30879677/72829962-9f52cd00-3c77-11ea-8207-a2aa8b0f48e8.png)

Note that neither village has 3 validated WGs.

When i run the reports and select both Communities the data extract summary page lists both villages as included.
And the DI tab (the first one with actual data) shows only one village:

![image](https://user-images.githubusercontent.com/30879677/72830194-1a1be800-3c78-11ea-832f-d335f57ed085.png)

Note also the average number in household value is different in the WGI record and the data extract. This may well be a separate issue, but i'll log it if/when you confirm.

**Note** as discussed in #429, we may need to change the constraints on reports. you might prefer to discuss that before making changes to resolve this.

**Comment by dbrownukk** [comment]
Spurious data reporting needs fixing. Will tackle this now. Lets discuss #429 in a call

**Comment by dbrownukk** [comment]
Looping through the Community sites but not restricted to current Project. Hence picking up 'Student Demo' wealthgroups in Kisumu Homabay

**Comment by daiClegg** [comment]
**Tested OK**
