### ISSUE TITLE
Error running OHEA reports 

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#433]
Instance: EFD_HM
App: OHEA
Module: Project
Project: Karamoja - Central Sorghum and Livestock

1. in detail view of the project run reports 
(only one LZ:  Karamoja - Central Sorghum and Livestock)
1. Select All Reports from Report spec drop down.
1. Select Community (only 1: Cucu)
1. Click Run

> reports run and data extract is downloaded (attached below)
> message says reports successfully created, followed by 2 error messages (see screenshot).

[All ReportsTue Jan 21 17_43_38 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4098055/All.ReportsTue.Jan.21.17_43_38.UTC.2020.xlsx)

![image](https://user-images.githubusercontent.com/30879677/72907735-53159480-3d2c-11ea-9e89-c09c7342682e.png)

**Comment by dbrownukk** [comment]
Transfer Type is null which raise null exception, now to figure out why it has been allowed to be null.

Database transfertype should be not null. Attribute is definitely set to not null in Entity but not so in database schema.

Added @Required to transfer module transfertype 

deployed

**Comment by daiClegg** [comment]
**Tested Ok**
