### ISSUE TITLE
Wild Foods data entry does not default sold & other use values

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#434]
Instance: EFD_HM
App: OHEA
Module: WGI

1. Navigate to any WGI record in detail view.
1. Navigate to Wild Foods tab, select a wild food from the Name drop[down, enter Kg in the Unit and 100 in the Units Produced. 
1. Set the Status to Valid
1. Click Save
> record disappears with no error message

1. Repeat steps 1 & 2 above
1. Enter 0 in Units Sold and Other Use
1. Tab beyond the Other Use field to calculate the Units Consumed
1. Set the Status to Valid
1. Click Save
> record is saved successfully

The user has to enter two 0s and three tabs unnecessarily in order to succeed, and they get no explanation of why they've failed if they don't.
Defaulting Units Sold & Other Use to 0 and triggering the calculation would improve the user experience

**Comment by daiClegg** [comment]
The Creops, Transfers & Livestock Products tabs do have the defaults and the calculation appears to be triggered by moving to the Status drop down. 
Only missing on Wild Foods.

**Comment by dbrownukk** [comment]
Fixed on Wildfoods. Deployed

**Comment by daiClegg** [comment]
**Tested Ok**
