### ISSUE TITLE
OIHM StoL calculation seems wrong

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#435]
Instance: EFD_HM
App: OIHM
Module: Reporting
Study: Katakwi - NIMFRU Test
HH: HH5 (Ocepa Patrick)

1. Select Reports for above study
1. Select All Reports report spec 
1. Select HH5 (Ocepa Patrick) as the only HH to be included
1. Run the report
1. In Report data extract file, navigate to HH DI with StoL 

> note cost of StoL is 206000

6. In OIHM Study Module, detail view for the above Study, click StoL Element tab
> Note the components of the StoL:
![image.png](https://images.zenhubusercontent.com/5a81590c4b5806bc2bc688fc/4795ca38-9635-4671-8a16-b2d3f4858a60)

7. Invoke detail view of the 2 Clothing items to see they apply to children (3 - 13) & Adults (14 - 110) respectively
1. In the OIHM HH  Module, in the detail view for the above HH, click HH member tab
> Note the HH members:
![image.png](https://images.zenhubusercontent.com/5a81590c4b5806bc2bc688fc/727598da-a3d9-4965-9c92-cfdbab01776f)

> I make the Stol:

0 * Childs Clothing (0) +
3 * Adults Clothing(45000) +
1 * Drugs (36000) +
1 * Soap (110000)
= 191,000

**Comment by dbrownukk** [comment]
STOL calc had extra loop calculating HHM STOL 

fixed deployed - also fixed in OIHM Report as they use same code

**Comment by daiClegg** [comment]
**Tested OK**
