### ISSUE TITLE
Unable to Parse or Validate a hand-entered WG interview data set

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#436]
Instance: IDAPS_Livelihoods
App: OHEA
Module: WGI
Project: NIMFRU
LZ: Katakwi - Crop & Livestock Zone 
District: Katakwi 
Village: Obarute 
WG: Poor

In the detail view of the WG, note that there is an extensive data set of assets, all of which are in state Valid and the record saves successfully.

I created this WGI record by hand entry, rather than by uploading a spreadsheet.
In the first test, the Status was "Generated".

1. Click Validate
> ERROR: Impossible to execute Validate action: null
2. Click Parse Interview Spreadsheet
> (as expected) ERROR: Impossible to execute Parse Interview Spreadsheet action: null

I tried with the Status set to Uploaded, Part Parsed and Fully Parsed, but with no difference to the result.

I didn't attach a spreadsheet, cos i thought that might affect the internal state that's causing the problem.

This is the first WGI for a full production data set that i want to load for this Project.

**Comment by dbrownukk** [comment]
No uploaded spreadsheet - there is a test for spreadsheet field being empty, but empty is not null..

The whole flow depends on a spreadsheet being uploaded, but ease of data entry might negate this..

The checks for Status - Generated/Uploaded make no sense if a spreadsheet is not uploaded. 

Have changed ValidateAssets routine to ignore check of Spreadsheet being present, if spreadsheet is present will check if sequence is correct i.e. Must be Fully Parsed for Validation.

**Comment by daiClegg** [comment]
**Tested Ok**
