### ISSUE TITLE
Units Consumed not correctly calculated for Crops

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#437]
Instance IDAPS_LIvelihoods
App: OHEA
Module: WGI
Project: NIMFRU
LZ: Katakwi - Crop & Livestock Zone 
District: Katakwi 
Village: Obarute
WG: Poor

Navigate to Crops tab and note that although all the records are saved, the Units Consumed has not been calculated for any of them.
It is actually possible to successfully Validate the WGI in this state.
And any new Crop record will behave in the same way,

**note to self** there are 10 valid crops:

![image](https://user-images.githubusercontent.com/30879677/75096132-5d79b700-5594-11ea-96fe-4844337dc60a.png)

Anymore will be test data that can be removed

This issue does not reproduce in the latest test instance, but i can't work out from the closed issues which one fixed it.

**Comment by dbrownukk** [comment]
Will take backup of IDAPS_LIvelihoods and upgrade the Crops module which is used by WGI module

**Comment by dbrownukk** [comment]
deployed latest version to IDAPS_Livelihoods

Units consumed calc now working

**Comment by daiClegg** [comment]
**Tested Ok**
