### ISSUE TITLE
When entering Wild Foods, Units Produced & Other Use do not default (OHEA & OIHM)

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#439]
Instance: EFD_HM (Also present in IDAPS_Livelihioods
App: OHEA (also present in OIHM)
Module: WGI
Project: Test #350
Village: Knowl Hill 
WG: #350Test WG

1. In Detail view, select Wild Food Tab
1. select any Wild Food in the Name drop-down
1. Enter 100 in the Units produced field
1. Tab through the Units Sold, Units Other Use and Units Consumed fields
1. Select Valid from the Status drop-down
1. Click Save

The record disappears.

1. Repeat the above sequence, except entering 0 in the Units Produced & Units Other Use fields

The record saves successfully

The defaults are provided in Crops, so the user would expect them here as well.
But since there is a simple workaround this is not an urgent issue.

**Comment by stellangoleka** [comment]
This should be included in the user's guide. It will really be confusing to many.

**Comment by daiClegg** [comment]
@celiapetty @stellangoleka Is this going to be noted in the user training materials?
Or should it be fixed in the software?

**Comment by dbrownukk** [comment]
This is a bug in the OX platform as we are using an ElementCollection to display the detail rows. Enabling a default results in an error on creating a new row. Hoping for a fix from OX

**Comment by celiapetty** [comment]
The bug should definitely be fixed in the software, rather than dealt with as a work around

**Comment by daiClegg** [comment]
Have added OX label.

@celiapetty  @stellangoleka , this means the bug in our App is caused by a bug in the underlying platform David uses to build our app (OpenXava).
The most efficient way to fix it is to wait for the fix in the platform.

Meanwhile i suggest a note in the training materials to the effect of

> "If you are using an early version of OHEA you might find that in the Wealth Group Interview module, Wild Food values do not default as they should, so when you save the record it is lost because there was missing data. If you encounter this bug, just remember to explicitly add zeroes for any values you otherwise would not enter. That will get round the problem."

@dbrownukk  have you bugged this with Xavier?

**Comment by stellangoleka** [comment]
This should be fixed in the software.

**Comment by dbrownukk** [comment]
This is fixed and applied to all values that are required but currently not defaulting to 0. Removed the OX DefaultValueCalculator and set the getter to check for null
i.e. return unitsOtherUse == null?0.0:unitsOtherUse

(if unitsOtherUse is null then set to 0.0 in Save action)

**Comment by daiClegg** [comment]
Tested in Instance:  IDAPS_Livelihoods, IDAPS_Livelihoods TESTING and  EFD_HM
for OHEA 
And OIHM in EfD_HM

**Tested Ok**

just tab through the fields:  Consumed is calculated, Sold & Other Use are defaulted and show on Save,

**Comment by daiClegg** [comment]
@celiapetty @stellangoleka  just to make sure you see that the fix is done
