### ISSUE TITLE
HEA reports summary lists communities that are not reported.

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#441]
Instance: IDAPS_Livelihoods
App: OHEA
Module: Projects
Project: NIMFRU
LZ: Katakwi - Fishing & Livestock Zone

1. Click Reports icon for Katakwi - Fishing & Livestock Zone
> Note 4 villages are offered for reporting

2. Select 'All Reports' Report Spec
1. Select all villages for reporting
1. Click Run
1. Open the generated data extract.
> Note on the summary tab, all  four villages are listed under selected communities
> Not on any of the report tabs only Okorio & Kamenu villages are included

Because there are not 3 WGIs for the other two villages, so they are, correctly, not reported.
But they are offered for inclusion in the reports.
They should not be.

I have note tested this in the Change Scenario reports yet

**Comment by dbrownukk** [comment]
deployed fix to EFD_HM. Once tested OK will deploy to IDAPS_Livelihoods Prod

**Comment by daiClegg** [comment]
Instance: EFD_HM
Project: Mukonu - Trial
LZ: Coffee-Banana-Pigs

Test steps as above, but in the test instance.


**Tested Ok**
