### ISSUE TITLE
OHEA Java exception running DI report

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#444]
Instance:EFD_HM
App: OHEA
Project: Mukono - New Test
LZ: Banana Coffee Piggery 
District: Mukono 
In detail view of the Project module:

1. Click  'Banana Coffee Piggery' LZ Reporting Icon
2. Select 'All Reports' in the Report Spec dropdown
3. Click 'Run'

The reports run, the data extract is downloaded, but then 2 exception message appear as well as the Run ok message:

![Screenshot 2020-03-10 at 16 23 18](https://user-images.githubusercontent.com/30879677/76335438-70a6b980-62ec-11ea-8e23-575a952b0f36.png)

This is the report file:

[All ReportsTue Mar 10 16_29_16 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4313560/All.ReportsTue.Mar.10.16_29_16.UTC.2020.xlsx)

Some villages that should be in the report are missing and i found the following anomalies in the data for WGs in those villages:

**Village |  WG  |  Comment**

Lusera         |  Better Off   |   Coffee sold at 0 price/unit
Nakisunga   |  Better Off   |   Coffee/Beans/Maize sold at 0 price/unit
Nakisunga   |   Poor   |  Matoke/Tomatoes sold at 0 price/unit

**Comment by dbrownukk** [comment]
Transfers is the problem - Old data with TransferType null. No longer allowed

**Comment by dbrownukk** [comment]
Fixed data on EFD_HM for this set of WGIs 
Report runs

**Comment by daiClegg** [comment]
**Tested Ok**
