### ISSUE TITLE
Unable to ascertain from file name what's in a Modelling data extract file

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#445]
I'm finding myself opening and re-opening countless spreadsheets cos i don't know if they're Change Scenario or Change  Scenario and  Coping Strategy or what the Study/Project.

So i think we need a better naming convention for the extract files,
TBD

**Comment by dbrownukk** [comment]
Easily fixed, but name could become long - need a code

ModChangeS_project_date  and ModCopingS_project_date ??

**Comment by daiClegg** [comment]
Since Mod is common, it's not strictly necessary, but distinguishes more easily from Reports
Just 'ChangeProjectDate' or 'CopingProjectDate'?
Project or Study name, as appropriate.

It's a bit cryptic, but allows the user to easily distinguish within a reasonable name length.

Could keep 'Mod' (only 3 letters) and apply something similar  ('Rep')to Reports as well, for consistency and to deliver the same benefit there?

**Comment by dbrownukk** [comment]
lets try the following to see if that helps identify the modelling reports:-
		if (isChangeScenario && isOHEA) {
			filename = "Change"+project.getProjecttitle().substring(1, 10) + Calendar.getInstance().getTime();
		}
		else if (isCopingStrategy && isOHEA) {
			filename = "Coping"+project.getProjecttitle().substring(1, 10) + Calendar.getInstance().getTime();
		}
		else if (isChangeScenario && isOIHM) {
			filename = "Change"+ihmProject.getProjecttitle().substring(1, 10) + Calendar.getInstance().getTime();
		}
		else if (isCopingStrategy && isOIHM) {
			filename = "Coping"+ihmProject.getProjecttitle().substring(1, 10) + Calendar.getInstance().getTime();
		}

**Comment by daiClegg** [comment]
**Tested Ok**
