### ISSUE TITLE
Unable to run Modelling reports

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#447]
Instance: EFD_HM
App: Modelling (OIHM & OHEA)
Module: Livelihoods MOdelling

1. Select any Change Scenario
2. Select Change Scenario option
3. Select all HHs/LZ available
4. Click Run

> org.hibernate.LazyInitializationException: could not initialize proxy [efd.model.ResourceSubType#8a80848464dc39a00164dc5f47140004] - no Session Errno = 2262

Reproduces on any existing scenario
Persists after log out/log in

**Comment by daiClegg** [comment]
Also occurs for new Change Scenario

**Comment by dbrownukk** [comment]
Restarted tomcat on server. Lots of traversing arrays and different deployments.

May need to change hibernate settings if we see this again.

<property
    name="hibernate.enable_lazy_load_no_trans"
    value="true"/>

**Comment by daiClegg** [comment]
But not ready for me to test yet, right?

**Comment by dbrownukk** [comment]
Tried with just reboot, but still failed. Now added hibernate setting and redeployed. Seems ok, tested half dozen modelling reports

**Comment by daiClegg** [comment]
**Tested Ok**
