### ISSUE TITLE
HH configuration questions appear not to be added to new HHs

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#448]

**Comment by daiClegg** [comment]
Instance: EFD_HM
App: OIHM:
Module: Household
Study: Test Questions

This study has been configured with 3 questions - 1 at HH level and 2 at HHM level 
1. In HH module list view, click New,
2. Select 'Test Questions' in the Study dop down. 
3. Click Save
> note the HH number is generated and the HH successfully saved.
> however there are no HH questions listed

4. In the HH Member frame, click New.
> note no questions are included in the Questions frame of the popup dialogue.

**Comment by daiClegg** [comment]
I  added a question to the Katakwi project and git a warning that HH data already exists - as i expected.
But the new question doesn't show up on editable existing HHs.
No questions show up on new HHs.

Have i forgotten something?

**Comment by dbrownukk** [comment]
deployed fix.

Note that HH without any HH Level questions will have questions added on first Save. A requery is required to view the list of HH questions

Questions can only be edited, not deleted. On create of questions a LOV type will have the word 'optional' and integer and decimal ranges have null - null range listed, indicating they need populating manually.

**Comment by daiClegg** [comment]
Re test, environment as above.

Module: HH
HH ID 5
HH Name TestFix

1. Create new HH, as above.
1. Click Save
> Note Question appears as expected.
3. Answer question
4. Click Save
> Successful, as expected.

5. Add HH Member 
6. Click Save
> Note questions appear as expected
7. Enter answers for questions
8. Click Save
9. Click Close
> As expected
10. Edit HHM
> Note the questions are replicated
11. Answer them again (with contradictory answers)
12. Click Save
> Save successfully
13. Click Close
14. Edit HHM
> the questions are replicated again...
![image](https://user-images.githubusercontent.com/30879677/78717586-bcaf4300-7918-11ea-9f0a-266015e047f1.png)

**Comment by dbrownukk** [comment]
Always good to remove code to fix an issue...  Now uses JPA Prepersist and removed ability to delete a question.
Fix deployed

**Comment by daiClegg** [comment]
**Tested Ok*
