### ISSUE TITLE
Expandability Limits & Expandability Increase Limit not editable

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#449]
INstance: EFD)HM
App: Modelling
Module: Expandability Rule

Expandability Limits & Expandability Increase Limit default in creation, but they should be user-overridable. That doesn't appear to be the case, either in editing an existing rule aor adding a new one.

![image](https://user-images.githubusercontent.com/30879677/77150251-61153680-6a8b-11ea-996f-a55e953f7be4.png)

**Comment by dbrownukk** [comment]
Indeed, somewhere I interpreted the default as not changeable..
Fixed, deployed

**Comment by daiClegg** [comment]
**Tested OK**
