### ISSUE TITLE
Clear community details in community detail page when project is changed

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#45]

**Comment by dbrownukk** [comment]
Done

On Change of Project

package efd.validations;

import java.math.*;

import org.openxava.actions.*;

public class OnChangeClearCommunity extends OnChangePropertyBaseAction  {
	public void execute() throws Exception {
		
		String proj = (String) getNewValue();
		
		getView().clear();
		getView().setKeyEditable(true);
		getView().setEditable(true);
		//getView().reset();
		getView().setValue("projectlz.projectid", proj);
	}

**Comment by daiClegg** [comment]
Tested ok
