### ISSUE TITLE
Modelling reports for HEA before/after Change Scenario misalign WG names

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#451]
Instance: EFD_HM
App: Modelling (HEA)
Module: Livelihoods Modelling
Project: Mukonu - New Test
Change Scenario:  Multi-element test

For this project, run the modellng reports (just change scenario)
Select all Villages (only 1 LZ)

My test results attached:

[ChangeMukono - NSat Mar 21 17_44_50 UTC 2020.xlsx](https://github.com/dbrownukk/EFD_v2/files/4363621/ChangeMukono.-.NSat.Mar.21.17_44_50.UTC.2020.xlsx)

Note on all four reports there is a blank row between Villages in Columns A & B.
But there is no blank row between the data for each Village in columns C onwards.

**Comment by dbrownukk** [comment]
Fortunately, all community and village name output  done in one place! Just needed to stop extra line..
Deployed

**Comment by daiClegg** [comment]
**Tested Ok**
