### ISSUE TITLE
Unable to create 2 Expandability Rules with the same name

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#452]
Instance: EFD_HM
App:: Modelling
Module: Expandability Rule

1. In list view note there is a rule called "Sell PIgs"
2. Click New
3. Enter "Sell Pigs" as the rule name
4. Enter valid values for other required fields
5. Click Save
Error:

![image.png](https://images.zenhubusercontent.com/5a81590c4b5806bc2bc688fc/6068966c-2197-40a9-8f50-4b49d15cd24a)

6. Change the name to "Sell Piggies"
7. Click Save

ok.

**Comment by daiClegg** [comment]
Because each Expandability Rule is part of the Coping Strategy of a Study or of a Community, it only needs to be unique within that grouping.

**Comment by dbrownukk** [comment]
Now have Unique Index for RulesetName within either Study or Community Expandability Rule set

deployed

**Comment by daiClegg** [comment]
**Tested Ok**
