### ISSUE TITLE
Java Exception running coping strategy on IHM study

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#454]
Instance: EFD_HM
App: Modelling
Study: Katakwi - NIMFRU Test
Module: Livelihoods Modelling

1. Select any Change Scenario for this Study
2. Select Change Scenario and Coping Strategy for Model Run Operation
3. Select All HHs
4. Click Run

ERROR: java.lang.NullPointerException Errno = 105

Other  Study runs Coping Strategy ok
This study runs Change Scenario ok

**Comment by dbrownukk** [comment]
No matter how many null checks are performed in java code, there is always one that gets away..
Working way through all getters to return 0.0 rather than null for Double datatypes 

Note that the defaultValuecalculator from OX is not setting the zero and permitting nulls

deployed

**Comment by daiClegg** [comment]
**Tested Ok**
