### ISSUE TITLE
OIHM does not capture Personal Characteristics

### ISSUE THREAD

**Issue by stellangoleka** [dbrownukk/EFD_v2#456]
OIHM does not capture Personal Characteristics e.g Household member currently attending school recorded as M10 - Primary - Yes or M19- Secondary - Yes in IHM spreadsheet.

**Comment by daiClegg** [comment]
How do i reproduce this bug?

**Comment by daiClegg** [comment]
assigning @stellangoleka

**Comment by daiClegg** [comment]
Unable to reproduce.
