### ISSUE TITLE
Unable to validate some WGI datasets

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#457]
Instance: IDAPS_Livelihoods_Testing
App: OHEA
Module: WGI

IN list view note there are 12 WGIs in the state "Generated"
All appear to have valid datasets
They all fail validation
> Error: Impossible to execute Validate action: null

I have reviewed them all but i can't find the error.
I have validated perhaps 20 other WGIs in this instance today.

**Comment by dbrownukk** [comment]
Curiously one of the market percent values was returning null, despite the value defaulting to 0 and showing on screen as 0. Coded around this. Also note that there is a restriction that a WGI must have a status of Fully Parsed before it can be transitioned to Validated via the Validate menu option. 

deployed to IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
**Tested Ok**

Since the user gets a helpful message re the Generated Status there is a simple workaround, so it doesn't need fixing. 
But, arguably, if we want to encourage users to by-pass spreadsheets for data entry we should not put even that small barrier in their way.

How about we remove the requirement and just insist there is at least one entry in one of the tabs to establish that some data has been entered by one means or another.

**Comment by daiClegg** [comment]
*TESTED OK **  On the user test instance. Can it be deployed to the other instances please?

Leaving the for discussion label until deployment is resolved
