### ISSUE TITLE
Exception running reports

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#458]
instance: IDAPs_LIvelihoods_Testing
App: OHEA
Module: Project
Project: NIMFRU
Function: Reporting

1. In detail view, click Reporting button for LZ 'Katakwi - Crop & Livestock Zone'
2. In the pop-up,, select 'All Reports' form the Report Spec dropdown
3. Select all villages except 'Obarute'
4. Click Run

> report data extract is downloaded

5. Repeat the process but select only 'Obarute'
> ERROR: java.lang.NullPointerException Errno = 2265

Note if you select all the villages using the group  select checkbox then un-check 'Obarute' you get another error - logged separately

**Comment by dbrownukk** [comment]
Obarute had Wildfoods with 0 price. Have coded around the error, but should '0' price be allowed

deployed fix to IDAPS_Livelihoods_Testing

**Comment by daiClegg** [comment]
**Tested Ok** - there were other WGIs with the same problem.

But, i think you're right that a zero price makes no sense if the amount sold is non-zero.
Should fail validation.

Leaving this open for that change.
If you prefer, close this and i'll add a new issue for the validation change.

**Comment by daiClegg** [comment]
I have moved the issue of zero prices to Issue #463 .

Wil close this one.
