### ISSUE TITLE
Wealth Group  should display SubDistrict in List view

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#46]
In list view you currently just see rows labelled "Poor", "Middle", "Better Off" etc
But if you're looking for a WG you'll need to know where it is, in order to identify that it's the one you're looking for.

SubDistrict of the Community this WG is part of, labelled "Sub-District/Village" should ideally be added as the first column and should be the major sort order, so all the WGs of a Community will sort together.
WGOrder should be the secondary sort, so WGs sort in ascending wealth within a Community.

**Comment by dbrownukk** [comment]
Wealthgroup 

@Tab(editors = "List, Cards", properties = "community.site.subdistrict,wgnameeng,wgnamelocal;wgorder,wgwives;wghhsize,wgpercent+")

added community.site.subdistrict to List

To be deployed

**Comment by daiClegg** [comment]
Tested ok & closed
