### ISSUE TITLE
Unable to validate HHs 

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#460]
Instance: IDAPS_Livelihoods_ Testing
App: OIHM
Study: KAtakwi - NImfru
Household: *any*

Attempt to validate any HH in the study:
> Impossible to execute Validate action: null

Looked to me like the same issue as #457 , so i picked a HH (19) and went through explicitly entering zero for all market percentages. It makde no difference; maybe i missed one

**Comment by dbrownukk** [comment]
Same validation script as WGI but checks that HH spreadsheet is present. But returns null, not an empty string. 

As per #457 need to change the check of status before Validation:-

Only permit validation if there is at least one entry in the asset tabes.

**Comment by dbrownukk** [comment]
deployed fix 

Now checks if assets exist. If not then will not Validate, otherwise will validate even if no spreadsheet exists.

Same for #457

**Comment by daiClegg** [comment]
Households 3 & 21 still fail with 

> Impossible to execute Validate action: null

Several others validated happily and others resist Validation, correctly, because they have no entered data, but these 2 are still misbehaving

**Comment by dbrownukk** [comment]
Went through all returned Double values in all assets to check for null being returned. Transfers seemed to be the problem. 

All now will Validate - note that if unitsSold > 0 then you need a priceperunit..

deployed into IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
**Tested Ok**
