### ISSUE TITLE
Zero price allowed for units of Livestock Prods, Wild Food & Transfers sold

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#463]
Instance: IDAPS_Livelihoods_TESTING
App:  OHEA
Module: WGI
Project: Katakwi - Crop & Livestock Zone 
Village: Obarute
WG: Better Off.

A zero price per unit sold is currently not allowed for crops if the units sold is non zero.
However it is still allowed for Food Transfers, Wild Foods & Livestock Products.

Note the WGI referenced above is validated ad includes a record of each of the above types with a zero price per unit sold.

**Comment by dbrownukk** [comment]
Assume during Validate. Would be best to fix in model but unable as constraint relaxed for spreadsheet upload, hence need for validation routine. Need for stateful constraints!

 However, need to make consistent.

Fixed and improved warning messages.

**Comment by dbrownukk** [comment]
Deployed to EFD_HM for initial testing - or should I be going straight to IDAPS_Livelihoods_TESTING ?

**Comment by daiClegg** [comment]
Will test where it is, but it needs to be deployed to  all instances when it's closed

**Comment by daiClegg** [comment]
**Tested OK**
