### ISSUE TITLE
Extend IDAPs Livelihoods modelling to represent change scenario elements that substitute one food source for another

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#466]

**Comment by daiClegg** [comment]
For the moment, pending discussion and agreement with user stakeholders, my proposal for modelling the impact on micronutrients on dietary changes is to add in LIvelihoods Modelling, the capability to define a change scenario element that substitutes one Food Source for another in the diet of a Community or Study.

The user should be able to specify, for any food source (Crop, Livestock Product, Wild Food or Food Purchase) an alternative Food Source. 
They should also be able to specify (as now for Change Scenario elements) %age differences for Yield/Production and Market Price.

This would support modelling the impact of substituting a food either by changing default diet, changing a crop or changing a livestock type. It would seem contrary not to include Wild Foods, regardless of whether such a switch would ever happen (why not gather both if they are available?)

**Comment by daiClegg** [comment]
This still reproduces (just tried it on Testing Instance).

**Comment by dbrownukk** [comment]
A complex fix that took some time. A WG had crept into a HH array.

Now fixed and tested on above example and by running all HHs in the STudy. Note that OpenXava Pro also upgraded to 6.5. Only visible difference is a collapsible menu giving back a chunk of screen estate.

**Comment by daiClegg** [comment]
Just tested this in the QA instance & the Testing instance.
Again, i just used HH91, to make mife simple for myself.

I get slightly different results between the two instances, but that might be due to changes done to the McC&W mappings; Celia has an intern who is planning to set up all the mappings correctly.

[ChangeNIMFRUFriMar05MicronutrientsQA.xlsx](https://github.com/dbrownukk/EFD_v2/files/6092426/ChangeNIMFRUFriMar05MicronutrientsQA.xlsx)
[ChangeNIMFRUFriMar05MicronutrientsTesting.xlsx](https://github.com/dbrownukk/EFD_v2/files/6092427/ChangeNIMFRUFriMar05MicronutrientsTesting.xlsx)

But in both cases, there are examples of -ive amounts of some nutrients, both before & after the change scenario.

**Comment by dbrownukk** [comment]
TESTING is the one I updated.

There was an issue with both  the OIHM and Modelling calculation, hence the small difference with the QA results. 

The negative is a result of the HH requirement for a Default Diet Item. We take each DDI that has a Nutrient mapping, take the value of a Nutrient and multiply by the kg required by the HH and multiply by -1 - being the requirement. 

The crop they consume then counts against this value. If it is not enough then the nutrient level is still negative. Perhaps needs a revisit. Should negatives be allowed and is the calculation correct.

**Comment by daiClegg** [comment]
I can't see how in a real-world situation a person can get a -ive amount of a nutrient from their diet.
I think i see why this happens, but i think it would be hard to explain the result to a nutritionist.
to be discussed...

**Comment by dbrownukk** [comment]
Removed '*-1' from the DDI amounts for micronutrient calc in OIHM, OHEA and Modelling Reports

Deployed to Testing

**Comment by daiClegg** [comment]
**Tested Ok**
