### ISSUE TITLE
Exception when Running Modelling

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#469]
Instance: IDAPS_Livelihoods_TESTING
App:  OHEA
Module: Livelihoods Modelling
Model: Click& Point

1. Click Report
1. Select all Communities
1. Click Run
> java.lang.StringIndexOutOfBoundsException: String index out of range: 10 Errno = 54`

**Comment by daiClegg** [comment]
Also tested in IHM:
Model: t1
Same steps to reproduce
Different Exception:
> java.lang.NullPointerException Errno = 54

If this is a different problem will rasie separate issue..

**Comment by dbrownukk** [comment]
Project title was less than 10 chars. In creation of spreadsheet filename there is a truncation, of what, until now, had been long Project names! Study names were always shorter and handled smaller name sizes. 

To be deployed

**Comment by dbrownukk** [comment]
Deployed to IDAPS_Livelihoods_TESTING

Modeling reports work but option to Download visualisation spreadsheet has a problem - a JSP file is not compiling on ubuntu 16. Compiles ok on Windows. Looking for a solution...

**Comment by daiClegg** [comment]
Was able to run the reports, but an additional tab appears in the data extract:  
'3 - Modelling Report Visualisatio'.

**Comment by daiClegg** [comment]
does the diagnosis of this issue suggest the Exception in IHM reporting (noted above) should be raised as a separate issue?

**Comment by dbrownukk** [comment]
Extra sheet was due to data driven sheets. Extra sheet came about because of extra report record to handle visualisation. 

OIHM Modelling report problem should be fixed as well. 

Deployed to IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
**Tested OK**

OHEA & OIHM
