### ISSUE TITLE
Modelling Report Data Extract Missing Rows

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#470]
Instance: IDAPS LIvelihoods Testing
App: OHEA
Module: Livelihoods Modelling
Change Scenario: Click&Point

1. Click Reports
1. Select Change Scenario
1. Select all Communities
1. Click Run

Extract runs as expected.

5. Open Extract file

Note the data for Okorio (the last Community) Middle & Better Off WGs  is missing from all reports.

**Comment by dbrownukk** [comment]
The missing data is related to subdistricts Obwokomor Better Off and Lale Better Off - neither have any WGI assets. This has resulted in all reported data being push up a row - (not clever) as these subdistricts should not be included as a valid site - or should they be and reported with zero assets?

**Comment by dbrownukk** [comment]
fixed
deployed to IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
**Tested Ok**
