### ISSUE TITLE
Discrepancy Between OHEA Reports & Change Scenario Data Extracts

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#471]
Instance:  IDAPS Livelihoods Testing
App: OHEA
Module: Projects (Reports) & LIvelihoods Modelling (Change Scenario - Click&Point)
Project: Nimfru
LZ: Fishing & Livestock

1. Run all reports for all communities
2. Run Change Scenario for all communities
3. Compare DI value in Reports extract  with DI value in Before Change Scenario in the Modelling  extract

With the exception of the first WG they all are different

**Comment by dbrownukk** [comment]
WGI order was wrong - was ordered by WG order before site, subdistrict 
Changed to ordered by Subdistrict then Order of WG (Poor/Middle/Better Off order field)

deployed to IDAPS_Livelihoods_Testing

**Comment by daiClegg** [comment]
**Tested Ok**
