### ISSUE TITLE
OIHM Reports missing reporting currency

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#473]
Instance: IDAPS_Livelihoods_Testing
App: OIHM
Module: Study
Study: Katakwi - NIMFRU

1. in detail view, note the Site location is in Uganda and the currency symbol (UGX) is correctly displayed from the Country record
1. Click Reports
1. Select All Reports report spec
1. Select all HHs to include
1. Click Run
1. Open the downloaded data extract

On the "Summary" tab, Reporting Currency (Cell B4) says "UNKOWN"
Note this spelling is incorrect, but why is it not UGX?

**Comment by dbrownukk** [comment]
Was looking for currency along site route, not lz if there was no Alt Currency in Project

Fixed, deployed to IDAPS_Livelihoods_TESTING 

Will deploy this and other issues awaiting promotion to IDAPS_Livelihoods when this has passed testing..

**Comment by daiClegg** [comment]
**Tested Ok**
