### ISSUE TITLE
OHEA Default Diet can vary by WG

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#474]
It seems that the default diet for different WGs in a Village can vary.
This is not what was specced, but we should consider an enhancement to accommodate this.
The data structure is the same, but just for the WG not for the Community.

**Comment by daiClegg** [comment]
This expansion to the requirement is not yet confirmed. It needs discussion amongst domain experts. 
Meanwhile, it is worth discussing potential implementation as the cost of that affects the cost/value equation of implementing the requirement if it is confirmed.

**Comment by daiClegg** [comment]
@DrJohnSeaman @celiapetty @Jamesacidri,  is it a requirement that different WGs in the same Village can have different Default Diets and different Standard of Living requirements (Food & Non-food, Survival and Social Inclusion)?

James' FEG spreadsheets from the NIMFRU project suggest they can.
OHEA was specced without this refinement.

Do we want to add it?
David & i will work on the cost since that might have a bearing on your debate.

Meanwhile can you folks please discuss the value and add a conclusion here, please?

**Comment by celiapetty** [comment]
The default diet should not vary by wealth group: DI is based on the most commonly purchased local staple, regardless of WG.  (FEG doesn't use this measure hence perhaps the confusion in the old NIMFRU spreadsheets). Please don't make any changes-DI correct as it is. 
I think the only query might be whether the default diet could vary across a livelihood zone. This is one for @DrJohnSeaman . Possible in a larger LZ perhaps? John could you respond to this, please.

**Comment by daiClegg** [comment]
Right. Default Diet shopuld be defined once for a Community - that is the current implementation. No change required.

Note that it can already vary by Community, because it is separately defined for each one, so no change is needed to support that.

Will close this; can always re-open if the debate re-ignites at some point.
