### ISSUE TITLE
Upload context information to OIHM project sites

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#483]
A feature on OIHM is needed allowing upload of files containing contextual information (word files, excel spreadsheets, maps, photographs etc)  . Suggest the paper clip/upload symbol is placed under the GPS box on the  Study Site page.
Others: please add any remarks if needed.

**Comment by daiClegg** [comment]
The site is the physical village. If you did a longitudinal study and surveyed the village twice (2 IHM studies or 2 HEA projects) or included it in an HEA study then went back to do an IHM drill down, you would want different context information each time, would you not?
In which case, i think the correct solution would be to have Notes on Community (that's added again if the HEA study is repeated)  and on Study in IHM.

@Celia can you confirm/correct please?

**Comment by celiapetty** [comment]
Yes - that's correct.

**Comment by daiClegg** [comment]
ok. That's what we'll do. when is another question, currently planning the next sprint.

**Comment by dbrownukk** [comment]
File upload field where multiple files can be uploaded are now on Study and Community. 

Is this sufficient or do we need a notepad text area as well?

**Comment by daiClegg** [comment]
Since we have upload capability for multiple files, i see no reason for an additional notepad area.

*Tested Ok**

**Comment by dbrownukk** [comment]
Deployed to QA and Prod
