### ISSUE TITLE
LiveStock CharacteristicResources should appear on Assets tab of WG Template Spreadsheet

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#51]
To see current behaviour, in "Admin" user, navigate to "Ngombere, Mpunge Sub Coun" Community. 
The navigate to the detail view of the "Better-Off" WG:
Note the CharacteristicResources are: Local Cattle, Improved Cattle (Dairy), Goats and Local Chickens; all of Resource Type "LIvestock"

Generate the spreadsheet for this WG.
Navigate to the LS tab, and there they are.

But in fact (ambiguously) this tab is for recording Use of Livestock (LIveStockUse entity in the design model).
The characteristic Livestock resources should be recorded in the Livestock section on the Assets tab.

**Comment by daiClegg** [comment]
did you see this one?

**Comment by dbrownukk** [comment]
Fixed 

Set the resourcetype code for LS to be "Use of Livestock"

**Comment by daiClegg** [comment]
Tested ok, both parts: Livestock now correctly in the 2nd block of the Assets Tab.
Use of Livestock, now correctly on the LS tab.
