### ISSUE TITLE
Apply all expandability rules to all WGs in a model 

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#518]
In Livelihoods modelling, Expandability Rules are applied to a WG until the DI of that family unit is +ive.
At that point, no further rules are applied.

If we are to support other targets than just +ive DI, we need to be able to flex that cut-off point.
We can support simple user control of targets in the visualisation spreadsheet, so the user doesn't have to go back to the model to change target. 

But that requires that the data extract includes the effect of all rules on all WGs.
To achieve that the current constraint on applying Expandability Rules should be removed

**Comment by dbrownukk** [comment]
Review that this is complete

**Comment by dbrownukk** [comment]
Now does not stop applying Expandability rules if DI becomes +ve.

Note, discovered bug in calc - one wealthgroupinterview was used for all 3 wgis. fixed.

Deployed IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
**Tested Ok**

**Comment by dbrownukk** [comment]
Deployed to QA and Prod
