### ISSUE TITLE
Livelihoods Modelling Expandability Rules only apply to Livestock that have already been sold

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#521]
Right now if an Expandabity rule says  'Sell Goats' it will only affect HHs or WGs that have already sold goats.
Any family grouping that has not sold Goats already will sell no more because of this Expandability Rule.

This is because Expandability Rules specify 2 limits for Livestock: '%age increase in the existing sale' & 'limit as a %age of total herd'.
If there is no initial sale, it doesn't matter what the %age increase allowed is, it's still going to be zero.

Is this correct or should it be possible for an Expandability Rule to specify sale of Livestock that has not already been sold?
If it should where does modelling get the price for it? And how is the size of the sale limited? Must the livestock be listed as an Asset with a herd size?

**Comment by dbrownukk** [comment]
Review and correct

**Comment by daiClegg** [comment]
MOved this forward; the information needed to implement was not available in the original sprint timeframe

**Comment by daiClegg** [comment]
Subsumed in #443 
Marking as a duplicate of that and closing her.
Will back reference for the notes here.

**Comment by celiapetty** [comment]
Returning to the coping strategy/expandability-sale of livestock and looking back through the comments, including John's  'There would have to be a way for the user to enter a price'.  
Users should enter a sale price for livestock-just as they enter a sale price for crops.
Is there any disagreement with this suggestion?  Not change to the rules governing % herd sold.

**Comment by daiClegg** [comment]
As noted, this is a subset f #443; i think the issue of entering a price is adequately handled there.
