### ISSUE TITLE
Country needs a Currency

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#53]
Have added Currency, Varchar(3)  from the ISO listing (http://www.xe.com/iso4217.php#section2)
And Currency Symbol Varchar (1) to the design model

I'm not sure we need the symbol - since it may not exist or be widely used or even be renderable from some keyboards (http://www.xe.com/symbols.php#section1), but we may as well have it.

Not needed for M1, but part of Country Entity that is in M1, so no Milestone assigned on logging

**Comment by dbrownukk** [comment]
Done. Deployed 
See Notes on #55

**Comment by daiClegg** [comment]
Tested ok.
