### ISSUE TITLE
Report: Disaggregated Resource usages (Food & Cash income) in Category-restricted reports. 

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#534]
For clarification: In the current version of open-IHM users can select individual income sources (eg from Crops: sorghum, maize and sweet potato; from Employment: brick making, agricultural labour; from Wild foods: Mangoes, fish).  This is an important function, particularly for OIHM (eg tracking project impact when a specific crop is targeted)  . Could we discuss costing please?

**Comment by daiClegg** [comment]
From further discussion in email:

From Celia:

> See attached 

Mukono HEA report, pp 7-11. Detailed % FI and CI from all income sources shown, disaggregated by WG. (Highlighted). Totals for each category (Crops, Livestock, Employment, Wild Foods, Transfers) also shown (Highlighted &Red).
> 
> The same outputs from OHEA would add value for research, policy and NGO users. ie
> 
> Sources of food income  Percent of food requirement @ 2,100Kcals/ person/day and cash income   Percent of cash income by wealth group cf Tables 3 and 4 in the Mukono document.
> In addition to this,  a  function that allows users to select specific sources of food income or cash income (eg top 4 FI and top 4 CI  from the above tables) and generate a report in excel (% food requirement and % cash income) would also add value for the same users. I don't think it would add significant value to produce visualisation spreadsheets. This level of detail is more expert focussed (including technicians with a policy brief).
> 
> We would like the same functions for OIHM. I can't show examples from earlier work by wealth groups as none of this was automated. In EFD Working Paper 7, see figs 8-11 ( examples of CI at community level from specific sources. There would be additional value for reports of CI and FI from user-specified sources, by DI   quantile-DI per AE probably not the best option here.  Finally, the IHM slides (from the Bath ART project) show selected sources of FI and CI for an individual household. For case study use, selected FI and CA sources from an individual household should be an option. (Note: I've also included a slide showing  % increase in a selected crop across the whole community - I think OIHM output would be similar and is already programmed as a change scenario?). There should also be an option to group HHolds by income (DI quantile) quantile. 

[Dai_EfD WP 6 HEA Mukono, Uganda.docx](https://github.com/dbrownukk/EFD_v2/files/6420582/Dai_EfD.WP.6.HEA.Mukono.Uganda.docx)

[EfD WP 7 Mityana&Wamala Uganda IHM.docx](https://github.com/dbrownukk/EFD_v2/files/6420600/EfD.WP.7.Mityana.Wamala.Uganda.IHM.docx)

[Example slides IHM disaggregated.pptx](https://github.com/dbrownukk/EFD_v2/files/6420604/Example.slides.IHM.disaggregated.pptx)

**Comment by daiClegg** [comment]
Follow up clarification questions:

What other Resource types, as well as Crops, should be disaggregated?
All Food and Cash income categories (Crops, Livestock Products, Livestock, Wild Foods, Transfers,  Employment).

What groupings are used:
Total per disaggregated RST, for each WG reported for each Village in the LZ, 
Total per disaggregated RST, for each Village reported for all  Villages in the LZ.

To support this in analysis we need to report for the LZ: CI & FI, for each RST for each WG for each Village.

Will add example output shortly

**Comment by daiClegg** [comment]
Note there is an assumption there that the user would use Categories to focus in just the food & cash income sources they want to analyse, but my feeling now is that Categories might be applicable here as elsewhere, but not mandatory.

**Comment by celiapetty** [comment]
Income from all resource types should be disaggregated ie all food and cash income categories (Crops, Livestock sales, Livestock products, Wild foods, Transfers, Employment.
Groupings used:
Total per disaggregated RST, for each WG reported for each Village in the LZ,
Total per disaggregated RST, for each Village reported for all Villages in the LZ.
Total disaggregated RST for each LZ

Also in OIHM: Total disaggregated RST  for each village site; for user selected households; and ideally for selected income quantiles.

**Comment by daiClegg** [comment]
From a bifurcational thread:

**Requirement refinement:**

The measurement of %ages of food requirements can be calculated as:

- %age of daily family group requirement (2100 kcal per day, per AE in OHEA) provided by that food income source 
- %age of total food income, provided by that food income source. 

Both metrics have value. The former shows how important a crop is compared with other crops grown - the latter says more about overall market dependence. Ideally the user would be able to select the measure they want to appply in a specific run.


**Implementation note:** 
Perhaps simpler to just provide both every time. 
It would only be a few extra columns in the report
That simplifies the interaction for the user and the logic for implentation

**Comment by daiClegg** [comment]
Example data extract file attached:

[OHEADisaggregatedFoodSourcesByVillage.xlsx](https://github.com/dbrownukk/EFD_v2/files/6424183/OHEADisaggregatedFoodSourcesByVillage.xlsx)

**Comment by daiClegg** [comment]
OIHM sample output to follow soon.

**Comment by daiClegg** [comment]
OIHM sample output:

[OIHMDisaggregatedFoodSourcesByHousehold.xlsx](https://github.com/dbrownukk/EFD_v2/files/6435684/OIHMDisaggregatedFoodSourcesByHousehold.xlsx)

Minor updates to OHEA sample output:

[OHEADisaggregatedFoodSourcesByWG.xlsx](https://github.com/dbrownukk/EFD_v2/files/6435686/OHEADisaggregatedFoodSourcesByWG.xlsx)

**Comment by celiapetty** [comment]
Great- many thanks. 
[OHEADisaggregatedFoodSourcesByWG_CP.xlsx](https://github.com/dbrownukk/EFD_v2/files/6435963/OHEADisaggregatedFoodSourcesByWG_CP.xlsx)
[OIHMDisaggregatedFoodSourcesByHousehold_CP.xlsx](https://github.com/dbrownukk/EFD_v2/files/6435978/OIHMDisaggregatedFoodSourcesByHousehold_CP.xlsx)

Comments posted on spreadsheets - I'm not sure if update automatically so attached again.

**Comment by daiClegg** [comment]
minor comments on @Celia review notes
I regard this as a candidate for implementation

[OIHMDisaggregatedFoodSourcesByHouseholdReviewed.xlsx](https://github.com/dbrownukk/EFD_v2/files/6436394/OIHMDisaggregatedFoodSourcesByHouseholdReviewed.xlsx)
[OHEADisaggregatedFoodSourcesByWGReviewed.xlsx](https://github.com/dbrownukk/EFD_v2/files/6436395/OHEADisaggregatedFoodSourcesByWGReviewed.xlsx)

**Comment by dbrownukk** [comment]
Report structure now a real timesaver!

Added 2 new reports 

240 HEA Disaggregated Food Source By Household - ready to Test 

374 Disaggregated Food Source By Wealthgroup - not implemented yet

Note that there is a discrepancy in Cash income - should Livestock Sales be included with Livestock Product Sales or not?  They are for existing Cash Income report.

Created new Report Spec 'Disaggregated' for testing

Tested with a Category to limit food items

**Comment by daiClegg** [comment]
Instance: Testing
Study: Katakwi - NIMFRU - AIHM 2018
HH Number: 3
HH Name: Esiret Richard
Report Spec: Disaggregated

Ran reports for the study as normal .
Report runs fine.
But there are some minor anomalies in the output.
These are highlighted in the uploaded data extract .

Note also comment above about Livestock Sales (LS), which were excluded because they make no contribution to FI.
But they do make a major difference to CI, which is also included in this report so perhaps LS should be included.


[DisaggregatedSat May 22 15_28_31 UTC 2021.xlsx](https://github.com/dbrownukk/EFD_v2/files/6528270/DisaggregatedSat.May.22.15_28_31.UTC.2021.xlsx)

**Comment by daiClegg** [comment]
@celiapetty : We agreed above that Livestock Sales  are not included since this is an FI report.
But the report does also include the CI contribution from Crops. LP, Emppl, WildFoods & Transfers.
So it seems to me it shoul dinclude LS.
That wouldn't affect the FI, but would complete the CI part of the report.

wdyt?

**Comment by dbrownukk** [comment]
Fixed Transfers - Total Production to include multiplier of people

Also deployed OHEA version of this report - again have created a new Report Spec 'Disaggregated' 

Deployed to IDAPS_Livelihoods_TESTING

For the Employment calculation 'Total Production' assume this should show People Count * Units Worked

Also for Employment - How to handle Food Payment Unit, Food Payment Units Worked and Food Payment Food Type   

Also, noticed above the AE multiplier is 2100 kcal per day. Somehow I have been using 2600 kcal per day. Easily changed but needs confirming.

**Comment by daiClegg** [comment]
Issue #372 states the AE for OHEA to be 2100.

@celiapetty : Can you confirm please that in HEA the AE = 2100 KCal per day.

**Comment by dbrownukk** [comment]
@daiClegg Yes, for IHM the AE calculated and used, but the multiplier / divider is 2600 - 2100 not used anywhere in the code..

**Comment by daiClegg** [comment]
I think that is correct. 

2600 is the maximum required KCal per day in the WHO table used in IHM (Documented in Issue #236).
It's the peak requirement for an Adult - from 18 to 29 years old.

That issue confirms that the AE for an IHM household is the calculated total requirement, divided by 2600 .
It's the equivalent number of adults that would need those calories.

In fact, because most of the HH will require less, the average KCal requirement per HH member is going to be less than 2600.
In HEA that is assumed to be 2100 and the family group requirement is calculated as number of HH members * 2100.

Make sense? 


This is a bit of an unnecessary explicatory discursion because Total HH reqt/2600 is the correct AE calcualtion for IHM - as you say.

**Comment by daiClegg** [comment]
I had been confused to see that there was 0 Total Production leading to non-zero Cash Income for Transfers (of cash) & for Employment.
But the the Total Production is calculated as the total Food Production - so it is correctly being reported as 0 for these resource types; i agree that is correct.

**Comment by daiClegg** [comment]
@celiapetty : The report does not show the kind of Food that is acquired in a food Transfer and Employment paid in food.
In both cases we have the KCal  but do we also need to know the Food RST?

Here is example output for one HH that has both of these sources of FI:

[DisaggregatedMon May 24 10_44_22 UTC 2021.xlsx](https://github.com/dbrownukk/EFD_v2/files/6532001/DisaggregatedMon.May.24.10_44_22.UTC.2021.xlsx)

**Comment by daiClegg** [comment]
@celiapetty : please see the full github history for this issue; there are 2 separate questions for you above in the thread (both today)

**Comment by celiapetty** [comment]
Just back and catching up on emails. I'll look at this first thing
tomorrow. Many thanks for all the progress you've been making on this.

**Comment by celiapetty** [comment]
1. @celiapetty : We agreed above that Livestock Sales are not included since this is an FI report.
But the report does also include the CI contribution from Crops. LP, Empl, WildFoods & Transfers.
So it seems to me it should include LS.
That wouldn't affect the FI, but would complete the CI part of the report.
@daiClegg Yes-agreed, it's needed to complete the CI part of the report

**Comment by celiapetty** [comment]
2. @celiapetty : The report does not show the kind of Food that is acquired in a food Transfer and Employment paid in food.
In both cases we have the KCal but do we also need to know the Food RST?

@daiClegg Yes, it's particularly  important to know the type of food acquired in food Transfers (typical situation is food aid-could be WFP is providing food not typically consumed by people in that area). In employment paid in food it's less important- However, if this doesn't involve a significant additional work, it would be useful to know the type of food

**Comment by celiapetty** [comment]
3. @celiapetty : Can you confirm please that in HEA the AE = 2100 KCal per day.
 @daiClegg  I think this is already resolved -yes HEA the AE is 2100Kcals per day. WG requirement based on typical hhold size for that WG

**Comment by dbrownukk** [comment]
AE set to 2100 Kcals
Transfers - if Food then the Food Resource is listed. If Cash then "Cash" is listed
Livestock Sales added to Cash Income only

deployed IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
@dbrownukk : The AE calculation is not needed for OIHM; the actual food requirement can be calculated from household members' ages & genders, as per the DI calculation. AE calculation is for the equivalent HEA report.

**Comment by daiClegg** [comment]
Instance: Testing
App: OIHM
Module: Study
Study Katakwi - AIHM
HH name Okwi Bosco
HH # 1

1. In the detail view of the above Study, select Reports in the menu bar
2. In the reports pop-up, select the Disaggregated from the Report Spec dropdown
3. In the HH list select HH 1 (Okwi Bosco)
4. click on the HH name to view the detail record
5. In the Livestock sales tab, note there are 2 livestock sales
6. Click Run
7. On the disaggregated food source tab note that no Livestock Sales are reported for HH1

I had expected the Livestock Sales to be recorded as 2 additional rows - with zeroes in the FI related columns.
as in the attached, edited data extract:
[DisaggregatedWithExpectedLivestockSales.xlsx](https://github.com/dbrownukk/EFD_v2/files/6542339/DisaggregatedWithExpectedLivestockSales.xlsx)

**Comment by daiClegg** [comment]
<same test as in previous comment>

Noted the Food type names for food transfers are now available  **Tested Ok**
I ran another test that verified that 'Cash' is still reported in this column for Cash Transfers **Tested Ok**


@celiapetty note (in the data extract attached to my previous comment) that for Employment paid in food the food type is still  **not** shown; to do so we'd have to lose the Employment type, but we do have the FI correctly included.
Is that satisfactory?

**Comment by celiapetty** [comment]
Query 25 May '@celiapetty note (in the data extract attached to my previous comment) that for Employment paid in food the food type is still not shown; to do so we'd have to lose the Employment type, but we do have the FI correctly included.
Is that satisfactory?' I think this is now resolved? 
Re transfers: 
Although the transfers are just labelled 'food'-they are disaggregated by amount, so  users could go back to the data to check food type . These responses could be out of date now? Could you please send the most recent disaggregated output in case I've missed anything. 
The 24 May spreadsheet looks great. I'm not so concerned about the visualisation charts as for this level of analysis users should be looking at the data and can create their own spreadsheets . Possibly just automate the disaggregated kcals chart?

**Comment by daiClegg** [comment]
Tested in OIHM & OHEA - both working fine, except for the absence of the cash income that accrues from Livestock Sales.


This was noted above - with a suggested correction (see annotated data extract attached 25th May)
This suggestion was then discussed and approved by Celia.

Now available as a backlog candidate & added to current sprint. - a bit late!

**Comment by dbrownukk** [comment]
Dev notes:
Validation of LSS misses blank RST rst==null
Moved to JDK 11 to use latest string utilities
---------------------------------------------

Added LSS individual items to OHEA and OIHM Disaggregated reports 

Deployed to IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
**Tested Ok**
