### ISSUE TITLE
Misleading behaviour when creating new Project/LZ from Community module

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#54]
In the Community ModuleClick New.
On the Project field click '+'
In the  Project popup enter a new project name & start date.
Click "Add LZ' or "NewLZ'
Both cause a page load but do nothing and show no message (tested in Chrome & Safari
Click "Create' to create a Project with no LZ
On return to Community module, on Project click  'edit" (pencil icon)
In the  Project popup click "Add LZ' or "NewLZ'
Behaviour is now as expected.

Should get a message to request Save.
And should remain in the Project popup to add LZ without having to return to Community

**Comment by dbrownukk** [comment]
Add LZ now works 

A New LZ fails to find project id for save - suspect this needs manytomany.new setting

**Comment by dbrownukk** [comment]
Community, New Project, add name and date

Add LZ works 

New LZ fails

**Comment by dbrownukk** [comment]
Fixed - deployed - warnings that project must exist before adding LZ

**Comment by daiClegg** [comment]
Tested Ok.
