### ISSUE TITLE
(OIHM & OHEA) Modelling: Should Visualisation show impact of rules that diminish income

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#546]
> I think the answer is that they wouldn't sell green maize if it was going to make them worse off. Maybe this creates an interesting question around the limitations of modelling?

in Livelihoods Modelling, the data extract shows the impact of applying every rule.
And the visualisation shows the impact of each rule on a HH until the HH achieves its target.
If the Coping Strategy has been correctly specified from field data, then that's basically what's would happen.

Are you suggesting a refinement here, that in the real world, a HH would not sell if the result is a shrinking of income?
That's a perfectly doable fix to the visualisation.

It doesn't fix the problem of coping strategies that don't appear to help people cope.
There may be other refinements that would help us approach the real world more closely.
#521 is still awaiting a methodological resolution, and another question is how should we calculate price for sales more generally:

- What was previously achieved by this HH? 
- The average of all prices achieved by all HHs? 
- Some other calculation?

(these comments apply to #521 and will be referenced there)

_Originally posted by @daiClegg in https://github.com/dbrownukk/EFD_v2/issues/543#issuecomment-738393958_

**Comment by celiapetty** [comment]
Response to query : Should visualisation show impact of rules that diminish income? My view is that they should, as this would educate policy makers who assume people would (say) sell all their maize to raise cash,  when  in fact the market price of maize is higher than then farm gate price they get from traders-so it's unlikely that they would in sell / @DrJohnSeaman What is your view?

**Comment by daiClegg** [comment]
For the moment we will not do anything special with expandability rules that don't help.
We can re-assess when we have more real-world model scenarios
