### ISSUE TITLE
Project may need an alternative currency

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#55]
Occasiionally trades may be recorded in a WG interview that are not in the currency of the Country in which the LZ is situated. Where this happens, and it is rare, there has only ever been observed to be one alternative currency used.
So ProjectLZ needs an Alternative Currency and an Exchange rate, so that such trades can be converted to the default currency of the project.

These attributes have been added to the Design Model

This is not needed until M2 but the Project module edit capability is in scope for M1 so adding this there; for consideration. Can be pushed to M2 if desired

**Comment by daiClegg** [comment]
created a dependency on Issue #53, because they are linked, although not strictly blocked.

**Comment by dbrownukk** [comment]
This requires attributes on the intersection entity which will require a chunk of recode and testing

From quick research this means changing to 2 ManyToOne with plenty of consequences. 

Would an alternative currency on Project suffice as an edge case.?

**Comment by daiClegg** [comment]
Is this because Project LZ is implemented as an intersection between Project & LZ? 
And this would require it to become an entity in its own right?

An alternative currency on Project would be acceptable.

There is the remotest of chances that a Project might involve more than one LZ and that they both needed an alternative currency, and it was a different one.
Not likely enough, i think, to incur the cost differential of the 100% solution

**Comment by dbrownukk** [comment]
Yep, implementation of attributes on intersection is doable but costly. Recommendations are to use ManytoOne and create a new intersection entity. 

How about a Trade has a default currency of the country which  could be overridden with another  currency that has a exchange rate to the base country of the LZ country currency?

**Comment by daiClegg** [comment]
Yes, that is fine.
One altenrative project per project is acceptable.
And a Trade (which will only appear in Milestone 2) is by default in the LZ's currency - inherited from Country.
If it is in another currency that will be entered on the Trade.
That is then matched with the project alternative and the exchange rate applied.
If a Trade has a non-default currency entered and it does not match the Project alternative currency, that is a data error and must be manually reviewed & corrected.

But to support that all we need is the alternative currency onProject and exchange rate to be applied.
An exchange rate will be set for the project, since it is not feasible, or even useful, to try to calculate what the exchange rate would have been at the date of the Trade.

**Comment by daiClegg** [comment]
Is this resolved by #53 & #57?

**Comment by dbrownukk** [comment]
deployed - extra currency and exchange rate in Project

**Comment by daiClegg** [comment]
Tested ok.\Note it displays the COuntry of the alternative currency, not the ISO code or symbol.
Probably not a bad idea.
