### ISSUE TITLE
Add Alternative Currency and Exchange Rate to Project 

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#57]
Done - to be deployed 
Drop Down List is from Country.Currency

**Comment by daiClegg** [comment]
Some currencies are very low value (e.g. Kenyan Shilling is 0.0070 pounds today.
VietnameseDFongis over 20,000 to the pound.

So i suggest we need the exchange rate field tobeDecimal (5,5)

**Comment by dbrownukk** [comment]
Decimal(5,5) it is

**Comment by daiClegg** [comment]
Tested OK.
