### ISSUE TITLE
Employment heading change

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#580]
To reduce the scope for error, could the Employment Heading 'Cash Payment Amount' be changed to' Cash paid per d/m/y'
and under the heading Unit add d/m/y

This wasn't understood by one of the Walker post docs suggesting a tweak is needed.

**Comment by celiapetty** [comment]
Reviewing changes in the data entry spreadsheet  headings, 'Employment': 
1. Further clarification for column E : add the words 'Number of' to  'Units worked' ie Number of Units worked'
2. Add 'item' to the drop down in column D  'Unit of work eg Day, Month'. This is to accommodate payment by individual items produced eg  bricks.  This is quite common.

**Comment by daiClegg** [comment]
Which app, pls? OIHM/OHEA or both? 

I think we should be working toward converging and consistency where possible, to make it easier for people to learn and use.

**Comment by celiapetty** [comment]
Git hub isn't  working this morning. I think this refers to my query on the
Drop down Employment: Employment  unit  to include 'item' along with
Day/Month/ Year - both apps.
Issue arose with Homa Bay but definitely piece work (payment per brick etc)
is common.

**Comment by celiapetty** [comment]
ok-Github is back. Just confirming,  my last issue (5 days ago) applies to both apps.

**Comment by celiapetty** [comment]
For greater clarity : Under Employment, data entry template  OHEA and OIHM, could 'piece' be added to the drop down for Unit of Work eg Day/Month etc -options to include Day, Week, Month, Year, Piece. Originally I suggested 'item' but on reflection 'piece' is better as it better reflects the idea of 'piece work' whether brick, piece of land, piece of craftwork.

**Comment by daiClegg** [comment]
You mean in the spreadsheets. right? 

This is now implemented in QA (and Testing) instance.

Can you check it is as you want and i'll  add it to the Production instance.

**Comment by celiapetty** [comment]
Checked-OHEA and OIHM are identical as requested and piece added as a unit of work. Thanks

**Comment by daiClegg** [comment]
Same change made to reference code table in Production
