### ISSUE TITLE
Log in screen provides incorrect login information

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#59]
The login screen:

![image.png](https://images.zenhubusercontent.com/5a81590c4b5806bc2bc688fc/373ef959-a97c-45eb-9397-36db5d6402d9)

Includes, at the bottom, the text:

"To start with Evidence for Development OHEA Data Set V2 sign in with user: admin, password: password"

It shouldn't. Users should request their own credentials. So i suggest the text should read:

"To start with Evidence for Development OHEA you will need a username and password. 
You can get these from the project directors, if you are a researcher in a relevant domain or if your organization is an accredited user."

**Comment by dbrownukk** [comment]
Done. In time will there be an email address. Self registration is possoble - we could setup a read only self registration user..

**Comment by daiClegg** [comment]
Could be issues of privacy of data for self-registration. 
But a good option to have for any projects that are declared open data.

Meanwhile, Tested ok
