### ISSUE TITLE
(OHEA) Project has no reference Year

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#598]
This one started life as a discussion about Reference Year in OHEA, then switched to a wider discussion about Context Data generally. The reference year was forgotten, the context data was resolved and the issue was closed.

And none of us noticed the original requirement had been lost.

As i recall, there was a lot of discussions (some above and some in the context of OIHM in #331)  about start of year and end of year in months. But i don't know what the final resolution was.
Since this issue became the Context Data discussion i propose we move the Reference Year requirement to a new one.

_Originally posted by @daiClegg in https://github.com/dbrownukk/EFD_v2/issues/394#issuecomment-774219076_

**Comment by daiClegg** [comment]
Implementaiton :

![image](https://user-images.githubusercontent.com/30879677/110376418-11889b80-804b-11eb-915a-ef3bb56ee60e.png)

is correct in terms of data content & interaction, but it needs to be on the Project, not the Community.
Celia confirms in a note on #599

**Comment by dbrownukk** [comment]
I believe this is done and deployed to IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
**Tested Ok**

**Comment by dbrownukk** [comment]
Deployed to QA and Prod

**Comment by celiapetty** [comment]
I'm currently writing the detailed guide for an upcoming training and working through the software step by step once more, I think we have an issue to resolve. I'm setting out below  my understanding of the  current set up with respect to Reference Year and what may need to be resolved.

OHEA/OIHM QA version
HM common
Screen:
Project 
Under project
Reference year         Start Date              End Date

Problem: A Project is the overarching entity which may continue over a period of several years,  with a series of HEA and/or IHM studies being carried out over this period. So the Project doesn’t have a reference year- only individual assessments in a specific Study at a specified Site (IHM) have this, or in HEA, a Community. The Project will have a Start Date and End Date eg March 2016- March 2021. However, on reflection I don’t think it’s essential to include this information on the HM Common Project screen. This information should be covered in the Project Background papers that will uploaded as Word documents.

Under OHEA Community, Reference Year, Start Date and End date should be recorded. As previously noted, Reference year often spans 2 calendar years. Currently Reference year box only accepts numbers, so eg  2019-20 can’t be entered. Can this be changed, please?

Also as I think previously noted,  to avoid the mistake of entering the dates the field study was conducted under ‘Start date’ and End date’ these boxes should read ‘Reference Year Start Date’ and Reference Year End Date’

Similarly, for OIHM on the Study screen.

Does this make sense? If we need to discuss directly to clarify anything, please let me know

**Comment by daiClegg** [comment]
I think you've redefined the meaning of Project, at least as far as we've used it in the software so far.
Originally, in OHEA, we talked about the Project being a single survey and if there was another survey of the same LZ or LZs, in a subsequent year that was another project. In OIHM from the early days, we had the concept of the Project as being an umbrella over multiple Studies (each at a specific site, and with a specific reference year).

I think what you are doing here is introducing the concept of an HEA Survey (or perhaps Study), of which there may be multiple (eg longitudinal), each of a potentially different set of Sites and in different Reference Years, but all in a single Project

btw this is not the original problem, which was that Project was lacking a Reference year. It's the opposite problem - now it has got a reference year, and you don't want it to, you need it to belong to some lower-level entity within the project of which there may be more than one.
I will re-close this issue and open a new one to discuss this new wrinkle on the problem.
