### ISSUE TITLE
Wealthgroup percent for a Community need to add up to 100 

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#6]

**Comment by dbrownukk** [comment]
Firstly - having to resize columns in Lists is annoying. Seems to set to data length not title 

in xava.properties set resizeColumns-false

**Comment by daiClegg** [comment]
Note that during the insertion of the multiple Wealth Group records this validation must fail until the last one is entered.

Discussed how to deal with this and agreed that a warning should be displayed whenever the validation fails, but the user can proceed anyway.

**Comment by daiClegg** [comment]
Note of conversation from 3/2/18 @dbrownukk & dai:

The current display of the total below the WGs is nice.
It would be cool if it were highlighted :
Ideally Amber if less than 100, Green if 100 & Red is greater than 100.

**Comment by dbrownukk** [comment]
Highlighting in a colour requires css and javascript - not a place I want to go introducing other technologies.

There is now a check when a wealthgroup percentage is updated, warning that total is not 100

Need to extend to include Insert and Remove of a Wealthgroup

**Comment by daiClegg** [comment]
Ok, i'll wait until you've deployed and take a look.
Agree it's not worth additional technological complexity just for colour coding.

**Comment by dbrownukk** [comment]
Warning only appears if wgpercent > 100 only fires on change of percent. 

Does not fire on New/Create of a new WG 

Perhaps set as a default of 0 forcing a change from 0 to a new value?? To try...

**Comment by dbrownukk** [comment]
Managed to colour code the message associated with the Total WG Percent for a COmmunity
1000 = Green
>100 Red
<100 Orange

**Comment by daiClegg** [comment]
Tested ok.  V nice.
