### ISSUE TITLE
Add security/access rights to Restful API access

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#601]
Using Spring 5 WebSecurity features.
Access OX User Entity via EfdUser (mapped to OX User) as OX Entities are not friendly to Spring 5 due to extra OX Annotations

Restriction is done in SecurityConfig.java using OX Roles where Role = ROLE_API (note 'ROLE_' is required by Spring 5)
See HttpSecurity configure and config data in application.properties

**Comment by dbrownukk** [comment]
endpoint efdrest ready for security testing. Endpoints at http://51.140.30.46:8080/efdrest/swagger-ui/index.html?configUrl=/efdrest/api-docs/swagger-config can be tested

**Comment by daiClegg** [comment]
I am able to log in using OX UN/PW. 

- Tested as http from browser (prompts for UN/PW
- Postman (authorisation set in the collection)
- Swagger.

**Feature COmplete**
