### ISSUE TITLE
Document Rest API using Swagger or similar

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#603]

**Comment by dbrownukk** [comment]
Add to main class

    @Bean
    public OpenAPI IDAPS_API() {
        return new OpenAPI().info(new Info()
                .title("EFD IDAPS API")
                .version("1.0")
                .description("Access IDAPS data via Restful API. Note that a username/password is required. Note that this is in testing and liable to change")
               );
    }

For each controller add
@RestControllerAdvice

@Operation(summary = "Get a list of crops for a Livelihood Zone {name}")  // at Module level

Available at http://localhost(or idaps server):8080/swagger-ui/index.html?configUrl=/api-docs/swagger-config

**Comment by dbrownukk** [comment]
API Docs available at 

http://51.140.30.46:8080/efdrest/swagger-ui

Setting to For Testing for feedback

**Comment by daiClegg** [comment]
I've been using Swagger for my testing, in conjunction with Postman, and i have had no problems using the site not understanding what it is telling me.

**(Feature Complete**

**Comment by dbrownukk** [comment]
https://idaps.walker.ac.uk/efdrest/swagger-ui/index.html?configUrl=/efdrest/api-docs/swagger-config
