### ISSUE TITLE
API to create a change scenario for a given LZ (including Price/Yield Variations)

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#609]

**Comment by daiClegg** [comment]
This feature will allow users to create a new Change Scenario and add price/yield variations.
Should we also provide the ability to get a list of Change Scenarios already defined for a LZ, and change/replacde an existing Change Scenario.

this that what the existing calls (culled from Swagger) do:

GET    /api​/v1​/modellingscenario
POST ​/api​/v1​/modellingscenario
GET   ​/api​/v1​/modellingscenario​/{title}
PUT   ​/api​/v1​/modellingscenario​/{name}

But not full detail yet for the updates?

**Comment by daiClegg** [comment]
btw, this appears to be in progress

**Comment by dbrownukk** [comment]
Update ChangeScenario - Postman is best to test this with or use the below JSON in Swagger 

Use a PUT and /api/v1/modellingscenario/Katakwi - OHEA

{
    "id": "8a8084847203409f01728abac6160012",
    "notes": "some notes",
    "version": 4,
    "author": "brian",
    "date": "2020-10-07T00:00:00.000+0000",
    "description": null,
    "title": "Katakwi - OHEA",
    "projectProjectId": "846f1f147c016f9e0019",
    "studyId": null,
    "modelType": "HEA",
    "livelihoodZoneLzid": "8a8084846f1f147c016f296aab450017",
    "foodsubstitutionId": null
}

**Comment by daiClegg** [comment]
I get a 403 when i try this.

Instance: Testing
User: APITest 
Test scenario:

- I have a Collection in Postman, with basic authorization set at the collection level and 'inherit from parent' for all the members of the collection.
- The collection also includes Gets - of LZ & Modelling Scenario.
- Both of which work fine, so the authentication is ok

Test Result: 

- The Put of the JSON body above fails:

![image](https://user-images.githubusercontent.com/30879677/111228215-bc650080-85db-11eb-86a7-0b585815e1a5.png)

**Comment by daiClegg** [comment]
Help please.

**Comment by dbrownukk** [comment]
Ah, my last entry was my dev notes. Had not set to ready to test, but clearly read as though it was ready to test.  Not deployed yet. Should have the Update, Create and Delete for modellingscenario deployed to Testing today.

**Comment by daiClegg** [comment]
Sorry. Please don't be deterred from using the issues for dev notes. 
I will use the 'for testing' tag as my definitive guide in future.

**Comment by dbrownukk** [comment]
Ready for some testing. PriceYield Variation not done yet. 

baseurl = 51.140.30.46:8080/efdrest      (Postman has variable which I use for Local and IDAPS testing)

Documentation http://51.140.30.46:8080/efdrest/swagger-ui/index.html?configUrl=/efdrest/api-docs/swagger-config

Setting to For testing while I continue with PriceYieldVariations



1. Create new modellingscenario 
POST  {{base_url}}/api/v1/modellingscenario  and pass in JSON

{
            "notes": "some notes",
            "version": 15,
            "author": "brian",
            "date": "2021-03-15T00:00:00.000+0000",
            "description": null,
            "title": "Katakwi - OHEA 55555",
            "projectProjectId": "8a8084846f1f147c016f296bd89e0019",
            "studyId": "",
            "modelType": "HEA",
            "livelihoodZoneLzid": "8a8084846f1f147c016f296aab450017",
            "priceYieldVariations": [],
            "foodSubstitutions": []
        }

2. Update a Modellingscenario
PUT {{base_url}}/api/v1/modellingscenario/

with following JSON (just change one of the values i.e. author..

        {
            "id": "2c9f7081783b425f01783b4496330000",
            "notes": "some notes",
            "version": 15,
            "author": "basil",
            "date": "2021-03-16T00:00:00.000+0000",
            "description": null,
            "title": "Katakwi - OHEA 77776767",
            "projectProjectId": "8a8084846f1f147c016f296bd89e0019",
            "studyId": null,
            "modelType": "HEA",
            "livelihoodZoneLzid": "8a8084846f1f147c016f296aab450017",
            "priceYieldVariations": [],
            "foodSubstitutions": []
        }

3. List of ModellingScenarios
GET {{base_url}}/api/v1/modellingscenario

4. List a single ModellingScenario

GET {{base_url}}/api/v1/modellingscenario/Katakwi - OHEA

**Comment by dbrownukk** [comment]
Added list of Crops - will be needed to create new PriceYieldVariations

GET {{base_url}}/api/v1/rst

**Comment by dbrownukk** [comment]
Get a list of Price Yield Variations for a Modelling Change Scenario

GET {{base_url}}/api/v1/pyv/{ModellingChangeScenarioTitle} (i.e. Katakwi - OHEA)

Update of Price Yield Variation

PUT {{base_url}}/api/v1/pyv

and change Yield and/or Price

eg.

{
    "id": "8a8084847502ce5b017504951ab70006",
    "resourceSubTypeId": "8a8084846f618e0f016f816aba9c0011",
    "resourceSubTypeName": "Cassava chips",
    "modellingScenarioId": "8a8084847203409f01728abac6160012",
    "modellingScenarioTitle": "Katakwi - OHEA",
    "yield": 12,
    "price": 24
}
Create NEW Price Yield Variation for a Modelling Scenario

POST {{base_url}}/api/v1/pyv

with
{
"id": "8a8084847502ce5b017504951ab70006",
"resourceSubTypeId": "8a8084846f618e0f016f816aba9c0011",
"resourceSubTypeName": "Cassava chips",
"modellingScenarioId": "8a8084847203409f01728abac6160012",
"modellingScenarioTitle": "Katakwi - OHEA",
"yield": 1,
"price": 23
}

Documentation available on swagger as before

Deployed to TESTING

**Comment by daiClegg** [comment]
Testing Post new scenario

> Ready for some testing. PriceYield Variation not done yet.
> 
> baseurl = 51.140.30.46:8080/efdrest (Postman has variable which I use for Local and IDAPS testing)
> 
> Documentation http://51.140.30.46:8080/efdrest/swagger-ui/index.html?configUrl=/efdrest/api-docs/swagger-config
> 
> Setting to For testing while I continue with PriceYieldVariations
> 
> 1. Create new modellingscenario
>    POST  {{base_url}}/api/v1/modellingscenario  and pass in JSON
> 
> {
> "notes": "some notes",
> "version": 15,
> "author": "brian",
> "date": "2021-03-15T00:00:00.000+0000",
> "description": null,
> "title": "Katakwi - OHEA 55555",
> "projectProjectId": "8a8084846f1f147c016f296bd89e0019",
> "studyId": "",
> "modelType": "HEA",
> "livelihoodZoneLzid": "8a8084846f1f147c016f296aab450017",
> "priceYieldVariations": [],
> "foodSubstitutions": []
> }
> 
> 1. Update a Modellingscenario
>    PUT {{base_url}}/api/v1/modellingscenario/
> 
> with following JSON (just change one of the values i.e. author..
> 
> ```
>     {
>         "id": "2c9f7081783b425f01783b4496330000",
>         "notes": "some notes",
>         "version": 15,
>         "author": "basil",
>         "date": "2021-03-16T00:00:00.000+0000",
>         "description": null,
>         "title": "Katakwi - OHEA 77776767",
>         "projectProjectId": "8a8084846f1f147c016f296bd89e0019",
>         "studyId": null,
>         "modelType": "HEA",
>         "livelihoodZoneLzid": "8a8084846f1f147c016f296aab450017",
>         "priceYieldVariations": [],
>         "foodSubstitutions": []
>     }
> ```
> 
> 1. List of ModellingScenarios
>    GET {{base_url}}/api/v1/modellingscenario
> 2. List a single ModellingScenario
> 
> GET {{base_url}}/api/v1/modellingscenario/Katakwi - OHEA

**In Postman**

executed this as directed.
> i get a '201 Created'. Success.

**in IDAPs Web App**

Instance: Testing
Module: Livelihoods Mode
> no new scenario has been created in the database.

i retested other calls (list of LZs, List of LZs within Country successfully

**Comment by dbrownukk** [comment]
The above ModellingScenario has an ID, normally would mean an update, but as using POST this should be ignored - is now.
Also added more error handling

Deployed new version to Testing (Tested on my local and Idaps Testing instances)

**Comment by daiClegg** [comment]
### Part 1: Creating a new scenario (with no price/yield entries)
Using the instructions and sample json content above
Status 201 (success resource created)

**Tested Ok**

**Comment by daiClegg** [comment]
### Part 2: Update a modelling scenario (just change header details)

1. (part 1 above) create new scenario
2.  get details of scenario (to provide the core content for the update json)
3. edit the details (change version & notes)
4. PUT the modelling scenario

**Tested Ok**

**Comment by daiClegg** [comment]
Part 3: Update a modelling scenario (add a price/yield entry)
1. get details of an existing non-null scenario for valid price/yield data definition
2. edit scenario used in part 1 & part 2 to include the price/yield data
> this was the body submitted: 
{
  "id": "8a80848478ca83200178d1f538290007",
  "notes": "update test",
  "version": 3,
  "author": "daiC",
  "date": "2021-04-14T00:00:00.000+0000",
  "description": null,
  "title": "Katakwi - OHEA API Create",
  "projectProjectId": "8a8084846f1f147c016f296bd89e0019",
  "studyId": null,
  "modelType": "HEA",
  "livelihoodZoneLzid": "8a8084846f1f147c016f296aab450017",
  "priceYieldVariations": [
    {
                    "id": "8a8084847454c6e0017477588b04000f",
                    "resourceSubTypeId": "8a8084846bc21862016bcdf131e90132",
                    "resourceSubTypeName": "Cassava, dry",
                    "modellingScenarioId": "8a80848478ca83200178d1f538290007",
                    "modellingScenarioTitle": "Katakwi - OHEA API Create",
                    "yield": 3,
                    "price": 100
                }
  ],
  "foodSubstitutions": []
}
3. PUT the modelling scenario
> Return status 500
> this was the exception:
>{
  "timestamp": "2021-04-14T21:51:56.435+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "Update Error org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : efd.model.PriceYieldVariation.modellingScenario -> efd.model.ModellingScenario; nested exception is java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : efd.model.PriceYieldVariation.modellingScenario -> efd.model.ModellingScenario",
  "path": "/efdrest/api/v1/modellingscenario/"
}

**Comment by daiClegg** [comment]
not sure if this is me submitting an invalid body, cos it's built by cut and paste.
so will retry a different test...

**Comment by daiClegg** [comment]
**Testing for this needs to be broken into sevaral different components:**
1. Create a new Change Scenario
2. Add a Price/Yield element to a Change Scenario
3. Chance an existing Price/Yield component

**Testing to date:**
3. (23/5/21) **Tested OK**

**Comment by daiClegg** [comment]
**Tested Ok**


See #655 for details of testing
