### ISSUE TITLE
Capture and report the average Yield of a Crop in an LZ during a survey

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#611]
The expected Yield for a crop at a place is potentially useful for many kinds of livelihoods data analysis.
How it should be captured, what data should be captured and what data collection protocol should be used have not been decided.
This issue is recorded to provide a place for that exploration of the issue.

**Comment by daiClegg** [comment]
Some starter quesitons:

1. Is this required for OIHM as well as OHEA
2. In OHEA, would it be recorded by Site (Village) or by LZ?
3. Is it a recorded data item, calculated or elicited by the interviewer?
4. Is it calculated within OHEA/OIHM from raw data captured? 
- For example if we knew the area (Acres or Hectares) cultivated for a given crop in a given place, we could calculate the yield per unit area from the total yield reported be each WG/HH.
- Since we have to capture more data fro each crop, or at least for significant crops, is it simpler and less error prone to just capture the total area under cultivation for a Crop and let IDAPs calculate the yield per unit area?

**Comment by celiapetty** [comment]
The expected Yield for a crop at a place is potentially useful for many kinds of livelihoods data analysis.
How it should be captured, what data should be captured and what data collection protocol should be used have not been decided.
1. This data is collected in both HEA and IHM field work at the start of surveys. In OIHM and OHEA studies, information is elicited by field team interviewers in group interviews. Standard forms have been developed for both OHEA and OIHM. The Templates have been shared with @daiClegg. Note that in OIHM in addition to data on crops, (yields with and without fertiliser, market price in the study year) assets and other income types are included as well as standard of living information, use of inputs, local measures and conversions and bad year notes. This is reference material that is used to a) provide interviewers with information on 'plausible answers' ie to assist in probing and cross questioning b) act as a repository of information for setting up local measures and c) It will also provide over time an important archive of local prices. 
[Template  context interview IHM.xlsx](https://github.com/dbrownukk/EFD_v2/files/6477816/Template.context.interview.IHM.xlsx)
 Data is recorded by interviewers, not calculated. (Local measures are established using measuring scales). Yield data, employment income, livestock income etc is not calculated within OHEA/OIHM from this reference data. Standard of living is calculated from the information collected. Yields are only approximate guides but some automation here could be useful and give interesting results in OHEA as suggested. In OHEA contextual data is also collected for each village site. Template provided by John and used in HyCristal studies is attached. To date HEA hasn't formally recorded expected yields-my view is that this information is helpful to interviewers new to a location who don't know what a 'plausible' yield looks like. Writing this it occurs to me that it would be useful to amend the basic OHEA community interview form to include a) average expected yields with/without fertiliser b) standard of living information c) survival threshold % decreases for each  standard of livingitem as these apply to all WGs. WG interviews will record WG specific items (eg livelihood maintenance/resilience expenditure).
[Template  community interview  blank.xlsx](https://github.com/dbrownukk/EFD_v2/files/6477924/Template.community.interview.blank.xlsx)

**Comment by daiClegg** [comment]
So are you happy that this is just handled in the context interview spreadsheet (as referenced above)?
That means OHEA & OIHM, as apps, have no visibility of it (ie do not use it in any calculations).
Any calculation or analysis based on this data would be entirely manual.
If that's ok, i'll close this as covered by the upload of context interview data.

**Comment by celiapetty** [comment]
Yes, agree with all of this

**Comment by celiapetty** [comment]
Yes-thanks

**Comment by daiClegg** [comment]
This is then covered by #637 which will cover the management of context interview data more widely than just his data item.
