### ISSUE TITLE
(OHEA) Spurious error message generated when generating template WG interview template spreadsheet

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#612]
Instance: QA
Project: Highland
Community: Loch
Module: Community

1. in the detail view of the above Community, click the 'Template spreadsheet' control for any WG
> the spreadsheet is correctly generated and downloaded
> but an error message is shown: "Value for {0} in {1} is required"

**Comment by daiClegg** [comment]
Not a high priority since the action completes successfully.

**Comment by dbrownukk** [comment]
Will review

**Comment by dbrownukk** [comment]
Not spurious at all. Was failing to create the WGI because avgNumber in HH was not being set and somewhere along the line became required.

Set avgNumberinHH with default value of 1 

deployed to IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
Aah, i had only been checking on the format of the generated s'sheet - i hadn't checked the WGI.

**Tested OK**
