### ISSUE TITLE
OIHM Unable to add two 'Topics' to a study

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#615]
These are points for clarification please. 
1. It looks as if it's not possible to add new questions to a Study once the instruction 'Copy in Topic questions' has been made. This is good, as it means new questions can't be added half way through an assessment.  Could you confirm the cut off point for new questions is it once the Copy Topic questions instruction has been given? Or is it once the interview template has been created.   Just need clarification for the next set of training videos.
2. From my test runs, it looks as if each OIHM study can only interrogate one Topic - so questions covering, say, floods and education can't be configured in the same study? (unless a topic 'Floods and Education' were created?) Is this correct?

**Comment by daiClegg** [comment]
Reworded subject to reflect the issue (steps to reproduce below)

wrt cut off for adding questions: 

When at least one Household has been uploaded any attempt to add a question will result in a warning  message:

 > "A Household within this Study already has an uploaded Spreadsheet"

This recognises the potential inconsistency that the pre-existing households cannot have been asked the added questions, so any analysis if answers will be incomplete.

But you can still go ahead and add the question.

**Comment by daiClegg** [comment]
Instance: Testing
Module: Study
Study: Mukono-HyCRISTAL-Victoria lakeshore - B

1. In the detail view of the above study, click on the Questions Tab
Note there are 3 questions defined - from copying in the Migration topic 
2. Click the "Copy in Topic Questions" button on menu bar
3. From the drop-down select "Education" topic
4. Click "Copy"
> ERROR: Impossible to execute Copy action: null

It should be possible to add multiple topics
Extending the  test to establish that it is adding a second topic that triggers the error, not a faulty topic definition:

5. Click "Cancel"
6. Select all 3 defined configuration questions
7. Click "Remove"
8. Click "ok"
9. Click "Save"
10. Repeat steps 2. to 4. above
> Success.

**Comment by dbrownukk** [comment]
Was a bug, iterator issue when checking if existing Topic already used. 

Fixed. Deployed to IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
**Tested Ok**
