### ISSUE TITLE
(OIHM) Unable to add new configuration question

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#616]
Instance: Testing
Module:  Configuration Question 

In list view, click "New"
> ERROR: Impossible to execute New action: null

logged off and on, tried multiple users, same result

**Comment by daiClegg** [comment]
Reproduces in QA instance.

**Comment by daiClegg** [comment]
I notice that it is possible to create new Configuration Questions in the context of a Topic.

**Comment by dbrownukk** [comment]
ConfigurationQuestionUse should not exist as a standalone menu option. Only makes sense in context of a Study.

Go to a Study and select the 'Question' Tab. Just tested (in Testing app) that you can create a new ConfigurationQuestionUse and a ConfigurationQuestion and Answer. 

Need to remove as a standalone module - if that is sensible?

**Comment by daiClegg** [comment]
Yes. Remove the module from all menus.

I will test and document in detail the correct process. 

Can you tag for testing when the standalone menu is gone pls.

**Comment by dbrownukk** [comment]
ConfigQuestionUse now set to Hidden in OX Module Admin. Module is still visible from Study Questions (if not, it is a Role issue)

Set in IDAPS_Livelihoods_TESTING only.

**Comment by daiClegg** [comment]
*Tested Ok**

This arose because i had forgotten how to create new questions.

A little background:

A study may have one or more questions associated with it.
To add a question to a study the user has 3 options, all in the Study module, detail view.
1. if the question is already defined and is part of a topic that the user wants all of:
-  click the 'copy in topic questions' button in the menu bar 
2. If the question is already defined (either free-standing or as part of a topic the user doesn't want the rest of):
- in the Questions tab, click the 'New' button
- in the pop-up, click the Search icon (magnifying glass next to the 'Configuration Question' title
- click 'choose' next to the question you want to add.
3. if the question does not exist yet (always worth checking method 2 above first):
- in the Questions tab, click the 'New' button
- in the pop-up, click the Add icon (plus sign) to add a new question and include it in this study
-  select the topic you wish to add the question to (if any) specify the Prompt and HInt, then select the question level (Study, HH or HHM) and the type of question
- depending on the question type selected you may have to specify ranges or which predefined List of Values (LoV) to be used.

**Comment by daiClegg** [comment]
Assigning Celia because she first highlighted the problem and needs to know the resolution

**Comment by daiClegg** [comment]
In Testing instance, 'Configuration Question' module was visible in the OIHM Extras menu.
It was still exhibiting the behaviour initially reported.
I set it to hidden and in QA instance for Celia's review.
