### ISSUE TITLE
OIHM  Amend  2 headings under Transfers,  Household data

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#617]
Please amend the heading  'Resource type of food resource sub type' to 'Food type' and 'Transfer food other type '
to 'Transfer food type'.
Dai, I think this captures our discussion?

**Comment by daiClegg** [comment]
Household module, Transfers Tab, which looks like this:

![image](https://user-images.githubusercontent.com/30879677/112384348-35eca500-8ce6-11eb-9bcb-7280ce60cc2b.png)

_**'Resource type of food resource sub type'**_ is the food resource subtype transferred
_**'Transfer food other type** '_ is the value entered on the uploaded spreadsheet (blank in these examples, cos the data was entered directly).

The former is derived in Parsing and Validation from the latter, if possible, or else is manually selected by the user.
But neither of them is really meaningfully named right now.

I'm thinking **_'Food Type Transferred'_**  & **_'Uploaded Food Name'_**
That's slightly different from what Celia has suggested but i wanted to make the distinction between the uploaded value and the parsed/validated value, although they should be the same in most cases.

@celiapetty wdyt?
@dbrownukk we have many places where there is a pair of fields (Uploaded & Parsed) should we be thinking of some generic (now where have i heard that word before?) solution, even if we only implement it where there is genuine confusion?

**Comment by celiapetty** [comment]
Dai, your suggestion  Food Type transferred (ie selected from drop down) and 'uploaded food name' works for me. I found myself trying to explain to Alice what we can now describe as the 'Uploaded food name' and this accurately summarises the  several sentences I needed... And I think this is a generic solution for the 'blank box'.

**Comment by dbrownukk** [comment]
Change deployed to IDAPS_Livelihoods_TESTING - change to i18n label

**Comment by daiClegg** [comment]
Changed this to add OHEA, since the new column headings re no visible in the Transfer tab of the HH Module in OIHM, and also in the Transfer tab of ther WG Interview module in OHEA.

**Tested Ok**
