### ISSUE TITLE
OIHM Household Module Inputs headings

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#618]
Please amend 

Resource 1 used for | Percent resource 1 | Resource 2 used for | Percent resource 2 | Resource 3 used for | Percent resource 3

To read
Resource used for 1/ Percent resource 1/ Resource used for 2/ Percent resource 2/ Resource used for 3/ Percent resource 3

**Comment by daiClegg** [comment]
This refers to the Household Interview Module, Inputs tab, which looks like this:

![image](https://user-images.githubusercontent.com/30879677/112382560-ea38fc00-8ce3-11eb-872a-146cc6e93364.png)

Note the column names for the assignment of the input to different resources. They have been causing some confusion to users, so an alternative is suggested.

I'm not sure the alternative is a lot better, but then i'm not a user of the software.
Even so, i'm going to hazard another alternative:

> First resource used for/ Percent used for first resource / Second resource used for/ Percent used for second resource/ Third Resource used for/ Percent used for third resource

@David very long column names, but will probably fit without horizontal scrolling in most browser windows. Any thoughts?
Your call @celiapetty. Unless David raises an implementation problem, we'll just go with your choice. 
I'm not sure my use of ordinals is going to help or hinder user :o/

**Comment by dbrownukk** [comment]
Changed to @celiapetty choice...  changed in i18n label file

Deployed to IDAPS_Livelihood_TESTING

**Comment by daiClegg** [comment]
**Tested Ok**

**Comment by daiClegg** [comment]
@celiapetty the headings are as you requested in my test instance.
David always puts fixes there as he makes them.
I test them and tag them for deployment to QA & Production.
But those get bundled and done one when there is a good bunch of fixes.
That way users aren't in danger of being interrupted every day with a single fix that they don't care about anyway.

**Comment by celiapetty** [comment]
Great-thanks. I'll look out for when it's deployed in QA:
C
