### ISSUE TITLE
Add 'local currency' box to Project module

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#621]
Instance QA
Module : Project
For ease of use, and to simplify training , it would be helpful to have a box 'local currency'  before 'alternative currency' and 'alternative exchange rate'

**Comment by daiClegg** [comment]
The local currency comes from the LZ. 
Because we did discuss the possibility of a project covering LZs in 2 different countries.
You can see the LZ local currency with the LZ description below the project description.

wdyt?

**Comment by celiapetty** [comment]
If the LZ covered more than 1 country, the relevant currency would need to be shown at community level wouldn't it?

**Comment by daiClegg** [comment]
I've never been in a discussion where transnational LZs were mentioned.
Transnational Projects (one or more LZ in each), yes,  but not a transnational LZ.

Is this really a requirement? It is a significant change to the way the data is currently structured. 
It would piut an additional burden on the User to specify for each Site they defined (for a Community), what Country it was in as well as what LZ. 
This seems very burdensome for a very exceptional use case.

It can be managed by having 2 LZs (e.g Crops & Coffee District A, Uganda & Crops & Coffee, District X, Kenya)

wdyt?

**Comment by celiapetty** [comment]
Agreed- that's exactly how it would need to be handled.

**Comment by daiClegg** [comment]
And LZ already has a local currency (visible in the Project module, so are we ok as we are?

**Comment by celiapetty** [comment]
Yes, all ok. Thanks for looking at this
C

**Comment by daiClegg** [comment]
no problem. I'll close it
