### ISSUE TITLE
OIHM: Household Member Configuration Question LoV Answers are not displayed

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#622]
Instance TESTING
Study: Test Questions
Module: Household

1. in Study Module, detail view of the 'Test Questions' Study, click Questions tab
> note there are 5 questions, one at Study level and two each at Household & Household Member level. Note also that there is, correctly,  one row defined in the Study Questions Answers tab 
2. In the Household module, click 'New'
3. Select 'Test Questions' from the Study dropdown
4. Click Save
5. In the Configuration Answer frame answer the 2 (correctly) displayed HH level questions
6. Click Save 
7. In the HH Member tab, click New
> note there are no rows in the HH Member Configuration Answer frame 
8.  Enter Household member Name, Age & Head of Household status (arbitrarily)
9. Click Save
10. Click on the new HH member to open for edit
> note the Configuration Answer rows are populated correctly
11. Click on each Configuration Answer, select an answer and click Save
> note the Answers are not displayed in the Answer field
12. Click Save to exit HH Member edit popup
13. Click HH Member record to re-enter edit popup
14. Click Configuration Answer record to edit
> note the answer previously entered is offered.
15. Click Save
16. Using the customize list feature add  the 'Lov value of Lov Answer' field to the record
> note the correct answer is now displayed

I completed and  validated a HH to run the reports and the HHM answers were correctly included

**Comment by daiClegg** [comment]
i have only tested this for LoV questions so far. Can add more test cases if that is helpful

**Comment by dbrownukk** [comment]
Will Review and fix

**Comment by dbrownukk** [comment]
removed use of @Transients in ConfigAnswer class - transient value was not maintained using non default editor

**Comment by daiClegg** [comment]
**Tested Ok**
