### ISSUE TITLE
Include OHEA projects to drop down configure category

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#626]
QA instance
Select HM common
Select Category
Select Add New 
Select Project
Not possible to add or select an HEA LZ
Only  Drop down option is select Study  
My aim was to select HyCRISTAL (OHEA) Mukono, Banana Coffee Piggery LZ to explore function/select specific crop type/s

**Comment by daiClegg** [comment]
I don't believe we included Project-specific Categories in OHEA.
That seems to be an omission, given it's available for OIHM.

It is,  however, possible to define Categories that are available to every Study or Project

For example Fish is a defined Category in the QA instance.
And there is an OHEA Report Spec called Fish Only - OHEA, which only reports that CAtegory.

If you run that for 'Homa Bay, Sugar cane & Bricks'  LZ, you'll see that the Poor' WG in 'Disii', has cash and food income from Tilapia. anf everything else is excluded.
Incidentally Disii Poor have fish income cos i added it. No villages in the lakeside LZs are validated. 


When you've tried this, can you confirm whether we also need project-specific Categories?
The only advantage is that it allows yo to filter the list of available categories to the ones you might be interested it.

**Comment by celiapetty** [comment]
Dai
I've run this and it seems like a good feature. I can see how/where the
categories are defined. Could you take me through   'Add new reports' at
some point? (OHEA extra. )
This seems like a  separate issue from the  disaggregated reports of
sources of food and cash income?- (Examples of reports sent earlier in the
week, shown in the HEA Mukono paper -tables  on pp 8-11) It would be good
to have an estimate of the cost of producing these breakdown reports.  We
would then have a complete set: disaggregated,   part aggregated through
categories, and finally the 5 broad categories (crops, livestock etc)
Does that make sense?
Celia

**Comment by daiClegg** [comment]
So this is a satisfactory solution for Categories?

Wil deal with other issues in separate threads

**Comment by celiapetty** [comment]
Re project specific categories: I'd envisage users defining categories as
the need arises eg 'Lake shore services' -creating a category that includes
-say 'repairing fishing nets, bar, restaurant, selling cooked food'. In
another project the category might be women's village enterprises including
(say) -hair salon, restaurant, selling cooked foods, selling second hand
clothes. So individual RSTs might move across categories, depending on
context. Does that work for the current design?

**Comment by daiClegg** [comment]
If you put the same RST in two categories, and then report on those two categories, what do you expect to happen?
Count the FI & CI from the RST twice?

**Comment by celiapetty** [comment]
Sorry-I wasn't clear. The question was:should users delete existing
categories when starting a new project? It looks from your reply that  the
same  RST may feature in different  categories  in different projects.
Users will need to ensure that category name relates to the specific
project (eg Lakeshore businesses Bulebi may be different from Lakeshore
businesses Wamala so this needs to be indicated in the category name).
To generate the report, do users need to describe this in OHEA extra?  Is
this defined under custom report spec? Could we arrange a demo for this ?
Thanks
Celia

**Comment by daiClegg** [comment]
No users should not delete categories. 
They may exist for other projects that are currently on-going or that might need to be analysed in retrospect.
They might also be Categories another user has defined intending to use on their next project.

When we initially discussed Categories the examples used were 'Pulses', 'Legumes', "Grains' etc.
These are objective realities, not dependent on a particular user's temporary needs. 
So it might be a good idea to create these one time for reuse.
John defined these some time ago: https://github.com/dbrownukk/EFD_v2/issues/102

The feature that allows a Category to be private to an OIHM study was not implemented for OHEA Projects. 
As noted above, it isn't necessary, but if many users use many one-off Categories, it might make sense to add that feature so the Categories are pre-arranged by context. But without that refinement, users would be well advised to use a naming convention for categories that indicates the context for which they are intended.

**Comment by daiClegg** [comment]
@celiapetty Is this clarified now? 
Can i close it?

**Comment by celiapetty** [comment]
Yes, thanks.
