### ISSUE TITLE
OHEA: Unable to define Characteristic resources for a WG

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#628]
Instance: Testing
App: OHEA
Module: Community

Project: NIMFRU
District: Katakwi
Community: Ai II
WG Middle II

1. In detail view of Community 'Ai II', click WG 'Middle II' to invoke pop-up WG editor
2. Under Characteristic Resources click 'New'

> ERROR: Impossible to execute action: Session object sessionTab not found in controllers.xml

it is possible to apparently omplete the edit operation despite this message, but the data is not saved

**Comment by dbrownukk** [comment]
Was somewhat bigger than the above issue. Characteristic Resources had same problem in IHM Study Module. 

Fixed.

Deployed - IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
**Tested Ok**

in OHEA (as in the original log) and in OIHM (as noted above)

**Comment by dbrownukk** [comment]
Deployed to QA and Prod
