### ISSUE TITLE
OIHM: modelling Change Scenario calculation not as expected.

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#630]
Instance: Testing
App: OIHM - Modelling.
Change Scenario: Test partial sale

1. In Livelihoods Modelling module, detail view of "Test partial sale" change scenario, note Maize, dry has Yield 50% & Price 200%
2. Click Reports
3. In the pop up editor click 'view' (eye icon) HH1.
4.  Under 'Crops' tab, note this HH produces 5 units of 'Maize, dry' sells 3 & consumes 2
5. Exit the detail view popup
6. Select HH1
7. Click Run
8. Open the downloaded data extract.
9. In the CI before & after tab, note the CI is unchanged (50% yield * 200% price =100%), this indicates 1.5 units were sold.
10. in the FI before & after tab, note the post-change scenario FI is 25% of the pre-change scenario FI, not this implies amount consumed diminished by 75% - but i expect it to be 50% (only 50% available.

Note this is a Local Unit.
I have not yet tested with Kgs. tbd

**Comment by dbrownukk** [comment]
Yield % change was being used twice via code change for local Units, but only in Crop FI calculation

 Fix deployed to IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
**Tested Ok**

**Comment by dbrownukk** [comment]
Deployed to QA and Prod
