### ISSUE TITLE
Templates and storing of contextual information

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#637]
See also #625
To avoid loss of valuable local data ideally users should be able to download the attached templates then upload completed files at Study (O
[Template  context interview IHM.xlsx](https://github.com/dbrownukk/EFD_v2/files/6391346/Template.context.interview.IHM.xlsx)
[Seasonal Interview OHEA &OIHM.xlsx](https://github.com/dbrownukk/EFD_v2/files/6391347/Seasonal.Interview.OHEA.OIHM.xlsx)

IHM) or Community (OHEA) level
1. Seasonal calendars (applies to both OHEA and OIHM)
2. Information from OIHM context interviews.

Could you estimate the cost please?

**Comment by daiClegg** [comment]
Would you not want to capture the name of the study/project/LZ?
Or is that encoded in the name of the spreadsheet when it is saved?

and is there not an analogous Community interview template?

**Comment by daiClegg** [comment]
@dbrownukk:

1. Store the templates for reuse. Note they are not generated on download. They are analogous to visualisation spreadsheets in that way.
2. Add control to request download of both templates on the Study module (both templates)
3. Add control to request download of Seasonal calendar on the Project Module

I've suggested one control that delivers the appropriate context interview template(s) in a single action.
If that is possible (multiple downloads from one control event) it means we can add, remove or rename templates without the user experience changing.
It may be that this is overcomplicating implementation for the sake of a benefit to the user we will not get unless  the template library changes, so if there is overhead a control per template is acceptable.

**Comment by daiClegg** [comment]
@dbrownukk Need to estimate the cost of implementation before this feature can be scheduled

**Comment by dbrownukk** [comment]
Suggestion

Create a new Entity - Templates with - > Description, Version, Status(?), File

Access Templates from a Menu to enable Download.

Both Study and Community have files 'Notes' that can store multiple files.

**Comment by celiapetty** [comment]
Yes: confirming, we now have 3 templates: Seasonal, OHEA and OIHM, and the 2 contextual sets. Also agree we need notes with a description of why and when to use the templates. This would be covered in training but important to include this in the software.

**Comment by daiClegg** [comment]
Ready for implementation

**Comment by dbrownukk** [comment]
Added Templates module

Template

Description
Date
Version
Status
file

Added module to HM Admin in TESTING

If this works then can add a second read only module in HM Common.

**Comment by daiClegg** [comment]
I think the combination of Description and Version Number should be unique. That isn't currently enforced.

And default order by Version Number (descending) within Description, to group all the versions of the same doc together with the latest at the top.

An admin user can abuse this by just uploading whatever they like to whichever version number they like.
I'm thinking of the end-user experience here and this constraint and ordering would make good usability i think.

**Comment by dbrownukk** [comment]
Description + Version are now Unique
Ordered by Version Number

Update via HM Admin Folder menu
Read Only via HM Common Folder

**Comment by daiClegg** [comment]
**Tested Ok**

**Comment by daiClegg** [comment]
@Celia: this is currently only implemented on the Testing instance.
It will be available on Q & Production at the end of the current sprint.
If you want to test it before then, i can activate your credentials for the Testing instance.
