### ISSUE TITLE
Exception invoking WGI module

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#638]
Instance: Testing
App: OHEA
Module: Wealth Group INterview

From OHEA core menu, invoke WGI module:

> ERROR:
> 
> type Exception report
> 
> message An exception occurred processing JSP page /naviox/index.jsp at line 120
> 
> description The server encountered an internal error that prevented it from fulfilling this request.
> 
> exception
> 
> org.apache.jasper.JasperException: An exception occurred processing JSP page /naviox/index.jsp at line 120
> 
> 117: 			<jsp:include page='signIn.jsp'/>
> 118: 			<% } else { %>
> 119: 			<div id="module"> 	
> 120: 				<jsp:include page='<%="../xava/module.jsp?application=" + app + "&module=" + module + "&htmlHead=false"%>'/>
> 121: 			</div> 
> 122: 			<% } %>
> 123: 		</div>

**Comment by daiClegg** [comment]
Does not reproduce on QA instance.

**Comment by dbrownukk** [comment]
An issue with the isOfficial boolean in Transfer. Should have been the same issue in Household, but notice 'Official' has never been used in HH Transfer

Removed Official from WealthgroupInterview Transfer while I investigate. 

Predeply test needs an update - should have picked this up..

Temp fix deployed to IDAPS_Livelihoods_TESTING

**Comment by dbrownukk** [comment]
Changed isOfficial from Boolean to a YN type.

tested and deployed to  IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
**Tested Ok**


Question: is the pre-deploy test now updated to cover this?

**Comment by dbrownukk** [comment]
Created new tests using Selenium IDE and Applitools - runs through each menu option and screen checking that a detail screen appears.

**Comment by daiClegg** [comment]
Excellent.

**Comment by dbrownukk** [comment]
Deployed to QA and Prod
