### ISSUE TITLE
Add unit type to drop down option

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#639]
I can't find where the unit 'litre' can be added - have tried 'add RST' but it doesn't fit. We need to add litre to the drop down for unit options eg 'Milk'  . This is probably obvious but have searched ....

**Comment by daiClegg** [comment]
So is the requirement that the interview template spreadsheet generation should include Litre as a pre-set optional unit?

You can write it in, regardless of whether it's in the drop-down, i think, no?
On upload, it will be parsed as Litre if that's what the RST has set up unless you write in a local unit, in which case that will be used instead of the RST recorded unit.

btw, are you encouraging people to use the spreadsheet? 
When Stella entered the backlog she just bypassed the spreadsheets and loaded the data directly into the app.

**Comment by celiapetty** [comment]
Ideally litre should be a pre-set optional unit as it may confuse users if
it isn't there and is likely to come up often for livestock products.

Re spreadsheet use: we'll be using spreadsheets for the data entry practice
in the next training, as this may well be needed in the field eg if network
is poor. Also, we haven't tested 15+ people simultaneously trying to use
the cloud dbase. It would be a good test, but not if people are paying for
the course...

**Comment by daiClegg** [comment]
@dbrownukk 

**Requirement:**
1. That "Litre" be added as a standard element of the 'Unit' range in the WGI interview template spreadsheet.
2. That "Litre" be added as a standard element of the 'Unit' range in the HH interview template spreadsheet.

ready to be implemented. Add any additional one if they are requested before implementation


@celiapetty 

**Question:**
Note that this list will include any local units for the LZ. The standard units are currently  Item and Kg.
Should any others be added apart from Litre?

**Comment by celiapetty** [comment]
Using the word 'Item' for Animal where this relates to livestock has always
seemed wrong. Could we add 'Animal' as an option?

**Comment by daiClegg** [comment]
Previous spec comment edited accordingly.

**Comment by dbrownukk** [comment]
Reference Code under HM Admin holds these values

Have added 'Unit' 'Litre' and 'Animal'

No code changes, visible  (deployed) in IDAPS_Livelihoods_TESTING

Appears in generated spreadsheet Unit dropdowns

**Comment by daiClegg** [comment]
**Tested Ok**

both as user EFD - no admin privilege - read only
and as an admin user - editing as expected.

**Comment by daiClegg** [comment]
also generated template interview spreadsheet - Litre now included

**Comment by daiClegg** [comment]
added the same new reference codes to QA & Production instance, so the issue is resolved as requested.
