### ISSUE TITLE
Validate resource data in the intermediate tables - mark those records that are invalid and need correcting 

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#64]

**Comment by daiClegg** [comment]
I had anticipated that this would be a partially automated step, where each resource subtype would be looked up by name in the resource sub-types table and if it matched, then the record would be set to Valid or Invalid.
The user would then only need to correct the, hopefully, few anomalous records by hand.
Have i misunderstood?

So, i think we have an 'Epic' consisting of 2 Issue/Stories.

* Auto-check parsed interview data to identify invalid records. A record is invalid if the resource subtype is not valid for the resource type it claims to be.
*  Manually correct or delete invalid entries by:
  ** Correcting typo in resource subtype name to that of an existing resource sub type of the correct resource type
  ** Creating a new resource subtype with the entered name, either as a synonym of an existing resource subtype or as a genuinely new resource subtype (this should be a restricted function, see note below.

Note on creating or editing resource sub types: This should only be accessible to an "OHEA-Admin" role unless it is a synonym of an existing resource sub type. In which case (true for all synonyms) it cannot have a Calorific Value. It inherits that from the base resource sub type it is a Synonym of.

**Comment by dbrownukk** [comment]
Thanks. Somehow I stupidly moved this issue to testing. I meant to move the Parse Issue. Long day.. Yes, you are correct about the validate phase (the first pass could be part of the parse??) and the way we discussed it would work. 

Now moved back to In Progress - I have created the first steps...

**Comment by daiClegg** [comment]
See comments on Issue #65 

Tested ok.
