### ISSUE TITLE
Unable to log into QA instance: Unable to acquire JDBC Connection

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#641]
Attempting to log in here:http://idaps.walker.ac.uk:8080/IDAPS_Livelihoods_QA/m/SignIn
Error message appears:  Impossible to execute Sign in action: Unable to acquire JDBC Connection

**Comment by dbrownukk** [comment]
I have rolled back the QA Application to the 18th May when it was last updated. This is working - will investigate issue, but note that some of the latest enhancements will not be present.

**Comment by dbrownukk** [comment]
redeployed latest QA version - as per current Prod version and all seems well. Must have been a corrupted file upload?
