### ISSUE TITLE
Reporting currency appears to be incorrect

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#642]
Instance QA
Module: OIHM Reports
Study : Mukono-HyCRISTAL-Victoria lakeshore - B
Ran livelihoods IHM report
Report spec shows reporting currency KSH (not UGX)-see below cc'd from Custom Report Spec worksheet
Date: | 27/05/2021
-- | --
Spec Name: | Livelihoods IHM
Study: | Mukono-HyCRISTAL-Victoria lakeshore - B 2015
Reporting   Currency: | KSH

KSH also appears on the visualisation spreadsheet

**Comment by daiClegg** [comment]
Detailed view of the Study :
![image](https://user-images.githubusercontent.com/30879677/119903810-2df8ed80-bf41-11eb-98ad-de48f998c228.png)

**Comment by daiClegg** [comment]
Reproduces in Testing, even though the Study has no site in Testing: 

![image](https://user-images.githubusercontent.com/30879677/119904430-44537900-bf42-11eb-8299-cefad7759427.png)

**Comment by dbrownukk** [comment]
Agree, is wrong. 

With no Site, thus no LZ, no country thus currency then reported currency should be "Unknown"

How would Currency for Study "Mukono-HyCRISTAL-Victoria lakeshore - B" be found? 

With Site populated a Currency can be found and will be correctly displayed. 

Not deployed yet - working on Modelling - Transfers which is not in a deployable state, yet

**Comment by daiClegg** [comment]
Butm on QA, even though Mukono study has a site - which is in Uganda, the Currency is still reported as KSH

**Comment by daiClegg** [comment]
Cracked it. `reporting is taking the Currency from the first LZ in the Project that contains the Study.
HyCristal has 5 LZs. IN the QA instance the first one listed is Homa Bay - in Kenya.
In Testing i changed that record so that Homa Bay is in Burkina Faso - and sure enough that's what appears n the reports,

**Comment by dbrownukk** [comment]
Spot on. If it could not find a Site -> LZ it found the first LZ in the related Project. Was best guess at the time, until found out..  Have changed currency to be 'Unknown' if no related Site. This raises the question, should Site be mandatory within a Study?

**Comment by daiClegg** [comment]
I think Site should be mandatory. But how and when to enforce?
Could just fail reporting and modelling if the site link fails.
ie you can record whatever data you like without specifying the site, but you can't do anything with it?

@celiapetty wdyt?

**Comment by celiapetty** [comment]
Sorry for the delay: all messages from Github go into Spam. Not sure if
that can be fixed.
Agree with the suggestion. I can clarify this in training docs ie
identifying a  Site is mandatory in any Study. I think this omission
originates from our/my first  assumption that Study and Site are synonymous
in IHM. Then realised that in a longitudinal study (within an overarching
project) you might return to the same Site, so would need to give the Study
a different name eg Wamala lakeshore yr 1, Wamala lakeshore Year 2.
Many thanks for sorting this out.

**Comment by daiClegg** [comment]
@celiapetty 
> Then realised that in a longitudinal study (within an overarching
> project) you might return to the same Site, so would need to give the Study
> a different name eg Wamala lakeshore yr 1, Wamala lakeshore Year 2.

exactly.

**Comment by daiClegg** [comment]
@dbrownukk 

Is it a simple change to disallow any reporting or modelling for OIHM if there is no site?
If so, can you do that please?

**Comment by dbrownukk** [comment]
@daiClegg Yes, a check for Site within Study on running a report is a simple solution. If no site then raise an error message. 

@Celia ref Spam - Your email client should have an option to mark an email as 'Not Spam' (usually on a right mouse button menu)  Once you do this then the spam engine should learn that emails from Github are not spam.

**Comment by dbrownukk** [comment]
changes made, not deployed until complete Modelling changes..

**Comment by dbrownukk** [comment]
deployed to IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
Instance: Testing
App: OIHM - Reporting & Modcelling
Study: Mitinyana-HyCRISTAL-Wamala lakeshore 

Reporting: 
---

1. In the detail view of the above Study
> Note there is no Site for this Study
2. Click Report menu bar option
> ERROR: Study requires a Site to run Report.

**Tested OK** 


Modelling: 
--
1. In the Modelling Module, select Change Scenario titled: "Uganda small lake"
> Note this is a model of the Wamala Study used above
2. Click  Report menu bar option
> Note the HH selection popup appears as normal
3. Select Change Scenario and any 1 household ( tried several)
4. Click Run
>  ERROR: Impossible to execute Run action: null

So the action is correct - but the message is not as helpful as the Reptor run error message
And ideally, the site check and the error message should precede the popup to minimise wasted user time

**Comment by dbrownukk** [comment]
Modelling OIHM report now checks that a Site exists for the Study before popup appears.

Deployed IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
Modelling:
==

1. In the Modelling Module, select Change Scenario titled: "Uganda small lake"
> Note this is a model of the Wamala Study used above
2. Click Report menu bar option
>ERROR: Study requires a Site to run Report.

**Tested Ok**
