### ISSUE TITLE
OHEA: Modeling - Unable to run Change Scenario for a particular Village

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#643]
Instance: Testing
App: OHEA Modelling
Change Scenario: Modelling Extensions Test
LZ: Katakwi - Fishing & Livestock Zone
Village: Ku

1. In Livelihhods Modelling module, select this change Scenario
2. Click Report menu bar button
3. Select village 'Ku'
4. Click Run
> ERROR Impossible to execute Run action: null

I have inspected the Community record and the others in the LZ (which all run fine), but i can't spot the faulty data - and i guess that's what it is.

**Comment by dbrownukk** [comment]
fixed - problem with optional returning value.

deployed to IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
**Tested Ok**
