### ISSUE TITLE
Price yield model bug?

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#645]
QA instance
Livelihoods modelling
Nimfru, Katakwi
Fishing & Livestock LZ 
Clicked new to create new change price yield scenario
Selected cassava chips
Yield change 50
Price change 140
clicked save and continue
Error message: modellingscenario.uk_qbgrp2jkeklp69r1j82vuahlo

**Comment by daiClegg** [comment]
Which change scenario is this, please?

**Comment by daiClegg** [comment]
@celiapetty which change scenario were you using, please?
I'm back now and will test and try to diagnose.

**Comment by celiapetty** [comment]
I was trying to create a new change scenario-as the exercise failed, it doesn't appear on the list. I'll go through the routine again and let you know if the same error message comes up

**Comment by celiapetty** [comment]
OK-problem resolved, have created a new price yield change for Katakwi Fishing and l'stock labelled new price yield Katakwi

**Comment by celiapetty** [comment]
Resolved
