### ISSUE TITLE
OHEA change scenario visualisation not functioning as expected

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#646]
QA instance
Livelihoods modelling
Nimfru
Katawi crop and livestock zone
Selected  Katakwi OHEA Floods, 
Celia 11.01.21
Charts with combined results for the zone are not shown: only individual results for each site.

**Comment by daiClegg** [comment]
Should have added a comment: 
I'm not sure what you n=mean here.
Do you mean you want LZ level reporting?
If so which reports?

**Comment by celiapetty** [comment]
Resolved-just commented

**Comment by celiapetty** [comment]
Resolved
