### ISSUE TITLE
Suspect Data in a study

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#647]
Instance: Test (but presumably the others as well)
App: OIHM
Study: MINFRU - Katakwi AIHM
Household: 1
Household Name: Okwi Bosco

This HH  has employment, Agricultural Day Labour, Unit year,  of units 1, payment 60 Kg Sorghum Flour
That means they got paid 60Kg for a year's work.
That sound wrong, unless the meaning is that they worked for 1 short period of time in the year and got paid 60KG Sorghum Flour for that.

But it looks suspicious, so i thought i'd raise it.

**Comment by celiapetty** [comment]
The data is ok - it will be 60kg for harvesting work. Stella will have
overseen this- so 1 = all the harvesting and all the food. Thanks for
querying this.
