### ISSUE TITLE
Livestock Sales have no Name

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#648]
Instance: Testing
App: OIHM
Study:  Katakwi - AIHM (but also present in every relevant HH i looked at in several studies)
Module: HH

1. In Detail view of any HH, navigate to Livestock Sales tab
2. If necessary navigate between HHs until you find on with at least one Livestock Sale record
> It has no name.

I did set on HH to editable  - to check if it was a display issue, but the links appear to have been lost everywhere.

**Comment by daiClegg** [comment]
does not reproduce in LIvestock sales in OHEA (same instance)

**Comment by dbrownukk** [comment]
You can add LSS Resource Type in both Wealthgroup and Household when they are set to editable.

When validated they do not disappear and when set to editable again they are available.

Somewhere in Testing data they became null. No idea where or when. 

Seems OK in QA instance.

Have manual backups of test, qa, and prod data (also rainwatch!) as of today.

**Comment by daiClegg** [comment]
**Tested Ok**
