### ISSUE TITLE
Unable to run coping strategy reports for 1 specific HH

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#651]
Instance: Testing
App: OIHM / Modelling
Change Scenario: CopingStrategyTests
HH: 91

1. navigate to the 'CopingStrategyTests' Change Scenario 
2. click Reports
3. select 'change scenario and coping strategy' execution option
4. in the HH list select HH91
5. Click Run
> ERROR: Impossible to execute Run action: null

**Comment by daiClegg** [comment]
I've tried it for every other HH in this Study with no error.

I've inspected the HH data set, but i cannot find a missing data item,

**Comment by daiClegg** [comment]
i tried setting it editable and then validating it - to see if there's old data that is now invalid, but it validated fine and still fails.

**Comment by dbrownukk** [comment]
Damn curse of java '.equals'. If a transfer then it could have a SizeofTransfer, which was null.

Using  expandabilityRule sizefoTransfer for Study == Family then multiplier is x1, but needs to handle no sizeoftransfer

**Comment by dbrownukk** [comment]
fixed - deployed to IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
**Tested Ok**
