### ISSUE TITLE
Some employment cash income appears to be missing in OIHM reports

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#653]
Instance QA
Module OIHM livelihoods reports
Study Chilimba
Comparing OIHM output with the original IHM output (prompted by Alice Murphy's dissertation)
Alice has uploaded all 88 spreadsheets from the original study. I have randomly checked a small sample and no errors in data entry were found.
I have compared OIHM DI with IHM reports (DI; cash income-non standardised; food income-non standardised.  Discrepancies in food income not found (very minor differences as noted in Stella's original testing). However, many households are reporting 0 cash income from employment. I've cross checked a number of households uploaded in the software, and income is recorded eg  HH6 Clearing land (12000) and selling crops (24000).  Not all households register 0 income from employment-particularly those higher up the income distribution.
Do you have an idea on the cause of the problem? I will need to let Alice know there's a problem before she starts working on her analysis and final report.

cc'd Stella whom I alerted to the problem. Stella-it looks as if the cause relates to employment income and may be the result of a user error.

**Comment by daiClegg** [comment]
For HH 6 in Chilimba, the number of people who were employed is recorded as 0 for both employments - hence the total payment would be 0. I assume it should be 1.
Can you fix that and see if that eliminates the discrepancy?


I haven't checked any other HHs.

**Comment by celiapetty** [comment]
Yes it looks as if this is the problem. Alice is correcting employment
data entry. Will look at the revised output tomorrow. Many thanks for
following up.

**Comment by celiapetty** [comment]
This was a data entry error which has now been resolved
