### ISSUE TITLE
OIHM: Reporting gives 'Index Out of Bounds' exception for Disaggregated Food Sources report, if no LZ in the Project.

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#654]
Instance: QA
App: OIHM
Module: Study
Study: Chilimba

1.  In the Detail view of 'Chilimba' Study, click Reports
2. In the report spec drop-down select 'Disaggregated Food Sources'
3. Select HH1 in the Households list
4.  Click Run

> ERROR: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0 Errno = 2266

**Comment by daiClegg** [comment]
This reproduces for the next 2 HHs in 'Chilimba' (the only others i've tried so far).

It does NOT reproduce for any HH in 'Katakwi - AIHM'.

So i guess it's a data problem.
I've only had a very quick look so far, but i can't see the problem yet.
Alice the MSc student entered ths data and is not as real-world as Stella, so it's conceivable her 'fresh pair of eyes' has inadvertently spotted a chink in the validation.

But if we knew the error i can ask Alice to fix it by hand and then she can complete her analysis (and her thesis), which she needs to do by 30th August.

**Comment by daiClegg** [comment]
Tested for OHEA on QA and it worked - but that was old data.

**Comment by dbrownukk** [comment]
Data looks ok. exporting QA data to my dev machine to debug

**Comment by daiClegg** [comment]
Update from David's investigation: 

OIHM Study Reports expect and LZ in the Project that contains the Study.
'Chilimba' has no LZ.
So the bug is that there is not a helpful error message - tbd.

Meanwhile adding a LZ to the  Chilimba' Project will fix this issue, for current needs.

**Comment by daiClegg** [comment]
Added the LZ ('Chilimba'  to the 'Chilimba'  Project 
**Tested Ok**

but will leave open with revised subject pending the improved error message

**Comment by dbrownukk** [comment]
OIHM report now checks for Study.Project.Livelihoodzone >0 and errors if not. 
Not deployed

**Comment by dbrownukk** [comment]
Deployed to IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
Instance: Testing
App: OIHM
Module: Study

It is not possible to run reports if there is no Site in the Study.
It is not possible to define a Site without an LZ in the Project that contains the Study.
So it is not possible, using best practice, to get into the previously anomalous situation.


But it is possible to edit  the Study to change Project.
That Project can be one with no LZ.
The Study still has a Site.,
But the LZ that contains that Site is not in the Project.

Then you can run reports & use a report spec that included Disaggregated Income,
When you hit run, you get "Study Project has no Livelihood Zones"

**Tested Ok**

The unusual edit sequence of Project, Study, LZ & Site that is required to get here might conceivably happen if the user was  fixing up a data set  that had been incorrectly set up, so it's hard to say we should prohibit this - especially as the software protects the user from reporting while in that state. 
So i think we leave well alone
