### ISSUE TITLE
OIHM: Disaggregated Food Sources report contains wrong LZ

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#657]
Disaggregated Food Sources report always reports the LZ to be the first one in the Project, regardless of whether that is the one in which the Study is located.
It should use the LZ that contains the Site of the Study.

**Comment by daiClegg** [comment]
See also #656

**Comment by dbrownukk** [comment]
Now selects correct LZ and displays in Disaggregated report 

Deployed to IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
Instance: Testing
App: OHEA
Module: Reporting
Project: NIMFRU
LZ: Katakwi - Crop & Livestock Zone & Katakwi - Fishing & Livestock Zone

1. In Project Report module, click report icon for LZ 'Katakwi - Crop & Livestock Zone'
2. In report pop up select Disaggregated Food Sources from report Spec drop down
3. Select all Communities
4. Click Run
5. Dismiss the report pop up
6. Open the downloaded data extract & navigate to the Disaggregated Food Sources tab
> Note the LZ name in col A is 'Katakwi - Crop & Livestock Zone '
7. click report icon for LZ 'Katakwi - `Fishing  & Livestock Zone'
8. Repeat steps 2. to 6. 
> Note the LZ name in col A is 'Katakwi - Fishing & Livestock Zone '

**Tested Ok**

**Comment by celiapetty** [comment]
Before promoting this to QA: would it be more accurate replace references to Disaggregated Food Sources to Disaggregated Income sources-as this also includes all sources of cash income? Unless there's any reason not to do this?

**Comment by daiClegg** [comment]
No problem. I wanted to check that livestock sales are covered (affect CI but not FI), otherwise the CI coverage would be incomplete,

Let's keep this closed and could you raise a new issue for the name change, please?
I'll schedule it asap.
