### ISSUE TITLE
List Projects and Studies via API request.

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#658]

**Comment by dbrownukk** [comment]
Deployed and available from https://idaps.walker.ac.uk/efdrest/swagger-ui/index.html

Note this is on data from Prod database

https://idaps.walker.ac.uk/efdrest/api/v1/projects
https://idaps.walker.ac.uk/efdrest/api/v1/studies

**Comment by daiClegg** [comment]
**Tested Ok**
