### ISSUE TITLE
Messages displayed in an invisible position

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#66]
Testing Issue #54, i had 2 confirmation messages (create project * add LZ to project were successful.
But i could not see them,  as in screenshot below:

![image.png](https://images.zenhubusercontent.com/5a81590c4b5806bc2bc688fc/35171dd0-0d9f-42dd-b77a-53aa986a8a1a)

If i scrolled up, i could see the confirms, but the failure message was truncated, as in the screen shot below:

![image.png](https://images.zenhubusercontent.com/5a81590c4b5806bc2bc688fc/fafd5fe2-72bd-493f-8016-aa3817d484c1)

I then resized display and now i can see the message, but not the whole screen, as in screen shot below:

![image.png](https://images.zenhubusercontent.com/5a81590c4b5806bc2bc688fc/81dd44e5-9d44-4342-aa2a-a88bcefb4f2a)

i'm sure this is a restriction due to the small screen i'm using, but one for the openZava community?O

**Comment by dbrownukk** [comment]
OpenXava - should be fixed in OX 6

**Comment by daiClegg** [comment]
To be tested when we've upgraded to OX6.0

**Comment by daiClegg** [comment]
Does not reproduce in OX 6.0.

As you resize the window, right-aligned error messages move to remain visible adn then wrap to multiline if the window becomes very narrow.

Nice
