### ISSUE TITLE
Value for employment sub type unit required in RST listing

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#662]
QA instance
HM  Common
Resource sub type
List:  Employment

This may be problematic.  The RSTs show a unit (day, month etc) beside each employment type. However, we now have a data entry set up (spreadsheet template and direct data entry) that correctly allows users to enter the employment unit (day, week, month, year, piece) for each employment type. This is needed as the same employment type (eg repairing bicycles) at different sites, and even among different households in the same site, might be paid daily, weekly or monthly. I've checked in the RST module to see if the it's necessary to enter a resource sub type unit. It is.   As a resource sub type unit is needed
1. could n/a be entered here (or something similar) and the unit entered as appropriate when hhold data is being entered?
2. if the items in the RST are edited (eg Sub type unit under Agricultural Labour  changed to n/a) will that affect all the existing data entered as Agricultural labour (meaning this isn't an option?) 
3. If a change is made that removes the requirement to enter a sub type unit would that also have the effect of deleting/making unsearchable, employment data that has already been entered?

**Comment by celiapetty** [comment]
Will get back on this when we've had a chance to discuss/I understand the question fully . The user needs to be able to enter the unit relevant to  that specific study location and particularly with employment this is not fixed (hence the potential confusion with say-a RST that was listed as  'Selling fruit, month' when fruit sellers in that place only know how much they earn/day. ) I may have misunderstood the question

**Comment by daiClegg** [comment]
If the data entry overwrites the default 'month' with 'day' and enters '52' meaning 52 days of fruit selling, meaning once a week, then the income calculation will come out correctly as 52 times whatever they enter for the daily income.

If you say you have 'x' units of any commodity and you get paid 'y' per unit, then your income is 'x' times 'y'. 
It doesn't matter what the unit is, as long as it matches the income **per** unit

**Comment by celiapetty** [comment]
I think this means we leave things as they are but clarify in training interviewers should establish the relevant time period (day/week/month/year) for the rate and can ignore the time period shown on the RST?

**Comment by daiClegg** [comment]
We would care what the unit is would be if we wanted to know say, how much employment of a specific type was available in a   village - we would know how much was earned from that employment, but a user would need to check the unit  the unit we to work out the total days available.
But even then, if it's recorded in months , say unless we know how many actual days we don't know (e.g. Brewing, 100, 000 per month - is that 50,000 a day for 2 days or 25,000 for 4 days?)
If that's a degree of detail you'd not expect to automate then, i agree, we don' t care about the unit and can leave the software as is.

Please re-open this if i'm wrong.
