### ISSUE TITLE
OIHM: In  HH Interview Template Spreadsheet, LOVs for HH & HHM  Configuration Questions are assigned to incorrect questions

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#664]
Instance: Testing
App: OIHM
Module: Study
Study: Chitipa - MA4 - Mk

1. in detail view of above study navigate to Questions tab
> Note there are multiple questions for HH  & HH Members most with LoVs
2. Examine the question definitions
> Note they are all correctly specified with meaningful answer validation
3. Click 'Template Spreadsheet'
4. Open downloaded spreadsheet & navigate to HH Config tab
> Note that the answer validation for the two questions are transposed
5. Navigate to the HH Members tab
> Note that the answer validation for the questions are ordered differently from the questions

**Comment by daiClegg** [comment]
added to sprint

**Comment by dbrownukk** [comment]
Template creation did not increment row if answer type was text - now handles for HH and HHM 
line 343 in createXlsFileActionTemplate.java

**Comment by dbrownukk** [comment]
deployed to IDAPS_Livelihoods_TESTING

**Comment by daiClegg** [comment]
HH questions now correct.
HH Member questions are using the wrong Lists for LoV Questions

**Comment by dbrownukk** [comment]
Code was nowhere near HHM, but had reused variable and not reset... fixed.

Deployed IDAPS_Livelihoods_testing

For info - making changes to Asset Units LOV in HH module - not finished yet

**Comment by daiClegg** [comment]
Behaviour for HHMember spreadsheet tab does not appear to have changed.
Repeated steps as above  (ignoring step 4 since that's tested ok, above).

Attached is the template spreadsheet created, with a sample HHMember dataset filled in.

[MA4 Chitipa_Chitipa - MA4 - MkMon Sep 27 16_54_03 UTC 2021.xlsx](https://github.com/dbrownukk/EFD_v2/files/7238087/MA4.Chitipa_Chitipa.-.MA4.-.MkMon.Sep.27.16_54_03.UTC.2021.xlsx)

**Comment by dbrownukk** [comment]
No idea, had tested this locally and on server. deployed again and tested again and is working. Uganda is drop down option for the country question

**Comment by daiClegg** [comment]
**Tested Ok**
