### ISSUE TITLE
Wrong community interview template uploaded

### ISSUE THREAD

**Issue by celiapetty** [dbrownukk/EFD_v2#665]
QA Instance
HM Common
Template download

This will be my error-I must have forwarded the wrong template spreadsheet for the Community Interview. Please delete 'Example blank community interview' Current and 'Example blank community interview' Archive. These are in fact wealth group interview templates.
Please replace with the attached template labelled ' Template community interview blank'
[Template  community interview  blank.xlsx](https://github.com/dbrownukk/EFD_v2/files/7178242/Template.community.interview.blank.xlsx)

**Comment by daiClegg** [comment]
You can upload it yourself.
See the Templates module on the HM Admin menu.
Im away this week so won't get to th  oh s before I get back.
If you do upload it please note her which instance(s) you've done it for.

**Comment by celiapetty** [comment]
Done-Uploaded to QA instance
