### ISSUE TITLE
OIHM: Apparently valid Transfer record does not parse

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#666]
Instance: Testing
App: OIHM
Module: HH
Study: Chitipa - MA4 - Mk 
HH #: 60

1. View HH above in HH module (detail view)
2. Download uploaded interview spreadsheet and inspect Crop, Employment & Transfers tabs
> note:  There is one Crop record, one Employment record and Two transfer records. All appear to be correct.
3. In the app, click Parse Interview Spreadsheet
> ERROR: Problem parsing Transfers worksheet java.lang.IllegalStateException: Cannot get a STRING value from a NUMERIC cell
> note: The parse completes and the interview validates; the Crop and Employment records are successfully added and validated. But there are no Transfer records.

**Comment by daiClegg** [comment]
Further test:

HH #: 61

only 1 transfer (the first) all other data the same.
same process
same error

**Comment by daiClegg** [comment]
Further test:

HH #: 62

only 1 transfer (the other) all other data the same.
same process
same error

**Comment by dbrownukk** [comment]
It was what it said - Cannot get a STRING value from a NUMERIC cell

Fixed and deployed idaps_livelihoods_testing. Also noted that the parse was not firing the update to the on screen Units - also fixed (and in HEA parse)

**Comment by daiClegg** [comment]
Testing on same Study as above.
 HH60 now successfully validated, so test as follows:

1. Download the Spreadsheet attached to HH60 of Chitipa study
2. Open downloaded spreadsheet; on Interview Details Tab, change HH name to a new unique name
3. Save Spreadsheet
4. In HH module, create new HH - select Chitipa study, enter interviewer & data
5. Click Save
> HH created successfully
6. Upload interview spreadsheet, set status to uploaded
7. Click Save
> HH updated successfully
8.  Click Parse Interview Spreadsheet
> PArse succeeds, HH record styatus s set to Validated

**Tested Ok**
