### ISSUE TITLE
Can add the same LZ to a project twice,

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#68]
In Project module, List view, select any project which already has at least one LZ, e.g.P1
In project detail edit for selected project click Add LZ
From the LZ list, select an LZ relady in the project.
Click Add.
Successfully adds the LZ a second time to the project.

**Comment by dbrownukk** [comment]
Need unikque constraint on intersection

joinColumns = @JoinColumn(name = "Project", referencedColumnName = "ProjectID", nullable = false), 
	inverseJoinColumns = @JoinColumn(name = "LZ", referencedColumnName = "LZID", nullable = false),uniqueConstraints=
            @UniqueConstraint(columnNames = { "Project", "LZ" }))

**Comment by dbrownukk** [comment]
deployed constraint

**Comment by daiClegg** [comment]
Tested ok, but you are left in a list view of the LZs, not as a popup, but full window.
If you click cancel it returns correctly to the Project detail view correctly.
if you click Add, with either no LZ selected or a different LZ selected or the same LZ selected if fails.

So functionally it works.
From a UX perspective it would be better to either return to the Project detail view or the LZ picker list popup - and support legitimate LZ selection.

If this is a complex fix - push it.

**Comment by daiClegg** [comment]
Tested ok. Functionality is correct, UX is fine
