### ISSUE TITLE
Complete Spreadsheet generation 

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#7]

**Comment by dbrownukk** [comment]
Go to Community module. Wealthgroups now have an extra column to generate template spreadsheet
Will need some tweaking but up for testing

**Comment by daiClegg** [comment]
I see it and have tested, but i cannot find a generated spreadsheet, either in the Downloads folder or anywhere on the hard disk.
On a Mac, where should it be and what should it be called?

**Comment by dbrownukk** [comment]
It should appear as a file starting with the Project Name  i.e. 

6 Community Interview N Gombere.xls

If you have an application associated with the /xls extension then the file should open in the application - excel 

tested on Mac and Windows here

**Comment by daiClegg** [comment]
The name of the spreadsheet is derived only from the Project name.

That means it will be the same for each WG in each Community, which will be confusing for users.
We can only guarantee uniqueness if the spreadsheet name is a concatenation of WG (English name), SubDistrict Name, District Name, LZ Name & Project Name. But that would be way too long and almost certainly unnecessary.
So i suggest <Project>_<SubDistrict>_WG.xls
and truncate the SubDistrict to 10 characters. 

WDYT?

**Comment by dbrownukk** [comment]
Dai,
Getting to like OpenXava even more!
The file name can be any length. Windows and Mac seem to handle large file names. Any truncation does run the risk of a duplicate
filename = community.getProjectlz().getProjecttitle()+'_'
 +site.getLivelihoodZone().getLzname()+'_' +wealthgroup.getCommunity().getSite().getLocationdistrict()+'_' +wealthgroup.getCommunity().getSite().getSubdistrict()+'_' +wealthgroup.getWgnameeng(); 



Will that work for the moment?
David 
    On Monday, 12 February 2018, 12:27:57 GMT, dai clegg <notifications@github.com> wrote:  
 
 
The name of the spreadsheet is derived only from the Project name.

That means it will be the same for each WG in each Community, which will be confusing for users.
We can only guarantee uniqueness if the spreadsheet name is a concatenation of WG (English name), SubDistrict Name, District Name, LZ Name & Project Name. But that would be way too long and almost certainly unnecessary.
So i suggest __WG.xls
and truncate the SubDistrict to 10 characters.

WDYT?

**Comment by daiClegg** [comment]
The names could be very long, and only unique in the last few letters (Poor, Middle, BetterOff).
So how about moving the distinguishing sections to the front:

filename = wealthgroup.getCommunity().getSite().getSubdistrict()+'_' +wealthgroup.getWgnameeng()+'_'community.getProjectlz().getProjecttitle()+'_'
 +site.getLivelihoodZone().getLzname()+'_' +wealthgroup.getCommunity().getSite().getLocationdistrict();

**Comment by dbrownukk** [comment]
How about

**Comment by dbrownukk** [comment]
That will work 


deploying now

**Comment by daiClegg** [comment]
Tested ok & closed
