### ISSUE TITLE
On CommunityYearNotes tab of Community module, Year should be "yyyy" format, not ""dd/mm/yyyy" format

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#70]
Only need the year for year notes - indeed anything else is confusing.

**Comment by dbrownukk** [comment]
Done - Numeric between 2000 and 2030 (should see us through...)

**Comment by daiClegg** [comment]
Tested ok in display in list view of Community Year Notres in Commmunity module,
And in Edit popup for Year Notes detail.
Not tested in Community Year Notes Module (Hidden).
