### ISSUE TITLE
Cannot add Community Year Notes iYear Notes tab of Community Module

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#72]
IN Community Module
In List view
Select Any Community.
In Detail view
Select Community Year Notes Tab
Enter Year & txt.
Press Save, 
- you momentarily get a "Loading" indicator. The returns to the input record, unsaved.
Save & Continue behaves similarly.

Is this related to the fact the Community Year Notes module is "Hidden"?  
Popups are enabled

**Comment by dbrownukk** [comment]
Wrong datatype on server - needed to change datetime to int(4)

Would help if port 3306 was open and I could do a database compare with local db .....

Fixed

**Comment by daiClegg** [comment]
Tested Ok.
