### ISSUE TITLE
Renamed Resource type "Use of Livestock" to "Livestock Products"

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#74]
After discussion with John, i have made this change to the static data to better represent best practice.

Does this affect the generation of the  WG interview template spreadsheet or is that driven from the UID of this row, rather than the name field?

**Comment by dbrownukk** [comment]
Spreadsheet worksheet tab is now  "Livestock Products" 

Currently the resource type and spreadsheet name are hard coded - they could be linked so that we get a new worksheet for each asset type but without a generic layout this is pointless as the layout is hard coded

**Comment by daiClegg** [comment]
I'll raise another issue, as a question, about how we might genericise the spreadsheet tab to resource subtype instance belonging to a WG Interview.

**Comment by dbrownukk** [comment]
done - deployed

**Comment by daiClegg** [comment]
Tested OK.
