### ISSUE TITLE
Cannot see LZ map field in any view of the record

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#75]
In all views in the LZ module (detail, edit & new.), and in LZ frame of Project module, the Map is no longer visible.  I think it should be in the Project module and it must be in the Edit & New views

**Comment by dbrownukk** [comment]
Seem to have removed lzzonemap when adding currency!

Back now - maps look great

**Comment by daiClegg** [comment]
Tested OK, in LZ create  & edit and in Project.
