### ISSUE TITLE
Is it possible to pin modules in the menu, or is it always dynamic?

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#77]
It would make life easier for ordinary project users who will primarily use Project & Community if those 2 modules were pinned in the menu.

This thread albeit on a slightly different subject:

https://sourceforge.net/p/openxava/discussion/419690/thread/17b3741b/
seems to say that permanent menu items can be defined in application.xml.
Is that right? The documentation for application.xml doesn't make it obvious how you'd do that.

I can't find any more definitive answer in the forum or elsewhere.

**Comment by dbrownukk** [comment]
This will be in version 5.9 of OpenXava - no release date...

To have certain modules always present on top menu use fixModulesOnTopMenu (new in v5.9) in naviox.properties:
fixModulesOnTopMenu=Invoice, Order
Just the list of modules separated by commas. The modules will be always on the top bar, unless the user has no rights to access them.

**Comment by daiClegg** [comment]
Changing the tag to Enhancement for consideration when the feature is available

Pinning Project & Community would be valuable for the M1 features.
Revisit this in the light of later milestones when UX specifics defined and tested by end users.


Reason: see original description for the user value of this.

Dependent on OpenXava Release 5.9

**Comment by dbrownukk** [comment]
I have pinned Project, LZ, Site, COmmunity and WealthGroupInterview

need to edit naviox.properties in properties directory

fixModulesOnTopMenu = Project,LivelihoodZone,Site,Community,WealthGroupInterview

**Comment by daiClegg** [comment]
Tested OK.
