### ISSUE TITLE
Error generating WG I/V spreadsheet

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#78]
Attempting to generate a spreadsheet and got:

>Impossible to execute Template spreadsheet action: could not initialize proxy - no Session

Save and retry - works.
But try to generate the next WG spreadsaheet - fails again.

**Comment by daiClegg** [comment]
If it works for the first spreadsheet, try another WG in the same Community.

**Comment by dbrownukk** [comment]
looks like a hibernate problem with the transaction. suspect it might be the creation of the WealthGroupInterview  record and setting its status to 'Generated'  - that is all that has changed.  Investigating - I can reproduce

**Comment by dbrownukk** [comment]
removed extra hibernate commit - tested

**Comment by daiClegg** [comment]
Tested OK.
