### ISSUE TITLE
LIst view of WG Interview needs to include LZ & Project

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#79]
When viewing the list view of WG I/Vs there will typically be 20+ per project, so in a database with dozens or even hundreds of Projects, there's no chance of finding the ones you want.

So the first 2 columns need to be the project name and the LZ name.

**Comment by daiClegg** [comment]
Ideally the sort order should be WG order, within Subdistrict, within LZ within Project

ie Poor, Middle, Better off, for each village together - and in the same order.

**Comment by daiClegg** [comment]
Ideally the sort order should be WG order, within Subdistrict, within LZ within Project

ie Poor, Middle, Better off, for each village together - and in the same order.

**Comment by dbrownukk** [comment]
Thus we need site location district and subdistrict in List.

List is getting busy!

**Comment by daiClegg** [comment]
Tested OK.
