### ISSUE TITLE
IN the detail view of the WG interview we need the Subdistrict name

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#80]
In order to upload you need to identify the spreadsheet you want in the file-search dialog.
The name of the spreadsheet will be some combination of LZ, subdistrict & WG. So you need to have these in front of you as you go through the list of .xls to be sure you've got the right one.

**Comment by dbrownukk** [comment]
Extended the Wealthgroup field to include subdistrict 

Would be better to have individual fields but the reference view option to show individual fields has an issue..

Anyway, you can see context.

**Comment by daiClegg** [comment]
Tested OK.
