### ISSUE TITLE
Ambiguous error message when generating WG i/v spreadsheet

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#82]
Project = NewTestProject
Commmunity District  =  D Z11
Commmunity SubDistrict = SD Z11

entered minimal data  (ie no interviewer or attendees data)
Saved ok.

Generated spreadsheet ok; content appears to be correct.
But 2 error messages thrown by the app:

>Value for {0} in {1} is required

>is not a valid value for Wg interviewers of Wealth group interview: Value for in cannot be an empty string

**Comment by daiClegg** [comment]
Cannot subsequently see the Wealth Group in the WG I/V module, so i suspect the record has not been crerated, even though the spreadsheet has been generated.

**Comment by dbrownukk** [comment]
Needed to set mandatory columns in WealthGroupInterview to a value if they are blank in Community

InterviewNumber
Interviewers
IntervieweesCount

**Comment by daiClegg** [comment]
Tested OK
