### ISSUE TITLE
Create  downloadable installable instance for Mac & Windows

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#83]

**Comment by dbrownukk** [comment]
No dependencies might be interesting. The best way that jumps to mind is a virtual machine or docker image with self contained working environment.  Yes, a VM engine or Docker would be needed but other than that things should be straight forward

**Comment by daiClegg** [comment]
You're not reading the Zenhub-added message above about (issue) dependencies are you?

That said, a container approach would make life very simple for users. 
If all they have to do is download a Docker installer and then an OHEA, bundled install.
easier than MySQL, Tomcat, Java, OpenZava, etc, etc as separate installs, even with a sophisticated installer.

To be discussed.

**Comment by daiClegg** [comment]
Tested VirtualBox VM , all ok, functionally.

2  issues:

1. User needs to share files between physical host and VM (e.g.spreadsheets for uploading)
2. Many users will not be comfortable with using another operating system inside the VM

The chosen resolution of  both these issues is to expose the VM to the host as a localhost.
Then it can be accessed exactly as though it were the cebtral IDAPs server.
See Issue #84 for progress on documenting install and configuration.
