### ISSUE TITLE
Include a single  default user for instance - with no rights to update core static data

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#85]

**Comment by daiClegg** [comment]
Need a mechanism for accredited users to download the latest version and need that to be empty (no projects.
Preferably only allow one project; could this be a database value? Since it always has an empty database (empty of dynamic data) that might be possible.

For discussion

**Comment by daiClegg** [comment]
Fr this to be workable we need an page on the IDAPs server where users can request a download.
Not this will have to be user credential constrained, because we do not want people to download the software without registering.

See also #115 which has an analogous requirement,

**Comment by dbrownukk** [comment]
See #164 for downloadable virtual image - yet to configure image to be single user and restrict ability to create  rst

**Comment by dbrownukk** [comment]
Virtual Image 

New Role EFD_REMOTE - read only on RST

Users admin, efd and efdfield

efdfield user has role efd_remote

**Comment by dbrownukk** [comment]
User efdfield has 1 Project available with name 'Change Project Name'

The role EFD_REMOTE cannot create or delete a Project

**Comment by daiClegg** [comment]
RSTs will be updated before shipping, but since the code will as well, i assume this is an interim test version anyway.

We discussed a requirement for the remote user to be able to create synonyms of existing RST, by no new RSTs. But i'm not sure i captured that as an issue anywhere.
If i did i can't find it.

Can we do that?

**Comment by dbrownukk** [comment]
If field admin wants a new RST it must have a completed synonym field  (check use of Role)

**Comment by dbrownukk** [comment]
If user has role 'efd_remote' then the synonym must be entered for a RST. 

User efdfield has one role only - efd_remote for use on single Project instance. No create or delete privileges on 'Project'

Note - to get User Privs need the following 

		String userName = Users.getCurrent();
		User user = User.find(userName);	

	if (user.hasRole("efd_remote") && resourcesubtypesynonym == null) {
			System.out.println("Need to stop update");
			throw new javax.validation.ValidationException(
					XavaResources.getString("Field Users must enter a SubType Synonym"));
		}

**Comment by dbrownukk** [comment]
deployed - can test on idaps with User efdfield that has role efd_remote

**Comment by daiClegg** [comment]
1. tested project create - no 'New' button on the Project module - tested ok.
 2. tested creating an RST - disallowed without a synonym - tested ok.
 3. general project test - community, WG, generate spreadsheet - tested ok.
 4. general project test - upload, parse, validate, report - tested - ok

seems to be working fine.
