### ISSUE TITLE
Spurious data values created on upload of WG interview spreadsheet

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#89]
Project:                    Mukono Trial
Village/Subdistrict: Bugoye/Ntenjeru 
WG:                          Middle
Resource Type:       Transfers

'Other Use' value is set to "35.0" for all rows. This value is not in the spreadsheet

Similar spurious values are not created in other WG Interview records (not searched all - but no others i looked at are similarly incorrect.

**Comment by dbrownukk** [comment]
Lesson learnt. 

'Other' variable not reset between getting each resourcetype.

Fixed

**Comment by daiClegg** [comment]
No longer able to reproduce this error, either by displaying the previously incorrect record or by navigating between tabs with the  'other use' column set - which would testt he diagnosed fault.
So closing as fixed.
