### ISSUE TITLE
ResourceSubType Unit - 

### ISSUE THREAD

**Issue by dbrownukk** [dbrownukk/EFD_v2#9]
ResourceSubType Unit is current modelled as a decimal and implemented as a decimal 
BUT spreadsheet has 'Acre' as a Unit i.e. a String

**Comment by daiClegg** [comment]
It should be a varchar.
Example values might be Kg, Acre, Unit (ie count, e.g. of Chickens).

This is an error in the model - now corrected

**Comment by dbrownukk** [comment]
is Varchar(20) sufficient length 

fixed on laptop version and github

**Comment by daiClegg** [comment]
Yes; let's go with 20
