### ISSUE TITLE
Site module should include Project as well as LZ and they should be 1st 2 columns

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#90]
when i use the site module i ned to know what project i am in

**Comment by dbrownukk** [comment]
Have been working on this and finally realised why I cannot get this to work. 

Any of the extra columns shown in the List view, not belonging to core entity - namely 'Site' must be a reference not a collection. 

Site has a reference to a LZ but the relationship to Project is then a manytomany

Similarly Site is related to Community, but it could be one or more communities, making it impossible to display many communities against one site in a list. 

Does that make sense.

The way to do this would be to only show the Site list in context of Project and LZ - for discussion..

**Comment by daiClegg** [comment]
In normal use Site is usually viewed in the context of a Community.
Restricting it to only be otherwise accessed as part of an LZ would be an acceptable resolution

Low priority to remove Site from the user accessible modules list, since they won't use it very often anyway,

**Comment by daiClegg** [comment]
This is no longer a requirement, since the Site module is not used in any real-world usecase
