### ISSUE TITLE
Provide visual summary of Assets, by Resource SubType, by Wealth Group

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#92]

**Comment by daiClegg** [comment]
As per the 'Assets' tab of the standard reports spreadsheet (attached to parent Epic of this Issue).

**Comment by dbrownukk** [comment]
The standard core.spreadsheet with example reports is keeping something hidden from me. Now that I have one graph working I focused on the data quality. For this report - 'Assets' what value is on the Y axis? Comparing number of acres in Land asset with number of cows in Livestock asset is nonsense. Thus I am missing, misplaced, forgotten the calculation for the Y axis values.

**Comment by daiClegg** [comment]
I have asked John to clarify. I don't have the original spreadsheets this data was derived from.

**Comment by dbrownukk** [comment]
Example now deployed to get the chart ball rolling.

Communityid is passed to chart which then displays Assets of type land and Livestock 

Asset Report is only available from the WGI detail page - but does not quite make sense, as we display multiple wealthgroups on the chart but only see one wealthgroup in the screen..

for discussion... but the main point is that we can now attached charts to the application.

**Comment by daiClegg** [comment]
Seems to report accurately, but the WG name is not displayed (truncated to 2 characters) and the order of WGs appears to change when i rerun the report (having changed assets).
Need that fixing somehow to test properly.
Smaller font might be good enough, since the legend is very likely only 'very poor', 'poor', 'middle' or 'better off'.


I agree that running the report from a single WG for all WGs is not the right place.
But it does report on that WG (amongst others) so it's not wrong.
Perhaps the reports should be on the Community module, if that's their scope, as well as the WGI module?

**Comment by dbrownukk** [comment]
Strange - I have tried on mac and windows laptop in Chrome and Safari and I get the full wealthgroup names. 

![Screen Shot 2018-08-11 at 08.51.43.jpg](https://images.zenhubusercontent.com/5a814e994b5806bc2bc6879c/565a21e0-d669-4003-b8ee-96fccfc24197)

The graphs do not shrink on reducing size of browser. Currently creates a PDF - I can change to HTML?

What browser are you using and which community?

I will add a default order to the wealthgroups

**Comment by daiClegg** [comment]
Aah, the problem arises because i have a community with 9 WGs - just for testing purposes.
Works fine for me on a more reasonable number.
Not important to fix for 9, since that will never occur in real use.
Tested OK.

before i close this i want to test on more complicated, real world, Community data sets. 
Still loading those, so will leave as awaiting testing.

One point though is that  if the is no data for a WG in the Community, the report doe not include it at all.
So if only 1 of 3 WGs has data you just get one column.
But this means if you have no assets for any WG you just get a blank page.
I had expected to at least see the title and axes.

Is this because only WGs that have been at least Parsed are included?
That sort of make sense, since the real world use case should not include examining the reports for Communities whose data is not there yet.
But some kind of indicator might be useful.

**Comment by dbrownukk** [comment]
Lets get a consistent filter of what is and what is not charted. 

1. It should only include validated wealthgroups (currently this is not used in any chart, just needs adding to the views)
2. If no Validated Wealthgroups for the particular community chart then just warn that no validated data exists.

would that work, or am I missing a filter or condition?

**Comment by daiClegg** [comment]
I think just including Validated WGs is the right way to go.
As you suggest, some visual cue to indicate there is no valid data would be helpful.

I'll add this refinement to the Epic,   to document that it is applied to all the reports.

**Comment by dbrownukk** [comment]
need to add Wealthgroup.WGIStatus = 4 (Validated) to Views..

**Comment by dbrownukk** [comment]
all views changed to include Wealthgroupinterview.WGIStatus = 4

**Comment by daiClegg** [comment]
The only open issue i know of on this is the problem of how to calculate value of Assets. 
Livestock,  Trees and Other Tradeable all have a value per unit, so their value is no. of units * value per unit.
Cash is just cash. If it is not the currency of the country in which the project is taking place it should be the alternative current - and the exchange rate is in the project.
If it's any other, i guess it should fail at parse. 

Will raise this as a separate issue - validation of Cash asset currency?

But Land and Foodstore have no unit value. 
Am discussing with John.

**Comment by daiClegg** [comment]
See also Issue #141 for the problem of Cash  assets in  currencies undefined in the project.

**Comment by dbrownukk** [comment]
I have split the Assets chart into 3 as above

The Cash is calculated using the following

If Currency Entered = Currency of Project.Country then use Amount Entered

If Currency Entered != Currency of Project.Country then divide(?) by Project Exchange Rate

The other cash assets are calculated as ppu * number of units

Land and Food Stocks are in separate charts

**Comment by daiClegg** [comment]
Would it be possible to run all three reports and present as 3 pages.
Alternatively the "Assets" report should be retitled "Assets - Livestock, Tradeable, Trees  & Cash"

**Comment by dbrownukk** [comment]
All 3 reports now concatenated into one report driven off Asset and Asset(Normalised) menus

**Comment by daiClegg** [comment]
Tested on: 
Project: Mukono - New Test
LZ:Banana Coffee Piggery 
District: Mukono 
Sub District: Nakisunga 

I manipulated data to get values in for all three sub-reports.
All tested ok.
Also tested with a blank page; nice message.

Core use case satisfied 
-----------------------

Validation for Food Stocks still wip (Issue #161)
