### ISSUE TITLE
Provide visual summary of Food Consumed, by Resource SubType, by Wealth Group

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#93]

**Comment by daiClegg** [comment]
Food consumed is in all cases measured in KCals of the food type. 
This is calculated as the product of the KCal value per unit, as recorded on the resource subtype, and the number of units consumed.

**Comment by daiClegg** [comment]
The food consumed calculation is as folows:

Calorific value of all food produced (crops, livestock products and wild food and Food Transfers)  less the amounts sold, plus the calorific value of food as payment for labour.
But **excluding** calorific value of food purchased.


(from John in email 22/5/18)

**Comment by dbrownukk** [comment]
Food as payment - Employment.FoodPaymentFoodType not linked to Food Resource type (at the moment) - change to model needed..   otherwise calorific value is missing

Also, concerned about Units. We have unit in the Resource intersection table and Unit in the Resource Type table, but no validation (again, at the moment)

i.e. in Crops intersection table for community we could have Matoke Unit 'Bag' and in the intersection table, from the spreadsheet we could have kg or KG or bag. Somehow we need a check - in the validation run???

**Comment by daiClegg** [comment]
Units
====

See Issues #100, #101 and #103.

If i enter 10 Bags of Maize, and the Unit (in resource subtypes) for Maize is Kg, that should fail parsing until i make the conversion, say change it to 500 KG - cos i know they are 
 50Kg Bags. Right now it passes validation, even though the unit in the WGI resource subtype records says "Bags"


To correct this there needs to be some interaction to show the user what the valid unit is for a given resource sub-type. It woul dthen be the users problem to do the conversion and enter it accordingly.
But there would need to be that and more (allow definition of project-specific, resourceSubType-specific units) for #103, because there would still be the case where somebody entered "Bag" when the local unit was set up as "Bags"

Need to discuss

**Comment by daiClegg** [comment]
Requirement discussed; implementation under investigation

**Comment by dbrownukk** [comment]
#160  handles the Entered Unit validation with RST Unit

Calc needs correcting in View

**Comment by dbrownukk** [comment]
Working through the calculation 

From John (see above), food consumed calc is:

Calorific value of all food produced (crops, livestock products and wild food and Food Transfers) less the amounts sold, plus the calorific value of food as payment for labour.
But excluding calorific value of food purchased.

- OK, we do not include Food Purchased 
- Why is there a UnitsConsumed column in Crops, LSP, WildFood and Transfer

Employment - Food Payments NEED VALIDATION
- Calorific value of Food as payment. Properties of Employment include:
-- FoodPaymentFoodType (this should be a FK to RST of Food (or can they be paid in livestock that is then eaten!!)
--FoodPaymentUnit
--FoodPaymentUnitsPaidWork 



Current Food Consumed Chart out for testing has following

Crops - UnitsProduced-UnitsSold*KCal value from RST
Transfer - UnitsTransferred-UnitsSold  *KCal value from RST
LivestockProducts - UnitsProduced-UnitsSold*KCal value from RST
Wildfood - UnitsProduced-UnitsSold*KCal value from RST
Employment - 0 the moment  (need to work on some validation for the Employment Food payments)

**Comment by daiClegg** [comment]
> Why is there a UnitsConsumed column in Crops, LSP, WildFood and Transfer

Crops, LSP, WildFood and Transfers can all be sold as well as consumed.
So for each resource there will be an amount consumed and an amount sold.
BUT - here is also an amount 'Other use'; That might be a gift or a quid pro quo for some obligation or anything else. We can ignore the 'Other use'.
So the amount consumed is in the consumed calculation and the amount sold is in the income calculation.

Make sense?

**Comment by daiClegg** [comment]
Note Employment osnot yet properly dealt with (as per notre above) .
Need more testing.
Also see previous comment re 'Other Use'

**Comment by daiClegg** [comment]
Further commeent from JOhn.

**Comment by daiClegg** [comment]
What is the status of this?
Is it related to another issue?

**Comment by daiClegg** [comment]
See issue #...

**Comment by daiClegg** [comment]
Dependent issue closed.

**Feature Complete**

**Comment by daiClegg** [comment]
@celiapetty This is the issue the Feature Issue for the Food Consumed report.

I added the note from John - see above, which was equivocal, so i didn't take the Food Purchases out.
Can easily do that, if it is the correct requirement. I will discuss with David later today.

**Comment by daiClegg** [comment]
@celiapetty this is the issue you were searching for.
My fault i had not re-opened the issue when discussion of the requirement was re-opened

Can you just confirm, here, please that Food Purchases are to be removed from the Food Consumed charts?

And should the chart be renamed "Food Income"?

**Comment by celiapetty** [comment]
Confirming that Food Purchases should be removed from Food Consumed charts. The chart should be renamed 'Food Income'.

**Comment by daiClegg** [comment]
@dbrownukk  we have discussed this @celia is now confirming it is required.

**Comment by dbrownukk** [comment]
removed food purchases from food consumed details view

deployed

**Comment by daiClegg** [comment]
Removal of Food Purchases tested ok, but Celia also requested, above, change of the chart titles for what are currently
 
_"Food Consumed" & "Food Consumed(Normalised)"_ 

to: 

_"Food Income" & "Food Income(Normalised)"_

**Comment by dbrownukk** [comment]
renamed...

deployed

**Comment by daiClegg** [comment]
**Tested Ok**
