### ISSUE TITLE
Provide visual summary of Cash Income, by Resource SubType, by Wealth Group

### ISSUE THREAD

**Issue by daiClegg** [dbrownukk/EFD_v2#94]

**Comment by daiClegg** [comment]
Basis for this is the sales of Crops. Wilds Foods and  Livestock Products

**Comment by dbrownukk** [comment]
deployed

**Comment by daiClegg** [comment]
Eejit that I am, I failed to include Employment and Transfers of type ‘Cash’. 
I need to check my notes for the calculations for total cash amount from these

**Comment by dbrownukk** [comment]
Have added in Employment and Cash Transfers

Should Livestock Sales remain in? Livestock Products is in.

Calculations
Crops  - Units Sold * PPU
Livestock Sales - Units * PPU
Livestock Products - Units Sold * PPU
Employment - PeopleCount * UnitsWorked * CashPaymentAmount
WildFood - Units Sold * PPU
Transfers - CashTransferAmount

(Also - small prob with front screen - lost image - happens on deployment to Linux, all works the same from entering un/pw - will investigate)

**Comment by daiClegg** [comment]
Yes, Livestock Sales are included.

**Comment by daiClegg** [comment]
Are livestock sales now included? is this ready for testing?

**Comment by dbrownukk** [comment]
Yes, LivestockSales should be in this chart

**Comment by daiClegg** [comment]
Tested on: 
Project-Mukconu - New Test
LZ -Banana Coffee Piggery 
District - Mukono 
SubDistrict - Ntenjeru 

The Middle WG has 4 employment types.
Two of them have been recorded as "Petty Day Trade"
One of them  (originally entered as "Fish Trader") appears to have been omitted from the calculation
Poor & Better Off groups appear to be accurate.

**Comment by daiClegg** [comment]
**Feature Complete**

moving one remaining anomaly  (missing employment type) to separate issue
